/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:44:13 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/MapsSuggestions.framework/MapsSuggestions
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapsSuggestions/MapsSuggestions-Structs.h>
#import <MapsSuggestions/MapsSuggestionsFlightRequester.h>

@class NSArray, NSError, NSString;

@interface MapsSuggestionsFakeFlightRequester : NSObject <MapsSuggestionsFlightRequester> {

	ReadWriteQueue _rwQueue;
	NSArray* _configuredFlights;
	NSError* _configuredError;
	unsigned long long _calledRequestFlights;

}

@property (nonatomic,readonly) NSString * uniqueName; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)configureFlights:(id)arg1 ;
-(unsigned long long)calledRequestFlights;
-(NSString *)uniqueName;
-(id)init;
-(void)configureError:(id)arg1 ;
-(char)requestFlightsWithFullFlightNumber:(id)arg1 departureDate:(id)arg2 handler:(/*^block*/id)arg3 ;
@end

