/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:42:25 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface HUIconContentViewReuseQueue : NSObject {

	Class _contentViewClass;
	NSMutableArray* _reuseStack;

}

@property (nonatomic,readonly) NSMutableArray * reuseStack;              //@synthesize reuseStack=_reuseStack - In the implementation block
@property (nonatomic,readonly) Class contentViewClass;                   //@synthesize contentViewClass=_contentViewClass - In the implementation block
+(id)globalReuseQueueForContentViewClass:(Class)arg1 ;
-(Class)contentViewClass;
-(id)init;
-(id)initWithContentViewClass:(Class)arg1 ;
-(NSMutableArray *)reuseStack;
-(id)dequeueContentView;
-(void)reapContentView:(id)arg1 ;
@end

