/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:46:39 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PassKitCore/PKContactFieldConfiguration.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString, NSCharacterSet, NSRegularExpression;

@interface PKTextContactFieldConfiguration : PKContactFieldConfiguration <NSSecureCoding> {

	BOOL _numeric;
	BOOL _keepPaddingCharactersForSubmission;
	BOOL _isValidCharacterSet;
	long long _minLength;
	long long _maxLength;
	NSString* _displayFormat;
	NSString* _displayFormatPlaceholder;
	NSCharacterSet* _characterSet;
	NSRegularExpression* _validRegex;

}

@property (nonatomic,readonly) long long minLength;                                   //@synthesize minLength=_minLength - In the implementation block
@property (nonatomic,readonly) long long maxLength;                                   //@synthesize maxLength=_maxLength - In the implementation block
@property (getter=isNumeric,nonatomic,readonly) BOOL numeric;                         //@synthesize numeric=_numeric - In the implementation block
@property (nonatomic,copy,readonly) NSString * displayFormat;                         //@synthesize displayFormat=_displayFormat - In the implementation block
@property (nonatomic,copy,readonly) NSString * displayFormatPlaceholder;              //@synthesize displayFormatPlaceholder=_displayFormatPlaceholder - In the implementation block
@property (nonatomic,readonly) BOOL keepPaddingCharactersForSubmission;               //@synthesize keepPaddingCharactersForSubmission=_keepPaddingCharactersForSubmission - In the implementation block
@property (nonatomic,readonly) NSCharacterSet * characterSet;                         //@synthesize characterSet=_characterSet - In the implementation block
@property (nonatomic,readonly) BOOL isValidCharacterSet;                              //@synthesize isValidCharacterSet=_isValidCharacterSet - In the implementation block
@property (nonatomic,readonly) NSRegularExpression * validRegex;                      //@synthesize validRegex=_validRegex - In the implementation block
+(BOOL)supportsSecureCoding;
-(long long)minLength;
-(NSCharacterSet *)characterSet;
-(BOOL)isNumeric;
-(NSString *)displayFormat;
-(NSString *)displayFormatPlaceholder;
-(BOOL)keepPaddingCharactersForSubmission;
-(id)initWithCoder:(id)arg1 ;
-(long long)maxLength;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithDictionary:(id)arg1 ;
-(NSRegularExpression *)validRegex;
-(BOOL)isValidCharacterSet;
-(id)description;
@end

