/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:43:56 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/CoreDuetDataModel.framework/CoreDuetDataModel
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSNumber, NSDate;

@interface CDDMAppStateChangeEvent : NSManagedObject

@property (nonatomic,retain) NSNumber * anonymizedBeacon; 
@property (nonatomic,retain) NSNumber * anonymizedLocation; 
@property (nonatomic,retain) NSNumber * appState; 
@property (nonatomic,retain) NSNumber * computeUtilization; 
@property (nonatomic,retain) NSDate * creationDate; 
@property (nonatomic,retain) NSNumber * integerId; 
@property (nonatomic,retain) NSNumber * ioBytesRead; 
@property (nonatomic,retain) NSNumber * ioBytesWritten; 
@property (nonatomic,retain) NSNumber * isFront; 
@property (nonatomic,retain) NSNumber * localDaysSinceSunday; 
@property (nonatomic,retain) NSNumber * localTime; 
@property (nonatomic,retain) NSNumber * localTimeQuarterHourSlot; 
@property (nonatomic,retain) NSNumber * memoryPhysicalFootprint; 
@property (nonatomic,retain) NSNumber * networkQuality; 
@property (nonatomic,retain) NSNumber * networkRxBytes; 
@property (nonatomic,retain) NSNumber * networkTxBytes; 
@property (nonatomic,retain) NSNumber * runReason; 
@property (nonatomic,retain) NSNumber * usedCellData; 
@property (nonatomic,retain) NSNumber * userId; 
@property (nonatomic,retain) NSNumber * networkBytes; 
@property (nonatomic,retain) NSNumber * ioBytes; 
@end

