#import <CoreDuetDataModel/CDDMAirplaneModeEvent.h>
#import <CoreDuetDataModel/CDDMScreenLockEvent.h>
#import <CoreDuetDataModel/CDDMStatisticInteger.h>
#import <CoreDuetDataModel/CDDMStatisticString.h>
#import <CoreDuetDataModel/CDDMThermalEvent.h>
#import <CoreDuetDataModel/CDDMForecastScore.h>
#import <CoreDuetDataModel/CDDMBootOrShutdownEvent.h>
#import <CoreDuetDataModel/CDDMBatteryEvent.h>
#import <CoreDuetDataModel/CDDMRealAttribute.h>
#import <CoreDuetDataModel/CDDMForecast.h>
#import <CoreDuetDataModel/CDDMWakednessEvent.h>
#import <CoreDuetDataModel/CDDMStringAttribute.h>
#import <CoreDuetDataModel/CDDMAppNameMapper.h>
#import <CoreDuetDataModel/CDDMDeviceMapper.h>
#import <CoreDuetDataModel/CDDMBookkeeping.h>
#import <CoreDuetDataModel/CDDMForecastReal.h>
#import <CoreDuetDataModel/CDDMAppStateChangeEvent.h>
#import <CoreDuetDataModel/CDDMForecastInteger.h>
#import <CoreDuetDataModel/CDDMStatisticReal.h>
#import <CoreDuetDataModel/CDDMIntegerAttribute.h>
#import <CoreDuetDataModel/CDDMPluginEvent.h>
#import <CoreDuetDataModel/CDDMPool.h>
#import <CoreDuetDataModel/CDDMBacklightEvent.h>
#import <CoreDuetDataModel/CDDMAttributeNameMapper.h>
#import <CoreDuetDataModel/CDDMPoolNameMapper.h>
#import <CoreDuetDataModel/CDDMForecastString.h>
#import <CoreDuetDataModel/CDDMSleepOrWakeEvent.h>
#import <CoreDuetDataModel/CDDMDeviceEvent.h>
