#import <CoreLocationProtobuf/CLPAccessoryMeta.h>
#import <CoreLocationProtobuf/CLPAltimeterCollectionRequest.h>
#import <CoreLocationProtobuf/CLPAppCollectionRequest.h>
#import <CoreLocationProtobuf/CLPAppCollectionResponse.h>
#import <CoreLocationProtobuf/CLPAppLocation.h>
#import <CoreLocationProtobuf/CLPBaroCalibrationIndication.h>
#import <CoreLocationProtobuf/CLPBundleId.h>
#import <CoreLocationProtobuf/CLPCdmaCellNeighbor.h>
#import <CoreLocationProtobuf/CLPCdmaCellTowerLocation.h>
#import <CoreLocationProtobuf/CLPCellNeighbor.h>
#import <CoreLocationProtobuf/CLPCellNeighborsGroup.h>
#import <CoreLocationProtobuf/CLPCellOutOfServiceInfo.h>
#import <CoreLocationProtobuf/CLPCellTowerLocation.h>
#import <CoreLocationProtobuf/CLPCellWifiCollectionRequest.h>
#import <CoreLocationProtobuf/CLPCellWifiCollectionResponse.h>
#import <CoreLocationProtobuf/CLPContext.h>
#import <CoreLocationProtobuf/CLPIndoorCMAttitude.h>
#import <CoreLocationProtobuf/CLPIndoorCMPedometer.h>
#import <CoreLocationProtobuf/CLPIndoorCollectionRequest.h>
#import <CoreLocationProtobuf/CLPIndoorCollectionResponse.h>
#import <CoreLocationProtobuf/CLPIndoorEvent.h>
#import <CoreLocationProtobuf/CLPIndoorMotionActivity.h>
#import <CoreLocationProtobuf/CLPIndoorPressure.h>
#import <CoreLocationProtobuf/CLPIndoorWifiScan.h>
#import <CoreLocationProtobuf/CLPIonosphereCollectionRequest.h>
#import <CoreLocationProtobuf/CLPIonosphereData.h>
#import <CoreLocationProtobuf/CLPLocation.h>
#import <CoreLocationProtobuf/CLPLocationCollectionRequest.h>
#import <CoreLocationProtobuf/CLPLocationCollectionResponse.h>
#import <CoreLocationProtobuf/CLPLocationConsumptionScoreInfo.h>
#import <CoreLocationProtobuf/CLPLocationConsumptionScoreInfoRequest.h>
#import <CoreLocationProtobuf/CLPLteCellNeighbor.h>
#import <CoreLocationProtobuf/CLPLteCellTowerLocation.h>
#import <CoreLocationProtobuf/CLPMeta.h>
#import <CoreLocationProtobuf/CLPMotionActivity.h>
#import <CoreLocationProtobuf/CLPNRCellNeighbor.h>
#import <CoreLocationProtobuf/CLPNRCellTowerLocation.h>
#import <CoreLocationProtobuf/CLPPassCollectionRequest.h>
#import <CoreLocationProtobuf/CLPPassCollectionResponse.h>
#import <CoreLocationProtobuf/CLPPassLocation.h>
#import <CoreLocationProtobuf/CLPPipelineDiagnosticReport.h>
#import <CoreLocationProtobuf/CLPPoiCollectionRequest.h>
#import <CoreLocationProtobuf/CLPPoiCollectionResponse.h>
#import <CoreLocationProtobuf/CLPPoiHarvest.h>
#import <CoreLocationProtobuf/CLPPoiTriggerEvent.h>
#import <CoreLocationProtobuf/CLPPoiWifiAccessPoint.h>
#import <CoreLocationProtobuf/CLPPressure.h>
#import <CoreLocationProtobuf/CLPPressureCollectionRequest.h>
#import <CoreLocationProtobuf/CLPPressureCollectionResponse.h>
#import <CoreLocationProtobuf/CLPQuaternion.h>
#import <CoreLocationProtobuf/CLPRTVisit.h>
#import <CoreLocationProtobuf/CLPSCdmaCellTowerLocation.h>
#import <CoreLocationProtobuf/CLPSatelliteInfo.h>
#import <CoreLocationProtobuf/CLPSatelliteReport.h>
#import <CoreLocationProtobuf/CLPTraceCollectionRequest.h>
#import <CoreLocationProtobuf/CLPTraceCollectionResponse.h>
#import <CoreLocationProtobuf/CLPWifiAPLocation.h>
#import <CoreLocationProtobuf/CLPWtwCollectionRequest.h>
#import <CoreLocationProtobuf/CLPWtwCollectionResponse.h>
