/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:41:50 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SoftwareUpdateServices.framework/SoftwareUpdateServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SoftwareUpdateServices/SoftwareUpdateServices-Structs.h>
#import <SoftwareUpdateServices/SUOptionsBase.h>
#import <libobjc.A.dylib/NSSecureCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@class SUScanOptions, NSString;

@interface SUMDMScanOptions : SUOptionsBase <NSSecureCoding, NSCopying> {

	SUScanOptions* _scanOptions;

}

@property (nonatomic,retain) SUScanOptions * scanOptions;                                       //@synthesize scanOptions=_scanOptions - In the implementation block
@property (nonatomic,retain,readonly) NSString * requestedProductMarketingVersion; 
@property (nonatomic,readonly) BOOL useDelayPeriod; 
@property (nonatomic,readonly) unsigned long long delayPeriodDays; 
-(id)copyWithZone:(NSZone*)arg1 ;
-(SUScanOptions *)scanOptions;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setScanOptions:(SUScanOptions *)arg1 ;
-(id)description;
-(BOOL)useDelayPeriod;
-(BOOL)deviceIsSupervised;
-(NSString *)requestedProductMarketingVersion;
-(id)initWithScanOption:(id)arg1 ;
-(unsigned long long)delayPeriodDays;
@end

