#import <SiriSettingsIntents/SiriSettingsIntents.GetBluetoothHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetLowPowerModeHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.FlowFrameHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SettingsNativeApiClient.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetFlashlightHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetWifiHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetNightShiftHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.OpenIntentHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetBinaryIntentHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetVoiceOverHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetTemporalIntentHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.AuthenticationSupportFlow.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetIntentHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetCellularDataHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.UsageCountConfigProvider.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetLowPowerModeHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.AuthenticationHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetAppearanceHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetAirplaneModeHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetInvertColorsHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetWifiHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetBluetoothHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetLabeledIntentHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetLocationServicesHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.DialogProvider.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SettingsIntentConfirmationConfigProvider.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetLocationServicesHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetNightShiftHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetInvertColorsHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetVoiceOverHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetAssistiveTouchHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetHandlerProvider.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetCellularDataHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetFlashlightHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetAssistiveTouchHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.GetAirplaneModeHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.BoolSnippetProvider.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SetNumericIntentHandler.h>
#import <SiriSettingsIntents/SiriSettingsIntents.SettingsUserDefaultsProvider.h>
