#import <MetalPerformanceShadersGraph/MPSGraphOperation.h>
#import <MetalPerformanceShadersGraph/StitchedRegionDAG.h>
#import <MetalPerformanceShadersGraph/MPSGraphOneHotOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphArithmeticOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DOpDescriptor.h>
#import <MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DBaseOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DDataGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DWeightsGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphTensor.h>
#import <MetalPerformanceShadersGraph/MPSGraphReductionBaseOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphReductionSumOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphReductionMinOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphReductionMaxOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphReductionProdOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphExecutionDescriptor.h>
#import <MetalPerformanceShadersGraph/MPSGraph.h>
#import <MetalPerformanceShadersGraph/MPSGraphResizeBaseOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphResizeOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphResizeGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphPlaceholderOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphConstantOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphVariableOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphReadVariableOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphAssignVariableOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphTensorData.h>
#import <MetalPerformanceShadersGraph/CPURuntime.h>
#import <MetalPerformanceShadersGraph/MPSGraphDevice.h>
#import <MetalPerformanceShadersGraph/MPSGraphConvolution2DOpDescriptor.h>
#import <MetalPerformanceShadersGraph/MPSGraphConvolution2DBaseOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphConvolution2DOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphConvolution2DDataGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphConvolution2DWeightsGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphRandomUniformOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphShapedType.h>
#import <MetalPerformanceShadersGraph/MPSGraphScatterNDOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphGatherNDOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphGatherOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphVariable.h>
#import <MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor.h>
#import <MetalPerformanceShadersGraph/MPSGraphPooling2DBaseOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphMaxPooling2DOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphAvgPooling2DOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphMaxPooling2DGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphAvgPooling2DGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphTransposeOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphReshapeOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphSliceOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphConcatOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphCastOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphPadOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphTileOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphPadGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphTileGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphIdentityOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphShapeOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphRankOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphSizeOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphDimensionSizeOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphBroadcastOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphBroadcastGradientArgsOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphVariableInitializer.h>
#import <MetalPerformanceShadersGraph/MPSGraphOptimizer.h>
#import <MetalPerformanceShadersGraph/MPSGraphStochasticGradientDescentOptimizer.h>
#import <MetalPerformanceShadersGraph/MPSGraphAdamOptimizer.h>
#import <MetalPerformanceShadersGraph/MPSGraphStitchedOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphMatrixMultiplicationOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphMatrixMultiplicationPrimaryGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphMatrixMultiplicationSecondaryGradientOp.h>
#import <MetalPerformanceShadersGraph/MPSGraphExecutable.h>
