/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:35:42 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/AVFCore.framework/AVFCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <AVFCore/AVFCore-Structs.h>
@class AVNetworkPlaybackPerfHUDLayer, NSObject, AVKeyPathDependencyManager, AVPlayer, NSString, NSDictionary, FigBaseCALayer, FigVideoContainerLayer, FigSubtitleCALayer, AVPlayerLayer, NSSet, CALayer;

@interface AVPlayerLayerInternal : NSObject {

	AVNetworkPlaybackPerfHUDLayer* hudLayer;
	NSObject*<OS_dispatch_queue> serialQueue;
	BOOL isPresentationLayer;
	OpaqueFigSimpleMutexRef isReadyForDisplayMutex;
	NSObject*<OS_dispatch_queue> configurationQueue;
	AVKeyPathDependencyManager* dependencyManager;
	id playerItemHasEnqueuedVideoFrameListener;
	id windowSceneDidEnterBackgroundListener;
	id windowSceneWillEnterForegroundListener;
	AVPlayer* player;
	NSString* videoGravity;
	NSDictionary* pixelBufferAttributes;
	BOOL lanczosDownscalingEnabled;
	long long lanczosDownscalingFactor;
	FigBaseCALayer* maskLayer;
	FigVideoContainerLayer* videoLayer;
	FigSubtitleCALayer* subtitleLayer;
	FigBaseCALayer* closedCaptionLayer;
	BOOL isLegibleDisplayEnabled;
	BOOL isForScrubbingOnly;
	AVPlayerLayer* associatedRemoteModeLayer;
	BOOL willManageSublayersAsSwappedLayers;
	long long activeMode;
	BOOL isPartOfForegroundScene;
	BOOL isReadyForDisplay;
	AVPlayer* playerBeingObserved;
	NSSet* KVOInvokers;
	CGSize latestAppliedPresentationSize;
	BOOL preventsChangesToSublayerHierarchy;
	NSDictionary* clientLayers;
	BOOL isPIPModeEnabled;
	CALayer* placeholderContentLayerDuringPIPMode;
	BOOL isConnectedToSecondScreen;
	NSEdgeInsets legibleContentInsets;
	BOOL honorContentScale;
	double screenScale;

}
@end

