/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:45:02 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/WFCloudKitItem.h>

@class CKRecordID, NSData, NSDate, NSString, WFFileRepresentation, WFWorkflowRecord;

@interface WFCloudKitWorkflow : NSObject <WFCloudKitItem> {

	CKRecordID* _identifier;
	NSData* _recordSystemFieldsData;
	NSDate* _createdAt;
	NSDate* _modifiedAt;
	NSString* _name;
	NSString* _workflowSubtitle;
	NSString* _associatedAppBundleIdentifier;
	NSString* _source;
	NSString* _galleryIdentifier;
	WFFileRepresentation* _serializedDataFile;
	long long _cachedSyncHash;
	NSData* _serializedQuarantineData;
	NSData* _serializedAccessResourcePerWorkflowStateData;
	NSString* _lastSavedOnDeviceName;
	WFWorkflowRecord* _cachedRecord;

}

@property (nonatomic,retain) WFWorkflowRecord * cachedRecord;                                  //@synthesize cachedRecord=_cachedRecord - In the implementation block
@property (nonatomic,readonly) NSDate * createdAt;                                             //@synthesize createdAt=_createdAt - In the implementation block
@property (nonatomic,readonly) NSDate * modifiedAt;                                            //@synthesize modifiedAt=_modifiedAt - In the implementation block
@property (nonatomic,copy) NSString * name;                                                    //@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString * workflowSubtitle;                                        //@synthesize workflowSubtitle=_workflowSubtitle - In the implementation block
@property (nonatomic,copy) NSString * associatedAppBundleIdentifier;                           //@synthesize associatedAppBundleIdentifier=_associatedAppBundleIdentifier - In the implementation block
@property (nonatomic,copy) NSString * source;                                                  //@synthesize source=_source - In the implementation block
@property (nonatomic,copy) NSString * galleryIdentifier;                                       //@synthesize galleryIdentifier=_galleryIdentifier - In the implementation block
@property (nonatomic,retain) WFFileRepresentation * serializedDataFile;                        //@synthesize serializedDataFile=_serializedDataFile - In the implementation block
@property (assign,nonatomic) long long cachedSyncHash;                                         //@synthesize cachedSyncHash=_cachedSyncHash - In the implementation block
@property (nonatomic,copy) NSData * serializedQuarantineData;                                  //@synthesize serializedQuarantineData=_serializedQuarantineData - In the implementation block
@property (nonatomic,copy) NSData * serializedAccessResourcePerWorkflowStateData;              //@synthesize serializedAccessResourcePerWorkflowStateData=_serializedAccessResourcePerWorkflowStateData - In the implementation block
@property (nonatomic,copy) NSString * lastSavedOnDeviceName;                                   //@synthesize lastSavedOnDeviceName=_lastSavedOnDeviceName - In the implementation block
@property (nonatomic,readonly) CKRecordID * identifier;                                        //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,copy) NSData * recordSystemFieldsData;                                    //@synthesize recordSystemFieldsData=_recordSystemFieldsData - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)properties;
+(id)recordType;
+(id)recordIDWithZoneID:(id)arg1 workflowID:(id)arg2 ;
-(NSDate *)createdAt;
-(CKRecordID *)identifier;
-(void)setSource:(NSString *)arg1 ;
-(void)setAssociatedAppBundleIdentifier:(NSString *)arg1 ;
-(void)setName:(NSString *)arg1 ;
-(NSString *)source;
-(NSString *)name;
-(NSString *)associatedAppBundleIdentifier;
-(id)recordRepresentationWithError:(id*)arg1 ;
-(void)setGalleryIdentifier:(NSString *)arg1 ;
-(NSString *)galleryIdentifier;
-(NSData *)recordSystemFieldsData;
-(long long)cachedSyncHash;
-(void)setRecordSystemFieldsData:(NSData *)arg1 ;
-(WFFileRepresentation *)serializedDataFile;
-(BOOL)isValidForSyncing;
-(id)initWithRecord:(id)arg1 identifier:(id)arg2 ;
-(NSString *)workflowSubtitle;
-(void)setWorkflowSubtitle:(NSString *)arg1 ;
-(void)setCreatedAt:(id)arg1 modifiedAt:(id)arg2 createdBy:(id)arg3 ;
-(NSDate *)modifiedAt;
-(void)setSerializedDataFile:(WFFileRepresentation *)arg1 ;
-(void)setCachedSyncHash:(long long)arg1 ;
-(NSData *)serializedQuarantineData;
-(void)setSerializedQuarantineData:(NSData *)arg1 ;
-(NSData *)serializedAccessResourcePerWorkflowStateData;
-(void)setSerializedAccessResourcePerWorkflowStateData:(NSData *)arg1 ;
-(NSString *)lastSavedOnDeviceName;
-(void)setLastSavedOnDeviceName:(NSString *)arg1 ;
-(WFWorkflowRecord *)cachedRecord;
-(void)setCachedRecord:(WFWorkflowRecord *)arg1 ;
@end

