/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:43:38 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/AccessibilityUIUtilities.framework/AccessibilityUIUtilities
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AccessibilityUIUtilities/AccessibilityUIUtilities-Structs.h>
#import <UIKitCore/UIImageView.h>

@class UIFontMetrics, NSString;

@interface AXDynamicTypeImageView : UIImageView {

	UIFontMetrics* _fontMetrics;
	NSString* _minimumContentSizeCategory;
	NSString* _maximumContentSizeCategory;

}

@property (nonatomic,retain) UIFontMetrics * fontMetrics;                      //@synthesize fontMetrics=_fontMetrics - In the implementation block
@property (nonatomic,copy) NSString * minimumContentSizeCategory;              //@synthesize minimumContentSizeCategory=_minimumContentSizeCategory - In the implementation block
@property (nonatomic,copy) NSString * maximumContentSizeCategory;              //@synthesize maximumContentSizeCategory=_maximumContentSizeCategory - In the implementation block
-(id)initWithImage:(id)arg1 ;
-(NSString *)minimumContentSizeCategory;
-(CGSize)intrinsicContentSize;
-(id)initWithFrame:(CGRect)arg1 ;
-(UIFontMetrics *)fontMetrics;
-(CGSize)_scaledSizeForSize:(CGSize)arg1 ;
-(void)setFontMetrics:(UIFontMetrics *)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setMinimumContentSizeCategory:(NSString *)arg1 ;
-(void)_commonInit;
-(void)setMaximumContentSizeCategory:(NSString *)arg1 ;
-(id)initWithImage:(id)arg1 highlightedImage:(id)arg2 ;
-(NSString *)maximumContentSizeCategory;
@end

