/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:42:01 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <HealthRecordsUI/HealthRecordsUI-Structs.h>
#import <UIKitCore/UIView.h>

@protocol HKClinicalBrandable;
@class UILabel, WDClinicalSourcesDataProvider, WDBrandLogoView, UIStackView, UIView;

@interface WDMedicalRecordBrandView : UIView {

	UILabel* _brandTitleLabel;
	UILabel* _brandSubtitleLabel;
	UILabel* _brandDetailLabel;
	id<HKClinicalBrandable> _brandable;
	WDClinicalSourcesDataProvider* _dataProvider;
	WDBrandLogoView* _logoView;
	UIStackView* _stackView;
	UIView* _logoAlignedContentView;
	UIStackView* _verticalSpecContainerView;

}

@property (nonatomic,readonly) id<HKClinicalBrandable> brandable;                         //@synthesize brandable=_brandable - In the implementation block
@property (nonatomic,readonly) WDClinicalSourcesDataProvider * dataProvider;              //@synthesize dataProvider=_dataProvider - In the implementation block
@property (nonatomic,readonly) WDBrandLogoView * logoView;                                //@synthesize logoView=_logoView - In the implementation block
@property (nonatomic,readonly) UIStackView * stackView;                                   //@synthesize stackView=_stackView - In the implementation block
@property (nonatomic,readonly) UIView * logoAlignedContentView;                           //@synthesize logoAlignedContentView=_logoAlignedContentView - In the implementation block
@property (nonatomic,readonly) UIStackView * verticalSpecContainerView;                   //@synthesize verticalSpecContainerView=_verticalSpecContainerView - In the implementation block
@property (nonatomic,readonly) UILabel * brandTitleLabel;                                 //@synthesize brandTitleLabel=_brandTitleLabel - In the implementation block
@property (nonatomic,readonly) UILabel * brandSubtitleLabel;                              //@synthesize brandSubtitleLabel=_brandSubtitleLabel - In the implementation block
@property (nonatomic,readonly) UILabel * brandDetailLabel;                                //@synthesize brandDetailLabel=_brandDetailLabel - In the implementation block
@property (assign,nonatomic) double logoSize; 
-(UIStackView *)stackView;
-(void)_setupConstraints;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)_setupSubviews;
-(void)setLogoSize:(double)arg1 ;
-(void)setBrandable:(id)arg1 dataProvider:(id)arg2 ;
-(id<HKClinicalBrandable>)brandable;
-(WDBrandLogoView *)logoView;
-(void)_updateContentWithBrandable:(id)arg1 dataProvider:(id)arg2 ;
-(UIStackView *)verticalSpecContainerView;
-(UIView *)logoAlignedContentView;
-(UILabel *)brandTitleLabel;
-(UILabel *)brandSubtitleLabel;
-(UILabel *)brandDetailLabel;
-(void)_updateForContentSizeCategory:(id)arg1 ;
-(void)_updateBasedOnAccessibilityCategory:(BOOL)arg1 ;
-(double)logoSize;
-(WDClinicalSourcesDataProvider *)dataProvider;
-(void)_updateLabelVisibility;
-(void)_updateForCurrentSizeCategory;
@end

