/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:38:34 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIImageView.h>
#import <libobjc.A.dylib/CKActionMenuItemView.h>

@class UIColor, NSString;

@interface CKActionMenuItemImageView : UIImageView <CKActionMenuItemView> {

	UIColor* _unhighlightedTintColor;
	UIColor* _highlightedTintColor;
	BOOL _enabled;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setEnabled:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setHighlighted:(BOOL)arg1 ;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)updateTintColor;
-(id)initWithImage:(id)arg1 tintColor:(id)arg2 highlightedTintColor:(id)arg3 ;
@end

