/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:38:27 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/CKPinnedConversationActivityItem.h>

@class NSString, IMMessage;

@interface CKPinnedConversationTapbackBubbleActivityItem : NSObject <CKPinnedConversationActivityItem> {

	double _activityItemContentScale;
	NSString* _attachedContactItemIdentifier;
	IMMessage* _message;

}

@property (nonatomic,readonly) IMMessage * message;                                   //@synthesize message=_message - In the implementation block
@property (nonatomic,readonly) NSString * attachedContactItemIdentifier;              //@synthesize attachedContactItemIdentifier=_attachedContactItemIdentifier - In the implementation block
@property (nonatomic,readonly) NSString * activityItemIdentifier; 
@property (nonatomic,readonly) BOOL activityItemAppearsWithAnimation; 
@property (nonatomic,readonly) BOOL activityItemDisappearsWithAnimation; 
@property (nonatomic,readonly) double activityItemContentScale;                       //@synthesize activityItemContentScale=_activityItemContentScale - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)activityItemView;
-(NSString *)activityItemIdentifier;
-(double)activityItemContentScale;
-(BOOL)activityItemAppearsWithAnimation;
-(BOOL)activityItemDisappearsWithAnimation;
-(NSString *)attachedContactItemIdentifier;
-(id)initWithMessage:(id)arg1 contentScale:(double)arg2 attachedContactItemIdentifier:(id)arg3 ;
-(IMMessage *)message;
@end

