/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:46:52 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/CDDataAccess.framework/CDDataAccess
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol DAContactsAccount <DACardDAVRecord>
@required
-(id)identifier;
-(id)externalIdentifier;
-(int)legacyIdentifier;

@end

