/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:42:04 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/TestFlightCore.framework/TestFlightCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/TFFeedbackDataContainerObserver.h>
#import <libobjc.A.dylib/TFFeedbackDataUpdateProxy.h>

@protocol TFFeedbackFormPresenterView;
@class TFFeedbackForm, TFFeedbackDataContainer, TFFeedbackSession, NSString;

@interface TFFeedbackFormPresenter : NSObject <TFFeedbackDataContainerObserver, TFFeedbackDataUpdateProxy> {

	id<TFFeedbackFormPresenterView> _presenterView;
	TFFeedbackForm* _form;
	TFFeedbackDataContainer* _dataContainer;
	TFFeedbackSession* _session;

}

@property (nonatomic,readonly) TFFeedbackForm * form;                                           //@synthesize form=_form - In the implementation block
@property (nonatomic,readonly) TFFeedbackDataContainer * dataContainer;                         //@synthesize dataContainer=_dataContainer - In the implementation block
@property (nonatomic,readonly) TFFeedbackSession * session;                                     //@synthesize session=_session - In the implementation block
@property (assign,nonatomic,__weak) id<TFFeedbackFormPresenterView> presenterView;              //@synthesize presenterView=_presenterView - In the implementation block
@property (nonatomic,readonly) id<TFFeedbackDataSource> feedbackDataSource; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(TFFeedbackForm *)form;
-(TFFeedbackSession *)session;
-(void)didUpdateEntry:(id)arg1 toString:(id)arg2 editInProgress:(BOOL)arg3 ;
-(void)prepareViewForForm;
-(void)presenterViewDidInitiateFeedbackSubmission:(id)arg1 ;
-(void)setPresenterView:(id<TFFeedbackFormPresenterView>)arg1 ;
-(id)visibleEntryAtGroupIndex:(long long)arg1 entryIndex:(long long)arg2 ;
-(id<TFFeedbackDataSource>)feedbackDataSource;
-(unsigned long long)numberOfVisibleItemsInGroupAtIndex:(long long)arg1 ;
-(unsigned long long)numberOfEntryGroupsInForm;
-(id)headerTextForGroupAtIndex:(long long)arg1 ;
-(id)footerTextForGroupAtIndex:(long long)arg1 ;
-(id)footerTextLinkMapForGroupAtIndex:(long long)arg1 ;
-(void)feedbackDataContainer:(id)arg1 didUpdateValuesForGroupIdentifiers:(id)arg2 entryIdentifiers:(id)arg3 ;
-(void)didUpdateEntry:(id)arg1 toGroupInclusionBool:(BOOL)arg2 ;
-(id<TFFeedbackFormPresenterView>)presenterView;
-(TFFeedbackDataContainer *)dataContainer;
-(id)_indexPathsOfVisibleEntriesWithIdentifiers:(id)arg1 ;
-(id)_indicesOfGroupsWithIdentifiers:(id)arg1 ;
-(id)initWithForm:(id)arg1 dataContainer:(id)arg2 session:(id)arg3 ;
-(id)headerTextLinkMapForGroupAtIndex:(long long)arg1 ;
-(void)showSubmissionFailureWithMessage:(id)arg1 ;
@end

