/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:37:33 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class SBFolder, UIView, _UILegibilitySettings, UIViewController, SBFolderIconImageCache, SBHIconImageCache;


@protocol SBHIconRootViewProviding <SBIconLocationPresenting,SBIconViewQuerying,NSObject>
@property (nonatomic,retain) SBFolder * folder; 
@property (nonatomic,readonly) UIView * contentView; 
@property (nonatomic,retain) _UILegibilitySettings * legibilitySettings; 
@property (nonatomic,readonly) UIViewController * deepestFolderController; 
@property (assign,getter=isEditing,nonatomic) BOOL editing; 
@property (getter=isScrolling,nonatomic,readonly) BOOL scrolling; 
@property (getter=isScrollTracking,nonatomic,readonly) BOOL scrollTracking; 
@property (assign,nonatomic) long long currentPageIndex; 
@property (nonatomic,retain) SBFolderIconImageCache * folderIconImageCache; 
@property (nonatomic,retain) SBHIconImageCache * iconImageCache; 
@required
-(void)setIdleText:(id)arg1;
-(SBFolder *)folder;
-(UIView *)contentView;
-(void)setEditing:(BOOL)arg1;
-(void)setLegibilitySettings:(id)arg1;
-(void)setFolderIconImageCache:(id)arg1;
-(void)setIconImageCache:(id)arg1;
-(BOOL)setCurrentPageIndex:(long long)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3;
-(void)revealIcon:(id)arg1 animated:(BOOL)arg2 completionHandler:(/*^block*/id)arg3;
-(SBHIconImageCache *)iconImageCache;
-(BOOL)isEditing;
-(SBFolderIconImageCache *)folderIconImageCache;
-(BOOL)isScrollTracking;
-(UIViewController *)deepestFolderController;
-(void)setFolder:(id)arg1;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
-(BOOL)isScrolling;
-(void)setCurrentPageIndex:(long long)arg1;
-(void)cancelScrolling;
-(_UILegibilitySettings *)legibilitySettings;
-(long long)currentPageIndex;
-(void)noteUserIsInteractingWithIcons;

@end

