/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:42:21 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, NSXPCConnection;

@interface SFDiagnostics : NSObject {

	BOOL _btUser;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	BOOL _invalidateCalled;
	BOOL _invalidateDone;
	NSXPCConnection* _xpcCnx;
	/*^block*/id _interruptionHandler;
	/*^block*/id _invalidationHandler;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (nonatomic,copy) id interruptionHandler;                                    //@synthesize interruptionHandler=_interruptionHandler - In the implementation block
@property (nonatomic,copy) id invalidationHandler;                                    //@synthesize invalidationHandler=_invalidationHandler - In the implementation block
-(id)invalidationHandler;
-(void)invalidate;
-(void)_ensureXPCStarted;
-(void)_invalidated;
-(void)dealloc;
-(void)diagnosticControl:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)interruptionHandler;
-(void)_invalidate;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(id)init;
-(void)_interrupted;
-(void)bluetoothUserInteraction;
-(void)diagnosticMock:(id)arg1 device:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)diagnosticMockStart:(/*^block*/id)arg1 ;
-(void)diagnosticMockStop:(/*^block*/id)arg1 ;
-(void)_logControl:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_show:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)logControl:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)show:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)unlockTestClientWithDevice:(id)arg1 ;
-(void)unlockTestServer;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setInvalidationHandler:(id)arg1 ;
-(void)setInterruptionHandler:(id)arg1 ;
-(void)diagnosticBLEModeWithCompletion:(/*^block*/id)arg1 ;
@end

