/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:42:21 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct __SFBrowser* SFBrowserRef;

typedef struct __SFOperation* SFOperationRef;

typedef struct CGImage* CGImageRef;

typedef struct __SFNode* SFNodeRef;

typedef struct __CFArray* CFArrayRef;

typedef struct __SecIdentity* SecIdentityRef;

typedef struct {
	unsigned char field1;
	unsigned char field2;
	unsigned char field3;
	unsigned char field4;
	unsigned char field5;
	unsigned char field6;
} SCD_Struct_SF7;

typedef struct OpaqueIOPSPowerSourceID* OpaqueIOPSPowerSourceIDRef;

typedef struct __SecCertificate* SecCertificateRef;

typedef struct __CFUserNotification* CFUserNotificationRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef struct channel* channelRef;

typedef struct channel_ring_desc* channel_ring_descRef;

typedef struct BTSessionImpl* BTSessionImplRef;

typedef struct BTDeviceImpl* BTDeviceImplRef;

typedef struct BTPairingAgentImpl* BTPairingAgentImplRef;

typedef struct __WiFiManagerClient* WiFiManagerClientRef;

typedef struct PairingSessionPrivate* PairingSessionPrivateRef;

typedef struct {
	unsigned char channel;
	3c rssiValues;
	unsigned char rssiIndex;
	unsigned char rssiCount;
	char rssiMedian;
} SCD_Struct_SF19;

typedef struct PairingSubstate {
	int contacts;
	int homeKit;
	int visual;
	int pairVerify;
	int pin;
} PairingSubstate;

typedef struct CryptoAEADPrivate* CryptoAEADPrivateRef;

typedef struct NSRange {
	unsigned long long location;
	unsigned long long length;
} NSRange;

typedef struct __WiFiDeviceClient* WiFiDeviceClientRef;

