/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:42:07 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SPFinder.framework/SPFinder
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SPSchedulerXPCProtocol, OS_dispatch_queue;
@class FMXPCServiceDescription, FMXPCSession, NSObject;

@interface SPScheduler : NSObject {

	FMXPCServiceDescription* _serviceDescription;
	FMXPCSession* _session;
	id<SPSchedulerXPCProtocol> _proxy;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,retain) FMXPCServiceDescription * serviceDescription;              //@synthesize serviceDescription=_serviceDescription - In the implementation block
@property (nonatomic,retain) FMXPCSession * session;                                    //@synthesize session=_session - In the implementation block
@property (nonatomic,retain) id<SPSchedulerXPCProtocol> proxy;                          //@synthesize proxy=_proxy - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                        //@synthesize queue=_queue - In the implementation block
-(void)setProxy:(id<SPSchedulerXPCProtocol>)arg1 ;
-(void)setServiceDescription:(FMXPCServiceDescription *)arg1 ;
-(id<SPSchedulerXPCProtocol>)proxy;
-(FMXPCServiceDescription *)serviceDescription;
-(void)setSession:(FMXPCSession *)arg1 ;
-(FMXPCSession *)session;
-(void)dealloc;
-(id)init;
-(id)remoteInterface;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)schedulePublishWakeWithInformation:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)publishImmediatelyWithCompletion:(/*^block*/id)arg1 ;
@end

