/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:41:49 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/FMCoreLite.framework/FMCoreLite
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FMCoreLite/FMFuture.h>

@protocol FMScheduler, OS_dispatch_queue;
@class NSObject;

@interface _FMLazyFuture : FMFuture {

	BOOL _started;
	/*^block*/id _block;
	id<FMScheduler> _scheduler;
	NSObject*<OS_dispatch_queue> _accessQueue;

}

@property (nonatomic,copy) id block;                                                //@synthesize block=_block - In the implementation block
@property (nonatomic,retain) id<FMScheduler> scheduler;                             //@synthesize scheduler=_scheduler - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> accessQueue;              //@synthesize accessQueue=_accessQueue - In the implementation block
@property (assign,nonatomic) BOOL started;                                          //@synthesize started=_started - In the implementation block
-(id)addFailureBlock:(/*^block*/id)arg1 ;
-(void)setScheduler:(id<FMScheduler>)arg1 ;
-(id<FMScheduler>)scheduler;
-(void)setAccessQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)addSuccessBlock:(/*^block*/id)arg1 ;
-(NSObject*<OS_dispatch_queue>)accessQueue;
-(id)addCompletionBlock:(/*^block*/id)arg1 ;
-(void)setStarted:(BOOL)arg1 ;
-(BOOL)started;
-(id)initWithBlock:(/*^block*/id)arg1 scheduler:(id)arg2 ;
-(id)block;
-(void)setBlock:(id)arg1 ;
-(void)_runIfNecessary;
@end

