#import <AvatarKit/AVTAvatarMemoryOptimizer.h>
#import <AvatarKit/AVTCompositorPipeline.h>
#import <AvatarKit/AVTCompositorPipelineCache.h>
#import <AvatarKit/AVTCompositorTextureProvider.h>
#import <AvatarKit/AVTCompositor.h>
#import <AvatarKit/AVTPhysicsRig.h>
#import <AvatarKit/AVTPhysicsController.h>
#import <AvatarKit/AVTAvatarPhysicsState.h>
#import <AvatarKit/AVTFaceTrackingInfo.h>
#import <AvatarKit/AVTFaceTracker.h>
#import <AvatarKit/AVTAsset.h>
#import <AvatarKit/AVTAssetResourceCache.h>
#import <AvatarKit/AVTAssetLibrary.h>
#import <AvatarKit/AVTStickerGeneratorOptions.h>
#import <AvatarKit/AVTStickerGenerator.h>
#import <AvatarKit/AVTStickerConfigurationLocator.h>
#import <AvatarKit/AVTResourceLocator.h>
#import <AvatarKit/AVTMaterial.h>
#import <AvatarKit/AVTStickerCamera.h>
#import <AvatarKit/AVTAvatarPoseAnimation.h>
#import <AvatarKit/AVTAnimoji.h>
#import <AvatarKit/AVTComponentInstance.h>
#import <AvatarKit/AVTARMaskRenderer.h>
#import <AvatarKit/AVTStickerProp.h>
#import <AvatarKit/AVTStickerImageProp.h>
#import <AvatarKit/AVTStickerMovieProp.h>
#import <AvatarKit/AVTStickerSceneProp.h>
#import <AvatarKit/AVTStickerPropAdjustTransformProperty.h>
#import <AvatarKit/AVTComponent.h>
#import <AvatarKit/AVTColorDescription.h>
#import <AvatarKit/AVTColorPreset.h>
#import <AvatarKit/AVTAvatarEnvironment.h>
#import <AvatarKit/AVTStickerConfiguration.h>
#import <AvatarKit/AVTPhysicalizedMorpherDescriptor.h>
#import <AvatarKit/AVTPhysicalizedSkeletonDescriptor.h>
#import <AvatarKit/AVTCorrectiveMorpherDescriptor.h>
#import <AvatarKit/AVTPupilReflectionCorrectionDescriptor.h>
#import <AvatarKit/AVTEyeSkinningDescriptor.h>
#import <AvatarKit/AVTMorpherDrivenMaterialDescriptor.h>
#import <AvatarKit/AVTHUDView.h>
#import <AvatarKit/AVTStickerLogger.h>
#import <AvatarKit/AVTView.h>
#import <AvatarKit/AVTStickerMorpherOverride.h>
#import <AvatarKit/AVTStickerPoseAdjustment.h>
#import <AvatarKit/AVTStickerMoviePropNode.h>
#import <AvatarKit/AVTStickerPresetOverride.h>
#import <AvatarKit/AVTVariantBatchSnapshotter.h>
#import <AvatarKit/AVTSnapshotBuilder.h>
#import <AvatarKit/AVTRenderer.h>
#import <AvatarKit/AVTPresetDependency.h>
#import <AvatarKit/AVTPreset.h>
#import <AvatarKit/AVTMemoji.h>
#import <AvatarKit/AVTImageUtilities.h>
#import <AvatarKit/AVTRecordView.h>
#import <AvatarKit/AVTStickerShaderModifierProperty.h>
#import <AvatarKit/AVTStickerShaderModifier.h>
#import <AvatarKit/AVTAvatarPose.h>
#import <AvatarKit/AVTAvatarPhysicalizedPose.h>
