/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:40:18 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSArray, NSDictionary;

@interface AVTStickerShaderModifier : NSObject {

	BOOL _forceDoubleSided;
	NSString* _entryPoint;
	NSString* _geometryName;
	NSString* _data;
	NSArray* _properties;
	NSDictionary* _dictionary;

}

@property (nonatomic,retain) NSDictionary * dictionary;              //@synthesize dictionary=_dictionary - In the implementation block
@property (nonatomic,readonly) NSString * entryPoint;                //@synthesize entryPoint=_entryPoint - In the implementation block
@property (nonatomic,readonly) NSString * geometryName;              //@synthesize geometryName=_geometryName - In the implementation block
@property (nonatomic,readonly) NSString * data;                      //@synthesize data=_data - In the implementation block
@property (nonatomic,readonly) NSArray * properties;                 //@synthesize properties=_properties - In the implementation block
@property (nonatomic,readonly) BOOL forceDoubleSided;                //@synthesize forceDoubleSided=_forceDoubleSided - In the implementation block
+(id)shaderModifierFromDictionary:(id)arg1 assetsPath:(id)arg2 ;
+(id)entryPointForModifierName:(id)arg1 ;
+(id)shaderModifierCache;
+(id)encapsulateShaderData:(id)arg1 ;
-(void)setDictionary:(NSDictionary *)arg1 ;
-(NSString *)data;
-(NSString *)entryPoint;
-(BOOL)applyToAvatar:(id)arg1 ;
-(NSArray *)properties;
-(NSDictionary *)dictionary;
-(id)description;
-(void)removeFromAvatar:(id)arg1 error:(id*)arg2 ;
-(id)dictionaryWithTargetPath:(id)arg1 ;
-(BOOL)applyToNode:(id)arg1 ;
-(BOOL)applyToNodeHierarchy:(id)arg1 ;
-(id)initWithEntryPoint:(id)arg1 geometryName:(id)arg2 data:(id)arg3 properties:(id)arg4 forceDoubleSided:(BOOL)arg5 ;
-(id)cloneWithProperties:(id)arg1 ;
-(NSString *)geometryName;
-(BOOL)forceDoubleSided;
-(id)findMaterialsForGeometryName:(id)arg1 inAvatar:(id)arg2 ;
-(BOOL)removeFromMaterial:(id)arg1 ;
-(BOOL)applyToMaterial:(id)arg1 ;
@end

