/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:38:54 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/ARKitCore.framework/ARKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSXPCListenerDelegate.h>

@protocol OS_dispatch_queue, ARDaemonServiceListenerDelegate;
@class NSMutableDictionary, NSObject, NSDictionary, NSString;

@interface ARDaemonServiceListener : NSObject <NSXPCListenerDelegate> {

	NSMutableDictionary* _xpcListeners;
	NSMutableDictionary* _serviceClasses;
	NSObject*<OS_dispatch_queue> _serviceQueue;
	BOOL _anonymousListenerEnabled;
	id<ARDaemonServiceListenerDelegate> _delegate;

}

@property (nonatomic,readonly) NSDictionary * listeners; 
@property (nonatomic,__weak,readonly) id<ARDaemonServiceListenerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)getARDaemonServiceSubClasses;
-(BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(id)initWithDelegate:(id)arg1 ;
-(id<ARDaemonServiceListenerDelegate>)delegate;
-(NSDictionary *)listeners;
-(id)initWithDelegate:(id)arg1 enableAnonymousListeners:(BOOL)arg2 ;
-(BOOL)addServiceByName:(id)arg1 serviceClass:(Class)arg2 ;
-(BOOL)createService:(id)arg1 ;
@end

