/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:38:54 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/ARKitCore.framework/ARKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ARKitCore/ARImageBasedTechnique.h>

@class NSUUID;

@interface ARFaceTrackingTechnique : ARImageBasedTechnique {

	NSUUID* _singleUserAnchorIdentifier;
	BOOL _isFaceTracked;
	long long _maximumNumberOfTrackedFaces;

}

@property (assign) BOOL isFaceTracked;                                             //@synthesize isFaceTracked=_isFaceTracked - In the implementation block
@property (nonatomic,readonly) long long maximumNumberOfTrackedFaces;              //@synthesize maximumNumberOfTrackedFaces=_maximumNumberOfTrackedFaces - In the implementation block
+(BOOL)isSupported;
-(id)processData:(id)arg1 ;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(id)resultDataClasses;
-(unsigned long long)requiredSensorDataTypes;
-(long long)maximumNumberOfTrackedFaces;
-(id)initWithMaximumNumberOfTrackedFaces:(long long)arg1 ;
-(BOOL)isFaceTracked;
-(void)setIsFaceTracked:(BOOL)arg1 ;
@end

