#import <MailServices/MSAccounts.h>
#import <MailServices/MSAutosave.h>
#import <MailServices/MSAutosaveSession.h>
#import <MailServices/MSEmailModel.h>
#import <MailServices/MSIdleAutosaveItem.h>
#import <MailServices/MSKeyValueStore.h>
#import <MailServices/MSMailDefaultService.h>
#import <MailServices/MSPushRegistration.h>
#import <MailServices/MSSaveEmail.h>
#import <MailServices/MSCriterion.h>
#import <MailServices/MSSearch.h>
#import <MailServices/MSSendEmail.h>
#import <MailServices/MSService.h>
#import <MailServices/MSXPCConnection.h>
#import <MailServices/_MSXPCRemoteProxy.h>
#import <MailServices/MSXPCEndpoint.h>
#import <MailServices/MSXPCService.h>
