/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:44:01 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/SBSwitcherLiveContentOverlay.h>

@class SBSceneLayoutAnimationWrapperView, UIView, NSString;

@interface SBAnimationWrapperViewLiveContentOverlay : NSObject <SBSwitcherLiveContentOverlay> {

	long long _containerOrientation;
	SBSceneLayoutAnimationWrapperView* _animationWrapperView;

}

@property (nonatomic,readonly) SBSceneLayoutAnimationWrapperView * animationWrapperView;              //@synthesize animationWrapperView=_animationWrapperView - In the implementation block
@property (assign,nonatomic) long long containerOrientation;                                          //@synthesize containerOrientation=_containerOrientation - In the implementation block
@property (nonatomic,readonly) UIView * contentOverlayView; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(long long)containerOrientation;
-(long long)rasterizationStyle;
-(void)setStatusBarHidden:(BOOL)arg1 nubViewHidden:(BOOL)arg2 animator:(/*^block*/id)arg3 ;
-(UIView *)contentOverlayView;
-(void)setUsesBrightSceneViewBackgroundMaterial:(BOOL)arg1 ;
-(void)setContainerOrientation:(long long)arg1 ;
-(void)noteKeyboardFocusDidChangeToSceneID:(id)arg1 ;
-(id)initWithAnimationWrapperView:(id)arg1 ;
-(void)setRasterizationStyle:(long long)arg1 withMinificationFilterEnabled:(BOOL)arg2 ;
-(void)disableAsynchronousRenderingForNextCommit;
-(void)setHomeGrabberHidden:(BOOL)arg1 animated:(BOOL)arg2 ;
-(SBSceneLayoutAnimationWrapperView *)animationWrapperView;
@end

