/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:44:08 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/BSInvalidatable.h>

@class NSString, SBDeviceOrientationUpdateManager;

@interface SBDeviceOrientationUpdateDeferralAssertion : NSObject <BSInvalidatable> {

	BOOL _invalidated;
	NSString* _reason;
	SBDeviceOrientationUpdateManager* _hackyBackReference;

}

@property (assign,setter=_setHackyBackReference:,nonatomic,__weak) SBDeviceOrientationUpdateManager * hackyBackReference;              //@synthesize hackyBackReference=_hackyBackReference - In the implementation block
@property (getter=isInvalidated,nonatomic,readonly) BOOL invalidated;                                                                  //@synthesize invalidated=_invalidated - In the implementation block
@property (nonatomic,copy,readonly) NSString * reason;                                                                                 //@synthesize reason=_reason - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)isInvalidated;
-(id)initWithReason:(id)arg1 ;
-(void)invalidate;
-(void)dealloc;
-(id)init;
-(SBDeviceOrientationUpdateManager *)hackyBackReference;
-(NSString *)reason;
-(NSString *)description;
-(void)_setHackyBackReference:(id)arg1 ;
@end

