/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:44:04 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/BSDescriptionProviding.h>

@class NSSet, NSString;

@interface SBLayoutState : NSObject <BSDescriptionProviding> {

	long long _interfaceOrientation;
	long long _elementInterfaceOrientation;
	NSSet* _elements;

}

@property (nonatomic,readonly) NSSet * elements;                                   //@synthesize elements=_elements - In the implementation block
@property (nonatomic,readonly) long long interfaceOrientation; 
@property (nonatomic,readonly) long long elementInterfaceOrientation; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(long long)_defaultInterfaceOrientation;
-(long long)interfaceOrientation;
-(id)appLayout;
-(id)elementWithIdentifier:(id)arg1 ;
-(BOOL)layoutContainsRole:(long long)arg1 ;
-(BOOL)isEqual:(id)arg1 withRole:(long long)arg2 ;
-(NSSet *)elements;
-(id)floatingAppLayout;
-(id)elementWithRole:(long long)arg1 ;
-(id)descriptionBuilderWithMultilinePrefix:(id)arg1 ;
-(long long)elementInterfaceOrientation;
-(id)init;
-(id)displayItemFromLayoutElement:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)succinctDescriptionBuilder;
-(unsigned long long)hash;
-(id)_initWithLayoutElements:(id)arg1 interfaceOrientation:(long long)arg2 elementInterfaceOrientation:(long long)arg3 ;
-(id)succinctDescription;
-(id)descriptionWithMultilinePrefix:(id)arg1 ;
-(NSString *)description;
@end

