/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:44:11 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface SBShutdownContext : NSObject <NSCopying> {

	NSString* _reason;
	BOOL _fromUserPowerDown;

}

@property (nonatomic,copy,readonly) NSString * reason;              //@synthesize reason=_reason - In the implementation block
@property (assign,nonatomic) BOOL fromUserPowerDown;                //@synthesize fromUserPowerDown=_fromUserPowerDown - In the implementation block
-(id)initWithReason:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setFromUserPowerDown:(BOOL)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(BOOL)fromUserPowerDown;
-(NSString *)reason;
-(id)description;
@end

