#import <SpringBoard/SBAppDeniedAlertItem.h>
#import <SpringBoard/SBRingerVolumeSliderView.h>
#import <SpringBoard/SBDeviceUnlockAggdLogger.h>
#import <SpringBoard/SBPearlInterlockObserver.h>
#import <SpringBoard/SBIconDeleteMetric.h>
#import <SpringBoard/SBTransientOverlayPresentWorkspaceTransaction.h>
#import <SpringBoard/SBSystemGestureSwitchMetric.h>
#import <SpringBoard/SBLoginAppSceneHoster.h>
#import <SpringBoard/SBLoginAppClientSettingObserverContext.h>
#import <SpringBoard/SBAccessibilityMesaUnlockTrigger.h>
#import <SpringBoard/SBReachabilityManager.h>
#import <SpringBoard/SBApplicationStateServiceDelegate.h>
#import <SpringBoard/SBApplicationStateServiceSingleton.h>
#import <SpringBoard/SBPowerDownViewController.h>
#import <SpringBoard/SBAccountStoreManager.h>
#import <SpringBoard/SBHomeGestureDomain.h>
#import <SpringBoard/SBHomeToSwitcherSwitcherModifier.h>
#import <SpringBoard/SBSpotlightCrossblurToFullscreenSwitcherModifier.h>
#import <SpringBoard/SBAppSwitcherPageShadowView.h>
#import <SpringBoard/SBDashBoardPluginViewController.h>
#import <SpringBoard/SpringBoard.h>
#import <SpringBoard/SBTransientActiveInterfaceOrientationRequester.h>
#import <SpringBoard/SBUIController.h>
#import <SpringBoard/SBSceneStatusBarManager.h>
#import <SpringBoard/SBApplicationLaunchNotifyInCallWithoutDataSwitchingAlertItem.h>
#import <SpringBoard/SBApplicationIcon.h>
#import <SpringBoard/SBAppSwitcherServiceManager.h>
#import <SpringBoard/SBWorkspace.h>
#import <SpringBoard/SBMainWorkspace.h>
#import <SpringBoard/SBFluidSwitcherAnimationSettings.h>
#import <SpringBoard/SBDashBoardWallpaperViewProvider.h>
#import <SpringBoard/SBBiometricMonitorUI.h>
#import <SpringBoard/SBHUDViewController.h>
#import <SpringBoard/SBAppSwitcherPageView.h>
#import <SpringBoard/SBIconViewVisibilitySwitcherEventResponse.h>
#import <SpringBoard/SBAlertItemTestRecipe.h>
#import <SpringBoard/SBApplicationTestingManager.h>
#import <SpringBoard/SBPPTSearchGestureObserver.h>
#import <SpringBoard/SBPPTFakeAppSuggestion.h>
#import <SpringBoard/SBWorkspaceTransitionRequest.h>
#import <SpringBoard/SBLockHardwareButtonActions.h>
#import <SpringBoard/SBUIPasscodeViewWithLockScreenStyle.h>
#import <SpringBoard/SBVolumeHardwareButton.h>
#import <SpringBoard/SBHomeGestureToHomeSwitcherModifier.h>
#import <SpringBoard/SBRingerPillView.h>
#import <SpringBoard/SBPearlUnlockTrigger.h>
#import <SpringBoard/SBInCallBannerSceneBackgroundView.h>
#import <SpringBoard/SBPressCollector.h>
#import <SpringBoard/SBApplication.h>
#import <SpringBoard/SBTelephonyManager.h>
#import <SpringBoard/SBInlineGridToFullScreenSwitcherModifier.h>
#import <SpringBoard/SBZoomView.h>
#import <SpringBoard/SBFullscreenZoomView.h>
#import <SpringBoard/SBClippedZoomView.h>
#import <SpringBoard/SBAppSwitcherOrbGestureAnimationSettings.h>
#import <SpringBoard/SBGuidedAccessListener.h>
#import <SpringBoard/SBVolumeControl.h>
#import <SpringBoard/SBUIStartupFromOverlayAnimationController.h>
#import <SpringBoard/SBInlineEmptyGridSwitcherModifier.h>
#import <SpringBoard/SBHUDDomain.h>
#import <SpringBoard/SBHomeToGridSwitcherModifier.h>
#import <SpringBoard/SBContinuityDisplayItem.h>
#import <SpringBoard/SBDeviceApplicationSceneStatusBarStateProvider.h>
#import <SpringBoard/SBHIDInterface.h>
#import <SpringBoard/SBUIStartupToUserSetupAppZoomInAnimationController.h>
#import <SpringBoard/SBGenerateLaunchSnapshotsAlertItem.h>
#import <SpringBoard/SBLaunchSnapshotWaitingAlertItem.h>
#import <SpringBoard/SBDefaultLaunchSnapshotTestRecipe.h>
#import <SpringBoard/SBHardwareButtonGestureParametersProviderBase.h>
#import <SpringBoard/SBRemoteTransientOverlayPresentationRequest.h>
#import <SpringBoard/SBBiometricMonitorPearlDataSource.h>
#import <SpringBoard/SBVolumeHUDViewController.h>
#import <SpringBoard/_SBVolumeHUDViewControllerNullAnimator.h>
#import <SpringBoard/SBSystemPointerInteractionManager.h>
#import <SpringBoard/SBSceneManager.h>
#import <SpringBoard/SBAppSwitcherPageServiceRemoteViewController.h>
#import <SpringBoard/SBRequestFolderSnapshotsSwitcherEventResponse.h>
#import <SpringBoard/SBRemovalSwitcherModifierEvent.h>
#import <SpringBoard/SBDashBoardSetupViewController.h>
#import <SpringBoard/SBSwitcherSwipeUpToSwitcherFloatingSwitcherModifier.h>
#import <SpringBoard/SBHomeGestureDismissableCoverSheetViewController.h>
#import <SpringBoard/SBFloatingSwitcherSettings.h>
#import <SpringBoard/SBSwitcherDisplayItemRemovalResolutionRequest.h>
#import <SpringBoard/SBOrientationAggdLogger.h>
#import <SpringBoard/SBInlineAppExposeLayoutElementViewController.h>
#import <SpringBoard/SBWalletPrearmRecognizer.h>
#import <SpringBoard/SBReduceMotionGridSwitcherModifier.h>
#import <SpringBoard/_SBCameraLaunchCondition.h>
#import <SpringBoard/_SBAggregateCameraLaunchCondition.h>
#import <SpringBoard/SBCameraHardwareButton.h>
#import <SpringBoard/SBCalendarApplicationIcon.h>
#import <SpringBoard/SBIdleTimerProxy.h>
#import <SpringBoard/SBIconLaunchContext.h>
#import <SpringBoard/SBLockScreenAutoUnlockAggregateRule.h>
#import <SpringBoard/SBElasticSliderMaterialWrapperView.h>
#import <SpringBoard/SBSoundPreferences.h>
#import <SpringBoard/SBHomeHardwareButtonLongPressDurationAssertion.h>
#import <SpringBoard/SBBatteryDeviceCountTestRecipe.h>
#import <SpringBoard/SBGreenController.h>
#import <SpringBoard/SBTapToWakeController.h>
#import <SpringBoard/SBCommandTabIconView.h>
#import <SpringBoard/SBRenderOverlayRecipe.h>
#import <SpringBoard/SBDistanceFieldView.h>
#import <SpringBoard/SBSwitcherTransitionRequest.h>
#import <SpringBoard/SBMutableSwitcherTransitionRequest.h>
#import <SpringBoard/SBDashBoardCameraPageViewController.h>
#import <SpringBoard/SBPBAppLayoutList.h>
#import <SpringBoard/SBDataAccessSettings.h>
#import <SpringBoard/SBFolderStatsQueryableMetric.h>
#import <SpringBoard/SBOverrideAppLayoutsSwitcherModifier.h>
#import <SpringBoard/SBLoginAppContainerOverlayWrapperView.h>
#import <SpringBoard/SBEntityRemovalSlideOffscreenSwitcherModifier.h>
#import <SpringBoard/SBUserNotificationCenter.h>
#import <SpringBoard/SBBulletinSpokenObserverGateway.h>
#import <SpringBoard/SBMainDisplaySceneLayoutWindow.h>
#import <SpringBoard/SBSensorActivityAttribution.h>
#import <SpringBoard/SBIdleTimerDescriptorFactory.h>
#import <SpringBoard/SBIdleBehavior.h>
#import <SpringBoard/SBRemoteTransientOverlayDismissalRequest.h>
#import <SpringBoard/SBLegacyVOIPRefreshWakeTracker.h>
#import <SpringBoard/SBInteractiveScreenshotGestureMultiPartAnimation.h>
#import <SpringBoard/_SBLegacyRemoteAlertContentHostViewController.h>
#import <SpringBoard/SBUserNotificationAlert.h>
#import <SpringBoard/_SBUserNotificationImageDescriptor.h>
#import <SpringBoard/SBGradientView.h>
#import <SpringBoard/SBInCallPresentationRequestServer.h>
#import <SpringBoard/_SBInCallPresentationRequestServerTarget.h>
#import <SpringBoard/SBBluetoothAccessoryBatteryMonitor.h>
#import <SpringBoard/SBAppVisibilityPreferences.h>
#import <SpringBoard/SBModalAlertPresentationCoordinator.h>
#import <SpringBoard/SBInCallSettings.h>
#import <SpringBoard/SBIconPageHidingMetric.h>
#import <SpringBoard/SBDisabledIdleTimer.h>
#import <SpringBoard/SBSpotlightTransientOverlayInteractiveGestureTransaction.h>
#import <SpringBoard/SBUISettings.h>
#import <SpringBoard/SBHomeScreenBackdropViewBase.h>
#import <SpringBoard/SBAlertItemsController.h>
#import <SpringBoard/SBApplicationInfo.h>
#import <SpringBoard/SBSwitcherSettingsChangedSwitcherModifierEvent.h>
#import <SpringBoard/SBLaunchImageOverridesContext.h>
#import <SpringBoard/SBDisplayItem.h>
#import <SpringBoard/SBTransitionSwitcherModifierEvent.h>
#import <SpringBoard/SBMainTransitionSwitcherModifierEvent.h>
#import <SpringBoard/SBInlineTransitionSwitcherModifierEvent.h>
#import <SpringBoard/SBBacklightStudyLogger.h>
#import <SpringBoard/SBFluidSwitcherViewController.h>
#import <SpringBoard/SBInCallTestRecipe.h>
#import <SpringBoard/SBRecordingIndicatorWindow.h>
#import <SpringBoard/SBRecordingIndicatorManager.h>
#import <SpringBoard/SBDraggingSystemManager.h>
#import <SpringBoard/SBLowPowerAlertItem.h>
#import <SpringBoard/SBPresentationObservationToken.h>
#import <SpringBoard/SBFixedLayoutModeSwitcherModifier.h>
#import <SpringBoard/SBInteractiveScreenshotGestureRootWindow.h>
#import <SpringBoard/SBHomeToDeckSwitcherModifier.h>
#import <SpringBoard/SBIconListScrollingRecipe.h>
#import <SpringBoard/SBTransientOverlayDismissAllWorkspaceTransaction.h>
#import <SpringBoard/SBUISwitcherAnimationController.h>
#import <SpringBoard/SBPhoneAlertItem.h>
#import <SpringBoard/SBNetworkReselectionAlertItem.h>
#import <SpringBoard/SBIndirectTouchLifecycleMonitor.h>
#import <SpringBoard/SBTransitionSwitcherModifier.h>
#import <SpringBoard/SBExampleUserNotificationCenter.h>
#import <SpringBoard/SBInvalidateReopenButtonTextSwitcherEventResponse.h>
#import <SpringBoard/SBSceneViewStatusBarAssertion.h>
#import <SpringBoard/SBRemoteTransientOverlaySessionManager.h>
#import <SpringBoard/SBRecentDisplayItemsController.h>
#import <SpringBoard/SBWiFiManager.h>
#import <SpringBoard/SBLockdownManager.h>
#import <SpringBoard/SBSyncController.h>
#import <SpringBoard/SBMainSwitcherRootSwitcherModifier.h>
#import <SpringBoard/SBApplicationService.h>
#import <SpringBoard/SBSOSClawGestureObserver.h>
#import <SpringBoard/SBInjectVelocitySwitcherEventResponse.h>
#import <SpringBoard/SBBreadcrumbActionContext.h>
#import <SpringBoard/SBDeviceApplicationSceneStatusBarBreadcrumbProvider.h>
#import <SpringBoard/SBDashBoardIdleTimerProvider.h>
#import <SpringBoard/SBScreenFlash.h>
#import <SpringBoard/SBAppProfileNeedsValidationAlertItem.h>
#import <SpringBoard/SBLockScreenPluginOverlayViewController.h>
#import <SpringBoard/SBUIWorkspaceAnimationController.h>
#import <SpringBoard/SBModalUIFluidDismissGestureWorkspaceTransaction.h>
#import <SpringBoard/SBSpringloadingMetric.h>
#import <SpringBoard/SBEntityRemovalDeclineFloatingSwitcherModifier.h>
#import <SpringBoard/SBIconFlockingMetric.h>
#import <SpringBoard/SBDropApplicationFloatingSwitcherModifier.h>
#import <SpringBoard/SBInCallTransientOverlayManager.h>
#import <SpringBoard/SBAppClipPlaceholderWorkspaceEntity.h>
#import <SpringBoard/_SBSceneLayoutViewControllerAnimator.h>
#import <SpringBoard/SBStatusBarStyleOverridesAssertionManager.h>
#import <SpringBoard/SBApplicationLayoutGestureMetric.h>
#import <SpringBoard/SBFluidSwitcherLayoutContext.h>
#import <SpringBoard/SBPressPrecedenceArbiter.h>
#import <SpringBoard/SBMainSwitcherRoutingSwitcherModifier.h>
#import <SpringBoard/SBRestoreFailureAlertItem.h>
#import <SpringBoard/SBDashBoardThermalStatusProvider.h>
#import <SpringBoard/SBPlatformController.h>
#import <SpringBoard/SBTapAppLayoutSwitcherModifierEvent.h>
#import <SpringBoard/SBIconController.h>
#import <SpringBoard/SBForceTouchAppIconInfoProvider.h>
#import <SpringBoard/SBIconDragPlatterWindow.h>
#import <SpringBoard/SBIconViewSnapshotProvider.h>
#import <SpringBoard/SBHardwareButtonGestureParameters.h>
#import <SpringBoard/SBMutableHardwareButtonGestureParameters.h>
#import <SpringBoard/SBFluidSwitcherGestureWorkspaceTransaction.h>
#import <SpringBoard/SBDismissSiriSwitcherEventResponse.h>
#import <SpringBoard/SBMainDisplayInterfaceOrientationAggregator.h>
#import <SpringBoard/SBHomeGestureSwitcherModifier.h>
#import <SpringBoard/SBScrollToTopSceneProxyView.h>
#import <SpringBoard/SBWidgetDebuggingTestRecipe.h>
#import <SpringBoard/SBKeyboardBrightnessController.h>
#import <SpringBoard/SBSwitcherWallpaperPageContentView.h>
#import <SpringBoard/SBInlineGridSwitcherModifier.h>
#import <SpringBoard/_SBInlineGridFloorSwitcherModifier.h>
#import <SpringBoard/SBBarSwipeAffordanceView.h>
#import <SpringBoard/SBIconModel.h>
#import <SpringBoard/SBNetworkReselectionController.h>
#import <SpringBoard/SBCombinationHardwareButton.h>
#import <SpringBoard/SBEntityRemovalMedusaDefaultAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalMedusaSlideOutAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalMedusaSlideOutUpwardAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalMedusaSlideOutDownwardAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalFloatingDefaultAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalFloatingSlideOutAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalFloatingSlideOutUpwardAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalFloatingSlideOutDownwardAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalDosidoDefaultAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalDosidoSlideOutAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalDosidoSlideOutUpwardAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalDosidoSlideOutDownwardAnimationSettings.h>
#import <SpringBoard/SBEntityRemovalAnimationSettings.h>
#import <SpringBoard/SBAppStatusBarContentAssertion.h>
#import <SpringBoard/SBInCallBannerPresentableViewController.h>
#import <SpringBoard/SBBluetoothController.h>
#import <SpringBoard/SBSplashBoardLaunchRequestProvider.h>
#import <SpringBoard/SBSceneWatchdogProvider.h>
#import <SpringBoard/SBApplicationServer.h>
#import <SpringBoard/_SBPowerAssertionContext.h>
#import <SpringBoard/_SBBatteryLogContext.h>
#import <SpringBoard/SBBatteryLogger.h>
#import <SpringBoard/SBFullScreenSwitcherLiveContentOverlayCoordinator.h>
#import <SpringBoard/SBSceneLayoutLiveContentOverlay.h>
#import <SpringBoard/SBAnimationWrapperViewLiveContentOverlay.h>
#import <SpringBoard/SBDeviceApplicationSceneViewLiveContentOverlay.h>
#import <SpringBoard/_SBFullScreenSwitcherLiveContentOverlayContext.h>
#import <SpringBoard/SBSwitcherDemoFilteringController.h>
#import <SpringBoard/SBGestureRootSwitcherModifier.h>
#import <SpringBoard/SBPreemptAnimationSwitcherEventResponse.h>
#import <SpringBoard/_SBFakeBlurView.h>
#import <SpringBoard/_SBAccessibilityTintView.h>
#import <SpringBoard/SBWallpaperStyleInfo.h>
#import <SpringBoard/SBCameraHardwareButtonDomain.h>
#import <SpringBoard/SBChronoApplicationProcessStateObserver.h>
#import <SpringBoard/SBAccessibilityHardwareButtonInteraction.h>
#import <SpringBoard/SBTestAlertItem.h>
#import <SpringBoard/SBHomeGestureExclusionTrapezoidSettings.h>
#import <SpringBoard/SBSwitcherAccessoryLayoutElement.h>
#import <SpringBoard/SBMediaController.h>
#import <SpringBoard/SBDeviceApplicationSceneEntity.h>
#import <SpringBoard/SBNCNotificationDispatcherDelegate.h>
#import <SpringBoard/SBWeatherApplicationIcon.h>
#import <SpringBoard/SBTestAutomationService.h>
#import <SpringBoard/SBBookmarkIcon.h>
#import <SpringBoard/SBMinimumViableSwitcherTableViewController.h>
#import <SpringBoard/SBDeviceApplicationSceneStatusBarStateProvider_Base.h>
#import <SpringBoard/SBIconContentView.h>
#import <SpringBoard/SBVODController.h>
#import <SpringBoard/SBUIBlockAnimationController.h>
#import <SpringBoard/SBLockScreenPlugin.h>
#import <SpringBoard/SBDashBoardLegibilityProvider.h>
#import <SpringBoard/SBAppSwitcherSystemService.h>
#import <SpringBoard/SBDashBoardApplicationLauncher.h>
#import <SpringBoard/_SBTestRecipeSettings.h>
#import <SpringBoard/_SBTestRecipeDomain.h>
#import <SpringBoard/SBTestRecipeRegistrar.h>
#import <SpringBoard/SBReduceMotionSwitcherModifier.h>
#import <SpringBoard/SBMainSwitcherLiveContentOverlayCoordinator.h>
#import <SpringBoard/SBDeleteNonAppIconAlertItem.h>
#import <SpringBoard/SBWindowLevelAssertion.h>
#import <SpringBoard/SBDashBoardMesaUnlockBehaviorConfiguration.h>
#import <SpringBoard/SBFluidDismissalState.h>
#import <SpringBoard/SBReduceMotionChangedSwitcherModifierEvent.h>
#import <SpringBoard/SBForcePressGestureSwitcherModifier.h>
#import <SpringBoard/SBAppExitedWorkspaceTransaction.h>
#import <SpringBoard/SBUserSessionController.h>
#import <SpringBoard/SBRestartTransitionRequest.h>
#import <SpringBoard/SBMousePointerManager.h>
#import <SpringBoard/_SBProximityTouchHandlingWindow.h>
#import <SpringBoard/_SBProximityTouchHandlingView.h>
#import <SpringBoard/_SBProximityTouchHandlingViewController.h>
#import <SpringBoard/SBNotchedStatusBarProximityBacklightPolicy.h>
#import <SpringBoard/SBWallpaperAggdLogger.h>
#import <SpringBoard/SBSystemAnimationDomain.h>
#import <SpringBoard/SBRemoteTransientOverlayViewController.h>
#import <SpringBoard/SBFluidSwitcherItemContainerHeaderItem.h>
#import <SpringBoard/SBUnlockedAlertItemPresenter.h>
#import <SpringBoard/SBHomeScreenSwitcherModifier.h>
#import <SpringBoard/_SBHomeScreenFloorSwitcherModifier.h>
#import <SpringBoard/SBHUDSettings.h>
#import <SpringBoard/SBEntityRemovalCommitFloatingSwitcherModifier.h>
#import <SpringBoard/SBAccessibilityWindowHostingControllerServer.h>
#import <SpringBoard/_SBAccessibilityWindowHostingControllerServerTarget.h>
#import <SpringBoard/SBAppUnderFloatingSwitcherTransitionSwitcherModifier.h>
#import <SpringBoard/_SBLoadApplicationResult.h>
#import <SpringBoard/SBApplicationController.h>
#import <SpringBoard/SBUnsupportedURLAlertItem.h>
#import <SpringBoard/SBDefaultAuthenticationPolicy.h>
#import <SpringBoard/SBRotationSwitcherModifier.h>
#import <SpringBoard/SBAppSwitcherOrbGestureSettings.h>
#import <SpringBoard/SBSwitcherAppSuggestionBannerView.h>
#import <SpringBoard/SBEntityRemovalDeleteFloatingSwitcherModifier.h>
#import <SpringBoard/SBAVSystemControllerCache.h>
#import <SpringBoard/SBScreenshotManager.h>
#import <SpringBoard/SBPasscodeAlertItem.h>
#import <SpringBoard/SBPasscodeComplianceAlertItem.h>
#import <SpringBoard/SBPasscodeController.h>
#import <SpringBoard/SBCommunicationPolicyManager.h>
#import <SpringBoard/SBInAppStatusBarHiddenAssertion.h>
#import <SpringBoard/SBRecentAppLayoutsPersister.h>
#import <SpringBoard/SBFluidSwitcherGesture.h>
#import <SpringBoard/SBKeyboardSuppressionManager.h>
#import <SpringBoard/SBAppProfileExpiredAlertItem.h>
#import <SpringBoard/SBDashBoardVibrantWallpaperChevronView.h>
#import <SpringBoard/SBBaseStartupTransition.h>
#import <SpringBoard/SBAppProfileNotTrustedAlertItem.h>
#import <SpringBoard/SBTransientOverlayDismissToAppsWorkspaceTransaction.h>
#import <SpringBoard/SBSpotlightDomain.h>
#import <SpringBoard/SBSnapshotTestRecipe.h>
#import <SpringBoard/SBWidgetController.h>
#import <SpringBoard/SBApplicationLaunchNotifyInCallAlertItem.h>
#import <SpringBoard/_SBScreenshotPersistenceCoordinator.h>
#import <SpringBoard/SBMainDisplaySceneLayoutStatusBarView.h>
#import <SpringBoard/SBLockOverlayContext.h>
#import <SpringBoard/SBPPTOperation.h>
#import <SpringBoard/SBInCallDomain.h>
#import <SpringBoard/SBCoverSheetSlidingViewController.h>
#import <SpringBoard/SBAppBrightnessMetric.h>
#import <SpringBoard/SBAppBrightnessMetricData.h>
#import <SpringBoard/SBElasticVolumeViewController.h>
#import <SpringBoard/SBApplicationShortcutService.h>
#import <SpringBoard/SBDashBoardEmergencyDialerController.h>
#import <SpringBoard/SBSystemStatusBatteryDataProvider.h>
#import <SpringBoard/SBInteractiveScreenshotGestureHostWindow.h>
#import <SpringBoard/_SBApplicationLaunchAlertInfo.h>
#import <SpringBoard/SBApplicationLaunchAlertService.h>
#import <SpringBoard/SBHomeScreenService.h>
#import <SpringBoard/SBEntityRemovalToHomeSwitcherModifier.h>
#import <SpringBoard/SBLockScreenDisabledAssertionManager.h>
#import <SpringBoard/SBLoginAppContainerPluginWrapperView.h>
#import <SpringBoard/SBLoginAppContainerPluginWrapperViewController.h>
#import <SpringBoard/SBNCAlertingController.h>
#import <SpringBoard/SBControlCenterModuleTransientOverlayViewController.h>
#import <SpringBoard/SBDockSuggestionsIconListView.h>
#import <SpringBoard/SBFloatingDockSuggestionsViewController.h>
#import <SpringBoard/SBDeviceApplicationSceneClassicAccessoryView.h>
#import <SpringBoard/SBSoftwareUpdateService.h>
#import <SpringBoard/SBCommandTabWindow.h>
#import <SpringBoard/SBCommandTabController.h>
#import <SpringBoard/SBInCallPresentationSession.h>
#import <SpringBoard/SBInCallTransientOverlayPresentationContext.h>
#import <SpringBoard/SBApplicationSceneBackgroundView.h>
#import <SpringBoard/SBExternalDisplayController.h>
#import <SpringBoard/SBNCScreenController.h>
#import <SpringBoard/SBSceneLayoutWindow.h>
#import <SpringBoard/_SBHostedKeyboardViewController.h>
#import <SpringBoard/SBMedusaHostedKeyboardWindow.h>
#import <SpringBoard/SBMedusaHostedKeyboardWindowLevelAssertion.h>
#import <SpringBoard/SBLockOverlayViewController.h>
#import <SpringBoard/SBInCallSceneUpdateWorkspaceTransaction.h>
#import <SpringBoard/SBHarmonySettings.h>
#import <SpringBoard/SBAnalyticsStateMachineEdge.h>
#import <SpringBoard/SBCalendarDownloadingIcon.h>
#import <SpringBoard/SBSwitcherToAppTransitionMetric.h>
#import <SpringBoard/SBBannerGestureRecognizerPriorityAssertion.h>
#import <SpringBoard/SBLogoutDebugBlockingViewController.h>
#import <SpringBoard/SBReloadWallpaperTestRecipe.h>
#import <SpringBoard/SBApplicationSceneEntityDestructionIntent.h>
#import <SpringBoard/SBAssistantPresentationObservationToken.h>
#import <SpringBoard/SBHomeGestureArbiterRecipe.h>
#import <SpringBoard/SBAppFreeDevProfileNotTrustedAlertItem.h>
#import <SpringBoard/SBDeviceApplicationScreenTimeLockoutViewProvider.h>
#import <SpringBoard/SBIdleTimerCoordinatorHelper.h>
#import <SpringBoard/SBIdleTimerInfo.h>
#import <SpringBoard/SBDeckContinuityToFullScreenSwitcherModifier.h>
#import <SpringBoard/SBIconLaunchMetric.h>
#import <SpringBoard/SBSetupManager.h>
#import <SpringBoard/SBMedusaSettingsChangedSwitcherModifierEvent.h>
#import <SpringBoard/SBDosidoSwitcherModifier.h>
#import <SpringBoard/SBIdleTimerFactory.h>
#import <SpringBoard/SBStatusBarStyleOverridesCoordinatorClient.h>
#import <SpringBoard/SBLockScreenActionManager.h>
#import <SpringBoard/SBHomeButtonPressMesaUnlockTrigger.h>
#import <SpringBoard/SBSceneLayoutAnimationWrapperView.h>
#import <SpringBoard/SBSceneLayoutElementAnimationWrapperView.h>
#import <SpringBoard/SBTodayViewController.h>
#import <SpringBoard/SBExternalWifiDefaults.h>
#import <SpringBoard/SBRingerControl.h>
#import <SpringBoard/SBNotifyIconWillZoomDownSwitcherEventResponse.h>
#import <SpringBoard/SBMedusaAppsTestRecipe.h>
#import <SpringBoard/SBiCloudPasscodeRequirementLockoutController.h>
#import <SpringBoard/SBSecureAppPolicy.h>
#import <SpringBoard/SBTestableAlertItemTestRecipe.h>
#import <SpringBoard/SBApplicationUserQuitMonitorServer.h>
#import <SpringBoard/SBAsynchronousRenderingAssertion.h>
#import <SpringBoard/SBTransientOverlayDismissWorkspaceTransaction.h>
#import <SpringBoard/SBBrightnessHUDViewController.h>
#import <SpringBoard/SBDisplayBrightnessController.h>
#import <SpringBoard/SBHUDWindow.h>
#import <SpringBoard/SBHUDController.h>
#import <SpringBoard/_SBHUDModel.h>
#import <SpringBoard/_SBHUDHostViewController.h>
#import <SpringBoard/SBFullScreenToHomeIconZoomSwitcherModifier.h>
#import <SpringBoard/SBSwitcherAppSuggestionViewController.h>
#import <SpringBoard/SBSwitcherAppSuggestionContentView.h>
#import <SpringBoard/SBDataPlanAccountAlertItem.h>
#import <SpringBoard/SBDataPlanUsageAlertItem.h>
#import <SpringBoard/SBWorkspaceEntityRemovalContext.h>
#import <SpringBoard/SBDataPlanDisableAlertItem.h>
#import <SpringBoard/SBDataPlanActivationAlertItem.h>
#import <SpringBoard/SBSceneLayoutWhitePointAdaptationController.h>
#import <SpringBoard/SBDeviceApplicationSceneViewController.h>
#import <SpringBoard/SBDataPlanCompletionAlertItem.h>
#import <SpringBoard/SBHomeGestureInteraction.h>
#import <SpringBoard/SBInteractiveScreenshotGestureCropsView.h>
#import <SpringBoard/SBWidgetMetricsServer.h>
#import <SpringBoard/SBFluidSwitcherButton.h>
#import <SpringBoard/SBFluidSwitcherTitledButton.h>
#import <SpringBoard/SBTransientOverlayDismissAllToAppsWorkspaceTransaction.h>
#import <SpringBoard/SBHomeHardwareButtonActions.h>
#import <SpringBoard/SBScrollSwitcherModifierEvent.h>
#import <SpringBoard/SBFullScreenAppLayoutSwitcherModifier.h>
#import <SpringBoard/_SBFullScreenAppFloorSwitcherModifier.h>
#import <SpringBoard/SBApplicationMultiwindowService.h>
#import <SpringBoard/SBDataPlanFailureAlertItem.h>
#import <SpringBoard/SBApplication32BitDeprecationAlertItem.h>
#import <SpringBoard/SBButtonConsumerClient.h>
#import <SpringBoard/SBButtonConsumerRegistration.h>
#import <SpringBoard/SBHardwareButtonService.h>
#import <SpringBoard/SBIdleTimerAggregateClientConfiguration.h>
#import <SpringBoard/SBIdleTimerConfigurationDisablesTimerSetting.h>
#import <SpringBoard/SBIdleTimerTimeoutPrecedenceSettings.h>
#import <SpringBoard/SBIdleTimerTimeoutRange.h>
#import <SpringBoard/SBAutoUnlockComposableRule.h>
#import <SpringBoard/SBPBDisplayItem.h>
#import <SpringBoard/SBHomeGestureFinalDestinationSwitcherModifier.h>
#import <SpringBoard/SBInCallTransientOverlayViewController.h>
#import <SpringBoard/_SBInCallProxySceneBackgroundView.h>
#import <SpringBoard/SBStartupTransitionController.h>
#import <SpringBoard/SBFairPlayFamilyLeaveAlertItem.h>
#import <SpringBoard/SBForcePressGestureStateTrackingSwitcherModifier.h>
#import <SpringBoard/SBZoomableView.h>
#import <SpringBoard/SBMedusaOrientationTestRecipe.h>
#import <SpringBoard/SBActivatePlusButtonSwitcherEventResponse.h>
#import <SpringBoard/SBFluidSwitcherTouchPassThroughScrollView.h>
#import <SpringBoard/SBFluidSwitcherItemContainer.h>
#import <SpringBoard/SBLayoutStateTransitionCoordinator.h>
#import <SpringBoard/SBBannerUnfurlToFullScreenSwitcherModifier.h>
#import <SpringBoard/SBFailureNotifyingTapGestureRecognizer.h>
#import <SpringBoard/SBSetupRegulatoryInfoViewController.h>
#import <SpringBoard/SBDataPlanAlertItem.h>
#import <SpringBoard/SBDashBoardModalHomeAffordanceControllerClientBridge.h>
#import <SpringBoard/SBDashBoardModalHomeAffordanceController.h>
#import <SpringBoard/SBToggleClassroomPluginTestRecipe.h>
#import <SpringBoard/SBIsolatedSceneOrientationFollowingWindow.h>
#import <SpringBoard/SBIsolatedSceneOrientationFollowingSecureWindow.h>
#import <SpringBoard/SBIsolatedSceneOrientationFollowingWrapperViewController.h>
#import <SpringBoard/SBIsolatedSceneOrientationFollowingContainerView.h>
#import <SpringBoard/SBSceneOrientationFollowingWindowRootViewController.h>
#import <SpringBoard/SBRestartManagerWorkspaceDataSource.h>
#import <SpringBoard/SBCrossblurDosidoSwitcherModifier.h>
#import <SpringBoard/SBCoverSheetIconFlyInAnimator.h>
#import <SpringBoard/_SBDefaultScreenshotProvider.h>
#import <SpringBoard/SBSystemStatusWifiDataProvider.h>
#import <SpringBoard/SBAppSwitcherService.h>
#import <SpringBoard/SBDashBoardViewExternalControllerBase.h>
#import <SpringBoard/SBFailingSystemGestureRecognizer.h>
#import <SpringBoard/SBLongPressGestureRecognizer.h>
#import <SpringBoard/SBFloatingApplicationTestRecipe.h>
#import <SpringBoard/SBPresentCoverSheetRecipe.h>
#import <SpringBoard/SBDataAccessDomain.h>
#import <SpringBoard/SBTransientOverlayPresentationManager.h>
#import <SpringBoard/_SBTransientOverlayPresentedEntity.h>
#import <SpringBoard/SBConferenceManager.h>
#import <SpringBoard/SBExternalSoundsDefaults.h>
#import <SpringBoard/SBNotificationPresentableViewController.h>
#import <SpringBoard/SBWallpaperController.h>
#import <SpringBoard/_SBWallpaperWindow.h>
#import <SpringBoard/SBExternalGlobalDefaults.h>
#import <SpringBoard/SBWalletNotificationSource.h>
#import <SpringBoard/SBHBInitialPressDownGestureRecognizer.h>
#import <SpringBoard/SBHBInitialPressUpGestureRecognizer.h>
#import <SpringBoard/SBHBDoublePressDownGestureRecognizer.h>
#import <SpringBoard/SBHBDoublePressUpGestureRecognizer.h>
#import <SpringBoard/SBHBTriplePressDownGestureRecognizer.h>
#import <SpringBoard/SBHBSinglePressUpGestureRecognizer.h>
#import <SpringBoard/SBHBAcceleratedSinglePressUpGestureRecognizer.h>
#import <SpringBoard/SBHBTriplePressUpGestureRecognizer.h>
#import <SpringBoard/SBHBLongPressGestureRecognizer.h>
#import <SpringBoard/SBHBDoubleTapUpGestureRecognizer.h>
#import <SpringBoard/SBHomeHardwareButtonGestureRecognizerConfiguration.h>
#import <SpringBoard/SBHomeHardwareButton.h>
#import <SpringBoard/SBRotateHomeScreenWorkspaceTransaction.h>
#import <SpringBoard/SBEntityRemovalCrossblurSwitcherModifier.h>
#import <SpringBoard/SBAppSwitcherModel.h>
#import <SpringBoard/SBWorkspaceTransitionContext.h>
#import <SpringBoard/SBRotationLockHUDViewController.h>
#import <SpringBoard/SBRotationLockHUDController.h>
#import <SpringBoard/SBDataPlanExpirationAlertItem.h>
#import <SpringBoard/SBSwitcherCardUpdateTestRecipe.h>
#import <SpringBoard/SBBluetoothAccessoryLowPowerAlertItem.h>
#import <SpringBoard/SBApplicationLaunchNotifyAlertItem.h>
#import <SpringBoard/SBDismissOverlaysAnimationController.h>
#import <SpringBoard/SBHomeGrabberView.h>
#import <SpringBoard/SBHomeGrabberRevealGesturesManager.h>
#import <SpringBoard/SBLiftToWakeController.h>
#import <SpringBoard/SBTransientOverlayWallpaperEffectView.h>
#import <SpringBoard/SBAppSwitcherServicePageContentView.h>
#import <SpringBoard/SBProactiveHomeScreenUsageObserver.h>
#import <SpringBoard/SBOrientationLockManager.h>
#import <SpringBoard/SBStashedHyperrectangle.h>
#import <SpringBoard/SBPIPInteractionController.h>
#import <SpringBoard/SBLockScreenPreviewView.h>
#import <SpringBoard/SBSwitcherToAppExposeSwitcherModifier.h>
#import <SpringBoard/SBSceneLayoutViewController.h>
#import <SpringBoard/SBActivationFailedAlertItem.h>
#import <SpringBoard/SBAppExposeToHomeSwitcherModifier.h>
#import <SpringBoard/SBBacklightIdleTimer.h>
#import <SpringBoard/SBReachabilityDomain.h>
#import <SpringBoard/SBIconVisibilityService.h>
#import <SpringBoard/SBIconStateArchiver.h>
#import <SpringBoard/SBFullScreenFluidSwitcherRootSwitcherModifier.h>
#import <SpringBoard/SBCoverSheetPresentationManager.h>
#import <SpringBoard/SBAppPlatterDragPreview.h>
#import <SpringBoard/SBSplashBoardController.h>
#import <SpringBoard/SBSwipeUpFloatingApplicationGestureWorkspaceTransaction.h>
#import <SpringBoard/SBScreenshotManagerDataSource.h>
#import <SpringBoard/SBLiftToWakeStudyLogger.h>
#import <SpringBoard/SBIconProfileModelMemoryStore.h>
#import <SpringBoard/SBCompleteGestureSwitcherEventResponse.h>
#import <SpringBoard/_SBUIAnimationControllerCoordinatingChildRelationship.h>
#import <SpringBoard/SBUIAnimationController.h>
#import <SpringBoard/SBUIAnimationControllerActivatingAndDeactivatingAppTransitionContextProvider.h>
#import <SpringBoard/SBSnapshotWindow.h>
#import <SpringBoard/SBViewSnapshotProvider.h>
#import <SpringBoard/SBChainableModifierEvent.h>
#import <SpringBoard/SBFluidSwitcherScreenEdgePanGestureRecognizer.h>
#import <SpringBoard/SBFluidSwitcherPanGestureRecognizer.h>
#import <SpringBoard/SBSwitcherToActiveFloatingSwitcherModifier.h>
#import <SpringBoard/SBIdleTimerService.h>
#import <SpringBoard/_SBIdleTimerConfigurationInfo.h>
#import <SpringBoard/SBDropApplicationSwitcherModifier.h>
#import <SpringBoard/SBNotificationBannerDestinationTestActionRunner.h>
#import <SpringBoard/SBStashedFloatingSwitcherModifier.h>
#import <SpringBoard/SBActiveAppLayoutFloatingSwitcherModifier.h>
#import <SpringBoard/_SBActiveAppFloorFloatingSwitcherModifier.h>
#import <SpringBoard/SBHomeGestureRootFloatingSwitcherModifier.h>
#import <SpringBoard/SBHardwareButtonActionList.h>
#import <SpringBoard/SBLockScreenActionContextFactory.h>
#import <SpringBoard/SBUserAgent.h>
#import <SpringBoard/SBPolygon.h>
#import <SpringBoard/SBExternalSettingsDefaults.h>
#import <SpringBoard/SBHomeGesturePanGestureRecognizer.h>
#import <SpringBoard/SBTouchTemplate.h>
#import <SpringBoard/SBDockInteractionMetric.h>
#import <SpringBoard/SBPIPRestoreToFullScreenSwitcherModifier.h>
#import <SpringBoard/SBAnimationUtilities.h>
#import <SpringBoard/SBCAAnimationBlockDelegate.h>
#import <SpringBoard/SBBannerWindow.h>
#import <SpringBoard/SBBackBoardServicesInterface.h>
#import <SpringBoard/SBApplicationSupportServiceDelegate.h>
#import <SpringBoard/SBApplicationSupportServiceSingleton.h>
#import <SpringBoard/SBTouchRegionManager.h>
#import <SpringBoard/SBBarSwipeAffordanceViewController.h>
#import <SpringBoard/SBBiometricKitDefaults.h>
#import <SpringBoard/SBSetupWiFiScanner.h>
#import <SpringBoard/SBTransientOverlayWindow.h>
#import <SpringBoard/SBTransientOverlayBackgroundWindow.h>
#import <SpringBoard/SBHarmonyController.h>
#import <SpringBoard/SBExternalDuetDefaults.h>
#import <SpringBoard/_SBFloatingApplicationLiveContentContainerViewController.h>
#import <SpringBoard/SBFloatingApplicationLiveContentWindow.h>
#import <SpringBoard/SBBiometricMonitorTestRecipeDummyDataSource.h>
#import <SpringBoard/SBBiometricMonitorTestRecipe.h>
#import <SpringBoard/SBInsertionSwitcherModifierEvent.h>
#import <SpringBoard/SBControlCenterWindow.h>
#import <SpringBoard/SBControlCenterController.h>
#import <SpringBoard/SBAnimationStepper.h>
#import <SpringBoard/SBHomeGrabberRotationView.h>
#import <SpringBoard/SBWorkspaceApplicationSceneTransitionContext.h>
#import <SpringBoard/SBExternalDisplayApplicationSceneEntity.h>
#import <SpringBoard/SBLockScreenOrientationManager.h>
#import <SpringBoard/SBPearlInterlockAlertItem.h>
#import <SpringBoard/SBAppSwitcherDomain.h>
#import <SpringBoard/SBInteractiveScreenshotScreenEdgePanGestureRecognizer.h>
#import <SpringBoard/SBDashBoardEmergencyDialerViewController.h>
#import <SpringBoard/SBSiriHardwareButtonInteraction.h>
#import <SpringBoard/SBSuspendedWorkspaceTransaction.h>
#import <SpringBoard/SBDosidoScaleAnimationSwitcherEventResponse.h>
#import <SpringBoard/SBInCallPresentationManager.h>
#import <SpringBoard/SBInCallBannerAuthority.h>
#import <SpringBoard/SBDeactivationSettings.h>
#import <SpringBoard/SBSaturatedIconView.h>
#import <SpringBoard/SBReachabilityWindow.h>
#import <SpringBoard/SBReachabilityBackgroundViewController.h>
#import <SpringBoard/SBReachabilityBackgroundView.h>
#import <SpringBoard/SBLayoutStateTransitionContext.h>
#import <SpringBoard/SBEmitStudyLogSwitcherEventResponse.h>
#import <SpringBoard/SBActivateApplicationTestRecipe.h>
#import <SpringBoard/NCRevealWalletPassActionRunner.h>
#import <SpringBoard/SBLayoutState.h>
#import <SpringBoard/SBInteractiveScreenshotSettings.h>
#import <SpringBoard/SBApplicationSceneRemovalAnimationDomain.h>
#import <SpringBoard/SBAdvanceDateOverrideTestRecipe.h>
#import <SpringBoard/SBStartupTransitionFactory.h>
#import <SpringBoard/SBAnalyticsStateMachineEventHandler.h>
#import <SpringBoard/_SBPendingMesaUnlockBehaviorUnlockRequest.h>
#import <SpringBoard/SBLockScreenBiometricAuthenticationCoordinator.h>
#import <SpringBoard/SBLayoutElementViewController.h>
#import <SpringBoard/SBSpotlightSettings.h>
#import <SpringBoard/SBFluidSwitcherRootSwitcherModifier.h>
#import <SpringBoard/SBClawGestureMetric.h>
#import <SpringBoard/SBClawGestureMetricData.h>
#import <SpringBoard/SBSceneManagerReference.h>
#import <SpringBoard/SBSnapshotDataProviderContext.h>
#import <SpringBoard/SBSceneSnapshotDataProvider.h>
#import <SpringBoard/SBUIImageDataProvider.h>
#import <SpringBoard/SBFallbackSnapshotDataProvider.h>
#import <SpringBoard/SBClickGestureRecognizer.h>
#import <SpringBoard/SBDeveloperBuildExpirationAlert.h>
#import <SpringBoard/SBWebApplication.h>
#import <SpringBoard/SBModelessSyncController.h>
#import <SpringBoard/SBModelessSyncStubs.h>
#import <SpringBoard/SBInCallTransientOverlayPresentationWorkspaceTransaction.h>
#import <SpringBoard/SBAppStatusBarSettingsAssertion.h>
#import <SpringBoard/SBAppUnderFloatingSwitcherSwitcherModifier.h>
#import <SpringBoard/SBMainWorkspaceTransaction.h>
#import <SpringBoard/SBInteractiveScreenshotGestureRootViewController.h>
#import <SpringBoard/_SBInteractiveScreenshotGestureBackdropView.h>
#import <SpringBoard/_SBInteractiveScreenshotGestureReplicatorView.h>
#import <SpringBoard/SBViewMorphAnimatorContentClippingView.h>
#import <SpringBoard/SBViewMorphAnimatorContentBlackCurtainView.h>
#import <SpringBoard/SBViewMorphAnimator.h>
#import <SpringBoard/SBLogoutProgressView.h>
#import <SpringBoard/SBMainSwitcherTestRecipe.h>
#import <SpringBoard/SBNotificationBannerDestination.h>
#import <SpringBoard/SBAttentionAwarenessSettings.h>
#import <SpringBoard/SBAnalyticsCoreAnalyticsEventHandler.h>
#import <SpringBoard/SBDashBoardHomeAffordanceControllerClientBridge.h>
#import <SpringBoard/SBDashBoardHomeAffordanceController.h>
#import <SpringBoard/SBRecalibrateProximitySensorHardwareButtonInteraction.h>
#import <SpringBoard/SBRunWallpaperMigrationTestRecipe.h>
#import <SpringBoard/SBTimerSwitcherModifierEvent.h>
#import <SpringBoard/SBCarDoNotDisturbExitConfirmationAlertItem.h>
#import <SpringBoard/SBActionHandler.h>
#import <SpringBoard/SBPIPContainerViewController.h>
#import <SpringBoard/SBStartupTransitionToHome.h>
#import <SpringBoard/SBExternalDefaults.h>
#import <SpringBoard/SBApplicationSceneViewStatusBarDescriptor.h>
#import <SpringBoard/SBInvalidateAdjustedAppLayoutsSwitcherEventResponse.h>
#import <SpringBoard/SBDeviceApplicationSceneHandle.h>
#import <SpringBoard/SBLockedPointerManager.h>
#import <SpringBoard/SBSpotlightTransientOverlayViewController.h>
#import <SpringBoard/SBSpotlightTransientOverlaySpotlightViewController.h>
#import <SpringBoard/SBRenderImage.h>
#import <SpringBoard/SBWakeToInCallWorkspaceTransaction.h>
#import <SpringBoard/SBAutoPiPWorkspaceTransaction.h>
#import <SpringBoard/SBLockScreenService.h>
#import <SpringBoard/SBHideFolderContentsAlertItem.h>
#import <SpringBoard/SBInlineAppExposeContainerViewController.h>
#import <SpringBoard/UIGestureRecognizerTransformAnalyzerInfo.h>
#import <SpringBoard/UIGestureRecognizerTransformAnalyzer.h>
#import <SpringBoard/SBAppClipPlaceholderLayoutElementViewController.h>
#import <SpringBoard/SBFakeiTunesRestoreTestRecipe.h>
#import <SpringBoard/SBVPPAppRequiresHealingAlertItem.h>
#import <SpringBoard/SBProactiveHomeScreenSuggestionProvider.h>
#import <SpringBoard/SBMainSwitcherViewController.h>
#import <SpringBoard/SBSwipeToKillSwitcherModifierEvent.h>
#import <SpringBoard/SBIconRelayoutRecipe.h>
#import <SpringBoard/SBInCallPresentationSceneUpdateContext.h>
#import <SpringBoard/SBInteractiveScreenshotCommitWorkspaceTransaction.h>
#import <SpringBoard/SBIdleTimerGlobalCoordinator.h>
#import <SpringBoard/SBDaemonHandler.h>
#import <SpringBoard/SBDaemonRequest.h>
#import <SpringBoard/SBDaemonContext.h>
#import <SpringBoard/SBWallpaperEffectViewBase.h>
#import <SpringBoard/_SBMaskingContainerView.h>
#import <SpringBoard/_SBTintView.h>
#import <SpringBoard/SBScreenWakeAnimationController.h>
#import <SpringBoard/SBAlertItemPresentation.h>
#import <SpringBoard/SBFloatingDockController.h>
#import <SpringBoard/SBPresentDockSwitcherEventResponse.h>
#import <SpringBoard/SBLiquidDetectionManager.h>
#import <SpringBoard/SBAppRepairTransaction.h>
#import <SpringBoard/SBReduceMotionForcePressGestureSwitcherModifier.h>
#import <SpringBoard/SBMainDisplayLayoutStateManager.h>
#import <SpringBoard/SBDashBoardPearlUnlockBehavior.h>
#import <SpringBoard/SBTransientOverlayDismissalRequest.h>
#import <SpringBoard/SBMutableTransientOverlayDismissalRequest.h>
#import <SpringBoard/SBFluidSwitcherModifierTimelineViewController.h>
#import <SpringBoard/_SBFluidSwitcherModifierTimelineEntryView.h>
#import <SpringBoard/_SBModifierTimelineDetailViewController.h>
#import <SpringBoard/_SBModifierTimelineModifierDetailViewController.h>
#import <SpringBoard/_SBModifierTimelineTextViewController.h>
#import <SpringBoard/SBLayoutElement.h>
#import <SpringBoard/SBStatusBarForcedHiddenTestRecipe.h>
#import <SpringBoard/SBDashBoardIdleTimerController.h>
#import <SpringBoard/SBLockScreenUnlockRequest.h>
#import <SpringBoard/SBPasscodeEntryTransientOverlayViewController.h>
#import <SpringBoard/SBExternalPhoneDefaults.h>
#import <SpringBoard/SBWaitForSceneContentAvailableTransaction.h>
#import <SpringBoard/SBInitialRestartState.h>
#import <SpringBoard/SBMutableInitialRestartState.h>
#import <SpringBoard/SBInsecureDrawingAlertItemTestRecipe.h>
#import <SpringBoard/SBAppSwitcherServiceSet.h>
#import <SpringBoard/CSConcreteUnlockRequest.h>
#import <SpringBoard/SBDefaultCoverSheetContext.h>
#import <SpringBoard/SBHIDValueModifyingButtonSetArbiter.h>
#import <SpringBoard/SBAirplaneModeController.h>
#import <SpringBoard/SBStartupTransitionContext.h>
#import <SpringBoard/SBLayoutStateManager.h>
#import <SpringBoard/SBAnimationWrapperHostRequester.h>
#import <SpringBoard/SBDashBoardSetupController.h>
#import <SpringBoard/SBIdleTimerBase.h>
#import <SpringBoard/SBReachabilityTestRecipe.h>
#import <SpringBoard/SBGridToActiveAppLayoutsSwitcherModifier.h>
#import <SpringBoard/SBAssistantController.h>
#import <SpringBoard/SBReachabilityMetric.h>
#import <SpringBoard/SBAppSwitcherScrollView.h>
#import <SpringBoard/SBCoverSheetAnimator.h>
#import <SpringBoard/SBProximityBacklightPolicyFactory.h>
#import <SpringBoard/SBBannerUnfurlSourceContext.h>
#import <SpringBoard/SBMutableBannerUnfurlSourceContext.h>
#import <SpringBoard/SBChronoHomeScreenUsageObserver.h>
#import <SpringBoard/SBModalAlertPresenter.h>
#import <SpringBoard/SBAlertItemWindow.h>
#import <SpringBoard/SBSharedModalAlertItemPresenter.h>
#import <SpringBoard/SBPressSequenceSettings.h>
#import <SpringBoard/SBSwipeUpFloatingSwitcherGestureWorkspaceTransaction.h>
#import <SpringBoard/SBDisableActiveInterfaceOrientationChangeAssertion.h>
#import <SpringBoard/SBWallpaperLegibilitySettingsProvider.h>
#import <SpringBoard/SBApplicationWakeScheduler.h>
#import <SpringBoard/SBCoverSheetScreenEdgePanGestureRecognizer.h>
#import <SpringBoard/NCUserAlertActionRunner.h>
#import <SpringBoard/NCUserAlertDefaultActionRunner.h>
#import <SpringBoard/NCUserAlertDismissActionRunner.h>
#import <SpringBoard/SBCameraHardwareButtonSettings.h>
#import <SpringBoard/SBCoverSheetSecureAppEnvironmentViewController.h>
#import <SpringBoard/SBMainDisplayLayoutState.h>
#import <SpringBoard/SBSetupPiPMorphingSwitcherEventResponse.h>
#import <SpringBoard/SBAppLayout.h>
#import <SpringBoard/SBCoverSheetPrimarySlidingViewController.h>
#import <SpringBoard/SBRotateScenesWorkspaceTransaction.h>
#import <SpringBoard/SBInsecureDrawingAlertItem.h>
#import <SpringBoard/SBMedusaDomain.h>
#import <SpringBoard/SBStartupTransitionToLockOut.h>
#import <SpringBoard/SBDashBoardAnalyticsEmitter.h>
#import <SpringBoard/SBProcessSettings.h>
#import <SpringBoard/SBEmitSBEventSwitcherEventResponse.h>
#import <SpringBoard/SBCoverSheetWindow.h>
#import <SpringBoard/SBSecureAppWindow.h>
#import <SpringBoard/SBStackedFloatingSwitcherModifier.h>
#import <SpringBoard/SBHomeScreenBackdropView.h>
#import <SpringBoard/SBTapOutsideToDismissSwitcherModifierEvent.h>
#import <SpringBoard/SBRemoteTransientOverlayHostViewController.h>
#import <SpringBoard/SBPIPAnalytics.h>
#import <SpringBoard/SBPIPAnalyticsAssistant.h>
#import <SpringBoard/SBPIPAnalyticsSourceSummaryAssistant.h>
#import <SpringBoard/SBPIPAnalyticsSessionSummaryAssistant.h>
#import <SpringBoard/SBFluidSwitcherIconOverlayView.h>
#import <SpringBoard/SBIdleTimerPolicyAggregator.h>
#import <SpringBoard/SBTransitionSwitcherModifierRemovalContext.h>
#import <SpringBoard/SBVoiceDisabledBundles.h>
#import <SpringBoard/SBPBAppLayout.h>
#import <SpringBoard/SBSwitcherModifierEventResponse.h>
#import <SpringBoard/SBInteractiveScreenshotGestureHostRootViewController.h>
#import <SpringBoard/SBSceneLayoutSynchronizeTransitionTransaction.h>
#import <SpringBoard/SBSceneLayoutWorkspaceTransaction.h>
#import <SpringBoard/SBSceneClientRotationView.h>
#import <SpringBoard/_SBDeviceApplicationSceneClassicHostWrapperView.h>
#import <SpringBoard/_SBDeviceApplicationSceneClassicHostPositioningView.h>
#import <SpringBoard/SBDeviceApplicationSceneView.h>
#import <SpringBoard/SBSoundController.h>
#import <SpringBoard/SBApplicationBlurContentView.h>
#import <SpringBoard/SBApplicationBlurSnapshotGenerationContainerView.h>
#import <SpringBoard/SBApplicationBlurContentViewBackdropSettings.h>
#import <SpringBoard/SBAlertImageHeaderViewController.h>
#import <SpringBoard/SBImageHeaderAlertItem.h>
#import <SpringBoard/SBDeviceApplicationAppClipOverlayViewProvider.h>
#import <SpringBoard/SBCoverSheetSceneManager.h>
#import <SpringBoard/SBLoginAppContainerView.h>
#import <SpringBoard/SBSpotlightDelegateManager.h>
#import <SpringBoard/SBSpotlightMultiplexingViewController.h>
#import <SpringBoard/SBModifierCacheSelectorList.h>
#import <SpringBoard/SBModifierCacheCoordinator.h>
#import <SpringBoard/SBChainableModifierMethodCache.h>
#import <SpringBoard/SBSOSLockGestureObserver.h>
#import <SpringBoard/SBSensorActivityDataProvider.h>
#import <SpringBoard/SBMoveGestureRootFloatingSwitcherModifier.h>
#import <SpringBoard/SBTouchTemplateGestureRecognizer.h>
#import <SpringBoard/SBTemplateAndMorph.h>
#import <SpringBoard/SBDashBoardNotificationPresenter.h>
#import <SpringBoard/SBSpotlightLegibilityProvider.h>
#import <SpringBoard/SBClockApplicationIcon.h>
#import <SpringBoard/SBAttentionAwarenessClient.h>
#import <SpringBoard/SBVolumeHUDSettings.h>
#import <SpringBoard/SBTodayViewSpotlightPresenter.h>
#import <SpringBoard/_SBTodaySpotlightViewController.h>
#import <SpringBoard/SBCoverSheetBlurView.h>
#import <SpringBoard/SBWallpaperEffectView.h>
#import <SpringBoard/SBFluidSwitcherAnimationController.h>
#import <SpringBoard/SBBulletinLocalObserverGateway.h>
#import <SpringBoard/SBApplicationLaunchAlertEvaluatorForNetworkBasedAlertItems.h>
#import <SpringBoard/SBMainDisplaySystemGestureManager.h>
#import <SpringBoard/SBBiometricMonitorViewController.h>
#import <SpringBoard/SBMedusaSettings.h>
#import <SpringBoard/SBMedusa1oSettings.h>
#import <SpringBoard/SBLogoutProgressTestRecipe.h>
#import <SpringBoard/SBSwitcherKeyboardSuppressionMode.h>
#import <SpringBoard/SBBuddyLockScreenDismissOnlyAlertItem.h>
#import <SpringBoard/SBSecureAppViewController.h>
#import <SpringBoard/SBDismissEmergencyCallRecipe.h>
#import <SpringBoard/SBRemoteAlertHandleLocalClient.h>
#import <SpringBoard/SBSecureAppManager.h>
#import <SpringBoard/SBAutoPurgingImageView.h>
#import <SpringBoard/SBIdleTimerDescriptor.h>
#import <SpringBoard/SBScrollingSwitcherModifier.h>
#import <SpringBoard/SBBlockWorkspaceQueueTestRecipe.h>
#import <SpringBoard/SBDeviceApplicationScenePlaceholderContentContext.h>
#import <SpringBoard/SBMutableDeviceApplicationScenePlaceholderContentContext.h>
#import <SpringBoard/SBDefaultIconModelStore.h>
#import <SpringBoard/SBDefaultAutomaticIconModelStore.h>
#import <SpringBoard/SBFullScreenOcclusionTestRecipe.h>
#import <SpringBoard/SBActivationInfoViewController.h>
#import <SpringBoard/SBApplicationSceneHandleRequest.h>
#import <SpringBoard/SBAppClipOverlayViewController.h>
#import <SpringBoard/SBAppClipOverlayView.h>
#import <SpringBoard/SBRecordingIndicatorViewController.h>
#import <SpringBoard/SBForcePressGestureRootSwitcherModifier.h>
#import <SpringBoard/SBPrototypeDumpingGround.h>
#import <SpringBoard/SBDashBoardPluginController.h>
#import <SpringBoard/SBAppSuggestionManager.h>
#import <SpringBoard/_SBUABestAppSuggestion.h>
#import <SpringBoard/_SBExpertAppSuggestion.h>
#import <SpringBoard/_SBExpertLocationAppSuggestion.h>
#import <SpringBoard/SBUIAnimationPropertyAnimator.h>
#import <SpringBoard/SBTimerEventSwitcherEventResponse.h>
#import <SpringBoard/SBAppContainerViewController.h>
#import <SpringBoard/_SBAppContainerStatusBarStateProxy.h>
#import <SpringBoard/SBTransientOverlayPresentationRequest.h>
#import <SpringBoard/SBMutableTransientOverlayPresentationRequest.h>
#import <SpringBoard/SBFluidSwitcherContentView.h>
#import <SpringBoard/SBIconOverlayVisibilitySwitcherEventResponse.h>
#import <SpringBoard/SBMainWorkspaceApplicationSceneLayoutElementViewController.h>
#import <SpringBoard/SBLongPressDisambiguationAlertItem.h>
#import <SpringBoard/SBSoftwareUpdatePasscodePolicyManager.h>
#import <SpringBoard/SBRebootContext.h>
#import <SpringBoard/SBSwipeMetric.h>
#import <SpringBoard/SBFloatingLowEndHardwareModifier.h>
#import <SpringBoard/SBReverseCountedSemaphore.h>
#import <SpringBoard/SBDeviceApplicationSceneStatusBarStateProxy.h>
#import <SpringBoard/SBDeveloperBuildExpirationTrigger.h>
#import <SpringBoard/SBRingerHUDViewController.h>
#import <SpringBoard/SBBannerAuthority.h>
#import <SpringBoard/SBExternalDemoDefaults.h>
#import <SpringBoard/SBUIFullscreenAnimationView.h>
#import <SpringBoard/SBRootSettings.h>
#import <SpringBoard/SBScrollToAppLayoutSwitcherEventResponse.h>
#import <SpringBoard/SBVoiceControlController.h>
#import <SpringBoard/SBDismissOnlyAlertItem.h>
#import <SpringBoard/SBNotchedStatusBarProximityBacklightPolicyEnablementCondition.h>
#import <SpringBoard/SBApplicationLaunchImageParameters.h>
#import <SpringBoard/SBGridSwipeUpToSwitcherSwitcherModifier.h>
#import <SpringBoard/SBWallpaperPreviewSnapshotCache.h>
#import <SpringBoard/SBModalUIFluidDismissGestureManager.h>
#import <SpringBoard/SBLockStateAggregator.h>
#import <SpringBoard/SBZionUnlockTrigger.h>
#import <SpringBoard/SBAuthenticationFeedback.h>
#import <SpringBoard/SBGridSwitcherSwipeUpGestureWorkspaceTransaction.h>
#import <SpringBoard/SBLockScreenNowPlayingController.h>
#import <SpringBoard/SBInteractiveScreenshotGestureManager.h>
#import <SpringBoard/_SBInteractiveScreenshotGestureSession.h>
#import <SpringBoard/SBLockScreenBatteryChargingViewController.h>
#import <SpringBoard/SBSystemServiceServer.h>
#import <SpringBoard/SBSwipeToKillSwitcherModifier.h>
#import <SpringBoard/SBLegacyLockScreenEnvironment.h>
#import <SpringBoard/SBExternalInlineAppExposeTransitionSwitcherModifier.h>
#import <SpringBoard/SBCoplanarSwitcherModifier.h>
#import <SpringBoard/SBHomeGestureSettingsChangedSwitcherModifierEvent.h>
#import <SpringBoard/SBCoverSheetPanelBackgroundContainerView.h>
#import <SpringBoard/SBCoverSheetParallaxContainerView.h>
#import <SpringBoard/_SBAppSwitcherSnapshotCacheKey.h>
#import <SpringBoard/SBAppSwitcherSnapshotCacheEntry.h>
#import <SpringBoard/_SBAppSwitcherSnapshotImageCacheRequest.h>
#import <SpringBoard/SBAppSwitcherSnapshotImageCache.h>
#import <SpringBoard/SBIdleTimerSettings.h>
#import <SpringBoard/SBLockScreenPluginManager.h>
#import <SpringBoard/SBDashBoardHostedAppViewController.h>
#import <SpringBoard/_SBDashBoardHostedAppStatusBarStateProxy.h>
#import <SpringBoard/SBHomeButtonPressSpeedMesaUnlockTrigger.h>
#import <SpringBoard/SBIdleTimerDomain.h>
#import <SpringBoard/SBDashBoardMesaUnlockBehavior.h>
#import <SpringBoard/SBAppExposeGridSwitcherModifier.h>
#import <SpringBoard/SBSimScrollToIconTestRecipe.h>
#import <SpringBoard/SBSceneManagerCoordinator.h>
#import <SpringBoard/_SBSynchronizeOperation.h>
#import <SpringBoard/SBIPhotoLaunchDeniedAlertItem.h>
#import <SpringBoard/SBActivationSettings.h>
#import <SpringBoard/SBCarDoNotDisturbController.h>
#import <SpringBoard/_SBMainScreenScreenshotProvider.h>
#import <SpringBoard/SBDashBoardWallpaperEffectView.h>
#import <SpringBoard/SBDeckFloatingSwitcherModifier.h>
#import <SpringBoard/SBFluidScrunchGestureRecognizer.h>
#import <SpringBoard/SBAppStatusBarTransitionInfo.h>
#import <SpringBoard/SBDesiredIconStateMetric.h>
#import <SpringBoard/SBCancelableBlockOperation.h>
#import <SpringBoard/SBDisableSystemGestureAssertion.h>
#import <SpringBoard/SBStylusPriorityGestureRecognizer.h>
#import <SpringBoard/SBSystemGestureManager.h>
#import <SpringBoard/SBCoverSheetToAppsWorkspaceTransaction.h>
#import <SpringBoard/SBWallpaperServer.h>
#import <SpringBoard/SBFloatingSwitcherLiveContentOverlayCoordinator.h>
#import <SpringBoard/SBFloatingApplicationSceneLiveContentOverlayView.h>
#import <SpringBoard/SBFloatingApplicationInlineAppExposeLiveContentOverlayView.h>
#import <SpringBoard/SBInlineAppExposeLiveContentOverlayCoordinator.h>
#import <SpringBoard/SBInlineAppExposeLiveContentOverlayView.h>
#import <SpringBoard/SBCameraApplication.h>
#import <SpringBoard/SBKeyboardFocusRedirection.h>
#import <SpringBoard/SBKeyboardFocusHoldAssertion.h>
#import <SpringBoard/SBWorkspaceKeyboardFocusController.h>
#import <SpringBoard/SBDeckSwitcherViewController.h>
#import <SpringBoard/SBSceneBackgroundedStatusAssertion.h>
#import <SpringBoard/SBMedusaConfigurationUsageMetric.h>
#import <SpringBoard/SBMainDisplayWorkspaceAppInteractionEventSource.h>
#import <SpringBoard/SBMedusaDecoratedDeviceApplicationSceneViewController.h>
#import <SpringBoard/SBNubView.h>
#import <SpringBoard/SBArcSwipeFloatingSwitcherModifier.h>
#import <SpringBoard/SBPolicyAggregator.h>
#import <SpringBoard/SBPIPBehaviorOverrideAssertion.h>
#import <SpringBoard/SBPIPWindowLevelOverrideAssertion.h>
#import <SpringBoard/SBPIPEnvironmentDependentOverrideAssertion.h>
#import <SpringBoard/SBPIPStashAssertion.h>
#import <SpringBoard/SBPIPInterruptionAssertion.h>
#import <SpringBoard/SBDismissForEmptySwitcherSwitcherEventResponse.h>
#import <SpringBoard/SBReusableSnapshotItemContainer.h>
#import <SpringBoard/_SBDMPolicyTestAppInfo.h>
#import <SpringBoard/SBScreenTimeTestRecipe.h>
#import <SpringBoard/SBReduceMotionDeckSwitcherModifier.h>
#import <SpringBoard/SBApplicationLaunchAlertEvaluatorFactory.h>
#import <SpringBoard/SBFloatingDockRootViewController.h>
#import <SpringBoard/SBExternalDisplayManager.h>
#import <SpringBoard/SBFullScreenToHomePiPSwitcherModifier.h>
#import <SpringBoard/SBApplicationHarmonyService.h>
#import <SpringBoard/SBLoginAppContainerViewController.h>
#import <SpringBoard/SBAnalyticsAggdInterface.h>
#import <SpringBoard/SBCardItemsController.h>
#import <SpringBoard/SBSwitcherDemoCommandsServer.h>
#import <SpringBoard/SBAlertLayoutPresentationVerifier.h>
#import <SpringBoard/SBLockScreenTemperatureWarningView.h>
#import <SpringBoard/SBBiometricMonitorView.h>
#import <SpringBoard/SBElasticSliderView.h>
#import <SpringBoard/SBApplicationSupportServiceRequestContext.h>
#import <SpringBoard/SBLockToAppStatusBarAnimator.h>
#import <SpringBoard/SBSystemHapticsPreferencesMetric.h>
#import <SpringBoard/SBHomeGestureFloatingSwitcherModifier.h>
#import <SpringBoard/SBBiometricEventLogger.h>
#import <SpringBoard/SBEventObserverRegistry.h>
#import <SpringBoard/SBSpotlightTransitionAnimator.h>
#import <SpringBoard/SBSpotlightTransitionInteractor.h>
#import <SpringBoard/SBAppClipOverlayCoordinator.h>
#import <SpringBoard/SBMatchMoveToIconViewSwitcherEventResponse.h>
#import <SpringBoard/SBUIAnimationControllerAnimator.h>
#import <SpringBoard/SBHomeGestureDockSwitcherModifier.h>
#import <SpringBoard/SBDeviceOrientationUpdateManager.h>
#import <SpringBoard/SBDeviceOrientationUpdateDeferralAssertion.h>
#import <SpringBoard/SBVoiceControlPresentationSource.h>
#import <SpringBoard/SBWindowScene.h>
#import <SpringBoard/SBApplicationSceneSpecification.h>
#import <SpringBoard/SBCoverSheetBiometricResourceObserver.h>
#import <SpringBoard/SBSwitcherSnapshotImageView.h>
#import <SpringBoard/SBDeckSwitcherPanGestureWorkspaceTransaction.h>
#import <SpringBoard/SBTestTransitionSwitcherModifier.h>
#import <SpringBoard/SBSOSEventHandler.h>
#import <SpringBoard/SBSceneDisconnectionManager.h>
#import <SpringBoard/SBSceneLayoutTransitionAnimationController.h>
#import <SpringBoard/SBSceneRotationTransitionAnimationController.h>
#import <SpringBoard/SBApplicationAutoLaunchService.h>
#import <SpringBoard/SBApplicationDropSession.h>
#import <SpringBoard/SBMainScreenActiveInterfaceOrientationWindow.h>
#import <SpringBoard/SBSecureMainScreenActiveInterfaceOrientationWindow.h>
#import <SpringBoard/_SBMainScreenActiveInterfaceOrientationWindowRootViewController.h>
#import <SpringBoard/SBWorkspaceTransientOverlayTransitionContext.h>
#import <SpringBoard/_SBHomeScreenFolderDelegate.h>
#import <SpringBoard/SBPreviewFloatingDockViewController.h>
#import <SpringBoard/SBHomeScreenPreviewView.h>
#import <SpringBoard/SBSiriHardwareButtonEventsOnlyButtonInteraction.h>
#import <SpringBoard/SBTodayIconListLayoutDelegate.h>
#import <SpringBoard/SBReturnToLockscreenWorkspaceTransaction.h>
#import <SpringBoard/SBActivityAttribution.h>
#import <SpringBoard/SBApplicationShortcutPolluterRecipe.h>
#import <SpringBoard/SBHomeScreenBackdropDarkTintView.h>
#import <SpringBoard/SBAppViewController.h>
#import <SpringBoard/SBPriorityDeviceApplicationSceneViewController.h>
#import <SpringBoard/SBTransientOverlayDefaultTransitionContextProvider.h>
#import <SpringBoard/SBBadgeCountRecipe.h>
#import <SpringBoard/SBProactiveLibraryCategoryMapProviderSource.h>
#import <SpringBoard/SBWorkspaceTransientOverlay.h>
#import <SpringBoard/SBWipeSnapshotManifestTestRecipe.h>
#import <SpringBoard/SBHomeScreenView.h>
#import <SpringBoard/SBHomeScreenViewController.h>
#import <SpringBoard/SBWorkspaceTransaction.h>
#import <SpringBoard/SBAppToAppWorkspaceTransaction.h>
#import <SpringBoard/SBAnalyticsAggdSimpleEventHandler.h>
#import <SpringBoard/SBStartupTransitionToApp.h>
#import <SpringBoard/SBDashBoardBiometricUnlockController.h>
#import <SpringBoard/SBLogoutProgressTransientOverlayViewController.h>
#import <SpringBoard/SBGestureSwitcherModifier.h>
#import <SpringBoard/SBCoverSheetSystemGesturesDelegate.h>
#import <SpringBoard/SBAppSwitcherSettings.h>
#import <SpringBoard/SBSystemGestureMetric.h>
#import <SpringBoard/SBSystemGestureUsageMetric.h>
#import <SpringBoard/SBHIDButtonStateArbiter.h>
#import <SpringBoard/SBOmnibusAlertItemTestRecipe.h>
#import <SpringBoard/SBAppResizeGestureWorkspaceTransaction.h>
#import <SpringBoard/SBApplicationSceneHandle.h>
#import <SpringBoard/SBUIStartupFromBlackAnimationController.h>
#import <SpringBoard/SBUserAlertNotificationSource.h>
#import <SpringBoard/SBClientAlertItemTestRecipe.h>
#import <SpringBoard/SBReachabilitySettings.h>
#import <SpringBoard/SBCameraHardwareButtonStudyLogger.h>
#import <SpringBoard/SBDashBoardPolicyBasedBehaviorProvider.h>
#import <SpringBoard/SBRootSceneWindow.h>
#import <SpringBoard/SBSpringBoardApplicationIcon.h>
#import <SpringBoard/SBTransientOverlayBlockTransitionCoordinator.h>
#import <SpringBoard/SBFullScreenToHomeCenterZoomDownSwitcherModifier.h>
#import <SpringBoard/SBActivateAppUnderLockScreenWorkspaceTransaction.h>
#import <SpringBoard/SBCrossfadeDosidoSwitcherModifier.h>
#import <SpringBoard/SBMesaUnlockTrigger.h>
#import <SpringBoard/SBMainDisplaySceneLayoutGestureManager.h>
#import <SpringBoard/SBDashBoardApplicationInformer.h>
#import <SpringBoard/SBFullScreenToHomeSlideOverSwitcherModifier.h>
#import <SpringBoard/SBLockScreenEmergencyCallViewController.h>
#import <SpringBoard/SBSwitcherModelRemovalResults.h>
#import <SpringBoard/SBSwitcherModelRemovalResultAction.h>
#import <SpringBoard/_SBStatusBarLocalDataOverridesWrapper.h>
#import <SpringBoard/SBUIStartupToHomescreenAnimationController.h>
#import <SpringBoard/SBControlCenterPresentationObservationToken.h>
#import <SpringBoard/SBBlurItemContainerSwitcherEventResponse.h>
#import <SpringBoard/SBVoiceControlTransientOverlayViewController.h>
#import <SpringBoard/SBIndirectPanGestureRecognizer.h>
#import <SpringBoard/SBAvocadoDebuggingController.h>
#import <SpringBoard/SBWallpaperStyleRecipe.h>
#import <SpringBoard/SBAlertItemsObjectQueue.h>
#import <SpringBoard/SBSynchronizeCloudCriticalDataOperation.h>
#import <SpringBoard/SBNotificationLongLookBannerPresentationObservationToken.h>
#import <SpringBoard/SBInlineAppExposeRootSwitcherModifier.h>
#import <SpringBoard/SBGrabberTongue.h>
#import <SpringBoard/SBToAppsWorkspaceTransaction.h>
#import <SpringBoard/SBLockHardwareButton.h>
#import <SpringBoard/SBBulletinSystemStateAdapter.h>
#import <SpringBoard/SBCommandTabViewController.h>
#import <SpringBoard/SBBaseStatusBarChangeAssertion.h>
#import <SpringBoard/SBDisableAppStatusBarAlphaChangesAssertion.h>
#import <SpringBoard/SBDisableAppStatusBarUserInteractionChangesAssertion.h>
#import <SpringBoard/SBActivateReachabilitySwitcherEventResponse.h>
#import <SpringBoard/SBMedusaDragAndDropMetric.h>
#import <SpringBoard/SBApplicationWakeSchedulerFactory.h>
#import <SpringBoard/SBVolumeHUDDomain.h>
#import <SpringBoard/SBRecalibrateProximitySensorMultiphaseHardwareButtonInteraction.h>
#import <SpringBoard/SBLineFragment.h>
#import <SpringBoard/SBStringMetrics.h>
#import <SpringBoard/SBFloatingFluidSwitcherRootSwitcherModifier.h>
#import <SpringBoard/SBThermalController.h>
#import <SpringBoard/SBMoveGestureFloatingSwitcherModifier.h>
#import <SpringBoard/SBMainDisplaySceneLayoutDragAndDropInteractionManager.h>
#import <SpringBoard/_SBModalViewControllerStackTransition.h>
#import <SpringBoard/SBModalViewControllerStack.h>
#import <SpringBoard/SBPressSequenceRecognizer.h>
#import <SpringBoard/SBSwitcherModifierEvent.h>
#import <SpringBoard/SBFluidSwitcherModifierTimelineController.h>
#import <SpringBoard/_SBDashBoardSpotlightViewController.h>
#import <SpringBoard/SBDashBoardSpotlightViewController.h>
#import <SpringBoard/_SBSUICFUserNotificationContentHostViewController.h>
#import <SpringBoard/SBPieChartSlice.h>
#import <SpringBoard/SBPieChartView.h>
#import <SpringBoard/SBSwitcherForcePressSystemGestureRecognizer.h>
#import <SpringBoard/SBUpdateLayoutSwitcherEventResponse.h>
#import <SpringBoard/SBAppBrightnessChangeLogger.h>
#import <SpringBoard/SBReduceMotionHomeGestureSwitcherModifier.h>
#import <SpringBoard/SBAppStatusBarSettings.h>
#import <SpringBoard/SBMutableAppStatusBarSettings.h>
#import <SpringBoard/SBMainSwitcherWindow.h>
#import <SpringBoard/SBRemoteTransientOverlaySession.h>
#import <SpringBoard/SBLockScreenDisableAssertion.h>
#import <SpringBoard/SBFluidSwitcherGestureExclusionTrapezoid.h>
#import <SpringBoard/SBFluidSwitcherGestureExclusionCompositeShape.h>
#import <SpringBoard/_SBFluidSwitcherGestureExclusionTrapezoidDebugView.h>
#import <SpringBoard/_SBFluidSwitcherGestureExclusionCompositeShapeDebugView.h>
#import <SpringBoard/SBExternalNotesDefaults.h>
#import <SpringBoard/SBDiagnosticRequestAlertItem.h>
#import <SpringBoard/SBFluidSwitcherIconImageContainerView.h>
#import <SpringBoard/SBGestureSwitcherModifierEvent.h>
#import <SpringBoard/SBScrunchGestureSwitcherModifierEvent.h>
#import <SpringBoard/SBForcePressGestureSwitcherModifierEvent.h>
#import <SpringBoard/SBDragAndDropGestureSwitcherModifierEvent.h>
#import <SpringBoard/SBIndirectPanGestureSwitcherModifierEvent.h>
#import <SpringBoard/SBFluidSwitcherPageContentViewProvider.h>
#import <SpringBoard/SBWindowSelfHostWrapper.h>
#import <SpringBoard/SBDirectToAirPlayController.h>
#import <SpringBoard/_SBDirectToAirPlayPolicyState.h>
#import <SpringBoard/_SBMutableDirectToAirPlayPolicyState.h>
#import <SpringBoard/SBSwitcherDisplayItemRemovalResolutionResults.h>
#import <SpringBoard/SBSwitcherDisplayItemRemovalResolutionResultAction.h>
#import <SpringBoard/SBMainDisplaySceneManager.h>
#import <SpringBoard/SBClientSettingObserverContext.h>
#import <SpringBoard/SBAppClientSettingObserverContext.h>
#import <SpringBoard/SBInternalClientSettingObserverContext.h>
#import <SpringBoard/SBLogWindowController.h>
#import <SpringBoard/SBLogWindowTestRecipe.h>
#import <SpringBoard/SBNotificationCarPlayDestination.h>
#import <SpringBoard/SBForcePressToFullScreenAppLayoutSwitcherModifier.h>
#import <SpringBoard/SBHomeScreenSpotlightViewController.h>
#import <SpringBoard/SBSoftLockoutController.h>
#import <SpringBoard/SBAppLibraryMetric.h>
#import <SpringBoard/SBCollectionViewCell.h>
#import <SpringBoard/SBForcePressToSwitcherSwitcherModifier.h>
#import <SpringBoard/SBMoveFloatingConfigurationFloatingSwitcherModifier.h>
#import <SpringBoard/SBWidgetLaunchStatsTestRecipe.h>
#import <SpringBoard/SBGridToFullScreenSwitcherModifier.h>
#import <SpringBoard/SBAWDMetric.h>
#import <SpringBoard/SBAWDMetricData.h>
#import <SpringBoard/SBLowBatteryLogTestRecipe.h>
#import <SpringBoard/SBFaceContactExpectationManager.h>
#import <SpringBoard/SBStatusBarManager.h>
#import <SpringBoard/SBStatusBarContainer.h>
#import <SpringBoard/SBHapticSwitcherEventResponse.h>
#import <SpringBoard/SBLockOverlayView.h>
#import <SpringBoard/SBMainWorkspaceTransitionRequest.h>
#import <SpringBoard/SBApplicationPlaceholderProxy.h>
#import <SpringBoard/SBSuspendedUnderLockManager.h>
#import <SpringBoard/SBSwitcherModifier.h>
#import <SpringBoard/SBHomeScreenWindow.h>
#import <SpringBoard/SBPortalView.h>
#import <SpringBoard/SBFMotionGestureController.h>
#import <SpringBoard/SBSceneDataStore.h>
#import <SpringBoard/SBPIPWindow.h>
#import <SpringBoard/SBPIPWindowRootViewController.h>
#import <SpringBoard/SBRemovalSwitcherModifier.h>
#import <SpringBoard/SBScheduledAlarmObserver.h>
#import <SpringBoard/SBWorkspaceEntity.h>
#import <SpringBoard/SBPreviousWorkspaceEntity.h>
#import <SpringBoard/SBEmptyWorkspaceEntity.h>
#import <SpringBoard/SBHomeScreenEntity.h>
#import <SpringBoard/SBPocketStateMonitor.h>
#import <SpringBoard/SBInlineFullScreenSwitcherModifier.h>
#import <SpringBoard/SBStatusBarTapManager.h>
#import <SpringBoard/_SBStatusBarTapHandler.h>
#import <SpringBoard/_SBStatusBarTapApplicationDestination.h>
#import <SpringBoard/SBCalendarIconImageProvider.h>
#import <SpringBoard/SBApplicationLaunchNotifyAirplaneModeAlertItem.h>
#import <SpringBoard/SBStateDumpService.h>
#import <SpringBoard/SBHomeGestureSettings.h>
#import <SpringBoard/SBAppStatusBarAssertionManager.h>
#import <SpringBoard/SBAWDQueryableMetric.h>
#import <SpringBoard/SBInlineRotationSwitcherModifier.h>
#import <SpringBoard/SBApplicationSceneViewController.h>
#import <SpringBoard/SBAssistantRootViewController.h>
#import <SpringBoard/SBWebClipService.h>
#import <SpringBoard/SBWindowDragInteraction.h>
#import <SpringBoard/SBRemoveWidgetAlertItem.h>
#import <SpringBoard/SBRebootRecipe.h>
#import <SpringBoard/SBSystemAnimationSettings.h>
#import <SpringBoard/SBDeviceApplicationRemoteTransientOverlayContainerViewController.h>
#import <SpringBoard/SBDeviceApplicationRemoteTransientOverlayPresentationContext.h>
#import <SpringBoard/SBDeviceApplicationRemoteTransientOverlayViewProvider.h>
#import <SpringBoard/SBPressSequenceMetric.h>
#import <SpringBoard/SBPressSequenceMetricData.h>
#import <SpringBoard/SBRestartManager.h>
#import <SpringBoard/SBHIDUILockAssertion.h>
#import <SpringBoard/SBCenterAppIconZoomAnimator.h>
#import <SpringBoard/SBSecureMainDisplaySceneManager.h>
#import <SpringBoard/SBPressSequenceObserver.h>
#import <SpringBoard/SBUIStartupToLoginWindowAnimationController.h>
#import <SpringBoard/SBDeckSwitcherForcePressGestureWorkspaceTransaction.h>
#import <SpringBoard/SBWaitForSceneLayoutTransitionTransaction.h>
#import <SpringBoard/SBPIPContentViewLayoutSettings.h>
#import <SpringBoard/SBGridSwitcherModifier.h>
#import <SpringBoard/_SBGridFloorSwitcherModifier.h>
#import <SpringBoard/SBMainDisplaySceneLayoutViewController.h>
#import <SpringBoard/SBSeparatorNubView.h>
#import <SpringBoard/SBSeparatorView.h>
#import <SpringBoard/SBBreadcrumbMetric.h>
#import <SpringBoard/SBPowerDownView.h>
#import <SpringBoard/SBKeyboardHomeAffordanceController.h>
#import <SpringBoard/SBKeyboardHomeAffordanceAssertion.h>
#import <SpringBoard/SBSleepWakeHardwareButtonInteraction.h>
#import <SpringBoard/SBDoubleClickSleepWakeHardwareButtonInteraction.h>
#import <SpringBoard/SBScreenEdgePanGestureRecognizer.h>
#import <SpringBoard/SBPIPMorphAnimatorDataSource.h>
#import <SpringBoard/SBPIPMorphAnimatorController.h>
#import <SpringBoard/SBBannerManager.h>
#import <SpringBoard/SBLiftToWakeManager.h>
#import <SpringBoard/SBWakeDestination.h>
#import <SpringBoard/SBFaceIDCoachingConditionRecipe.h>
#import <SpringBoard/SBWorkItem.h>
#import <SpringBoard/SBWorkStore.h>
#import <SpringBoard/SBBestAppSuggestion.h>
#import <SpringBoard/SBGridSwipeUpGestureSwitcherModifier.h>
#import <SpringBoard/SBChainableModifier.h>
#import <SpringBoard/SBPresentFloatingDockTestRecipe.h>
#import <SpringBoard/SBDeckSwitcherModifier.h>
#import <SpringBoard/SBApplicationShortcutReportRecipe.h>
#import <SpringBoard/SBApplicationShortcutStore.h>
#import <SpringBoard/SBInsertionSwitcherModifier.h>
#import <SpringBoard/SBIdleTimerGlobalStateMonitor.h>
#import <SpringBoard/_SBIdleTimerGlobalSettingMonitor.h>
#import <SpringBoard/_SBIdleTimerGlobalNumericSettingMonitor.h>
#import <SpringBoard/_SBIdleTimerGlobalBoolSettingMonitor.h>
#import <SpringBoard/SBSwitcherModelRemovalRequest.h>
#import <SpringBoard/SBSwitcherModelRemovalRequestAction.h>
#import <SpringBoard/SBHomeGestureRootSwitcherModifier.h>
#import <SpringBoard/SBDashBoardLockScreenEnvironment.h>
#import <SpringBoard/SBMainDisplayRootWindowScenePresentationBinder.h>
#import <SpringBoard/SBFluidSwitcherGestureManager.h>
#import <SpringBoard/SBApplicationSceneUpdateTransaction.h>
#import <SpringBoard/SBDashBoardSetupView.h>
#import <SpringBoard/SBDismissSiriSwitcherModifier.h>
#import <SpringBoard/SBApplicationSceneEntity.h>
#import <SpringBoard/SBPerformTransitionSwitcherEventResponse.h>
#import <SpringBoard/SBSystemGestureWorkspaceTransaction.h>
#import <SpringBoard/SBMainWorkspaceLayoutStateContingencyPlan.h>
#import <SpringBoard/SBDragAndDropGestureSwitcherModifier.h>
#import <SpringBoard/SBUIMainScreenAnimationController.h>
#import <SpringBoard/SBProximitySensorManager.h>
#import <SpringBoard/SBVolumeHardwareButtonActions.h>
#import <SpringBoard/SBDashBoardSpotlightPresenter.h>
#import <SpringBoard/SBHomeScreenNagAlert.h>
#import <SpringBoard/SBFloatingDockWindowLevelAssertion.h>
#import <SpringBoard/SBInlineAppExposeWorkspaceEntity.h>
#import <SpringBoard/SBBookmark.h>
#import <SpringBoard/SBTodayWidgetXCodeDebuggingUtility.h>
#import <SpringBoard/SBRoundedRectBorderView.h>
#import <SpringBoard/SBSceneViewAppIconView.h>
#import <SpringBoard/SBGridSwitcherViewController.h>
#import <SpringBoard/SBDashBoardPluginView.h>
#import <SpringBoard/SBDashBoardOrientationController.h>
#import <SpringBoard/SBSpuriousScreenUndimmingAssertion.h>
#import <SpringBoard/SBPanSystemGestureRecognizer.h>
#import <SpringBoard/SBRemoteAlertHandleServer.h>
#import <SpringBoard/_SBRemoteAlertHandleServerTarget.h>
#import <SpringBoard/SBIconBlurryBackgroundView.h>
#import <SpringBoard/SBClawGestureLogger.h>
#import <SpringBoard/SBAppSwitcherSnapshotViewState.h>
#import <SpringBoard/SBAppSwitcherReusableSnapshotView.h>
#import <SpringBoard/SBDeviceApplicationSceneViewPlaceholderContentViewProvider.h>
#import <SpringBoard/_SBDeviceApplicationSceneViewPlaceholderContentView.h>
#import <SpringBoard/SBSwitcherPresentationInteractionMetric.h>
#import <SpringBoard/SBAsymmetricalCornerRadiusWrapperView.h>
#import <SpringBoard/SBRouteToAppExposeSwitcherModifier.h>
#import <SpringBoard/SBTouchHistory.h>
#import <SpringBoard/SBHomeGestureToZoomDownSwitcherModifier.h>
#import <SpringBoard/SBReachabilityGestureRecognizer.h>
#import <SpringBoard/SBPIPInterruptionDebouncingTimer.h>
#import <SpringBoard/SBPIPController.h>
#import <SpringBoard/SBInProcessSecureAppAction.h>
#import <SpringBoard/SBExternalSetupDefaults.h>
#import <SpringBoard/SBUIAnimationControllerSteppedAnimator.h>
#import <SpringBoard/SBRecentDisplayItemsDataStore.h>
#import <SpringBoard/SBBatteryDeviceChargeTestRecipe.h>
#import <SpringBoard/_SBDeviceApplicationSceneStatusBarStateProviderObserverRecord.h>
#import <SpringBoard/SBFloatingDockWindow.h>
#import <SpringBoard/SBStatusBarStateAggregator.h>
#import <SpringBoard/SBAppSwitcherSnapshotLockoutViewControllerProvider.h>
#import <SpringBoard/SBMainStatusBarStateProvider.h>
#import <SpringBoard/SBMainStatusBarContentAssertion.h>
#import <SpringBoard/SBPIPInteractionSettingsDomain.h>
#import <SpringBoard/SBPIPInteractionSettings.h>
#import <SpringBoard/SBStatusBarStateProvider.h>
#import <SpringBoard/SBControlCenterRingerSwitchController.h>
#import <SpringBoard/SBDockSuggestionsMetric.h>
#import <SpringBoard/SBArcSwipeSwitcherModifier.h>
#import <SpringBoard/SBChainableModifierEventResponse.h>
#import <SpringBoard/SBChainableModifierTitledEventResponse.h>
#import <SpringBoard/SBFloatingDockBehaviorAssertion.h>
#import <SpringBoard/SBPressTuple.h>
#import <SpringBoard/SBDefaultProximityBacklightPolicy.h>
#import <SpringBoard/SBInteractionAfterWakeMetric.h>
#import <SpringBoard/SBWalletPreArmController.h>
#import <SpringBoard/SBFluidSwitcherAppLayoutHeaderItemController.h>
#import <SpringBoard/SBVolumeControlState.h>
#import <SpringBoard/SBDefaults.h>
#import <SpringBoard/SBDeckToFullScreenSwitcherModifier.h>
#import <SpringBoard/SBDragAndDropAppActivationWorkspaceTransaction.h>
#import <SpringBoard/SBHomeGestureToSwitcherFloatingSwitcherModifier.h>
#import <SpringBoard/SBActivateHomeButtonSwitcherEventResponse.h>
#import <SpringBoard/SBLockScreenContentAssertionTestRecipe.h>
#import <SpringBoard/SBTripleClickSOSMigrationAlertItem.h>
#import <SpringBoard/SBHomeGestureToSwitcherSwitcherModifier.h>
#import <SpringBoard/SBApplicationShortcutStoreManager.h>
#import <SpringBoard/SBInteractiveScreenshotDomain.h>
#import <SpringBoard/SBDeviceApplicationSceneOverlayViewProvider.h>
#import <SpringBoard/SBExternalDisplayPresenter.h>
#import <SpringBoard/SBLowEndHardwareSwitcherModifier.h>
#import <SpringBoard/SBReorderInfoAlert.h>
#import <SpringBoard/SBAssistantActiveInterfaceOrientationWindow.h>
#import <SpringBoard/SBAssistantWindow.h>
#import <SpringBoard/SBSwitcherScrollViewAttributes.h>
#import <SpringBoard/SBMutableSwitcherScrollViewAttributes.h>
#import <SpringBoard/SBSwitcherAnimationAttributes.h>
#import <SpringBoard/SBMutableSwitcherAnimationAttributes.h>
#import <SpringBoard/SBSwitcherLiveContentRasterizationAttributes.h>
#import <SpringBoard/SBMutableSwitcherLiveContentRasterizationAttributes.h>
#import <SpringBoard/SBBlurViewCoordinator.h>
#import <SpringBoard/SBBacklightController.h>
#import <SpringBoard/SBShutdownContext.h>
#import <SpringBoard/SBApplicationRestrictionController.h>
#import <SpringBoard/SBTodayKeepOnHomeScreenPlatterView.h>
#import <SpringBoard/SBSnapshotSlotIdWrapper.h>
#import <SpringBoard/SBFloatingDockSuggestionsModel.h>
#import <SpringBoard/SBStartupTransitionToLoginWindow.h>
#import <SpringBoard/SBPrototypeController.h>
#import <SpringBoard/SBApplicationSceneView.h>
#import <SpringBoard/SBHomeGestureArbiter.h>
#import <SpringBoard/SBHomeGestureParticipant.h>
#import <SpringBoard/SBLockScreenEmergencyDialerController.h>
#import <SpringBoard/SBSlideUpAppGrabberView.h>
#import <SpringBoard/SBNotificationHomeAffordanceController.h>
#import <SpringBoard/SBNotificationKeyboardHomeAffordanceAssertion.h>
#import <SpringBoard/SBSceneViewController.h>
#import <SpringBoard/SBRecycledViewsContainer.h>
#import <SpringBoard/SBMainDisplayWindowLayoutStrategy.h>
#import <SpringBoard/SBWindow.h>
#import <SpringBoard/SBSecureWindow.h>
#import <SpringBoard/SBIgnoredForAutorotationSecureWindow.h>
#import <SpringBoard/SBFluidSwitcherItemContainerHeaderView.h>
#import <SpringBoard/SBIdleTimerBehavior.h>
#import <SpringBoard/SBNCSoundController.h>
#import <SpringBoard/SBHomeScreenTodayViewController.h>
#import <SpringBoard/SBHomeScreenOverlayController.h>
#import <SpringBoard/SBMoveFloatingApplicationGestureWorkspaceTransaction.h>
#import <SpringBoard/SBMainDisplayPolicyAggregator.h>
#import <SpringBoard/SBControlCenterSystemAgent.h>
#import <SpringBoard/SBAppSwitcherTransientOverlayPageContentView.h>
#import <SpringBoard/SBHistorianSwitcherModifier.h>
#import <SpringBoard/SBSwitcherModifierTimelineEntry.h>
#import <SpringBoard/SBSwitcherModifierStackSnapshot.h>
#import <SpringBoard/SBSwitcherModifierEventResponseSnapshot.h>
#import <SpringBoard/SBSwitcherModifierEventSnapshot.h>
#import <SpringBoard/SBSwitcherModifierQuerySnapshot.h>
#import <SpringBoard/SBNewsstandMonitor.h>
#import <SpringBoard/SBPressSequenceValidator.h>
#import <SpringBoard/SBNCNotificationDispatcher.h>
#import <SpringBoard/SBProximitySettings.h>
#import <SpringBoard/SBVoiceControlViewController.h>
#import <SpringBoard/SBGridLayoutSwitcherModifier.h>
#import <SpringBoard/SBApplicationProcessState.h>
#import <SpringBoard/SBWallpaperViewController.h>
#import <SpringBoard/_SBWallpaperViewControllerAssertion.h>
#import <SpringBoard/_SBWallpaperViewControllerScaleAssertion.h>
#import <SpringBoard/SBActivateAppClipFromPlaceholderWorkspaceTransaction.h>
#import <SpringBoard/SBApplicationLibraryObserver.h>
#import <SpringBoard/SBBackgroundFetchTask.h>
#import <SpringBoard/SBBackgroundMultitaskingManager.h>
#import <SpringBoard/SBBackgroundFetchExternalRequest.h>
#import <SpringBoard/SBStartupTransitionContextPersistence.h>
#import <SpringBoard/SBRecordingIndicatorView.h>
#import <SpringBoard/SBTransientOverlayViewController.h>
#import <SpringBoard/SBExternalHomeGestureFloatingSwitcherModifier.h>
#import <SpringBoard/SBEDUTemporarySessionLogoutWarningAlertItem.h>
#import <SpringBoard/SBSceneLayoutCoordinateSpace.h>
#import <SpringBoard/SBSceneLayoutOrientationCoordinateSpace.h>
#import <SpringBoard/SBSceneLayoutFrameCoordinateSpace.h>
#import <SpringBoard/SBLockScreenViewControllerBase.h>
#import <SpringBoard/SBLockScreenManager.h>
#import <SpringBoard/SBWindowHideRequest.h>
#import <SpringBoard/SBWindowHideState.h>
#import <SpringBoard/SBWindowHidingManager.h>
#import <SpringBoard/SBStartupTransitionToSetup.h>
#import <SpringBoard/SBTransaction.h>
#import <SpringBoard/SBDashBoardStatusBarController.h>
#import <SpringBoard/SBRecentAppLayouts.h>
#import <SpringBoard/SBSwitcherSwipeUpGestureFloatingSwitcherModifier.h>
#import <SpringBoard/SBLockedModalAlertItemPresenter.h>
#import <SpringBoard/SBCombinationHardwareButtonActions.h>
#import <SpringBoard/SBCoverSheetPositionView.h>
#import <SpringBoard/SBLockScreenTemperatureWarningViewController.h>
#import <SpringBoard/SBAppExposeToFullScreenSwitcherModifier.h>
#import <SpringBoard/SBDirectToAirPlayTestRecipe.h>
#import <SpringBoard/SBPPTBlockOperation.h>
#import <SpringBoard/SBBiometricsService.h>
#import <SpringBoard/SBHomeScreenOverlayViewController.h>
#import <SpringBoard/SBBiometricAuthenticationPolicy.h>
#import <SpringBoard/SBApplicationPlaceholder.h>
#import <SpringBoard/SBForcePressToHomeSwitcherModifier.h>
#import <SpringBoard/SBDataRecoveryController.h>
#import <SpringBoard/SBApplicationPlaceholderController.h>
#import <SpringBoard/SBDelayedPressInfo.h>
#import <SpringBoard/SBPressGestureStateInfo.h>
#import <SpringBoard/SBPressGestureRecognizer.h>
#import <SpringBoard/SBHideAppIconAlertItem.h>
#import <SpringBoard/SBPPTRunner.h>
