/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:38:08 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PocketAPIDelegate <NSObject>
@optional
-(void)pocketAPI:(id)arg1 receivedRequestToken:(id)arg2;
-(void)pocketAPILoggedIn:(id)arg1;
-(void)pocketAPI:(id)arg1 hadLoginError:(id)arg2;
-(void)pocketAPI:(id)arg1 savedURL:(id)arg2;
-(void)pocketAPI:(id)arg1 failedToSaveURL:(id)arg2 error:(id)arg3;
-(void)pocketAPI:(id)arg1 receivedResponse:(id)arg2 forAPIMethod:(id)arg3 error:(id)arg4;
-(void)pocketAPIDidStartLogin:(id)arg1;
-(void)pocketAPIDidFinishLogin:(id)arg1;
-(void)pocketAPI:(id)arg1 requestedOpenURL:(id)arg2 completionHandler:(/*^block*/id)arg3;

@end

