/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:38:10 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class NSURL, NSArray, NSError, NSFileCoordinator, NSProgress, NSMetadataQuery;

@interface WFiCloudFileDownloadOperation : NSOperation {

	BOOL _executing;
	BOOL _finished;
	NSURL* _fileURL;
	NSArray* _downloadedFiles;
	NSError* _downloadError;
	NSFileCoordinator* _fileCoordinator;
	NSProgress* _progress;
	NSMetadataQuery* _query;

}

@property (nonatomic,readonly) NSFileCoordinator * fileCoordinator;              //@synthesize fileCoordinator=_fileCoordinator - In the implementation block
@property (nonatomic,readonly) NSProgress * progress;                            //@synthesize progress=_progress - In the implementation block
@property (nonatomic,readonly) NSMetadataQuery * query;                          //@synthesize query=_query - In the implementation block
@property (assign,getter=isExecuting,nonatomic) BOOL executing;                  //@synthesize executing=_executing - In the implementation block
@property (assign,getter=isFinished,nonatomic) BOOL finished;                    //@synthesize finished=_finished - In the implementation block
@property (nonatomic,readonly) NSURL * fileURL;                                  //@synthesize fileURL=_fileURL - In the implementation block
@property (nonatomic,readonly) NSArray * downloadedFiles;                        //@synthesize downloadedFiles=_downloadedFiles - In the implementation block
@property (nonatomic,readonly) NSError * downloadError;                          //@synthesize downloadError=_downloadError - In the implementation block
-(NSMetadataQuery *)query;
-(void)setFinished:(BOOL)arg1 ;
-(BOOL)isFinished;
-(BOOL)isExecuting;
-(NSURL *)fileURL;
-(void)queryDidUpdate:(id)arg1 ;
-(void)start;
-(BOOL)isAsynchronous;
-(NSFileCoordinator *)fileCoordinator;
-(NSProgress *)progress;
-(void)setExecuting:(BOOL)arg1 ;
-(NSError *)downloadError;
-(void)queryDidFinishGathering:(id)arg1 ;
-(id)initWithFileURL:(id)arg1 progress:(id)arg2 ;
-(void)getFileInfoForURL:(id)arg1 fileIsUbiquitous:(BOOL*)arg2 fileIsDirectory:(BOOL*)arg3 fileSize:(id*)arg4 error:(id*)arg5 ;
-(void)downloadItemAtFileURL:(id)arg1 ofSize:(id)arg2 fileIsUbiquitous:(BOOL)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)finishRunningWithFiles:(id)arg1 error:(id)arg2 ;
-(NSArray *)downloadedFiles;
@end

