#import <WeatherFoundation/WFDefaultFavoritesProvider.h>
#import <WeatherFoundation/WFNextHourPrecipitationCondition.h>
#import <WeatherFoundation/WFAirQualityRequest.h>
#import <WeatherFoundation/WFWeatherAlmanacRequestFormatterV3.h>
#import <WeatherFoundation/WFUserDefaultsPersistence.h>
#import <WeatherFoundation/WFWeatherStoreServiceConfiguration.h>
#import <WeatherFoundation/WFWeatherEventConfig.h>
#import <WeatherFoundation/WFWeatherStoreCache.h>
#import <WeatherFoundation/WFWeatherEventsConfig.h>
#import <WeatherFoundation/WFWeatherChannelRequestFormatterV2.h>
#import <WeatherFoundation/WFAirQualityProviderStation.h>
#import <WeatherFoundation/WFLocationQueryGeocode.h>
#import <WeatherFoundation/WFWeatherUndergroundRequestFormatter.h>
#import <WeatherFoundation/WFTemperatureUnitObserver.h>
#import <WeatherFoundation/WFWeatherChannelParserV2.h>
#import <WeatherFoundation/WFAirQualityProviderAttributionManager.h>
#import <WeatherFoundation/WFTemperatureUnitResponse.h>
#import <WeatherFoundation/WFAPIConfigurationFactory.h>
#import <WeatherFoundation/WFWeatherHistorical30DaysRequestFormatterV3.h>
#import <WeatherFoundation/WFForecastDataParserUtils.h>
#import <WeatherFoundation/WFParsedForecastData.h>
#import <WeatherFoundation/WFChangeForecastRequest.h>
#import <WeatherFoundation/WFJSONStructureLeafNode.h>
#import <WeatherFoundation/WFWeatherChannelValidator.h>
#import <WeatherFoundation/WFLocationQueryGeocodeCache.h>
#import <WeatherFoundation/WeatherService.h>
#import <WeatherFoundation/WFNextHourPrecipitation.h>
#import <WeatherFoundation/WFAggregateForecastResponse.h>
#import <WeatherFoundation/WFForecastRequest.h>
#import <WeatherFoundation/WFRemoteAppSettings.h>
#import <WeatherFoundation/WFNetworkBehaviorMonitor.h>
#import <WeatherFoundation/WFTemperatureUnitRequest.h>
#import <WeatherFoundation/WFRequestFormattingRules.h>
#import <WeatherFoundation/WFUserInfoManager.h>
#import <WeatherFoundation/WFWeatherAlmanacParserV3.h>
#import <WeatherFoundation/WFGeocodeResponse.h>
#import <WeatherFoundation/WFPollenConditions.h>
#import <WeatherFoundation/WFServiceReachabilityObserver.h>
#import <WeatherFoundation/WFInternalAppSettings.h>
#import <WeatherFoundation/WFAirPollutant.h>
#import <WeatherFoundation/WFWeatherDataServiceRequestFormatterV1.h>
#import <WeatherFoundation/WFTypes.h>
#import <WeatherFoundation/WFWeatherConditions.h>
#import <WeatherFoundation/WFWeatherDataServiceParserV1.h>
#import <WeatherFoundation/WFURLComponents.h>
#import <WeatherFoundation/WFAirQualityConditions.h>
#import <WeatherFoundation/WFSevereWeatherEvent.h>
#import <WeatherFoundation/WFWeatherStoreService.h>
#import <WeatherFoundation/WFAggregateCommonResponse.h>
#import <WeatherFoundation/WFWeatherDataServiceParserMetadataV1.h>
#import <WeatherFoundation/WFAQIScaleCategory.h>
#import <WeatherFoundation/WFAQIScaleATMO.h>
#import <WeatherFoundation/WFAQIScaleCategoryATMO.h>
#import <WeatherFoundation/WFAQIScaleCAQI.h>
#import <WeatherFoundation/WFAQIScaleCategoryCAQI.h>
#import <WeatherFoundation/WFAQIScaleDAQI.h>
#import <WeatherFoundation/WFAQIScaleCategoryDAQI.h>
#import <WeatherFoundation/WFAQIScaleEPA.h>
#import <WeatherFoundation/WFAQIScaleCategoryEPA.h>
#import <WeatherFoundation/WFAQIScaleHJ6332012.h>
#import <WeatherFoundation/WFAQIScaleCategoryHJ6332012.h>
#import <WeatherFoundation/WFAQIScaleIMECA.h>
#import <WeatherFoundation/WFAQIScaleCategoryIMECA.h>
#import <WeatherFoundation/WFAQIScaleNAQI.h>
#import <WeatherFoundation/WFAQIScaleCategoryNAQI.h>
#import <WeatherFoundation/WFAQIScaleUBA.h>
#import <WeatherFoundation/WFAQIScaleCategoryUBA.h>
#import <WeatherFoundation/WFWeatherDataServiceRequestSigner.h>
#import <WeatherFoundation/WFWeatherHistorical1DayParserV2.h>
#import <WeatherFoundation/WFNextHourPrecipitationMinute.h>
#import <WeatherFoundation/WFAirQualityResponse.h>
#import <WeatherFoundation/WFTemperatureUnitChangeRequest.h>
#import <WeatherFoundation/WFWeatherUndergroundParser.h>
#import <WeatherFoundation/WFNetworkEvent.h>
#import <WeatherFoundation/WFHourlyForecastRequest.h>
#import <WeatherFoundation/WFForecastResponse.h>
#import <WeatherFoundation/WFWeatherHistorical1DayRequestFormatterV2.h>
#import <WeatherFoundation/WFFavoriteLocationRequest.h>
#import <WeatherFoundation/WFWeatherChannelAPIConfiguration.h>
#import <WeatherFoundation/WFTaskIdentifier.h>
#import <WeatherFoundation/WFWeatherDataServiceAPIConfiguration.h>
#import <WeatherFoundation/WFQueryDispatcher.h>
#import <WeatherFoundation/WFResourceManager.h>
#import <WeatherFoundation/WFWeatherChannelParserV3.h>
#import <WeatherFoundation/WFResponse.h>
#import <WeatherFoundation/WFNetworkFailTracker.h>
#import <WeatherFoundation/WFNetworkRetryManager.h>
#import <WeatherFoundation/WFChangeForecast.h>
#import <WeatherFoundation/WFTemperature.h>
#import <WeatherFoundation/WFReachabilityConfigurationRequest.h>
#import <WeatherFoundation/WFAirQualityProviderCompletionWrapper.h>
#import <WeatherFoundation/WFAirQualityProviderAttribution.h>
#import <WeatherFoundation/WFWeatherHistorical30DayParserV3.h>
#import <WeatherFoundation/WFLocation.h>
#import <WeatherFoundation/WFDailyForecastRequest.h>
#import <WeatherFoundation/WFGeocodeRequest.h>
#import <WeatherFoundation/WFNextHourPrecipitationDescription.h>
#import <WeatherFoundation/WFAggregateForecastRequest.h>
#import <WeatherFoundation/WFTask.h>
#import <WeatherFoundation/WFWeatherChannelRequestFormatterV3.h>
#import <WeatherFoundation/WFFavoriteLocationResponse.h>
#import <WeatherFoundation/WFAggregateCommonForecast.h>
#import <WeatherFoundation/WFAggregateCommonRequest.h>
#import <WeatherFoundation/WFSettingsManager.h>
#import <WeatherFoundation/WFAttribution.h>
#import <WeatherFoundation/WFResponseParsingRules.h>
#import <WeatherFoundation/WFTemperatureUnitProvider.h>
#import <WeatherFoundation/WFTemperatureFormatter.h>
#import <WeatherFoundation/WFServiceConnection.h>
#import <WeatherFoundation/WFReachabilityConfigurationResponse.h>
