/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:43:41 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TelephonyUI/TPBottomBar.h>

@class TPButton;

@interface TPBottomSingleButtonBar : TPBottomBar {

	id _delegate;
	TPButton* _button;

}
+(id)_backgroundImage;
-(id)button;
-(double)buttonWidth;
-(void)setButton:(id)arg1 andStyle:(BOOL)arg2 ;
@end

