/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:39:37 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/TUCallProviderManagerDelegate.h>

@class NSArray, CHManager, TUCallProviderManager, TUDispatcher, NSMutableSet, NSString;

@interface TUCallHistoryController : NSObject <TUCallProviderManagerDelegate> {

	unsigned long long _coalescingStrategy;
	unsigned long long _options;
	NSArray* _recentCalls;
	unsigned long long _unreadCallCount;
	CHManager* _callHistoryManager;
	TUCallProviderManager* _callProviderManager;
	TUDispatcher* _dispatcher;
	TUDispatcher* _simpleIvarDispatcher;
	NSArray* _thirdPartyCallProviders;
	NSMutableSet* _metadataPreCachedOptions;

}

@property (nonatomic,retain) CHManager * callHistoryManager;                           //@synthesize callHistoryManager=_callHistoryManager - In the implementation block
@property (nonatomic,retain) TUCallProviderManager * callProviderManager;              //@synthesize callProviderManager=_callProviderManager - In the implementation block
@property (nonatomic,retain) TUDispatcher * dispatcher;                                //@synthesize dispatcher=_dispatcher - In the implementation block
@property (nonatomic,retain) TUDispatcher * simpleIvarDispatcher;                      //@synthesize simpleIvarDispatcher=_simpleIvarDispatcher - In the implementation block
@property (nonatomic,retain) NSArray * recentCalls;                                    //@synthesize recentCalls=_recentCalls - In the implementation block
@property (assign,nonatomic) unsigned long long unreadCallCount;                       //@synthesize unreadCallCount=_unreadCallCount - In the implementation block
@property (nonatomic,copy) NSArray * thirdPartyCallProviders;                          //@synthesize thirdPartyCallProviders=_thirdPartyCallProviders - In the implementation block
@property (nonatomic,retain) NSMutableSet * metadataPreCachedOptions;                  //@synthesize metadataPreCachedOptions=_metadataPreCachedOptions - In the implementation block
@property (assign,nonatomic) unsigned long long coalescingStrategy;                    //@synthesize coalescingStrategy=_coalescingStrategy - In the implementation block
@property (assign,nonatomic) unsigned long long options;                               //@synthesize options=_options - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedController;
+(id)callHistoryControllerWithCoalescingStrategy:(unsigned long long)arg1 options:(unsigned long long)arg2 ;
+(id)sharedControllerWithCoalescingStrategy:(unsigned long long)arg1 options:(unsigned long long)arg2 ;
-(void)setDispatcher:(TUDispatcher *)arg1 ;
-(void)setCoalescingStrategy:(unsigned long long)arg1 ;
-(TUDispatcher *)dispatcher;
-(void)setThirdPartyCallProviders:(NSArray *)arg1 ;
-(void)setOptions:(unsigned long long)arg1 ;
-(void)reloadWithOptions:(unsigned long long)arg1 ;
-(id)_callHistoryCoalescingStrategyForCoalescingStrategy:(unsigned long long)arg1 ;
-(void)markRecentAudioCallsAsRead;
-(unsigned long long)options;
-(void)_updateCallHistoryManagerUsingCurrentOptions;
-(void)deleteRecentCall:(id)arg1 ;
-(void)setUnreadCallCount:(unsigned long long)arg1 ;
-(void)dealloc;
-(void)deleteRecentCalls:(id)arg1 ;
-(TUDispatcher *)simpleIvarDispatcher;
-(CHManager *)callHistoryManager;
-(/*^block*/id)callHistoryManagerRecentCallsDispatchBlock;
-(unsigned long long)unreadCallCount;
-(id)initWithCoalescingStrategy:(unsigned long long)arg1 options:(unsigned long long)arg2 ;
-(void)markRecentCallsAsRead;
-(id)recentCallsWithPredicate:(id)arg1 ;
-(void)dispatcherDidFinishBoost:(id)arg1 ;
-(id)init;
-(void)setSimpleIvarDispatcher:(TUDispatcher *)arg1 ;
-(NSMutableSet *)metadataPreCachedOptions;
-(void)setRecentCalls:(NSArray *)arg1 ;
-(void)markRecentVideoCallsAsRead;
-(void)boostQualityOfService;
-(void)setCallHistoryManager:(CHManager *)arg1 ;
-(TUCallProviderManager *)callProviderManager;
-(NSArray *)recentCalls;
-(void)markRecentCallsAsReadWithPredicate:(id)arg1 ;
-(void)setMetadataPreCachedOptions:(NSMutableSet *)arg1 ;
-(NSArray *)thirdPartyCallProviders;
-(void)setCallProviderManager:(TUCallProviderManager *)arg1 ;
-(void)providersChangedForProviderManager:(id)arg1 ;
-(void)deleteAllRecentCalls;
-(/*^block*/id)callHistoryManagerInitializationDispatchBlock;
-(unsigned long long)coalescingStrategy;
-(void)callHistoryDatabaseChanged:(id)arg1 ;
-(void)loadDispatchQueue;
@end

