#import <AVConference/VCMediaNegotiationBlobMultiwayVideoStream.h>
#import <AVConference/VCAudioManager.h>
#import <AVConference/AVCRateController.h>
#import <AVConference/VCNWConnectionCongestionDetector.h>
#import <AVConference/AVCRateControlFeedbackController.h>
#import <AVConference/VCMediaNegotiatorBandwidthConfiguration.h>
#import <AVConference/AVConferenceCallState.h>
#import <AVConference/AVConference.h>
#import <AVConference/VCHardwareSettingsMac.h>
#import <AVConference/VCAudioPowerSpectrum.h>
#import <AVConference/AVCStatisticsCollector.h>
#import <AVConference/VCVideoStreamOWRDLossEventRateControl.h>
#import <AVConference/VCMediaNegotiationBlobMultiwayAudioStream.h>
#import <AVConference/GKNATObserver_SCContext.h>
#import <AVConference/GKNATObserver.h>
#import <AVConference/GKNATObserverInternal.h>
#import <AVConference/VCAudioRelayIO.h>
#import <AVConference/VCAudioRelay.h>
#import <AVConference/VCSessionConfiguration.h>
#import <AVConference/VCAudioStreamCodecConfig.h>
#import <AVConference/AVCRTCPPacket.h>
#import <AVConference/AVCRTCPSenderReport.h>
#import <AVConference/AVCRTCPReceiverReport.h>
#import <AVConference/AVCRTCPSourceDescription.h>
#import <AVConference/VCAudioPowerSpectrumSource.h>
#import <AVConference/GKRingBuffer.h>
#import <AVConference/IPPortWrapper.h>
#import <AVConference/IPv6PrefixWrapper.h>
#import <AVConference/GKSConnectivitySettings.h>
#import <AVConference/VCRedundancyControlAlgorithmVideo.h>
#import <AVConference/VCMediaNegotiatorMultiwayMediaStream.h>
#import <AVConference/GKVoiceChatError.h>
#import <AVConference/VCVideoStreamNOWRDLossEventRateControl.h>
#import <AVConference/VCTransportSessionNW.h>
#import <AVConference/GKInterfaceListener.h>
#import <AVConference/VCRedundancyControlAlgorithmVideoIpadCompanion.h>
#import <AVConference/VCMediaNegotiationBlobBandwidthSettings.h>
#import <AVConference/VCRateControlUtil.h>
#import <AVConference/ICEResultQuery.h>
#import <AVConference/ICEResultWaitQueue.h>
#import <AVConference/VCMomentsHistory.h>
#import <AVConference/VCEmulatedNetworkAlgorithmQueueBandwidth.h>
#import <AVConference/VCMediaNegotiationBlobMomentsSettings.h>
#import <AVConference/VCRateControlAlgorithmSparseNOWRD.h>
#import <AVConference/VCTextStream.h>
#import <AVConference/LoopbackSocketTunnel.h>
#import <AVConference/VCMediaNegotiationBlobAudioSettings.h>
#import <AVConference/VCIDRSchedulerItem.h>
#import <AVConference/VCRedundancyControllerVideo.h>
#import <AVConference/VCMasterKeyIndex.h>
#import <AVConference/VCDisplayLink.h>
#import <AVConference/VCCryptoInfo.h>
#import <AVConference/VCEmulatedNetwork.h>
#import <AVConference/VCVideoStreamTransmitter.h>
#import <AVConference/VCCaptionsClientContext.h>
#import <AVConference/VCCaptionsManagerStreamTokenClientList.h>
#import <AVConference/VCCaptionsManager.h>
#import <AVConference/AVCEffects.h>
#import <AVConference/VCSessionUplinkVideoStreamController.h>
#import <AVConference/AVCPacketFilter.h>
#import <AVConference/AVCPacketFilterRTP.h>
#import <AVConference/VCAudioRuleCollection.h>
#import <AVConference/VCPayloadUtils.h>
#import <AVConference/VCAudioPowerSpectrumManager.h>
#import <AVConference/VCSessionParticipantAudioStreamConfig.h>
#import <AVConference/VCDatagramChannelManager.h>
#import <AVConference/VCDispatchTimer.h>
#import <AVConference/VCAudioStream.h>
#import <AVConference/VCScreenCapture.h>
#import <AVConference/AVCDaemonProcessInfo.h>
#import <AVConference/VCDatagramChannelIDS.h>
#import <AVConference/VCStatsRecorder.h>
#import <AVConference/VCEmulatedNetworkDoubleQueue.h>
#import <AVConference/VCRateControlOWRDEstimator.h>
#import <AVConference/VCDispatchQueue.h>
#import <AVConference/VCEmulatedNetworkElement.h>
#import <AVConference/VCMomentsHistoryBuffer.h>
#import <AVConference/VCMediaStreamManager.h>
#import <AVConference/VCDaemonProcessInfoManager.h>
#import <AVConference/VCVideoRule.h>
#import <AVConference/VCVideoStreamRTTPLRRateControl.h>
#import <AVConference/VCEmulatedPacket.h>
#import <AVConference/VCConnectionLegacy.h>
#import <AVConference/VCImageRotationConverter.h>
#import <AVConference/VCControlChannelFaceTime.h>
#import <AVConference/VCVideoSourceTokenManager.h>
#import <AVConference/VCWifiAssistManager.h>
#import <AVConference/VCMoments.h>
#import <AVConference/VCAudioRedBuilder.h>
#import <AVConference/SDPMini.h>
#import <AVConference/VCMediaNegotiatorLocalConfiguration.h>
#import <AVConference/SenderLargeFrameInfo.h>
#import <AVConference/VCRateControlMediaController.h>
#import <AVConference/VCEmulatedNetworkAlgorithmQueueDelay.h>
#import <AVConference/VCConnection.h>
#import <AVConference/VCCaptionsTranscriptionSegment.h>
#import <AVConference/VCIDRScheduler.h>
#import <AVConference/VCCaptionsTranscriptionBlob.h>
#import <AVConference/VCConnectionManagerLegacy.h>
#import <AVConference/VCRateControlAlgorithmLowLatencyNOWRD.h>
#import <AVConference/VCImageConverterBase.h>
#import <AVConference/AVCVideoFrame.h>
#import <AVConference/VCConnectionSelector.h>
#import <AVConference/VCSessionManager.h>
#import <AVConference/VCSessionUplinkBandwidthAllocator.h>
#import <AVConference/VCDatagramChannelIDSEmulated.h>
#import <AVConference/VCMediaControlInfoGenerator.h>
#import <AVConference/VCAudioPowerSpectrumMeter.h>
#import <AVConference/VCQoSReportSource.h>
#import <AVConference/VCQoSMonitorManager.h>
#import <AVConference/VCMomentsClientContext.h>
#import <AVConference/VCMomentsManagerStreamTokenClientList.h>
#import <AVConference/VCMomentsManager.h>
#import <AVConference/VCAudioSessionClient.h>
#import <AVConference/VCAudioSession.h>
#import <AVConference/VCMomentsCollector.h>
#import <AVConference/VCWRMHandler.h>
#import <AVConference/VCAudioPowerLevelMonitor.h>
#import <AVConference/VCVideoStreamReceiver.h>
#import <AVConference/VCSessionParticipantRemote.h>
#import <AVConference/VCTransportSessionIDS.h>
#import <AVConference/VCVideoReceiverBase.h>
#import <AVConference/VCMovieWriterUtil.h>
#import <AVConference/VCMediaNegotiationBlobVideoSettings.h>
#import <AVConference/VCVideoStreamRateAdaptation.h>
#import <AVConference/VCVideoRuleCollectionsScreenAirplayMac.h>
#import <AVConference/VCCaptionsTranscription.h>
#import <AVConference/VCMediaStreamStats.h>
#import <AVConference/VCSessionErrorUtils.h>
#import <AVConference/VCImageMirroringConverter.h>
#import <AVConference/VCVideoReceiverDefault.h>
#import <AVConference/VCConnectionManager.h>
#import <AVConference/VCVTPWrapper.h>
#import <AVConference/VCRecommendedNetworkSettings.h>
#import <AVConference/VCNetworkFeedbackController.h>
#import <AVConference/VCImageQueue.h>
#import <AVConference/VCAudioClient.h>
#import <AVConference/VideoUtil.h>
#import <AVConference/VCVideoRuleCollectionsScreenSecondary.h>
#import <AVConference/VCBasebandMetrics.h>
#import <AVConference/AVCBasebandCongestionDetector.h>
#import <AVConference/VCSessionBandwidthAllocationTableEntry.h>
#import <AVConference/TCPTunnelClient.h>
#import <AVConference/TCPBufferPool.h>
#import <AVConference/VCCallSession.h>
#import <AVConference/VCCallLinkCongestionDetector.h>
#import <AVConference/VCCapabilities.h>
#import <AVConference/HandleWrapper.h>
#import <AVConference/VideoConference.h>
#import <AVConference/VCCaptionsSegmentBlob.h>
#import <AVConference/VCTransportSessionLegacy.h>
#import <AVConference/VCAudioUnitProperties.h>
#import <AVConference/VCTextReceiver.h>
#import <AVConference/VideoConferenceManager.h>
#import <AVConference/VCAVFoundationCapture.h>
#import <AVConference/VCMediaNegotiationBlob.h>
#import <AVConference/VCVideoTransmitterDefault.h>
#import <AVConference/VCRedundancyControlAlgorithmVideoMultiway.h>
#import <AVConference/SDPMediaLine.h>
#import <AVConference/VCSession.h>
#import <AVConference/VCAudioRelayIOControllerSettings.h>
#import <AVConference/VCAudioRelayIOController.h>
#import <AVConference/VCMediaNegotiatorMultiwayVideoStream.h>
#import <AVConference/VCConnectionIDS.h>
#import <AVConference/VideoAttributes.h>
#import <AVConference/VCSessionParticipantVideoStreamConfig.h>
#import <AVConference/VCRateControlAlgorithmStabilizedNOWRD.h>
#import <AVConference/VCAudioRule.h>
#import <AVConference/VCTextTransmitter.h>
#import <AVConference/VCMediaNegotiatorMultiwayAudioStream.h>
#import <AVConference/VCEmulatedNetworkDoubleQueueReorder.h>
#import <AVConference/VCSessionParticipantLocal.h>
#import <AVConference/VCSessionBitrateArbiter.h>
#import <AVConference/VCTransportSessionSocket.h>
#import <AVConference/VCAudioIO.h>
#import <AVConference/VCStatisticsCollectorQueue.h>
#import <AVConference/VCCameraTorchManager.h>
#import <AVConference/VCPixelTransferSession.h>
#import <AVConference/VCVideoStreamRateAdaptationFeedbackOnly.h>
#import <AVConference/VCEmulatedNetworkQueue.h>
#import <AVConference/AVCCaptionsClient.h>
#import <AVConference/VCAudioIOControllerClient.h>
#import <AVConference/AVAudioDevice.h>
#import <AVConference/AVInternalDeviceList.h>
#import <AVConference/AVAudioDeviceList.h>
#import <AVConference/VCEmulatedNetworkAlgorithmQueueLoss.h>
#import <AVConference/VCSessionParticipantOneToOneConfig.h>
#import <AVConference/VCRedundancyControlAlgorithmAudioMultiWay.h>
#import <AVConference/AVCSessionParticipant.h>
#import <AVConference/AVCVideoDataOutput.h>
#import <AVConference/VCTransportSession.h>
#import <AVConference/VCSpatialAudioUnit.h>
#import <AVConference/VCVideoTransmitterConfig.h>
#import <AVConference/AVCQoSMonitor.h>
#import <AVConference/VCVisualAlert.h>
#import <AVConference/VCRemoteVideoState.h>
#import <AVConference/VCRemoteVideoManager.h>
#import <AVConference/AVCAudioPowerSpectrumChannel.h>
#import <AVConference/VCNetworkSimulator.h>
#import <AVConference/VCMediaNegotiationBlobCaptionsSettings.h>
#import <AVConference/VCMediaStream.h>
#import <AVConference/VCVideoRuleCollectionsMoments.h>
#import <AVConference/VCVideoRuleCollectionsMomentsMac.h>
#import <AVConference/VCVideoRuleCollectionsMomentsEmbeded.h>
#import <AVConference/WRMClient.h>
#import <AVConference/VCVideoRuleCollectionsScreenSecondaryMac.h>
#import <AVConference/AVCCaptionsToken.h>
#import <AVConference/AVCCaptionsResult.h>
#import <AVConference/AVCCaptionsConfig.h>
#import <AVConference/VCVideoDecoder.h>
#import <AVConference/VCImageResizingConverter.h>
#import <AVConference/VCHardwareSettingsEmbedded.h>
#import <AVConference/VCViewpointCorrection.h>
#import <AVConference/VCSwitchManager.h>
#import <AVConference/VCConnectionManagerIDS.h>
#import <AVConference/VCLocalAudioRecordingUtil.h>
#import <AVConference/VCIDRSchedulerStream.h>
#import <AVConference/VCMediaNegotiationBlobVideoPayloadSettings.h>
#import <AVConference/XPCClientUser.h>
#import <AVConference/AVConferenceXPCClient.h>
#import <AVConference/VCVideoRuleCollectionsCameraMac.h>
#import <AVConference/VCSecurityKeyManager.h>
#import <AVConference/VCMediaNegotiatorResults.h>
#import <AVConference/VCMediaNegotiatorAudioResults.h>
#import <AVConference/VCMediaNegotiatorVideoResults.h>
#import <AVConference/VCMediaNegotiatorCaptionsResults.h>
#import <AVConference/VCMediaNegotiatorMomentsResults.h>
#import <AVConference/VCMediaNegotiatorFaceTimeSettingsResults.h>
#import <AVConference/VCMediaNegotiatorMultiwayVideoResults.h>
#import <AVConference/VCMediaNegotiator.h>
#import <AVConference/VCVideoCaptureConverter.h>
#import <AVConference/VCConnectionHealthMonitor.h>
#import <AVConference/VCSessionMediaStreamConfigurationProvider.h>
#import <AVConference/VCPixelBufferOverlay.h>
#import <AVConference/VCVirtualTextDevice.h>
#import <AVConference/VCMediaStreamTransport.h>
#import <AVConference/VCXPCConnection.h>
#import <AVConference/VCXPCServerUser.h>
#import <AVConference/AVConferenceXPCServer.h>
#import <AVConference/VCVideoRuleCollectionsCamera.h>
#import <AVConference/VCMediaStreamMultiwayConfigVideo.h>
#import <AVConference/VCVideoStreamConfig.h>
#import <AVConference/VCXPCClientShared.h>
#import <AVConference/VCEffects.h>
#import <AVConference/AVCTestMonitorReport.h>
#import <AVConference/AVCTestMonitorInjectAudioConfig.h>
#import <AVConference/AVCTestMonitor.h>
#import <AVConference/BitrateLimits.h>
#import <AVConference/VCAudioTierPicker.h>
#import <AVConference/VCVideoRuleCollectionsCameraEmbedded.h>
#import <AVConference/VCImageAttributeRules.h>
#import <AVConference/VCVideoStreamRateController.h>
#import <AVConference/VCControlChannelTransaction.h>
#import <AVConference/VCControlChannelDialog.h>
#import <AVConference/VCControlChannelMultiWay.h>
#import <AVConference/SnapshotTimer.h>
#import <AVConference/VCTextJitterBuffer.h>
#import <AVConference/VCMomentsUtil.h>
#import <AVConference/VCPacketBundler.h>
#import <AVConference/VCVideoQualityInfo.h>
#import <AVConference/VCMediaNegotiatorAudioConfiguration.h>
#import <AVConference/AVCAudioStream.h>
#import <AVConference/VCEmulatedNetworkSingleQueue.h>
#import <AVConference/VCVideoCaptureServer.h>
#import <AVConference/VCSessionDownlinkBandwidthAllocator.h>
#import <AVConference/VCMockIDSDataChannelLinkContext.h>
#import <AVConference/VCMockIDSDatagramChannel.h>
#import <AVConference/VCMockIDSDatagramChannelController.h>
#import <AVConference/VCNetworkAgent.h>
#import <AVConference/AVConferencePreview.h>
#import <AVConference/DTMFEventHandler.h>
#import <AVConference/VCWiFiUtils.h>
#import <AVConference/VCSessionParticipantConfig.h>
#import <AVConference/VCDuplicationHandler.h>
#import <AVConference/VCSecureDataChannel.h>
#import <AVConference/VCIDSSessionInfoSynchronizer.h>
#import <AVConference/VCSessionStatsController.h>
#import <AVConference/CannedAudioInjector.h>
#import <AVConference/AVCPacketRelaySocketConnection.h>
#import <AVConference/AVCPacketRelayIDSConnection.h>
#import <AVConference/AVCPacketRelayConnection.h>
#import <AVConference/AVCPacketRelay.h>
#import <AVConference/CannedAVSync.h>
#import <AVConference/CannedEncodedVideoCapture.h>
#import <AVConference/AVCMediaStreamNegotiator.h>
#import <AVConference/VCMediaStreamSynchronizer.h>
#import <AVConference/AVCTextStream.h>
#import <AVConference/CannedRawVideoCapture.h>
#import <AVConference/SuddenChangeParameters.h>
#import <AVConference/VCRateControlBandwidthEstimator.h>
#import <AVConference/VCRateControlBandwidthEstimatorMap.h>
#import <AVConference/VCRateControlServerBag.h>
#import <AVConference/AVCAudioPowerSpectrumBin.h>
#import <AVConference/VCAudioClientManager.h>
#import <AVConference/VCTransportSessionProxy.h>
#import <AVConference/CannedVideoCapture.h>
#import <AVConference/VCVideoTransmitterBase.h>
#import <AVConference/VCClientRelay.h>
#import <AVConference/VCVideoFrameUtil.h>
#import <AVConference/VCVirtualTTYDevice.h>
#import <AVConference/AVCMoments.h>
#import <AVConference/VCNetworkAgentCell.h>
#import <AVConference/VCMediaNegotiationBlobVideoRuleCollection.h>
#import <AVConference/VCVideoRuleCollectionsScreenAirplayEmbedded.h>
#import <AVConference/VCVideoRuleCollectionsScreen.h>
#import <AVConference/NetworkUtils.h>
#import <AVConference/VCVideoCapture.h>
#import <AVConference/VCTransportSessionIDSMultiLink.h>
#import <AVConference/VCSpatialAudioIOController.h>
#import <AVConference/VCMovieWriter.h>
#import <AVConference/VCAudioStreamTransport.h>
#import <AVConference/VCAudioPowerSpectrumBin.h>
#import <AVConference/VCAudioPayload.h>
#import <AVConference/VCVideoStream.h>
#import <AVConference/VCAudioTier.h>
#import <AVConference/VCSessionMessaging.h>
#import <AVConference/VCNetworkAddress.h>
#import <AVConference/VCMediaStreamMultiwayConfig.h>
#import <AVConference/VCMediaStreamRateControlConfig.h>
#import <AVConference/VCMediaStreamConfig.h>
#import <AVConference/VCLinkProbingResult.h>
#import <AVConference/VCVideoFeatureListStringHelper.h>
#import <AVConference/SIPClientDataDictionary.h>
#import <AVConference/VCSessionMessageTopic.h>
#import <AVConference/VCRedundancyControlAlgorithmAudioLegacy.h>
#import <AVConference/AVCAudioPowerSpectrum.h>
#import <AVConference/VCLinkProbingHandler.h>
#import <AVConference/VideoScaler.h>
#import <AVConference/VCSessionParticipantMediaStreamInfo.h>
#import <AVConference/VCCallInfo.h>
#import <AVConference/VCCameraPreview.h>
#import <AVConference/VCVideoRelay.h>
#import <AVConference/AVCAudioPowerSpectrumMeter.h>
#import <AVConference/VCServerBag.h>
#import <AVConference/VCRedundancyControlAlgorithmAudio.h>
#import <AVConference/VCIDRSchedulerPeriodGroup.h>
#import <AVConference/VCAudioTransmitterConfig.h>
#import <AVConference/AVCMomentsRequest.h>
#import <AVConference/VCMediaStreamMultiwayConfigAudio.h>
#import <AVConference/VCAudioStreamConfig.h>
#import <AVConference/VCTestMonitorManager.h>
#import <AVConference/VCCaptionsReceiver.h>
#import <AVConference/VCFigAssetWriter.h>
#import <AVConference/VCImageRotationConverterBase.h>
#import <AVConference/VCRedundancyControllerAudio.h>
#import <AVConference/AVCRemoteVideoClient.h>
#import <AVConference/VCBitrateRule.h>
#import <AVConference/VCBitrateArbiter.h>
#import <AVConference/AVCPacketRelayDriver.h>
#import <AVConference/CameraConferenceSynchronizer.h>
#import <AVConference/VCMediaNegotiationFaceTimeSettings.h>
#import <AVConference/VCStatisticsHistory.h>
#import <AVConference/LogDumpUtility.h>
#import <AVConference/AVCSessionConfiguration.h>
#import <AVConference/VCVideoFrameBufferPool.h>
#import <AVConference/VCAudioTransmitter.h>
#import <AVConference/VCCallInfoBlob.h>
#import <AVConference/VCEmulatedOutputQueue.h>
#import <AVConference/AVTelephonyInterface.h>
#import <AVConference/AVCVirtualTTYDevice.h>
#import <AVConference/VCAudioPayloadConfig.h>
#import <AVConference/VCTransportStreamGFT.h>
#import <AVConference/VCSessionBandwidthAllocationTable.h>
#import <AVConference/VCEffectsManager.h>
#import <AVConference/VCDefaults.h>
#import <AVConference/VCControlChannel.h>
#import <AVConference/VCMediaControlInfo.h>
#import <AVConference/VCMediaControlInfoIPCamera.h>
#import <AVConference/VCMediaControlInfoFaceTimeAudio.h>
#import <AVConference/VCMediaControlInfoFaceTimeVideo.h>
#import <AVConference/VCMediaControlInfoMultiwayAudio.h>
#import <AVConference/VCVideoRuleCollectionsScreenSecondaryEmbedded.h>
#import <AVConference/AVCSession.h>
#import <AVConference/AVCVideoStream.h>
#import <AVConference/VCTextStreamConfig.h>
#import <AVConference/VCObject.h>
#import <AVConference/VCHardwareOperatingModeSettings.h>
#import <AVConference/VCHardwareSettings.h>
#import <AVConference/VCVideoRuleCollectionKey.h>
#import <AVConference/VCVideoRuleCollections.h>
#import <AVConference/VCSessionParticipant.h>
#import <AVConference/VCAudioSessionMediaProperties.h>
#import <AVConference/VCTransportSessionIDSSingleLink.h>
#import <AVConference/AVCNetworkAddress.h>
#import <AVConference/AVCMediaStreamConfig.h>
#import <AVConference/AVCAudioStreamConfig.h>
#import <AVConference/AVCVideoStreamConfig.h>
#import <AVConference/AVCTextStreamConfig.h>
#import <AVConference/VCWCMClient.h>
#import <AVConference/SDPParser.h>
#import <AVConference/VCTransport.h>
#import <AVConference/VCVideoRuleCollectionsScreenAirplay.h>
#import <AVConference/AVAudioClient.h>
