/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:47:02 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/AVConference.framework/AVConference
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AVConference/AVConference-Structs.h>
#import <AVConference/VCObject.h>

@protocol VCControlChannelTransactionDelegate;
@class NSData, NSNumber;

@interface VCControlChannelTransaction : VCObject {

	NSData* _data;
	unsigned _sessionID;
	NSNumber* _participantID;
	opaque_pthread_mutex_t _transactionLock;
	opaque_pthread_cond_t _transactionDone;
	BOOL _isConfirmed;
	BOOL _isFlushed;
	id<VCControlChannelTransactionDelegate> _weakTransactionDelegate;

}
+(BOOL)sendUnreliableMessage:(id)arg1 sessionID:(unsigned)arg2 participantID:(id)arg3 transactionDelegate:(id)arg4 ;
-(void)dealloc;
-(id)initWithTransportSessionID:(unsigned)arg1 transactionData:(id)arg2 participantID:(id)arg3 transactionDelegate:(id)arg4 ;
-(void)flushTransactions;
-(void)confirmedTransactionByParticipantID:(id)arg1 sessionID:(unsigned)arg2 ;
-(BOOL)sendReliableMessage:(id)arg1 sessionID:(unsigned)arg2 participantID:(id)arg3 timeout:(id)arg4 ;
@end

