/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:47:03 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/AVConference.framework/AVConference
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol VCVideoCaptureConverterDelegate <NSObject>
@required
-(void)converter:(id)arg1 didConvertFrame:(opaqueCMSampleBufferRef)arg2 frameTime:(SCD_Struct_VC84)arg3 cameraStatusBits:(unsigned char)arg4;

@end

