/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:40:00 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@protocol NSCopyingNSObjectNSSecureCoding;
@class NSString, TIKeyboardTouchEvent, TIKeyboardCandidate;

@interface TIKeyboardInput : NSObject <NSSecureCoding> {

	SCD_Union_TI5 _flags;
	BOOL _backspace;
	NSString* _string;
	id<NSCopying><NSObject><NSSecureCoding> _object;
	TIKeyboardTouchEvent* _touchEvent;
	TIKeyboardCandidate* _acceptedCandidate;
	NSString* _inputManagerHint;
	long long _transliterationType;
	double _timestamp;

}

@property (nonatomic,copy) NSString * string;                                                                            //@synthesize string=_string - In the implementation block
@property (nonatomic,copy) id<NSCopying><NSObject><NSSecureCoding> object;                                               //@synthesize object=_object - In the implementation block
@property (assign,getter=isBackspace,nonatomic) BOOL backspace;                                                          //@synthesize backspace=_backspace - In the implementation block
@property (assign,getter=isUppercase,nonatomic) BOOL uppercase; 
@property (assign,getter=isAutoshifted,nonatomic) BOOL autoshifted; 
@property (assign,getter=isPopupVariant,nonatomic) BOOL popupVariant; 
@property (assign,getter=isMultitap,nonatomic) BOOL multitap; 
@property (assign,getter=isFlick,nonatomic) BOOL flick; 
@property (assign,getter=isGesture,nonatomic) BOOL gesture; 
@property (assign,getter=isSynthesizedByAcceptingCandidate,nonatomic) BOOL synthesizedByAcceptingCandidate; 
@property (assign,getter=isDoubleSpace,nonatomic) BOOL doubleSpace; 
@property (assign,getter=isRapidDelete,nonatomic) BOOL rapidDelete; 
@property (assign,getter=isShiftDown,nonatomic) BOOL shiftDown; 
@property (nonatomic,retain) TIKeyboardTouchEvent * touchEvent;                                                          //@synthesize touchEvent=_touchEvent - In the implementation block
@property (assign,nonatomic) long long transliterationType;                                                              //@synthesize transliterationType=_transliterationType - In the implementation block
@property (nonatomic,retain) TIKeyboardCandidate * acceptedCandidate;                                                    //@synthesize acceptedCandidate=_acceptedCandidate - In the implementation block
@property (nonatomic,copy) NSString * inputManagerHint;                                                                  //@synthesize inputManagerHint=_inputManagerHint - In the implementation block
@property (assign,nonatomic) double timestamp;                                                                           //@synthesize timestamp=_timestamp - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSString *)string;
-(void)setObject:(id<NSCopying><NSObject><NSSecureCoding>)arg1 ;
-(BOOL)isFlick;
-(void)setString:(NSString *)arg1 ;
-(BOOL)isUppercase;
-(BOOL)isMultitap;
-(void)setGesture:(BOOL)arg1 ;
-(BOOL)isDoubleSpace;
-(void)setDoubleSpace:(BOOL)arg1 ;
-(BOOL)isRapidDelete;
-(void)setRapidDelete:(BOOL)arg1 ;
-(NSString *)inputManagerHint;
-(long long)transliterationType;
-(void)setTransliterationType:(long long)arg1 ;
-(double)timestamp;
-(void)setFlick:(BOOL)arg1 ;
-(void)setTimestamp:(double)arg1 ;
-(void)setTouchEvent:(TIKeyboardTouchEvent *)arg1 ;
-(BOOL)isPopupVariant;
-(void)setInputManagerHint:(NSString *)arg1 ;
-(void)setAutoshifted:(BOOL)arg1 ;
-(void)setPopupVariant:(BOOL)arg1 ;
-(BOOL)isSynthesizedByAcceptingCandidate;
-(void)setSynthesizedByAcceptingCandidate:(BOOL)arg1 ;
-(TIKeyboardCandidate *)acceptedCandidate;
-(void)setAcceptedCandidate:(TIKeyboardCandidate *)arg1 ;
-(BOOL)isGesture;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(TIKeyboardTouchEvent *)touchEvent;
-(void)setMultitap:(BOOL)arg1 ;
-(BOOL)isShiftDown;
-(BOOL)isBackspace;
-(id<NSCopying><NSObject><NSSecureCoding>)object;
-(id)description;
-(void)setBackspace:(BOOL)arg1 ;
-(void)setShiftDown:(BOOL)arg1 ;
-(void)setUppercase:(BOOL)arg1 ;
-(BOOL)isAutoshifted;
@end

