#import <CoreSuggestions/SGM2BadInteractionIgnored.h>
#import <CoreSuggestions/SGM2BundleIdsMissingEntitlement.h>
#import <CoreSuggestions/SGM2CNtoSGContactsCacheHit.h>
#import <CoreSuggestions/SGM2ContactConfirmed.h>
#import <CoreSuggestions/SGM2ContactDetailConfirmed.h>
#import <CoreSuggestions/SGEligibilityCheckResult.h>
#import <CoreSuggestions/SGHarvestEligibility.h>
#import <CoreSuggestions/SGM2ContactDetailRejected.h>
#import <CoreSuggestions/SGM2ContactDetailUsed.h>
#import <CoreSuggestions/SGM2ContactInBanner.h>
#import <CoreSuggestions/SGSearchableItemSerializedAttributes.h>
#import <CoreSuggestions/SGM2ContactRejected.h>
#import <CoreSuggestions/SGM2DDLinkShown.h>
#import <CoreSuggestions/SGDomainWhitelistCheckerGuardedData.h>
#import <CoreSuggestions/SGDomainWhitelistChecker.h>
#import <CoreSuggestions/SGM2EventBannerConfirmed.h>
#import <CoreSuggestions/SGM2EventBannerRejected.h>
#import <CoreSuggestions/SGM2EventICSOpportunity.h>
#import <CoreSuggestions/SGURL.h>
#import <CoreSuggestions/SGM2EventInBanner.h>
#import <CoreSuggestions/SGM2FoundInAppsICS.h>
#import <CoreSuggestions/SGSuggestions.h>
#import <CoreSuggestions/SGM2MaybeInformationShown.h>
#import <CoreSuggestions/SGM2NLEventInBanner.h>
#import <CoreSuggestions/SGSuggestedEventLaunchInfo.h>
#import <CoreSuggestions/SGM2SelfIdPatternMatched.h>
#import <CoreSuggestions/SGEntityTagLabelOptions.h>
#import <CoreSuggestions/SGEntityTag.h>
#import <CoreSuggestions/SGObjCRuntime.h>
#import <CoreSuggestions/SGEventActivity.h>
#import <CoreSuggestions/SGEKEventConversions.h>
#import <CoreSuggestions/SGReminder.h>
#import <CoreSuggestions/SGFuture.h>
#import <CoreSuggestions/SGM2BundleIdsUsingOldEntitlement.h>
#import <CoreSuggestions/SGReminderMetadata.h>
#import <CoreSuggestions/SGDirectory.h>
#import <CoreSuggestions/SGEventGeocode.h>
#import <CoreSuggestions/SGPostalAddressComponents.h>
#import <CoreSuggestions/SGPostalAddress.h>
#import <CoreSuggestions/SGKeyValueCacheFile.h>
#import <CoreSuggestions/SGRemoteObjectProxy.h>
#import <CoreSuggestions/SGDetailCacheSnapshot.h>
#import <CoreSuggestions/SGSuggestionsService.h>
#import <CoreSuggestions/SGRealtimeEvent.h>
#import <CoreSuggestions/SGMSqliteErrors.h>
#import <CoreSuggestions/SGMSuggestdExitReason.h>
#import <CoreSuggestions/SGMContactInBanner.h>
#import <CoreSuggestions/SGMContactConfirmed.h>
#import <CoreSuggestions/SGMContactRejected.h>
#import <CoreSuggestions/SGMContactDetailConfirmed.h>
#import <CoreSuggestions/SGMContactDetailUsed.h>
#import <CoreSuggestions/SGMContactDetailRejected.h>
#import <CoreSuggestions/SGMContactDetailConversationTurn.h>
#import <CoreSuggestions/SGMMaybeInformationShown.h>
#import <CoreSuggestions/SGMUnknownContactInformationShown.h>
#import <CoreSuggestions/SGMContactOpportunityInSpotlight.h>
#import <CoreSuggestions/SGMEventOpportunityInSpotlight.h>
#import <CoreSuggestions/SGMEventInBanner.h>
#import <CoreSuggestions/SGMEventBannerConfirmed.h>
#import <CoreSuggestions/SGMEventBannerRejected.h>
#import <CoreSuggestions/SGMEventICSOpportunity.h>
#import <CoreSuggestions/SGMContactResultInSpotlight.h>
#import <CoreSuggestions/SGMContactResultSelectedInSpotlight.h>
#import <CoreSuggestions/SGMEventResultInSpotlight.h>
#import <CoreSuggestions/SGMEventResultSelectedInSpotlight.h>
#import <CoreSuggestions/SGMNoResultSelectedInSpotlight.h>
#import <CoreSuggestions/SGMOtherResultSelectedInSpotlight.h>
#import <CoreSuggestions/SGMNLEventInBanner.h>
#import <CoreSuggestions/SGMDDLinkShown.h>
#import <CoreSuggestions/SGMSelfIdPatternMatched.h>
#import <CoreSuggestions/SGMBadInteractionIgnored.h>
#import <CoreSuggestions/SGMContactDetailExtraction.h>
#import <CoreSuggestions/SGMContactDetailSent.h>
#import <CoreSuggestions/SGMAutocompleteUserSelectedContact.h>
#import <CoreSuggestions/SGMSearchResultsUserSelectedContact.h>
#import <CoreSuggestions/SGMSuggestedContactDetailUsed.h>
#import <CoreSuggestions/SGMSuggestedContactDetailShown.h>
#import <CoreSuggestions/SGMContactCreated.h>
#import <CoreSuggestions/SGMSearchResultsIncludedPureSuggestion.h>
#import <CoreSuggestions/SGMFoundInMailModelScore.h>
#import <CoreSuggestions/SGMSelfIdModelScore.h>
#import <CoreSuggestions/SGMBundleIdsMissingEntitlement.h>
#import <CoreSuggestions/SGMBundleIdsUsingOldEntitlement.h>
#import <CoreSuggestions/SGMBundleIdsTrackedAsOther.h>
#import <CoreSuggestions/SGMContactsInterfaceCacheHit.h>
#import <CoreSuggestions/SGMContactsInterfaceCacheCount.h>
#import <CoreSuggestions/SGMSerializedContactsCacheHit.h>
#import <CoreSuggestions/SGMCNtoSGContactsCacheHit.h>
#import <CoreSuggestions/SGMMailClientInMailApp.h>
#import <CoreSuggestions/SGMFoundInAppsICS.h>
#import <CoreSuggestions/SGSimpleNamedEmailAddress.h>
#import <CoreSuggestions/SGRealtimeReminder.h>
#import <CoreSuggestions/SGObject.h>
#import <CoreSuggestions/SGLocation.h>
#import <CoreSuggestions/SGName.h>
#import <CoreSuggestions/SGMatchedDetails.h>
#import <CoreSuggestions/SGEventMetadata.h>
#import <CoreSuggestions/SGNotificationListener.h>
#import <CoreSuggestions/SGOrigin.h>
#import <CoreSuggestions/SGIPPerson.h>
#import <CoreSuggestions/SGIPMessage.h>
#import <CoreSuggestions/SGSearchableItemHelper.h>
#import <CoreSuggestions/SGDSuggestManagerInterface.h>
#import <CoreSuggestions/SGRealtimeSuggestionMock.h>
#import <CoreSuggestions/SGTimeZone.h>
#import <CoreSuggestions/SGTimeZoneDetector.h>
#import <CoreSuggestions/SGSimpleTimeRange.h>
#import <CoreSuggestions/SGFn.h>
#import <CoreSuggestions/SGCircularBufferArray.h>
#import <CoreSuggestions/SGMatchinfoData.h>
#import <CoreSuggestions/SGRealtimeContact.h>
#import <CoreSuggestions/SGPhoneNumber.h>
#import <CoreSuggestions/_SGNSStringEncodingEnumerator.h>
#import <CoreSuggestions/SGExtractionInfo.h>
#import <CoreSuggestions/SGDateComponents.h>
#import <CoreSuggestions/SGContactMatch.h>
#import <CoreSuggestions/SGEmailAddress.h>
#import <CoreSuggestions/SGPreferenceManager.h>
#import <CoreSuggestions/SGPreferenceStorage.h>
#import <CoreSuggestions/SGDelivery.h>
#import <CoreSuggestions/SGRecordId.h>
#import <CoreSuggestions/SGXPCResponse.h>
#import <CoreSuggestions/SGXPCResponse1.h>
#import <CoreSuggestions/SGXPCResponse2.h>
#import <CoreSuggestions/SGXPCResponse3.h>
#import <CoreSuggestions/SGMessagesDaemonConnection.h>
#import <CoreSuggestions/SGMessagesSuggestionsService.h>
#import <CoreSuggestions/SGMailMessageKey.h>
#import <CoreSuggestions/SGLabeledObject.h>
#import <CoreSuggestions/SGContact.h>
#import <CoreSuggestions/SGNLEventSuggestionsMetrics.h>
#import <CoreSuggestions/SGSuggestedActionMetrics.h>
#import <CoreSuggestions/SGPatternMetrics.h>
#import <CoreSuggestions/SGErrorMetrics.h>
#import <CoreSuggestions/SGSuggestionsICSMetrics.h>
#import <CoreSuggestions/SGDaemonConnection.h>
#import <CoreSuggestions/SGEvent.h>
