/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:40:37 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/TSReading.framework/TSReading
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol TSSPropertySource <NSObject>
@required
-(id)objectForProperty:(int)arg1;
-(float)floatValueForProperty:(int)arg1;
-(BOOL)containsProperty:(int)arg1;
-(id)boxedObjectForProperty:(int)arg1;
-(int)intValueForProperty:(int)arg1;
-(double)doubleValueForProperty:(int)arg1;
-(double)CGFloatValueForProperty:(int)arg1;

@end

