#import <Fitness/FITrailingQuantityTimeSlice.h>
#import <Fitness/FIValidation.h>
#import <Fitness/FISleepDataProvider.h>
#import <Fitness/FIFitnessAppsStateObserver.h>
#import <Fitness/FITrailingIntervalController.h>
#import <Fitness/FIIntervalDefinition.h>
#import <Fitness/FIMutableTimeSliceGroup.h>
#import <Fitness/FIReduction.h>
#import <Fitness/FISleepUserDay.h>
#import <Fitness/FIActivitySettingsController.h>
#import <Fitness/FIQuantityTimeSlice.h>
#import <Fitness/FIQuantityIntervalController.h>
#import <Fitness/FISimpleHistogram.h>
#import <Fitness/FIIntervalWorkoutDefinitionsManager.h>
#import <Fitness/FIIntervalWorkoutDefinition.h>
#import <Fitness/FITypicalDayActivityModel.h>
#import <Fitness/FIIntervalQuantityTrigger.h>
#import <Fitness/FIIntervalSetDefinition.h>
#import <Fitness/FIQuantityInterval.h>
