/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:36:46 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SilexVideo.framework/SilexVideo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/SVPlaybackTransitionContext.h>

@protocol SVPlaybackTransitionContext <NSObject>
@property (nonatomic,readonly) id<SVVideo> fromVideo; 
@property (nonatomic,readonly) id<SVVideo> toVideo; 
@required
-(id<SVVideo>)toVideo;
-(void)completeTransition:(BOOL)arg1;
-(id<SVVideo>)fromVideo;

@end


@protocol SVVideo;
@class NSString;

@interface SVPlaybackTransitionContext : NSObject <SVPlaybackTransitionContext> {

	id<SVVideo> _fromVideo;
	id<SVVideo> _toVideo;
	/*^block*/id _completionBlock;

}

@property (nonatomic,copy) id completionBlock;                      //@synthesize completionBlock=_completionBlock - In the implementation block
@property (nonatomic,readonly) id<SVVideo> fromVideo;               //@synthesize fromVideo=_fromVideo - In the implementation block
@property (nonatomic,readonly) id<SVVideo> toVideo;                 //@synthesize toVideo=_toVideo - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setCompletionBlock:(id)arg1 ;
-(id)completionBlock;
-(id<SVVideo>)toVideo;
-(void)completeTransition:(BOOL)arg1 ;
-(id<SVVideo>)fromVideo;
-(id)initWithFromVideo:(id)arg1 toVideo:(id)arg2 completionBlock:(/*^block*/id)arg3 ;
@end

