/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:38:14 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/Translation.framework/Translation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Translation/Translation-Structs.h>
#import <Translation/FTRepeatedItnAlignment.h>

@class NSArray;

@interface FTMutableRepeatedItnAlignment : FTRepeatedItnAlignment

@property (nonatomic,copy) NSArray * itn_alignment; 
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSArray *)itn_alignment;
-(void)setItn_alignment:(NSArray *)arg1 ;
-(id)init;
@end

