/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:42:13 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/VideoSubscriberAccountUI.framework/VideoSubscriberAccountUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol VSStateMachineDelegate <NSObject>
@optional
-(void)stateMachine:(id)arg1 transitionToState:(id)arg2;
-(void)stateMachine:(id)arg1 transitionFromState:(id)arg2;

@end

