/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:41:06 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol HMDDataStreamDelegate <NSObject>
@optional
-(void)dataStreamDidReceiveRawFrame:(id)arg1;

@required
-(void)dataStreamDidUpdateActiveStatus:(id)arg1;
-(void)dataStream:(id)arg1 didFailWithError:(id)arg2;
-(void)dataStreamDidClose:(id)arg1;
-(void)dataStreamDidOpen:(id)arg1;

@end

