/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:41:18 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/CameraEffectsKit.framework/CameraEffectsKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class PVRenderer, NSString;

@interface JFXEffectsPreviewGenerator : NSObject {

	PVRenderer* _renderer;
	NSString* _name;

}

@property (nonatomic,retain) NSString * name;              //@synthesize name=_name - In the implementation block
-(void)clearCaches;
-(void)dealloc;
-(id)init;
-(void)setName:(NSString *)arg1 ;
-(void)perfLog;
-(NSString *)name;
-(id)initWithRendererOptions:(id)arg1 ;
-(void)generatePreviewRequest:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)trackStats:(BOOL)arg1 ;
-(void)_renderJob:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
@end

