#import <CoreHaptics/CHHapticParameterAttributesImpl.h>
#import <CoreHaptics/CHDefaultHapticDeviceCapability.h>
#import <CoreHaptics/HapticServerConfig.h>
#import <CoreHaptics/CHMetricsPlayerData.h>
#import <CoreHaptics/CHMetricsKey.h>
#import <CoreHaptics/PlaybackAction.h>
#import <CoreHaptics/CHMetricsManager.h>
#import <CoreHaptics/EventToDictionaryConverter.h>
#import <CoreHaptics/HapticDictionaryWriter.h>
#import <CoreHaptics/HapticCommandConverter.h>
#import <CoreHaptics/HapticDictionaryReader.h>
#import <CoreHaptics/CHHapticEvent.h>
#import <CoreHaptics/CHHapticEventParameter.h>
#import <CoreHaptics/CHHapticDynamicParameter.h>
#import <CoreHaptics/CHHapticParameterCurve.h>
#import <CoreHaptics/CHHapticParameterCurveControlPoint.h>
#import <CoreHaptics/CHHapticPattern.h>
#import <CoreHaptics/PatternPlayer.h>
#import <CoreHaptics/AdvancedPatternPlayer.h>
#import <CoreHaptics/CHHapticEngine.h>
