/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:35:40 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/WebInspector.framework/WebInspector
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <WebInspector/WebInspector-Structs.h>
@interface RWIProtocolCSSDomainEventDispatcher : NSObject {

	AugmentableInspectorController* _controller;

}
-(id)initWithController:(AugmentableInspectorController*)arg1 ;
-(void)mediaQueryResultChanged;
-(void)styleSheetChangedWithStyleSheetId:(id)arg1 ;
-(void)styleSheetAddedWithHeader:(id)arg1 ;
-(void)styleSheetRemovedWithStyleSheetId:(id)arg1 ;
@end

