/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:41:25 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WorkflowEditor/WorkflowEditor-Structs.h>
#import <WorkflowEditor/WFRunWorkflowViewController.h>
#import <libobjc.A.dylib/WFDragControllerDelegate.h>
#import <libobjc.A.dylib/WFModulesCollectionViewDelegate.h>
#import <libobjc.A.dylib/WFWorkflowEmptyStateViewDelegate.h>
#import <libobjc.A.dylib/WFContentClassesToolbarDelegate.h>
#import <libobjc.A.dylib/WFModuleDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <libobjc.A.dylib/WFWorkflowEditingDelegate.h>

@protocol WFVariableUIDelegate;
@class NSUndoManager, NSAttributedString, NSHashTable, WFWorkflowEmptyStateView, UIView, WFActionDragFeedbackGenerator, UIResponder, NSLayoutConstraint, UIButton, NSIndexPath, WFEditShortcutEvent, NSString;

@interface WFEditWorkflowViewController : WFRunWorkflowViewController <WFDragControllerDelegate, WFModulesCollectionViewDelegate, WFWorkflowEmptyStateViewDelegate, WFContentClassesToolbarDelegate, WFModuleDelegate, UIGestureRecognizerDelegate, WFWorkflowEditingDelegate> {

	NSUndoManager* _undoManager;
	id<WFVariableUIDelegate> _variableUIDelegate;
	NSAttributedString* _emptyStateInstructionText;
	NSHashTable* _currentDragControllers;
	NSHashTable* _moduleDragControllers;
	WFWorkflowEmptyStateView* _emptyStateView;
	UIView* _borderView;
	WFActionDragFeedbackGenerator* _dragFeedbackGenerator;
	UIResponder* _wf_firstResponder;
	UIView* _firstResponderHintView;
	NSLayoutConstraint* _hintBottomConstraint;
	long long _revealState;
	/*^block*/id _endRevealGoBackHandler;
	/*^block*/id _endRevealScrolledAwayHandler;
	UIButton* _endRevealButton;
	NSIndexPath* _actionRevealFromIndexPath;
	NSIndexPath* _actionRevealToIndexPath;
	WFEditShortcutEvent* _editShortcutEvent;
	CGPoint _actionRevealInitialOffset;

}

@property (nonatomic,readonly) NSHashTable * currentDragControllers;                                //@synthesize currentDragControllers=_currentDragControllers - In the implementation block
@property (nonatomic,readonly) NSHashTable * moduleDragControllers;                                 //@synthesize moduleDragControllers=_moduleDragControllers - In the implementation block
@property (nonatomic,__weak,readonly) WFWorkflowEmptyStateView * emptyStateView;                    //@synthesize emptyStateView=_emptyStateView - In the implementation block
@property (nonatomic,__weak,readonly) UIView * borderView;                                          //@synthesize borderView=_borderView - In the implementation block
@property (nonatomic,readonly) NSUndoManager * undoManager;                                         //@synthesize undoManager=_undoManager - In the implementation block
@property (nonatomic,retain) WFActionDragFeedbackGenerator * dragFeedbackGenerator;                 //@synthesize dragFeedbackGenerator=_dragFeedbackGenerator - In the implementation block
@property (assign,nonatomic,__weak) UIResponder * wf_firstResponder;                                //@synthesize wf_firstResponder=_wf_firstResponder - In the implementation block
@property (assign,nonatomic,__weak) UIView * firstResponderHintView;                                //@synthesize firstResponderHintView=_firstResponderHintView - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * hintBottomConstraint;                             //@synthesize hintBottomConstraint=_hintBottomConstraint - In the implementation block
@property (assign,nonatomic) long long revealState;                                                 //@synthesize revealState=_revealState - In the implementation block
@property (nonatomic,copy) id endRevealGoBackHandler;                                               //@synthesize endRevealGoBackHandler=_endRevealGoBackHandler - In the implementation block
@property (nonatomic,copy) id endRevealScrolledAwayHandler;                                         //@synthesize endRevealScrolledAwayHandler=_endRevealScrolledAwayHandler - In the implementation block
@property (nonatomic,retain) UIButton * endRevealButton;                                            //@synthesize endRevealButton=_endRevealButton - In the implementation block
@property (nonatomic,retain) NSIndexPath * actionRevealFromIndexPath;                               //@synthesize actionRevealFromIndexPath=_actionRevealFromIndexPath - In the implementation block
@property (nonatomic,retain) NSIndexPath * actionRevealToIndexPath;                                 //@synthesize actionRevealToIndexPath=_actionRevealToIndexPath - In the implementation block
@property (assign,nonatomic) CGPoint actionRevealInitialOffset;                                     //@synthesize actionRevealInitialOffset=_actionRevealInitialOffset - In the implementation block
@property (nonatomic,retain) WFEditShortcutEvent * editShortcutEvent;                               //@synthesize editShortcutEvent=_editShortcutEvent - In the implementation block
@property (assign,nonatomic,__weak) id<WFEditWorkflowViewControllerDelegate> delegate; 
@property (assign,nonatomic,__weak) id<WFVariableUIDelegate> variableUIDelegate;                    //@synthesize variableUIDelegate=_variableUIDelegate - In the implementation block
@property (assign,nonatomic) BOOL scrollsToTop; 
@property (nonatomic,copy) NSAttributedString * emptyStateInstructionText;                          //@synthesize emptyStateInstructionText=_emptyStateInstructionText - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)displaysEmptyView;
-(void)paste:(id)arg1 ;
-(NSUndoManager *)undoManager;
-(id)collectionView:(id)arg1 contextMenuConfigurationForItemAtIndexPath:(id)arg2 point:(CGPoint)arg3 ;
-(void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(BOOL)canBecomeFirstResponder;
-(long long)revealState;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(BOOL)scrollsToTop;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)dealloc;
-(void)viewDidAppear:(BOOL)arg1 ;
-(UIView *)borderView;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)setScrollsToTop:(BOOL)arg1 ;
-(id)keyCommands;
-(void)loadView;
-(void)keyboardWillChangeFrame:(id)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)setRevealState:(long long)arg1 ;
-(void)workflow:(id)arg1 reloadActions:(id)arg2 ;
-(void)workflow:(id)arg1 actionForSuggestionsDrawerDidUpdateOutputContentClasses:(id)arg2 ;
-(void)workflow:(id)arg1 removeAction:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)workflow:(id)arg1 moveActionsAtIndexes:(id)arg2 toIndexes:(id)arg3 ;
-(void)workflow:(id)arg1 insertActions:(id)arg2 atIndexes:(id)arg3 ;
-(void)revealAction:(id)arg1 fromSourceView:(id)arg2 preScrollHandler:(/*^block*/id)arg3 goBackHandler:(/*^block*/id)arg4 scrolledAwayHandler:(/*^block*/id)arg5 ;
-(void)setVariableUIDelegate:(id<WFVariableUIDelegate>)arg1 ;
-(id<WFVariableUIDelegate>)variableUIDelegate;
-(void)runToolbarAddTapped:(id)arg1 ;
-(void)runToolbarRedoTapped:(id)arg1 ;
-(void)runToolbarUndoTapped:(id)arg1 ;
-(void)runToolbarShareTapped:(id)arg1 sender:(id)arg2 ;
-(BOOL)dragController:(id)arg1 shouldAcceptViewWithCompletion:(/*^block*/id)arg2 ;
-(void)dragController:(id)arg1 movedInsideViewControllers:(id)arg2 ;
-(void)dragController:(id)arg1 didEnterViewController:(id)arg2 ;
-(void)dragController:(id)arg1 didExitViewController:(id)arg2 ;
-(void)dragController:(id)arg1 willBeAcceptedByDelegate:(id)arg2 ;
-(void)dragControllerWillBeginDragging:(id)arg1 ;
-(void)emptyViewDidRequestActionDrawer:(id)arg1 ;
-(void)emptyViewDidRequestTutorial:(id)arg1 ;
-(BOOL)module:(id)arg1 setParameterState:(id)arg2 forParameter:(id)arg3 action:(id)arg4 ;
-(BOOL)module:(id)arg1 shouldAllowRemovingAction:(id)arg2 ;
-(void)removeActionPressedForModule:(id)arg1 withAction:(id)arg2 ;
-(void)documentationPressedForModule:(id)arg1 withAction:(id)arg2 sender:(id)arg3 ;
-(unsigned long long)indentationLevelForModule:(id)arg1 withAction:(id)arg2 ;
-(id)menuForModule:(id)arg1 withAction:(id)arg2 ;
-(void)contentClassesToolbarTapped:(id)arg1 ;
-(BOOL)collectionView:(id)arg1 layout:(id)arg2 shouldHideItemAtIndexPath:(id)arg3 ;
-(id)initWithWorkflow:(id)arg1 database:(id)arg2 ;
-(id)initWithWorkflow:(id)arg1 database:(id)arg2 allowsActionDragAndDrop:(BOOL)arg3 ;
-(id)initWithWorkflow:(id)arg1 database:(id)arg2 cellConfigurationFunction:(/*function pointer*/void*)arg3 ;
-(void)resetToolbar;
-(BOOL)hasActionsOnPasteboard;
-(id)actionsOnPasteboard;
-(void)updateEditingStateAnimated:(BOOL)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)setEditingState:(unsigned long long)arg1 animated:(BOOL)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)updateEmptyStateViewVisibilityAnimated:(BOOL)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)setEmptyStateInstructionText:(NSAttributedString *)arg1 ;
-(void)runWorkflowFromSource:(id)arg1 ;
-(WFActionDragFeedbackGenerator *)dragFeedbackGenerator;
-(void)scrollToAction:(id)arg1 ;
-(void)didFinishAnimatingReveal;
-(void)resetVisibleCellStylesForEndReveal;
-(void)didFinishAnimatingRevealGoBack;
-(void)didSelectEndRevealButton;
-(void)resetUIForRevealActionEnd;
-(void)cleanupAfterReveal;
-(void)cancelRevealAction;
-(id)createModelForAction:(id)arg1 ;
-(void)updateBorderWidth;
-(id)initialIndexPathForDragController:(id)arg1 ;
-(BOOL)canMoveActionsAtIndexes:(id)arg1 toIndexes:(id)arg2 ;
-(void)commitInsertionOfActions:(id)arg1 atIndexes:(id)arg2 allowUndo:(BOOL)arg3 ;
-(void)commitMovingOfActionsAtIndexes:(id)arg1 toIndexes:(id)arg2 allowUndo:(BOOL)arg3 ;
-(void)commitRemovalOfActions:(id)arg1 allowUndo:(BOOL)arg2 ;
-(void)appendActions:(id)arg1 ;
-(void)scrollViewToVisible:(id)arg1 ;
-(void)scrollFirstResponderToVisible;
-(void)updateContentInsetAnimated:(BOOL)arg1 ;
-(void)responderDidBeginEditing:(id)arg1 ;
-(void)responderDidEndEditing:(id)arg1 ;
-(void)responderDidType:(id)arg1 ;
-(void)checkRevealActionScrollState;
-(void)updateEditEvent;
-(void)logEditEventIfNeccesary;
-(NSAttributedString *)emptyStateInstructionText;
-(NSHashTable *)currentDragControllers;
-(NSHashTable *)moduleDragControllers;
-(WFWorkflowEmptyStateView *)emptyStateView;
-(void)setDragFeedbackGenerator:(WFActionDragFeedbackGenerator *)arg1 ;
-(UIResponder *)wf_firstResponder;
-(void)setWf_firstResponder:(UIResponder *)arg1 ;
-(UIView *)firstResponderHintView;
-(void)setFirstResponderHintView:(UIView *)arg1 ;
-(NSLayoutConstraint *)hintBottomConstraint;
-(void)setHintBottomConstraint:(NSLayoutConstraint *)arg1 ;
-(id)endRevealGoBackHandler;
-(void)setEndRevealGoBackHandler:(id)arg1 ;
-(id)endRevealScrolledAwayHandler;
-(void)setEndRevealScrolledAwayHandler:(id)arg1 ;
-(UIButton *)endRevealButton;
-(void)setEndRevealButton:(UIButton *)arg1 ;
-(NSIndexPath *)actionRevealFromIndexPath;
-(void)setActionRevealFromIndexPath:(NSIndexPath *)arg1 ;
-(NSIndexPath *)actionRevealToIndexPath;
-(void)setActionRevealToIndexPath:(NSIndexPath *)arg1 ;
-(CGPoint)actionRevealInitialOffset;
-(void)setActionRevealInitialOffset:(CGPoint)arg1 ;
-(WFEditShortcutEvent *)editShortcutEvent;
-(void)setEditShortcutEvent:(WFEditShortcutEvent *)arg1 ;
@end

