#import <AvatarUI/AVTAvatarLibraryRecordItem.h>
#import <AvatarUI/AVTAvatarAttributeEditorCategory.h>
#import <AvatarUI/AVTUIStickerItem.h>
#import <AvatarUI/AVTPresetImageProvider.h>
#import <AvatarUI/AVTAvatarListViewItem.h>
#import <AvatarUI/AVTAvatarLibraryCollectionViewCell.h>
#import <AvatarUI/AVTAlertController.h>
#import <AvatarUI/AVTCenteringCollectionViewDelegate.h>
#import <AvatarUI/AVTBackendVersion.h>
#import <AvatarUI/AVTStubbedStoreBackend.h>
#import <AvatarUI/AVTStickerRecentsOverlayViewLayout.h>
#import <AvatarUI/AVTAvatarRecordImageGenerator.h>
#import <AvatarUI/AVTAvatarAttributeEditorPreloader.h>
#import <AvatarUI/AVTInMemoryResourceCache.h>
#import <AvatarUI/AVTInMemoryResourceCacheEntry.h>
#import <AvatarUI/AVTAvatarAttributeEditorSectionColorItem.h>
#import <AvatarUI/AVTSplashScreenViewController.h>
#import <AvatarUI/AVTStickerRecentsOverlayView.h>
#import <AvatarUI/AVTAvatarsDaemonServer.h>
#import <AvatarUI/AVTAvatarFetchRequest.h>
#import <AvatarUI/AVTGroupDial.h>
#import <AvatarUI/AVTAvatarAttributeEditorTransitionFromActionsStartingPortraitLayout.h>
#import <AvatarUI/AVTCollapsibleHeaderController.h>
#import <AvatarUI/AVTAvatarAttributeEditorSectionSupplementalPickerItem.h>
#import <AvatarUI/AVTAvatarListRecordItem.h>
#import <AvatarUI/AVTEditingModelBuilder.h>
#import <AvatarUI/AVTArchiverBasedDomain.h>
#import <AvatarUI/AVTCoreDataStoreBackend.h>
#import <AvatarUI/AVTAvatarActionsViewControllerTransitionStartingLayout.h>
#import <AvatarUI/AVTCoreModelRowDisplayCondition.h>
#import <AvatarUI/AVTAvatarAttributeEditorDefaultPortraitLayout.h>
#import <AvatarUI/AVTAvatarLibraryCreateNewItem.h>
#import <AvatarUI/AVTAnimojiPoseSelectionHeaderViewController.h>
#import <AvatarUI/AVTViewUpdater.h>
#import <AvatarUI/AVTEdgeDisappearingCollectionViewLayout.h>
#import <AvatarUI/AVTCoreModelColorVariation.h>
#import <AvatarUI/AVTAvatarInlineActionsController.h>
#import <AvatarUI/AVTStickerSheetController.h>
#import <AvatarUI/AVTAvatarLibraryCollectionViewAddCell.h>
#import <AvatarUI/AVTCoreModelGroup.h>
#import <AvatarUI/AVTHEIFImageEncoder.h>
#import <AvatarUI/AVTCameraItemView.h>
#import <AvatarUI/AVTPoseSelectionViewController.h>
#import <AvatarUI/AVTAvatarAttributeEditorDataSource.h>
#import <AvatarUI/AVTCenteringCollectionViewHelper.h>
#import <AvatarUI/AVTCoreModel.h>
#import <AvatarUI/AVTCoreDataStoreMaintenance.h>
#import <AvatarUI/AVTStickerCollectionViewCell.h>
#import <AvatarUI/AVTComponentFactory.h>
#import <AvatarUI/AVTAvatarContainerViewController.h>
#import <AvatarUI/AVTCoreDataCloudKitMirroringHandler.h>
#import <AvatarUI/AVTDisabledMirroringHandler.h>
#import <AvatarUI/AVTStickerRecentsViewController.h>
#import <AvatarUI/AVTAvatarAttributeEditorColorSection.h>
#import <AvatarUI/AVTActionsToAttributeEditorTransitionAnimator.h>
#import <AvatarUI/AVTAvatarEditorViewController.h>
#import <AvatarUI/AVTSyncSchedulingAuthority.h>
#import <AvatarUI/AVTStickerPagingController.h>
#import <AvatarUI/AVTCircularView.h>
#import <AvatarUI/AVTAvatarAttributeEditorSectionController.h>
#import <AvatarUI/AVTCoreModelColor.h>
#import <AvatarUI/AVTSimpleAvatarPickerHeaderView.h>
#import <AvatarUI/AVTMultiAvatarController.h>
#import <AvatarUI/AVTTransitionSchedulerFactory.h>
#import <AvatarUI/AVTClippableImageStore.h>
#import <AvatarUI/AVTStickerRecentsMigrator.h>
#import <AvatarUI/AVTAvatarImageRenderer.h>
#import <AvatarUI/AVTStickerRecentsPlaceholderItem.h>
#import <AvatarUI/AVTStickerRecentsStickerItem.h>
#import <AvatarUI/AVTStickerRecentsButtonItem.h>
#import <AvatarUI/AVTAttributeEditorSectionHeaderView.h>
#import <AvatarUI/AVTAvatarLibraryModel.h>
#import <AvatarUI/AVTStickerRecentsPresetsProvider.h>
#import <AvatarUI/AVTCoreDataRemoteChangesObserver.h>
#import <AvatarUI/AVTCollectionViewCell.h>
#import <AvatarUI/AVTUITraitCollectionHelper.h>
#import <AvatarUI/AVTError.h>
#import <AvatarUI/AVTCaptureButtonView.h>
#import <AvatarUI/AVTSplashScreenConfiguration.h>
#import <AvatarUI/AVTStickerImageEncoder.h>
#import <AvatarUI/AVTPNGImageEncoder.h>
#import <AvatarUI/AVTUIStickerGeneratorPool.h>
#import <AvatarUI/AVTUIRaiseGestureManager.h>
#import <AvatarUI/AVTStickerPagingCollectionViewCell.h>
#import <AvatarUI/AVTViewCarouselLayout.h>
#import <AvatarUI/AVTGroupDialCell.h>
#import <AvatarUI/AVTCoreModelFramingModeOverrides.h>
#import <AvatarUI/AVTAvatarsDaemon.h>
#import <AvatarUI/AVTArrayPairClassification.h>
#import <AvatarUI/AVTAvatarAttributeEditorDefaultPortraitPadLayout.h>
#import <AvatarUI/AVTCoreDataChangeTracker.h>
#import <AvatarUI/AVTCoreDataChangeTrackerChange.h>
#import <AvatarUI/AVTAvatarManagedRecord.h>
#import <AvatarUI/AVTCoreModelPreset.h>
#import <AvatarUI/AVTUIStickerRenderer.h>
#import <AvatarUI/AVTAvatarPickerDataSource.h>
#import <AvatarUI/AVTAvatarManagedRecordTransformer.h>
#import <AvatarUI/AVTGroupListCollectionView.h>
#import <AvatarUI/AVTAvatarAttributeEditorDefaultMacLayout.h>
#import <AvatarUI/AVTAttributeEditorToActionsTransitionAnimator.h>
#import <AvatarUI/AVTPoseCollectionViewCell.h>
#import <AvatarUI/AVTStoreBackendMigrator.h>
#import <AvatarUI/AVTAvatarAttributeEditorModelManager.h>
#import <AvatarUI/AVTImageTransitioningContainerView.h>
#import <AvatarUI/AVTPassThroughResourceCache.h>
#import <AvatarUI/AVTShadowView.h>
#import <AvatarUI/AVTAvatarAttributeEditorModelDiff.h>
#import <AvatarUI/AVTEditingModelDefinitionsParser.h>
#import <AvatarUI/AVTGradientView.h>
#import <AvatarUI/AVTFunCamAvatarPickerController.h>
#import <AvatarUI/AVTBlockScheduler.h>
#import <AvatarUI/AVTSplashScreenLayout.h>
#import <AvatarUI/AVTAvatarActionButton.h>
#import <AvatarUI/AVTStickerUserDefaultsBackend.h>
#import <AvatarUI/AVTPresetResourceLoader.h>
#import <AvatarUI/AVTSectionItemLoadingTask.h>
#import <AvatarUI/AVTPresetResourcesLoadingTask.h>
#import <AvatarUI/AVTCoreModelPresetsRow.h>
#import <AvatarUI/AVTAvatarAttributeEditorSection.h>
#import <AvatarUI/AVTAvatarAttributeEditorFlowLayout.h>
#import <AvatarUI/AVTCircularButton.h>
#import <AvatarUI/AVTStickerRecentsLayout.h>
#import <AvatarUI/AVTAttributeCollectionViewCell.h>
#import <AvatarUI/AVTAvatarRecordRendering.h>
#import <AvatarUI/AVTMSStickerView.h>
#import <AvatarUI/AVTAvatarLibraryViewController.h>
#import <AvatarUI/AVTAvatarLibraryHeaderView.h>
#import <AvatarUI/AVTAvatarStore.h>
#import <AvatarUI/AVTPushNotificationsSupport.h>
#import <AvatarUI/AVTPushNotificationsConnectionFactory.h>
#import <AvatarUI/AVTAttributeValueView.h>
#import <AvatarUI/AVTCoalescingInvertingTaskScheduler.h>
#import <AvatarUI/AVTAvatarActionsProvider.h>
#import <AvatarUI/AVTCoreDataStoreServer.h>
#import <AvatarUI/AVTAvatarConfiguration.h>
#import <AvatarUI/AVTConfigurationPreset.h>
#import <AvatarUI/AVTAvatarRecordDataSource.h>
#import <AvatarUI/AVTSectionItemTransition.h>
#import <AvatarUI/CAShapeLayerAnimated.h>
#import <AvatarUI/AVTRecordingButton.h>
#import <AvatarUI/AVTAdaptativeLayoutView.h>
#import <AvatarUI/_AVTAdaptiveFullSizeLayout.h>
#import <AvatarUI/AVTFlippingCollectionViewFlowLayout.h>
#import <AvatarUI/AVTAvatarAttributeEditorSectionSupplementalPicker.h>
#import <AvatarUI/AVTColorSlider.h>
#import <AvatarUI/AVTRenderingScope.h>
#import <AvatarUI/AVTUILogger.h>
#import <AvatarUI/AVTFunCamAvatarPickerTitleCell.h>
#import <AvatarUI/AVTStickerRecentsButtonCollectionViewCell.h>
#import <AvatarUI/AVTInMemoryImageCache.h>
#import <AvatarUI/AVTViewSession.h>
#import <AvatarUI/AVTCoreDataCloudKitMirroringConfiguration.h>
#import <AvatarUI/AVTTransparentNavigationController.h>
#import <AvatarUI/AVTAvatarAttributeEditorOverridingLayout.h>
#import <AvatarUI/AVTGroupListCollectionViewCell.h>
#import <AvatarUI/AVTObservableAvatarStore.h>
#import <AvatarUI/AVTSimpleAvatarPickerCollectionViewCell.h>
#import <AvatarUI/AVTImmediateTaskScheduler.h>
#import <AvatarUI/AVTAvatarActionsViewControllerPadLayout.h>
#import <AvatarUI/AVTUsageTracker.h>
#import <AvatarUI/AVTUsageTrackingSession.h>
#import <AvatarUI/AVTUsageTrackingRecordTimedEvent.h>
#import <AvatarUI/AVTSideCoreDataStoreMigratableSource.h>
#import <AvatarUI/AVTImageValidator.h>
#import <AvatarUI/AVTStickerSheetModel.h>
#import <AvatarUI/AVTImageIOImageEncoder.h>
#import <AvatarUI/AVTPaddleView.h>
#import <AvatarUI/AVTStickerFetchRequest.h>
#import <AvatarUI/AVTAvatarConfigurationMetric.h>
#import <AvatarUI/AVTCarouselController.h>
#import <AvatarUI/AVTEngagementListCollectionViewLayout.h>
#import <AvatarUI/AVTToolbarButton.h>
#import <AvatarUI/AVTToolBar.h>
#import <AvatarUI/AVTGroupDialMaskingView.h>
#import <AvatarUI/AVTTwoLevelsImageCache.h>
#import <AvatarUI/AVTUIStickerPlaceholderProviderFactory.h>
#import <AvatarUI/AVTAvatarActionsViewController.h>
#import <AvatarUI/AVTAvatarUpdaterFactory.h>
#import <AvatarUI/AVTCoreModelPairing.h>
#import <AvatarUI/AVTFunCamAvatarPickerCollectionViewCell.h>
#import <AvatarUI/AVTCoreAnalyticsClient.h>
#import <AvatarUI/AVTTransition.h>
#import <AvatarUI/AVTStickerChangeObserver.h>
#import <AvatarUI/AVTSynchronousTransitionScheduler.h>
#import <AvatarUI/AVTAvatarRecord.h>
#import <AvatarUI/AVTDifferentialPrivacyRecorder.h>
#import <AvatarUI/AVTFunCamAvatarPickerCollectionViewLayout.h>
#import <AvatarUI/AVTPaddlePathGenerator.h>
#import <AvatarUI/AVTHEICImageIOImageEncoder.h>
#import <AvatarUI/AVTAvatarColorVariationStore.h>
#import <AvatarUI/AVTFunCamAvatarPickerStyle.h>
#import <AvatarUI/AVTUIEnvironment.h>
#import <AvatarUI/AVTEventCoalescer.h>
#import <AvatarUI/AVTPassthroughEventCoalescer.h>
#import <AvatarUI/AVTAvatarRecordCacheableResource.h>
#import <AvatarUI/AVTAvatarRecordCacheableResourceChangeToken.h>
#import <AvatarUI/_AVTAvatarRecordImageProvider.h>
#import <AvatarUI/AVTCoreModelRowOptions.h>
#import <AvatarUI/AVTColorWheelView.h>
#import <AvatarUI/AVTJPEGImageEncoder.h>
#import <AvatarUI/AVTAvatarPuppetRecord.h>
#import <AvatarUI/AVTViewSessionProvider.h>
#import <AvatarUI/AVTUIControllerPresentation.h>
#import <AvatarUI/AVTAvatarAttributeEditorModel.h>
#import <AvatarUI/AVTSerialTaskScheduler.h>
#import <AvatarUI/AVTFixedSizeViewContainer.h>
#import <AvatarUI/AVTTransitionCoordinator.h>
#import <AvatarUI/AVTCoreModelColorsRow.h>
#import <AvatarUI/AVTAvatarActionsViewControllerLayout.h>
#import <AvatarUI/AVTAvatarListCell.h>
#import <AvatarUI/AVTStickerRecord.h>
#import <AvatarUI/AVTAvatarStoreServer.h>
#import <AvatarUI/AVTColorLayerProvider.h>
#import <AvatarUI/AVTAvatarActionsViewControllerTransitionPadStartingLayout.h>
#import <AvatarUI/AVTArchiverBasedStoreBackend.h>
#import <AvatarUI/AVTTouchDownGestureRecognizer.h>
#import <AvatarUI/AVTAvatarAttributeEditorModelBuilder.h>
#import <AvatarUI/AVTCarouselPlusButtonView.h>
#import <AvatarUI/AVTAvatarAttributeEditorState.h>
#import <AvatarUI/AVTEditingModelMappings.h>
#import <AvatarUI/AVTAttributeSectionSeparator.h>
#import <AvatarUI/AVTArchiverBasedStoreRoot.h>
#import <AvatarUI/AVTFaceTrackingManager.h>
#import <AvatarUI/AVTAvatarAttributeEditorSectionItem.h>
#import <AvatarUI/AVTAvatarAttributeEditorViewController.h>
#import <AvatarUI/AVTViewThrottler.h>
#import <AvatarUI/AVTUINSURL.h>
#import <AvatarUI/AVTStickerResource.h>
#import <AvatarUI/AVTBackgroundActivitySchedulerFactory.h>
#import <AvatarUI/AVTAvatarAttributeEditorSectionOptions.h>
#import <AvatarUI/AVTAvatarAttributeEditorSectionColorDataSource.h>
#import <AvatarUI/AVTAvatarRecordImageProvider.h>
#import <AvatarUI/AVTStickerConfigurationProvider.h>
#import <AvatarUI/AVTAvatarListImageItem.h>
#import <AvatarUI/AVTArchiverBasedStorePersistence.h>
#import <AvatarUI/AVTAvatarConfigurationImageRenderer.h>
#import <AvatarUI/AVTIconImageProvider.h>
#import <AvatarUI/AVTStickerRecentsStickerCollectionViewCell.h>
#import <AvatarUI/AVTUIColorRepository.h>
#import <AvatarUI/AVTSimpleAvatarPicker.h>
#import <AvatarUI/AVTConcurrentTransitionScheduler.h>
#import <AvatarUI/AVTImageStore.h>
#import <AvatarUI/AVTZIndexEngagementListCollectionViewLayout.h>
#import <AvatarUI/AVTDeviceResourceManager.h>
#import <AvatarUI/AVTPresetResources.h>
#import <AvatarUI/AVTEditingModelColors.h>
#import <AvatarUI/AVTMutableEditingModelColors.h>
#import <AvatarUI/AVTEngagementLayout.h>
#import <AvatarUI/AVTUIStyle.h>
#import <AvatarUI/AVTOrderedIndexBasedTaskScheduler.h>
#import <AvatarUI/AVTAvatarToLiveTransition.h>
#import <AvatarUI/AVTAvatarToStaticTransition.h>
#import <AvatarUI/_AVTAvatarToStaticNoTransition.h>
#import <AvatarUI/_AVTAvatarToLiveNoTransition.h>
#import <AvatarUI/AVTSingleAvatarController.h>
#import <AvatarUI/AVTAvatarAttributeEditorLayoutProvider.h>
#import <AvatarUI/AVTResourceCacheSupport.h>
#import <AvatarUI/AVTUIAnimatingImageView.h>
#import <AvatarUI/AVTArchiverBasedStoreMigratableSource.h>
#import <AvatarUI/AVTAvatarActionsMenuController.h>
#import <AvatarUI/AVTAvatarsDaemonClient.h>
#import <AvatarUI/AVTMinimumContentSizeCollectionViewLayout.h>
#import <AvatarUI/AVTAvatarSettingKindValue.h>
#import <AvatarUI/AVTATXImageIOImageEncoder.h>
#import <AvatarUI/AVTStickerViewController.h>
#import <AvatarUI/AVTCoreModelCategory.h>
#import <AvatarUI/AVTAvatarActionsRecordUpdate.h>
#import <AvatarUI/AVTAvatarAttributeEditorSectionColorController.h>
#import <AvatarUI/AVTGroupPickerItem.h>
#import <AvatarUI/AVTCoreDataPersistentStoreConfiguration.h>
#import <AvatarUI/_AVTCoreDataPersistentStoreRemoteConfiguration.h>
#import <AvatarUI/_AVTCoreDataPersistentStoreLocalConfiguration.h>
#import <AvatarUI/AVTNotifyingContainerView.h>
#import <AvatarUI/AVTAvatarAttributeEditorLayout.h>
#import <AvatarUI/AVTCategorySegmentedControl.h>
#import <AvatarUI/AVTUserInfoView.h>
#import <AvatarUI/AVTAggregateCacheableResource.h>
#import <AvatarUI/AVTCoreEnvironment.h>
#import <AvatarUI/AVTAvatarColorSliderContainerView.h>
#import <AvatarUI/AVTPuppetStore.h>
