/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:41:54 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/MobileTimer.framework/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileTimer/MTStateMachine.h>
#import <libobjc.A.dylib/MTSleepCoordinatorStateMachineEventHandler.h>

@class MTSleepCoordinatorStateMachineAsleepState, MTSleepCoordinatorStateMachineAwakeState, MTSleepCoordinatorStateMachineDisabledState, NSString;

@interface MTSleepCoordinatorStateMachine : MTStateMachine <MTSleepCoordinatorStateMachineEventHandler> {

	MTSleepCoordinatorStateMachineAsleepState* _asleepState;
	MTSleepCoordinatorStateMachineAwakeState* _awakeState;
	MTSleepCoordinatorStateMachineDisabledState* _disabledState;

}

@property (nonatomic,retain) MTSleepCoordinatorStateMachineAsleepState * asleepState;                  //@synthesize asleepState=_asleepState - In the implementation block
@property (nonatomic,retain) MTSleepCoordinatorStateMachineAwakeState * awakeState;                    //@synthesize awakeState=_awakeState - In the implementation block
@property (nonatomic,retain) MTSleepCoordinatorStateMachineDisabledState * disabledState;              //@synthesize disabledState=_disabledState - In the implementation block
@property (nonatomic,readonly) BOOL isUserAsleep; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)sleepAlarm;
-(void)stateMachineUserWokeUp:(id)arg1 ;
-(void)updateState;
-(id)currentDate;
-(void)stateMachineUserWentToBed:(id)arg1 ;
-(id)stateMachineLog;
-(MTSleepCoordinatorStateMachineDisabledState *)disabledState;
-(id)initWithDelegate:(id)arg1 infoProvider:(id)arg2 ;
-(MTSleepCoordinatorStateMachineAsleepState *)asleepState;
-(MTSleepCoordinatorStateMachineAwakeState *)awakeState;
-(void)stateMachine:(id)arg1 dismissWakeUpAlarm:(id)arg2 dismissAction:(unsigned long long)arg3 ;
-(unsigned long long)sleepTimeOutMinutes;
-(void)stateMachine:(id)arg1 shouldScheduleAlarmTimeoutForSecondsFromNow:(double)arg2 ;
-(void)userWentToBed;
-(void)userWokeUp;
-(void)userBedTimeReached:(id)arg1 ;
-(void)userWakeTimeReached:(id)arg1 ;
-(void)userWakeUpAlarmFired;
-(void)wakeUpAlarmTimedOut;
-(BOOL)isUserAsleep;
-(void)setAsleepState:(MTSleepCoordinatorStateMachineAsleepState *)arg1 ;
-(void)setAwakeState:(MTSleepCoordinatorStateMachineAwakeState *)arg1 ;
-(void)setDisabledState:(MTSleepCoordinatorStateMachineDisabledState *)arg1 ;
@end

