#import <TextInputChinese/TIKeyboardInputManagerChinese.h>
#import <TextInputChinese/TIKeyboardInputManagerWubi.h>
#import <TextInputChinese/TIWordSearchWubihua.h>
#import <TextInputChinese/TIWordSearchWubihua_zh_Hans.h>
#import <TextInputChinese/TIWordSearchWubihua_zh_Hant.h>
#import <TextInputChinese/TIWordSearchWubihua_yue_Hant.h>
#import <TextInputChinese/TIWordSearchShapeBased.h>
#import <TextInputChinese/TIWordSearchCangjie.h>
#import <TextInputChinese/TIWordSearchCangjie_yue_Hant.h>
#import <TextInputChinese/TIKeyboardInputManagerShapeBased.h>
#import <TextInputChinese/CIMCandidateData.h>
#import <TextInputChinese/TIConversionHistory.h>
#import <TextInputChinese/TIConvertedCandidate.h>
#import <TextInputChinese/TIKeyboardInputManagerCangjie.h>
#import <TextInputChinese/TIKeyboardHandwritingSpecialization.h>
#import <TextInputChinese/TIWordSearchChinesePhoneticOperationGetCandidates.h>
#import <TextInputChinese/TIKeyboardInputManagerChinesePhonetic.h>
#import <TextInputChinese/TIKeyboardInputManagerWubixing.h>
#import <TextInputChinese/RecognizerProvider.h>
#import <TextInputChinese/RecognizeDrawingOperation.h>
#import <TextInputChinese/RecognizePredictionOperation.h>
#import <TextInputChinese/TIInputManagerHandwriting.h>
#import <TextInputChinese/TIWordSearchChinesePhonetic.h>
#import <TextInputChinese/TIWordSearchWubixing.h>
