/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:40:16 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/ManagedConfigurationUI.framework/ManagedConfigurationUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UINavigationController.h>

@interface MCUINavigationViewController : UINavigationController {

	/*^block*/id _showViewControllerCompletionBlock;

}

@property (nonatomic,copy) id showViewControllerCompletionBlock;              //@synthesize showViewControllerCompletionBlock=_showViewControllerCompletionBlock - In the implementation block
-(unsigned long long)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(void)viewDidLoad;
-(void)didShowViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)setShowViewControllerCompletionBlock:(id)arg1 ;
-(id)showViewControllerCompletionBlock;
@end

