#import <MessageLegacy/MFStream.h>
#import <MessageLegacy/_MFSocket.h>
#import <MessageLegacy/MFAccount.h>
#import <MessageLegacy/MFAccountValidator.h>
#import <MessageLegacy/MFActivityMonitor.h>
#import <MessageLegacy/_MFActivityMonitorMultiTarget.h>
#import <MessageLegacy/MFAuthScheme.h>
#import <MessageLegacy/MFBufferedQueue.h>
#import <MessageLegacy/MFConnectionSettings.h>
#import <MessageLegacy/MFCRAM_MD5AuthScheme.h>
#import <MessageLegacy/MFCRAM_MD5Authenticator.h>
#import <MessageLegacy/DeliveryAccount.h>
#import <MessageLegacy/MFDigestMD5AuthScheme.h>
#import <MessageLegacy/_MFDigestMD5Authenticator.h>
#import <MessageLegacy/_MFFormatFlowedWriter.h>
#import <MessageLegacy/_MFInvocationQOSOverride.h>
#import <MessageLegacy/MFInvocationQueue.h>
#import <MessageLegacy/MFLibraryMessage.h>
#import <MessageLegacy/MFMessageDetails.h>
#import <MessageLegacy/MFLibraryStore.h>
#import <MessageLegacy/LocalAccount.h>
#import <MessageLegacy/_MFRootlessMailboxUid.h>
#import <MessageLegacy/MailAccount.h>
#import <MessageLegacy/MFMailboxUid.h>
#import <MessageLegacy/_MFMailboxUidEnumerator.h>
#import <MessageLegacy/_MFMailboxUidChildrenEnumerator.h>
#import <MessageLegacy/MFMailDelivery.h>
#import <MessageLegacy/MFMailDataMessageStore.h>
#import <MessageLegacy/MFMailMessage.h>
#import <MessageLegacy/MFMessageTransferResult.h>
#import <MessageLegacy/MFMailMessageStore.h>
#import <MessageLegacy/MFMailMimePart.h>
#import <MessageLegacy/MFMailMimeTextAttachment.h>
#import <MessageLegacy/MFMessageCriterion.h>
#import <MessageLegacy/_MFMessageFlags.h>
#import <MessageLegacy/MFMessageLibrary.h>
#import <MessageLegacy/MFBasicMessageDataSection.h>
#import <MessageLegacy/MFMessageSigner.h>
#import <MessageLegacy/MFMessageWriter.h>
#import <MessageLegacy/_MFOutgoingMessageBody.h>
#import <MessageLegacy/MFOutgoingMessage.h>
#import <MessageLegacy/MFAccountLoader.h>
#import <MessageLegacy/MFAccountStore.h>
#import <MessageLegacy/MFAppStateMonitor.h>
#import <MessageLegacy/MFAttachment.h>
#import <MessageLegacy/MFAttachmentComposeManager.h>
#import <MessageLegacy/MFAttachmentCompositionContext.h>
#import <MessageLegacy/MFAttachmentDataProvider.h>
#import <MessageLegacy/MFAttachmentLibraryDataProvider.h>
#import <MessageLegacy/MFAttachmentLibraryManager.h>
#import <MessageLegacy/MFAttachmentManager.h>
#import <MessageLegacy/MFAttachmentPlaceholder.h>
#import <MessageLegacy/MFAttachmentRaw.h>
#import <MessageLegacy/MFAttachmentUtilities.h>
#import <MessageLegacy/MFAttachmentBundle.h>
#import <MessageLegacy/MFAttachmentSecurityScope.h>
#import <MessageLegacy/MFComposeAttachmentDataProvider.h>
#import <MessageLegacy/MFContentErrorDocument.h>
#import <MessageLegacy/_MFContentProtectionObserverWrapper.h>
#import <MessageLegacy/MFCertificateTrustInfo.h>
#import <MessageLegacy/MFDecryptedAttachmentDataProvider.h>
#import <MessageLegacy/MFDeliveryResult.h>
#import <MessageLegacy/MFError.h>
#import <MessageLegacy/MFFakeMailAccount.h>
#import <MessageLegacy/MFFakeMailboxUid.h>
#import <MessageLegacy/MFFakeMailMessage.h>
#import <MessageLegacy/MFFetchLimits.h>
#import <MessageLegacy/MFLocalizedMessageHeaders.h>
#import <MessageLegacy/MFLockStateMonitor.h>
#import <MessageLegacy/MFMailMessageRelationshipAnalyzer.h>
#import <MessageLegacy/MFMailMessageStoreSearchResult.h>
#import <MessageLegacy/MFMessageCollectionInfo.h>
#import <MessageLegacy/MFMessageInfo.h>
#import <MessageLegacy/MFMessageInfoOrderedSet.h>
#import <MessageLegacy/MFNetworkController.h>
#import <MessageLegacy/_MFNetworkObserver.h>
#import <MessageLegacy/MFOutgoingMessageContent.h>
#import <MessageLegacy/MFOutgoingLibraryMessageContent.h>
#import <MessageLegacy/MFOutgoingRichtextMessageContent.h>
#import <MessageLegacy/MFOutgoingMultipartRelatedContent.h>
#import <MessageLegacy/MFOutgoingMessageDelivery.h>
#import <MessageLegacy/MFPowerController.h>
#import <MessageLegacy/MFRFC822AttachmentDataProvider.h>
#import <MessageLegacy/MFSecureMIMECompositionManager.h>
#import <MessageLegacy/MFSignatures.h>
#import <MessageLegacy/MFSparseMutable64IndexSet.h>
#import <MessageLegacy/MFTaskAssertion.h>
#import <MessageLegacy/_MFWeakObjectCacheRef.h>
#import <MessageLegacy/MFWeakObjectCache.h>
#import <MessageLegacy/MFMimeEnrichedReader.h>
#import <MessageLegacy/MFMonitoredInvocation.h>
#import <MessageLegacy/MFMessageKeychainManager.h>
#import <MessageLegacy/MFMessageURLConnectionDelegate.h>
#import <MessageLegacy/MFNTLMAuthScheme.h>
#import <MessageLegacy/_MFNTLMAuthenticator.h>
#import <MessageLegacy/MFPlainAuthScheme.h>
#import <MessageLegacy/_MFPlainAuthenticator.h>
#import <MessageLegacy/_MFLoginAuthenticator.h>
#import <MessageLegacy/MFPlainTextFragment.h>
#import <MessageLegacy/MFPlainTextDocument.h>
#import <MessageLegacy/MFProgressiveMimeParser.h>
#import <MessageLegacy/MFRequestQueue.h>
#import <MessageLegacy/MFSASLAuthenticator.h>
#import <MessageLegacy/_MFSecCMSDecoder.h>
#import <MessageLegacy/_MFSecCMSEncoder.h>
#import <MessageLegacy/_MFSecDataMessageStore.h>
#import <MessageLegacy/SMTPAccount.h>
#import <MessageLegacy/MFSMTPDelivery.h>
#import <MessageLegacy/MFSMTPResponse.h>
#import <MessageLegacy/MFWebAttachmentSource.h>
#import <MessageLegacy/MFWebMessageDocument.h>
