/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:40:14 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SearchFoundation/SearchFoundation-Structs.h>
#import <libobjc.A.dylib/SFColor.h>
@class NSDictionary, NSData;


@protocol SFColor <NSObject>
@property (assign,nonatomic) double redComponent; 
@property (assign,nonatomic) double greenComponent; 
@property (assign,nonatomic) double blueComponent; 
@property (assign,nonatomic) double alphaComponent; 
@property (nonatomic,readonly) NSDictionary * dictionaryRepresentation; 
@property (nonatomic,readonly) NSData * jsonData; 
@required
-(void)setRedComponent:(double)arg1;
-(void)setGreenComponent:(double)arg1;
-(void)setBlueComponent:(double)arg1;
-(void)setAlphaComponent:(double)arg1;
-(double)greenComponent;
-(double)redComponent;
-(double)blueComponent;
-(double)alphaComponent;
-(NSData *)jsonData;
-(NSDictionary *)dictionaryRepresentation;

@end

#import <libobjc.A.dylib/NSSecureCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSDictionary, NSData, NSString;

@interface SFColor : NSObject <SFColor, NSSecureCoding, NSCopying> {

	SCD_Struct_SF4 _has;
	double _redComponent;
	double _greenComponent;
	double _blueComponent;
	double _alphaComponent;

}

@property (assign,nonatomic) double redComponent;                                    //@synthesize redComponent=_redComponent - In the implementation block
@property (assign,nonatomic) double greenComponent;                                  //@synthesize greenComponent=_greenComponent - In the implementation block
@property (assign,nonatomic) double blueComponent;                                   //@synthesize blueComponent=_blueComponent - In the implementation block
@property (assign,nonatomic) double alphaComponent;                                  //@synthesize alphaComponent=_alphaComponent - In the implementation block
@property (nonatomic,readonly) NSDictionary * dictionaryRepresentation; 
@property (nonatomic,readonly) NSData * jsonData; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)supportsSecureCoding;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithProtobuf:(id)arg1 ;
-(void)setRedComponent:(double)arg1 ;
-(void)setGreenComponent:(double)arg1 ;
-(void)setBlueComponent:(double)arg1 ;
-(void)setAlphaComponent:(double)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(BOOL)hasRedComponent;
-(BOOL)hasGreenComponent;
-(BOOL)hasBlueComponent;
-(BOOL)hasAlphaComponent;
-(void)encodeWithCoder:(id)arg1 ;
-(double)greenComponent;
-(double)redComponent;
-(double)blueComponent;
-(double)alphaComponent;
-(NSData *)jsonData;
-(NSDictionary *)dictionaryRepresentation;
@end

