/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:42:33 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SiriPlaybackControlIntents.framework/SiriPlaybackControlIntents
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/SkipTimeIntentHandling.h>

@interface SiriPlaybackControlIntents.SkipTimeIntentHandler : NSObject <SkipTimeIntentHandling> {

	 playbackController;
	 deviceSelector;
	 analyticsService;

}
-(id)init;
-(void)handleSkipTime:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)resolveDurationForSkipTime:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)resolveDevicesForSkipTime:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)confirmSkipTime:(id)arg1 completion:(/*^block*/id)arg2 ;
@end

