#import <SiriInference/SiriInference.SuggestedContactsFilter.h>
#import <SiriInference/_TtCC13SiriInference8DateTime4Time.h>
#import <SiriInference/SiriInference.RelationshipAliasGenerator.h>
#import <SiriInference/_TtCC13SiriInference8DateTime8Interval.h>
#import <SiriInference/SiriInference.FirstAdvent.h>
#import <SiriInference/SiriInference.BackfillInteractions.h>
#import <SiriInference/SiriInference.IsFavoriteSignalGenerator.h>
#import <SiriInference/SiriInference.HolidaysDBUpdater.h>
#import <SiriInference/SiriInference.HolidaysDBUpdaterOperation.h>
#import <SiriInference/SiriInference.HolidaysDBPollingOperation.h>
#import <SiriInference/SiriInference.ScrubOldRecords.h>
#import <SiriInference/SiriInference.SolsticeAndEquinox.h>
#import <SiriInference/SiriInference.ContactResolver.h>
#import <SiriInference/_TtCC13SiriInference15ContactResolver14RequestContext.h>
#import <SiriInference/_TtCC13SiriInference15ContactResolver4Spec.h>
#import <SiriInference/SiriInference.GregorianEasterHoliday.h>
#import <SiriInference/_TtCCC13SiriInference8DateTime4Date7Holiday.h>
#import <SiriInference/SiriInference.HolidaysDatabase.h>
#import <SiriInference/SiriInference.HolidaysDBHolidayResolver.h>
#import <SiriInference/SiriInference.MeCardContactGenerator.h>
#import <SiriInference/SiriInference.HolidaysDBMobileAsset.h>
#import <SiriInference/SiriInference.PhoneAppDonation.h>
#import <SiriInference/AppMatches.h>
#import <SiriInference/SiriInference.DateTimeConstraintSolver.h>
#import <SiriInference/SiriInference.RestartableBlockOperation.h>
#import <SiriInference/SiriInference.CoreDuetInteractionMonitor.h>
#import <SiriInference/SiriInference.DateTimeSuggestionResolver.h>
#import <SiriInference/SiriInference.EventKitSignalGenerator.h>
#import <SiriInference/_TtCC13SiriInference8DateTime4Date.h>
#import <SiriInference/SiriInference.HypocorismGenerator.h>
#import <SiriInference/SiriInference.SiriRemembersContactSignalProvider.h>
#import <SiriInference/SiriInference.RefreshRollups.h>
#import <SiriInference/SiriInference.ContactsFrameworkMatcher.h>
#import <SiriInference/SiriInference.JulianEasterHoliday.h>
#import <SiriInference/SiriInference.SortingResolverRule.h>
#import <SiriInference/SiriInference.ScrubRuntimeDataRecords.h>
#import <SiriInference/SiriInference.CancellableStitcher.h>
#import <SiriInference/SiriInference.Intent.h>
#import <SiriInference/SiriInference.EKEventStoreMatcher.h>
#import <SiriInference/SiriInference.ScrubDodMLRecords.h>
#import <SiriInference/SiriInference.RecurringDateInterval.h>
#import <SiriInference/SiriInference.DodMLStore.h>
#import <SiriInference/SiriInference.DefinedTimeStore.h>
#import <SiriInference/SiriInference.BackgroundQueue.h>
#import <SiriInference/SiriInference.DateTimeConstraint.h>
#import <SiriInference/SiriInference.BackgroundSignalGenerator.h>
#import <SiriInference/_TtCC13SiriInference8DateTime13DateTimeRange.h>
#import <SiriInference/SiriInference.PeopleSuggesterSignalGenerator.h>
#import <SiriInference/SiriInference.InferenceError.h>
#import <SiriInference/SiriInference.BackgroundManager.h>
#import <SiriInference/_TtCC13SiriInference17BackgroundManager5Inner.h>
#import <SiriInference/SiriInference.CandidateContactGenerator.h>
#import <SiriInference/SiriInference.Thanksgiving.h>
#import <SiriInference/SiriInference.DateTime.h>
#import <SiriInference/SiriInference.PickFirstResolverRule.h>
#import <SiriInference/SiriInference.SaveInteraction.h>
#import <SiriInference/SiriInference.PeopleSuggesterHandleScorer.h>
#import <SiriInference/SiriInference.ConvergenceStrategyResolverRule.h>
#import <SiriInference/SiriInference.ScrubDeletedRecords.h>
#import <SiriInference/SiriInference.ProcessUnstitchedIntents.h>
#import <SiriInference/SiriInference.DateTimeSuggestionGenerator.h>
#import <SiriInference/SiriInference.DateTimeResolutionContext.h>
#import <SiriInference/SiriInference.MatchRelationNameSignalProvider.h>
#import <SiriInference/SiriInference.XPCActivityOperation.h>
#import <SiriInference/_TtCC13SiriInference8DateTime17RecurrencePattern.h>
#import <SiriInference/SiriInference.AnonymizeIdsInStitchedData.h>
#import <SiriInference/SiriInference.ContactRankerInput.h>
#import <SiriInference/SiriInference.ContactRankerOutput.h>
#import <SiriInference/SiriInference.ContactRanker.h>
#import <SiriInference/SQLite.Statement.h>
#import <SiriInference/SQLite.Connection.h>
