/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:41:40 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SafariSharedUI.framework/SafariSharedUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/_CompletionListRankingObserverFeedbackGenerator.h>

@class NSDate, NSMutableArray, NSString, SFRankingFeedback;

@interface _WBSSearchFoundationFeedbackGenerator : NSObject <_CompletionListRankingObserverFeedbackGenerator> {

	NSDate* _rankingStartDate;
	NSMutableArray* _sectionRankingFeedbackObjects;
	NSString* _currentSectionBundleIdentifier;
	NSMutableArray* _currentSectionResultRankingFeedbackObjects;
	SFRankingFeedback* _rankingFeedback;

}

@property (nonatomic,readonly) SFRankingFeedback * rankingFeedback;                                                    //@synthesize rankingFeedback=_rankingFeedback - In the implementation block
@property (assign,nonatomic,__weak) id<_CompletionListRankingObserverFeedbackGeneratorDelegate> delegate; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(SFRankingFeedback *)rankingFeedback;
-(void)didBeginRanking;
-(void)didEndRanking;
-(void)didBeginSectionWithBundleIdentifier:(id)arg1 ;
-(void)didAddItem:(id)arg1 hidingOutrankedResults:(id)arg2 hidingDuplicateResults:(id)arg3 ;
-(void)removeAllSectionsAndItems;
-(void)_commitPreviousSectionIfNecessary;
@end

