/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:41:40 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SafariSharedUI.framework/SafariSharedUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class WBSCompletionQuery, WBSParsecABGroupManager;


@protocol WBSParsecSearchSession <NSObject>
@property (assign,nonatomic,__weak) id<WBSParsecSearchSessionDelegate> delegate; 
@property (nonatomic,retain) WBSCompletionQuery * currentQuery; 
@property (assign,setter=setUIScale:,nonatomic) double uiScale; 
@property (nonatomic,readonly) id<WBSParsecFeedbackDispatcher> feedbackDispatcher; 
@property (nonatomic,readonly) WBSParsecABGroupManager * abGroupManager; 
@property (getter=isABTestingEnabled,nonatomic,readonly) BOOL abTestingEnabled; 
@required
-(WBSCompletionQuery *)currentQuery;
-(BOOL)isABTestingEnabled;
-(void)setDelegate:(id)arg1;
-(id<WBSParsecFeedbackDispatcher>)feedbackDispatcher;
-(double)uiScale;
-(void)setCurrentQuery:(id)arg1;
-(WBSParsecABGroupManager *)abGroupManager;
-(id<WBSParsecSearchSessionDelegate>)delegate;
-(void)setUIScale:(double)arg1;

@end

