/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:44:43 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol BSInvalidatable;
#import <PassKitUI/PassKitUI-Structs.h>
@class NSString;

@interface PKIdleTimerAssertion : NSObject {

	atomic_flag _invalidated;
	NSString* _reason;
	id<BSInvalidatable> _idleTimerAssertion;

}
-(id)initWithReason:(id)arg1 ;
-(void)invalidate;
-(void)dealloc;
-(id)init;
@end

