/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:47:13 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/Intents.framework/Intents
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Intents/INIntentForwardingActionResponse.h>

@class NSData;

@interface INGetIntentParameterOptionsForwardingActionResponse : INIntentForwardingActionResponse {

	NSData* _archivedObjectCollection;

}

@property (nonatomic,readonly) NSData * archivedObjectCollection;              //@synthesize archivedObjectCollection=_archivedObjectCollection - In the implementation block
+(BOOL)supportsSecureCoding;
-(id)initWithArchivedObjectCollection:(id)arg1 error:(id)arg2 ;
-(NSData *)archivedObjectCollection;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
@end

