/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:35:49 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SearchUI/SearchUIHorizontallyScrollingButtonController.h>

@class TLKProminenceView, TLKTextButton;

@interface SearchUIHorizontallyScrollingMoreResultsButtonController : SearchUIHorizontallyScrollingButtonController {

	TLKProminenceView* _backgroundView;

}

@property (retain) TLKTextButton * button; 
@property (retain) TLKProminenceView * backgroundView;              //@synthesize backgroundView=_backgroundView - In the implementation block
-(void)setBackgroundView:(TLKProminenceView *)arg1 ;
-(void)setCardSectionRowModel:(id)arg1 ;
-(id)init;
-(TLKProminenceView *)backgroundView;
@end

