#import <SMBSearch/cdbProp.h>
#import <SMBSearch/catalogNameProp.h>
#import <SMBSearch/queryTypeProp.h>
#import <SMBSearch/includeScopesProp.h>
#import <SMBSearch/scopeFlagsProp.h>
#import <SMBSearch/machineProp.h>
#import <SMBSearch/useContentIndexProp.h>
#import <SMBSearch/deferNonIndexedTrimProp.h>
#import <SMBSearch/useExtendedBtypesProp.h>
#import <SMBSearch/ignoreNoiseOnlyClausesProp.h>
#import <SMBSearch/genericOptionsStrProp.h>
#import <SMBSearch/deferCatalogVerifyProp.h>
#import <SMBSearch/genParseTreeProp.h>
#import <SMBSearch/freeTextAnyTermProp.h>
#import <SMBSearch/freeTextUseStemmingProp.h>
#import <SMBSearch/ignoreSBRIProp.h>
#import <SMBSearch/noExpensivePropsProp.h>
#import <SMBSearch/enableRowSetEventsProp.h>
#import <SMBSearch/rowQueryStatusProp.h>
#import <SMBSearch/cmdLocaleStrProp.h>
#import <SMBSearch/queryRestrictionProp.h>
#import <SMBSearch/parseTreeProp.h>
#import <SMBSearch/maxRankProp.h>
#import <SMBSearch/resultsFoundProp.h>
#import <SMBSearch/whereIDProp.h>
#import <SMBSearch/serverVersionProp.h>
#import <SMBSearch/serverWinVersionMajorProp.h>
#import <SMBSearch/serverWinVersionMinorProp.h>
#import <SMBSearch/serverNlsVersionProp.h>
#import <SMBSearch/serverNlsVersionDefProp.h>
#import <SMBSearch/sameSortOrderUsedProp.h>
#import <SMBSearch/utf16leData.h>
#import <SMBSearch/vtVector.h>
#import <SMBSearch/safeArrayBound.h>
#import <SMBSearch/vtSafeArray.h>
#import <SMBSearch/cbaseVariant.h>
#import <SMBSearch/wspHeader.h>
#import <SMBSearch/wspGetRows.h>
#import <SMBSearch/wspGetRowsOut.h>
#import <SMBSearch/searchColumn.h>
#import <SMBSearch/searchRow.h>
#import <SMBSearch/searchResults.h>
#import <SMBSearch/wspContext.h>
#import <SMBSearch/wspQueryIn.h>
#import <SMBSearch/cRowsetProperties.h>
#import <SMBSearch/wspQueryOut.h>
#import <SMBSearch/wspQueryStatusIn.h>
#import <SMBSearch/wspQueryStatusOut.h>
#import <SMBSearch/QueryStatusExResults.h>
#import <SMBSearch/wspQueryStatusExIn.h>
#import <SMBSearch/wspQueryStatusExOut.h>
#import <SMBSearch/fullPropSpec.h>
#import <SMBSearch/wspFreeCursorIn.h>
#import <SMBSearch/wspFreeCursorOut.h>
#import <SMBSearch/wspDisconnectIn.h>
#import <SMBSearch/wspPropertySet.h>
#import <SMBSearch/cRestrictionArray.h>
#import <SMBSearch/cRestriction.h>
#import <SMBSearch/cNodeRestriction.h>
#import <SMBSearch/cnodeBuilder.h>
#import <SMBSearch/cPropertyRestriction.h>
#import <SMBSearch/cCoercionRestriction.h>
#import <SMBSearch/cContentRestriction.h>
#import <SMBSearch/reuseWhereRestriction.h>
#import <SMBSearch/colOffsetMap.h>
#import <SMBSearch/cTableColumn.h>
#import <SMBSearch/pidMapper.h>
#import <SMBSearch/rowVariant.h>
#import <SMBSearch/wspSetBindingsIn.h>
#import <SMBSearch/wspConnectIn.h>
#import <SMBSearch/wspConnectOut.h>
