#import <PowerUI/PowerUITrialManager.h>
#import <PowerUI/PowerUIModelPredictionContainer.h>
#import <PowerUI/PowerUIMLAudioAccessoryModelPredictor.h>
#import <PowerUI/PowerUILPMNotifier.h>
#import <PowerUI/PowerUIMLTwoStageModelPredictor.h>
#import <PowerUI/PowerUIUPOManager.h>
#import <PowerUI/PowerUISmartChargeUtilities.h>
#import <PowerUI/PowerUIDefines.h>
#import <PowerUI/PowerUISmartChargeClient.h>
#import <PowerUI/PowerUIBatteryMitigationManager.h>
#import <PowerUI/PowerUISmartChargeClientAudioAccessories.h>
#import <PowerUI/PowerUIWakeRequestSignalMonitor.h>
#import <PowerUI/PowerUIPredictorHelper.h>
#import <PowerUI/PowerUIAccessoryStatus.h>
#import <PowerUI/PowerUIBluetoothHandler.h>
#import <PowerUI/PowerUIBluetoothHandlerFake.h>
#import <PowerUI/PowerUIAudioAccessorySmartChargeManager.h>
#import <PowerUI/PowerUISmartChargeManager.h>
#import <PowerUI/PowerUISmartChargeManagerUnsupported.h>
#import <PowerUI/PowerUIWalletSignalMonitor.h>
#import <PowerUI/PowerUISleepWakeMonitor.h>
#import <PowerUI/PowerUICalendarSignalMonitor.h>
#import <PowerUI/PowerUIAlarmSignalMonitor.h>
#import <PowerUI/PowerUIDesktopModePredictor.h>
#import <PowerUI/PowerUILocationSignalMonitor.h>
#import <PowerUI/durationModelInput.h>
#import <PowerUI/durationModelOutput.h>
#import <PowerUI/durationModel.h>
#import <PowerUI/audioAccessory_higher_usage_engInput.h>
#import <PowerUI/audioAccessory_higher_usage_engOutput.h>
#import <PowerUI/audioAccessory_higher_usage_eng.h>
#import <PowerUI/audioAccessory_higher_usage_regInput.h>
#import <PowerUI/audioAccessory_higher_usage_regOutput.h>
#import <PowerUI/audioAccessory_higher_usage_reg.h>
#import <PowerUI/audioAccessory_lower_usage_regInput.h>
#import <PowerUI/audioAccessory_lower_usage_regOutput.h>
#import <PowerUI/audioAccessory_lower_usage_reg.h>
#import <PowerUI/engageModelInput.h>
#import <PowerUI/engageModelOutput.h>
#import <PowerUI/engageModel.h>
#import <PowerUI/watch_durationInput.h>
#import <PowerUI/watch_durationOutput.h>
#import <PowerUI/watch_duration.h>
#import <PowerUI/watch_engageInput.h>
#import <PowerUI/watch_engageOutput.h>
#import <PowerUI/watch_engage.h>
#import <PowerUI/gbtClassifierInput.h>
#import <PowerUI/gbtClassifierOutput.h>
#import <PowerUI/gbtClassifier.h>
#import <PowerUI/gbtRegressorInput.h>
#import <PowerUI/gbtRegressorOutput.h>
#import <PowerUI/gbtRegressor.h>
#import <PowerUI/audioAccessory_lower_usage_engInput.h>
#import <PowerUI/audioAccessory_lower_usage_engOutput.h>
#import <PowerUI/audioAccessory_lower_usage_eng.h>
#import <PowerUI/shallow_modelInput.h>
#import <PowerUI/shallow_modelOutput.h>
#import <PowerUI/shallow_model.h>
