/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:41:49 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUIKit/CCUIMenuModuleViewController.h>

@class SCUIAssetProvider, CCUIAppLauncherModule;

@interface CCUIAppLauncherViewController : CCUIMenuModuleViewController {

	SCUIAssetProvider* _assetProvider;
	CCUIAppLauncherModule* _module;

}

@property (assign,nonatomic,__weak) CCUIAppLauncherModule * module;              //@synthesize module=_module - In the implementation block
-(void)_updateApplicationShortcutsActions;
-(void)setModule:(CCUIAppLauncherModule *)arg1 ;
-(void)viewDidLoad;
-(void)_activateApplicationForShortcutItem:(id)arg1 ;
-(id)_menuItemForShortcutItem:(id)arg1 ;
-(id)leadingImageForMenuItem:(id)arg1 ;
-(CCUIAppLauncherModule *)module;
-(BOOL)shouldBeginTransitionToExpandedContentModule;
-(id)_assetProvider;
-(void)buttonTouchDown:(id)arg1 forEvent:(id)arg2 ;
-(void)buttonTapped:(id)arg1 forEvent:(id)arg2 ;
-(BOOL)_canShowWhileLocked;
@end

