#import <IconServices/ISResourceMetadata.h>
#import <IconServices/ISAssetCatalogResource.h>
#import <IconServices/ISiOSMacAppRecipe.h>
#import <IconServices/ISiOSAppRecipe.h>
#import <IconServices/ISiOSAppClipRecipe.h>
#import <IconServices/ISwatchOSAppRecipe.h>
#import <IconServices/ISMessagesAppRecipe.h>
#import <IconServices/ISGenericRecipe.h>
#import <IconServices/ISIconFactory.h>
#import <IconServices/ISIcon.h>
#import <IconServices/ISIconCacheClient.h>
#import <IconServices/ISImageCache.h>
#import <IconServices/ISIconSpecification.h>
#import <IconServices/_ISCompositorElement.h>
#import <IconServices/ISCompositor.h>
#import <IconServices/ISLayer.h>
#import <IconServices/ISImageBagIcon.h>
#import <IconServices/ISIconLayer.h>
#import <IconServices/ISColor.h>
#import <IconServices/ISGraphicsContext.h>
#import <IconServices/ISIconDecorationResource.h>
#import <IconServices/ISIconCacheIOS.h>
#import <IconServices/ISBundleIcon.h>
#import <IconServices/ISDefaults.h>
#import <IconServices/ISContinuousRoundedRect.h>
#import <IconServices/ISCircle.h>
#import <IconServices/ISShapeCompositorResource.h>
#import <IconServices/ISTrailingStatusBadgeRecipe.h>
#import <IconServices/ISLeadingStatusBadgeRecipe.h>
#import <IconServices/ISCenterEmbossRecipe.h>
#import <IconServices/ISBundle.h>
#import <IconServices/ISIconResourceLocator.h>
#import <IconServices/ISIconTypeResourceLocator.h>
#import <IconServices/ISImageBag.h>
#import <IconServices/ISIconManager.h>
#import <IconServices/ISDropShaddowEffect.h>
#import <IconServices/ISEmbossedEffect.h>
#import <IconServices/ISDimmedEffect.h>
#import <IconServices/ISDimmedDarkEffect.h>
#import <IconServices/ISBorderEffect.h>
#import <IconServices/ISBlurEffect.h>
#import <IconServices/ISDeviceInfo.h>
#import <IconServices/ISImage.h>
#import <IconServices/ISConcreteImage.h>
#import <IconServices/ISCacheImage.h>
#import <IconServices/ISPlaceholderImage.h>
#import <IconServices/ISSymbolImage.h>
#import <IconServices/ISImageDescriptor.h>
#import <IconServices/ISSymbolImageDescriptor.h>
#import <IconServices/ISiosmacDocumentRecipe.h>
#import <IconServices/ISmacosDocumentRecipe.h>
#import <IconServices/ISiosDocumentRecipe.h>
#import <IconServices/ISIconDecoration.h>
#import <IconServices/ISIconObserver.h>
#import <IconServices/ISHintedValue.h>
#import <IconServices/ISHintedRect.h>
#import <IconServices/ISHintedSize.h>
#import <IconServices/ISHintedFloat.h>
#import <IconServices/ISIconIOS.h>
#import <IconServices/ISGenericIconIOS.h>
#import <IconServices/ISImageSpecification.h>
