#import <ProVideo/PVTaskToken.h>
#import <ProVideo/PVComputeGuidedFilter.h>
#import <ProVideo/PVOrientationEffect.h>
#import <ProVideo/PVTaskTokenPool.h>
#import <ProVideo/PVInstructionGraphNode.h>
#import <ProVideo/PVInstructionGraphSourceNode.h>
#import <ProVideo/PVCompositeDelegateContext.h>
#import <ProVideo/PVCompositeDelegateEffect.h>
#import <ProVideo/PVInstructionGraphSourceCompositeNode.h>
#import <ProVideo/PVInstructionGraphEffectNode.h>
#import <ProVideo/PVCameraFrameSet.h>
#import <ProVideo/PVFaceDetectionDepr.h>
#import <ProVideo/PVPMR.h>
#import <ProVideo/PVTimedObject.h>
#import <ProVideo/PVMotionEffectTransformComponent.h>
#import <ProVideo/PVMatrix44Double.h>
#import <ProVideo/PVMotionEffectTextComponent.h>
#import <ProVideo/PVContentRegistry.h>
#import <ProVideo/PVLivePlayerRenderLink.h>
#import <ProVideo/PVLivePlayerCARenderLink.h>
#import <ProVideo/PVLivePlayerCameraRenderLink.h>
#import <ProVideo/PVHostApplicationDelegateHandler.h>
#import <ProVideo/PVRenderEffectLoader.h>
#import <ProVideo/PVLivePlayerCameraSource.h>
#import <ProVideo/PVImageBuffer.h>
#import <ProVideo/PVLivePlayerAVAssetSource.h>
#import <ProVideo/PVCGImageBufferImpl.h>
#import <ProVideo/PVPushTransition.h>
#import <ProVideo/PVEnvironment.h>
#import <ProVideo/PVCrossDissolveTransition.h>
#import <ProVideo/PVRendererBase.h>
#import <ProVideo/PVEffectResources.h>
#import <ProVideo/PVLivePlayerImageSource.h>
#import <ProVideo/PVThermalMonitor.h>
#import <ProVideo/PVHGBitmapImageBufferImpl.h>
#import <ProVideo/PVEffectScheduler.h>
#import <ProVideo/PVSimpleTransition.h>
#import <ProVideo/PVNoneEffect.h>
#import <ProVideo/HGInputBitmapCacheItem.h>
#import <ProVideo/PVInputBitmapCache.h>
#import <ProVideo/CVPixelBufferCacheItem.h>
#import <ProVideo/PVInstructionGraphImageSourceNode.h>
#import <ProVideo/PVInstructionGraphSourceTrackNode.h>
#import <ProVideo/PVDocumentWrapper.h>
#import <ProVideo/PVDocumentCacheManager.h>
#import <ProVideo/PVInstructionGraphImageBufferSourceNode.h>
#import <ProVideo/PVExposureAdjust.h>
#import <ProVideo/PVCVPixelBufferImageBufferImpl.h>
#import <ProVideo/PVTransformAnimation.h>
#import <ProVideo/PVDeviceCharacteristics.h>
#import <ProVideo/PVAVFRenderJobDelegate.h>
#import <ProVideo/PVPanTestEffect.h>
#import <ProVideo/PVComputeGrabCut.h>
#import <ProVideo/PVHeliumEffect.h>
#import <ProVideo/PVXFormEffect.h>
#import <ProVideo/PVMotionEffectHitAreaComponent.h>
#import <ProVideo/PVStabilizationConfig.h>
#import <ProVideo/PVClearAlphaEffect.h>
#import <ProVideo/PVVideoCompositionInstruction.h>
#import <ProVideo/PVInstructionGraphGeneratorNode.h>
#import <ProVideo/PVPanAndZoomManager.h>
#import <ProVideo/PVWipeTransition.h>
#import <ProVideo/PVComputeDenseCRF.h>
#import <ProVideo/PVRenderRequest.h>
#import <ProVideo/PVRenderer.h>
#import <ProVideo/PVEffectPreviewRenderJobDelegate.h>
#import <ProVideo/PVInstructionGraphOrientationEffectNode.h>
#import <ProVideo/PVEffect.h>
#import <ProVideo/PVRenderRequestJobDelegate.h>
#import <ProVideo/PVMotionEffectTranscriptionComponent.h>
#import <ProVideo/PVLivePlayerThrottlingControlParameters.h>
#import <ProVideo/PVLivePlayerThermalThrottlingPolicy.h>
#import <ProVideo/PVVideoCompositing.h>
#import <ProVideo/PVVideoCompositingExporter.h>
#import <ProVideo/PVCameraPreviewRequest.h>
#import <ProVideo/PVRenderedTexture.h>
#import <ProVideo/PVCameraPreviewRenderer.h>
#import <ProVideo/PVMotionEffect.h>
#import <ProVideo/PVNCLCTriplet.h>
#import <ProVideo/PVColorSpace.h>
#import <ProVideo/PVEffectAssets.h>
#import <ProVideo/PVEffectPreviewGenerator.h>
#import <ProVideo/PVEffectRegistryEntry.h>
#import <ProVideo/PVColorCorrectEffect.h>
#import <ProVideo/PVColorCorrectEffect_BnW.h>
#import <ProVideo/PVColorCorrectEffect_Contrast.h>
#import <ProVideo/PVColorCorrectEffect_Bright.h>
#import <ProVideo/PVColorCorrectEffect_Warm.h>
#import <ProVideo/PVColorCorrectEffect_Cool.h>
#import <ProVideo/PVMultiBlendEffect.h>
#import <ProVideo/PVMultiBlendLayerParams.h>
#import <ProVideo/PVVideoCompositingContext.h>
#import <ProVideo/PVCMSampleBuffer.h>
#import <ProVideo/PVFrameSet.h>
#import <ProVideo/PVCameraFrameMetadata.h>
#import <ProVideo/PVFaceDetection.h>
#import <ProVideo/PVLivePlayer.h>
#import <ProVideo/PVSlideTransition.h>
#import <ProVideo/PVEffectTimedPropertiesDelegateWrapper.h>
#import <ProVideo/PVEffectTimedPropertiesComponent.h>
#import <ProVideo/PVBlurEffect.h>
#import <ProVideo/BHBehaviorsBundle.h>
#import <ProVideo/PAEStroke.h>
#import <ProVideo/PAEOverlappingCircles.h>
#import <ProVideo/PAEPixellate.h>
#import <ProVideo/PAEKaleidascope.h>
#import <ProVideo/TDreamDistortionFX.h>
#import <ProVideo/TDreamProgramWrapperTwoInput.h>
#import <ProVideo/PAEPoke.h>
#import <ProVideo/PAESunburst.h>
#import <ProVideo/TDreamMaskBlend.h>
#import <ProVideo/PAEHueCurveChannelData.h>
#import <ProVideo/PAEFTHueCurveChannelData.h>
#import <ProVideo/PAEiOSLightTunnel.h>
#import <ProVideo/TDreamColoricer.h>
#import <ProVideo/PAETextureWrap.h>
#import <ProVideo/TDreamGaussBlurExpressOpt9.h>
#import <ProVideo/TDreamStrokeAndBlendOpt.h>
#import <ProVideo/PAEChannelBlur.h>
#import <ProVideo/PAECircleBlur.h>
#import <ProVideo/PAECompoundBlur.h>
#import <ProVideo/PAEDirectionalBlur.h>
#import <ProVideo/PAEGaussianBlur.h>
#import <ProVideo/PAEGradientBlur.h>
#import <ProVideo/PAEPrism.h>
#import <ProVideo/PAESoftFocus.h>
#import <ProVideo/PAEVariableBlur.h>
#import <ProVideo/PAEEquirectProjectFilter.h>
#import <ProVideo/PAESimpleBorder.h>
#import <ProVideo/TDreamFramebufferManager.h>
#import <ProVideo/PAEWidescreen.h>
#import <ProVideo/PAEColorSelectionChannelData.h>
#import <ProVideo/PAEFTColorSelectionChannelData.h>
#import <ProVideo/PAEGradientColorize.h>
#import <ProVideo/PAEBloom.h>
#import <ProVideo/PAEFracturedFilter.h>
#import <ProVideo/PAEFracturedTransition.h>
#import <ProVideo/PAEFracturedTransition_Shatter.h>
#import <ProVideo/PAEFracturedTransition_Wave.h>
#import <ProVideo/PAEFracturedTransition_Twirl.h>
#import <ProVideo/PAEFracturedTransition_Extend.h>
#import <ProVideo/PAEFracturedTransition_FlyBack.h>
#import <ProVideo/PAEFracturedTransition_Confetti.h>
#import <ProVideo/PAEFracturedTransition_Radial.h>
#import <ProVideo/PAEFracturedTransition_Flip.h>
#import <ProVideo/PAEBadTV.h>
#import <ProVideo/TDreamBFBlurPassTwoOpt.h>
#import <ProVideo/PAEiOSStretch.h>
#import <ProVideo/TDreamOutputBuffer.h>
#import <ProVideo/TDreamBFBlurPassTwo.h>
#import <ProVideo/TDreamStroke.h>
#import <ProVideo/PAEZoomBlur.h>
#import <ProVideo/PAESimpleKeyer.h>
#import <ProVideo/PAEChromaKeyeriOS.h>
#import <ProVideo/PAEBlackHole.h>
#import <ProVideo/PAEBulge.h>
#import <ProVideo/PAEHalftone.h>
#import <ProVideo/PAEBumpMap.h>
#import <ProVideo/PAEDisplace.h>
#import <ProVideo/PAEEarthquake.h>
#import <ProVideo/PAEFisheye.h>
#import <ProVideo/PAEFlop.h>
#import <ProVideo/TDreamGLProgramHelper.h>
#import <ProVideo/PAEColorWheelChannelData.h>
#import <ProVideo/PAEFTColorWheelChannelData.h>
#import <ProVideo/PAEFunHouse.h>
#import <ProVideo/PAEPhotosFilters.h>
#import <ProVideo/PAEGlassBlock.h>
#import <ProVideo/PAEInsectEye.h>
#import <ProVideo/PAEMirror.h>
#import <ProVideo/PAERingLens.h>
#import <ProVideo/PAEScrape.h>
#import <ProVideo/TDreamGrayscale.h>
#import <ProVideo/PAESphere.h>
#import <ProVideo/PAEStyleTransfer.h>
#import <ProVideo/PAEStarburst.h>
#import <ProVideo/TDreamEdges.h>
#import <ProVideo/PAEStripesFilter.h>
#import <ProVideo/TDreamQuanticeOpt.h>
#import <ProVideo/PAETarget.h>
#import <ProVideo/PAEKeyerSetupUtil.h>
#import <ProVideo/PAETwirl.h>
#import <ProVideo/PAEUnderwater.h>
#import <ProVideo/PAEOffset.h>
#import <ProVideo/PAEWave.h>
#import <ProVideo/TDreamStrokeAndBlend.h>
#import <ProVideo/PAEDummyiOS.h>
#import <ProVideo/PAECheckerboard.h>
#import <ProVideo/TDreamColorStroke.h>
#import <ProVideo/PAELightRays.h>
#import <ProVideo/TDreamManagerContextMapKey.h>
#import <ProVideo/TDreamManagerPrograms.h>
#import <ProVideo/TDreamManager.h>
#import <ProVideo/TDreamColorStrokeOpt.h>
#import <ProVideo/PAEFill.h>
#import <ProVideo/TDreamGaussBlurExpress.h>
#import <ProVideo/PAEGradient.h>
#import <ProVideo/PAESharpen.h>
#import <ProVideo/TDreamLookupFilter.h>
#import <ProVideo/PAEStripesGenerator.h>
#import <ProVideo/PAEColorSolid.h>
#import <ProVideo/PAEComicTown.h>
#import <ProVideo/TDreamBFBlurPassOne.h>
#import <ProVideo/TDreamSobel.h>
#import <ProVideo/PAEVignette.h>
#import <ProVideo/PAEColorBalance.h>
#import <ProVideo/PAELevels.h>
#import <ProVideo/PAELumaKeyer.h>
#import <ProVideo/PAEKeyerLumaSetup.h>
#import <ProVideo/TDreamBlend.h>
#import <ProVideo/PAELumaKey.h>
#import <ProVideo/PAEUnsharpMask.h>
#import <ProVideo/TDreamBFBlurPassOneOpt.h>
#import <ProVideo/PAEChannelMixer.h>
#import <ProVideo/TDreamFramebuffer.h>
#import <ProVideo/PAEComic.h>
#import <ProVideo/PAEKeyerOMVertex.h>
#import <ProVideo/PAEKeyerCbCrSetup.h>
#import <ProVideo/PAEKeyer.h>
#import <ProVideo/PAEKeyerAutokeySetupUtil.h>
#import <ProVideo/PAEKeyerHistogram.h>
#import <ProVideo/PAEKeyerAutokeySetup.h>
#import <ProVideo/PAEKeyerPreprocess.h>
#import <ProVideo/PAEKeyerMatteTools.h>
#import <ProVideo/TDreamVignetteAndQuantice.h>
#import <ProVideo/PAEColorCurveChannelData.h>
#import <ProVideo/PAEFTColorCurveChannelData.h>
#import <ProVideo/PAEKeyerInitialize.h>
#import <ProVideo/PAEBlueGreenScreen.h>
#import <ProVideo/TDreamGaussBlurExpressPassTwo.h>
#import <ProVideo/TDreamSobelOpt.h>
#import <ProVideo/PAEGamma.h>
#import <ProVideo/TDreamGaussBlurExpressPassTwoOpt9.h>
#import <ProVideo/TDreamVignette.h>
#import <ProVideo/TDreamEdgesOpt.h>
#import <ProVideo/PAEInvert.h>
#import <ProVideo/TDreamLookupFilterOpt.h>
#import <ProVideo/PAEMinMax.h>
#import <ProVideo/TDreamProgramWrapper.h>
#import <ProVideo/PAETint.h>
#import <ProVideo/PAEBrightness.h>
#import <ProVideo/TDreamZoomOutFX.h>
#import <ProVideo/PAEColorize.h>
#import <ProVideo/PAEOuterGlow.h>
#import <ProVideo/PAEiOSTwirl.h>
#import <ProVideo/PAEContrast.h>
#import <ProVideo/PAEOffsetColorCurveChannelData.h>
#import <ProVideo/PAEHSVAdjust.h>
#import <ProVideo/PAEDesaturate.h>
#import <ProVideo/PAEThreshold.h>
#import <ProVideo/PAEEquirectProject.h>
#import <ProVideo/PAEGlow.h>
#import <ProVideo/PAEAddNoise.h>
#import <ProVideo/PAEScratchVector.h>
#import <ProVideo/PAEBadFilm.h>
#import <ProVideo/PAEiOSKaleidoscope.h>
#import <ProVideo/PAECamcorder.h>
#import <ProVideo/PAEGloom.h>
#import <ProVideo/PAEMono.h>
#import <ProVideo/PAETonal.h>
#import <ProVideo/PAENoir.h>
#import <ProVideo/PAEFade.h>
#import <ProVideo/PAEChrome.h>
#import <ProVideo/PAEProcess.h>
#import <ProVideo/PAETransfer.h>
#import <ProVideo/PAEInstant.h>
#import <ProVideo/PAEBleach.h>
#import <ProVideo/PAECalifornia.h>
#import <ProVideo/PAENevada.h>
#import <ProVideo/PAENewYork.h>
#import <ProVideo/PAESixties.h>
#import <ProVideo/PAEVividStandardBG.h>
#import <ProVideo/PAEVividCoolBG.h>
#import <ProVideo/PAEVividWarmBG.h>
#import <ProVideo/PAEDramaticFG.h>
#import <ProVideo/PAEDramaticBG.h>
#import <ProVideo/PAEDramaticCoolBG.h>
#import <ProVideo/PAEDramaticCoolFG.h>
#import <ProVideo/PAEDramaticWarmBG.h>
#import <ProVideo/PAEDramaticWarmFG.h>
#import <ProVideo/PAESilvertone.h>
#import <ProVideo/PAEBlackAndWhiteNoir.h>
#import <ProVideo/PAEBlackAndWhiteMono.h>
#import <ProVideo/PAECool.h>
#import <ProVideo/PAEGrayscale.h>
#import <ProVideo/FxHostCapabilities.h>
#import <ProVideo/FxImage.h>
#import <ProVideo/FxBitmap.h>
#import <ProVideo/FxTexture.h>
#import <ProVideo/FxMatrix44.h>
#import <ProVideo/FxColor.h>
#import <ProVideo/FxTransform.h>
#import <ProVideo/FxVector.h>
#import <ProVideo/FxShape.h>
#import <ProVideo/FxPlug.h>
#import <ProVideo/FxPlugDescriptor.h>
#import <ProVideo/FxPlugGroup.h>
#import <ProVideo/FxPlugGroupDescriptor.h>
#import <ProVideo/FxStream.h>
#import <ProVideo/FxSample.h>
#import <ProVideo/FxPin.h>
#import <ProVideo/FxParameterAffineTransform.h>
#import <ProVideo/FxParameterAngle.h>
#import <ProVideo/FxParameterBoolean.h>
#import <ProVideo/FxParameterColor.h>
#import <ProVideo/FxParameterCustom.h>
#import <ProVideo/FxParameterGroup.h>
#import <ProVideo/FxParameterImage.h>
#import <ProVideo/FxParameterListSelection.h>
#import <ProVideo/FxParameterPoint2d.h>
#import <ProVideo/FxParameterPoint3d.h>
#import <ProVideo/FxParameterPushButton.h>
#import <ProVideo/FxParameterRect.h>
#import <ProVideo/FxParameterSlider.h>
#import <ProVideo/FxParameterText.h>
#import <ProVideo/FxBitmapImage.h>
#import <ProVideo/FxContext.h>
#import <ProVideo/FxMetaPlug.h>
#import <ProVideo/FxMetaPlugWrapper.h>
#import <ProVideo/FxHost.h>
#import <ProVideo/FxPinParameter.h>
#import <ProVideo/Program_Dummy.h>
#import <ProVideo/PSMain.h>
#import <ProVideo/OZFxPlugColorGamutHandler.h>
#import <ProVideo/OZNotificationStub.h>
#import <ProVideo/OZRigDropMenuTarget.h>
#import <ProVideo/ByteOffsetPair.h>
#import <ProVideo/TBXMLHelper.h>
#import <ProVideo/OZFxPixelTransformsHandler.h>
#import <ProVideo/OZFxPlugHostPrivateAPI.h>
#import <ProVideo/OZFxPlugParameterHandlerUIUpdate.h>
#import <ProVideo/OZFxPlugTimingAPI.h>
#import <ProVideo/OZFxPlugHostPropertiesAPI.h>
#import <ProVideo/OZFxPlugVersioningAPI.h>
#import <ProVideo/OZFxPlug3DAPI.h>
#import <ProVideo/OZFxPrincipalDelegate.h>
#import <ProVideo/OZFxPlugProgressAPI.h>
#import <ProVideo/OZFxPlugAPIManager.h>
#import <ProVideo/BlockedPlugin.h>
#import <ProVideo/PROConcretePlugInManager.h>
#import <ProVideo/PROPlugInManager.h>
#import <ProVideo/PROConcretePlugInGroup.h>
#import <ProVideo/PROPlugInGroup.h>
#import <ProVideo/PROConcretePlugIn.h>
#import <ProVideo/PROPlugIn.h>
#import <ProVideo/PROBundleHandler.h>
#import <ProVideo/PROPlugInFirewall.h>
#import <ProVideo/PROReadWriteLock.h>
#import <ProVideo/PROCAPIDelegate.h>
#import <ProVideo/PROLegacyPluginManager.h>
#import <ProVideo/PAESharedDefaultBase.h>
#import <ProVideo/FxHeliumImage.h>
#import <ProVideo/FxPlugAPIHandler.h>
#import <ProVideo/FxPrincipalAPIHandler.h>
#import <ProVideo/PAETile.h>
#import <ProVideo/PCUserDefaultsBroadcaster.h>
#import <ProVideo/FigTimeObj.h>
#import <ProVideo/PCWeakPointerValue.h>
#import <ProVideo/PCMatrix44Double.h>
#import <ProVideo/PMRSplitTime.h>
#import <ProVideo/PMRStopwatch.h>
#import <ProVideo/PCFxBlendOptions.h>
#import <ProVideo/PCFxLightWrapOptions.h>
#import <ProVideo/PCXMPStringParser.h>
#import <ProVideo/PMCachedBitmapObject.h>
#import <ProVideo/PMObjectCache.h>
#import <ProVideo/PMObjectCacheEntry.h>
#import <ProVideo/TXMain.h>
