/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:46:17 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/NanoPassKit.framework/NanoPassKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NanoPassKit/NPKPaymentProvisioningFlowStepContext.h>

@class NSString, NSArray, PKPaymentSetupProduct;

@interface NPKPaymentProvisioningFlowControllerReaderModeEntryStepContext : NPKPaymentProvisioningFlowStepContext {

	NSString* _title;
	NSString* _subtitle;
	NSArray* _setupFields;
	PKPaymentSetupProduct* _product;

}

@property (nonatomic,retain) NSString * title;                             //@synthesize title=_title - In the implementation block
@property (nonatomic,retain) NSString * subtitle;                          //@synthesize subtitle=_subtitle - In the implementation block
@property (nonatomic,retain) NSArray * setupFields;                        //@synthesize setupFields=_setupFields - In the implementation block
@property (nonatomic,retain) PKPaymentSetupProduct * product;              //@synthesize product=_product - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSString *)subtitle;
-(PKPaymentSetupProduct *)product;
-(void)setSubtitle:(NSString *)arg1 ;
-(NSString *)title;
-(id)initWithCoder:(id)arg1 ;
-(void)setProduct:(PKPaymentSetupProduct *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(id)initWithRequestContext:(id)arg1 ;
-(id)description;
-(void)setSetupFields:(NSArray *)arg1 ;
-(NSArray *)setupFields;
@end

