#import <HealthDiagnosticExtensionCore/HDDiagnosticExtension.h>
#import <HealthDiagnosticExtensionCore/HDDaemonDiagnosticOperation.h>
#import <HealthDiagnosticExtensionCore/HDCloudSyncDiagnosticOperation.h>
#import <HealthDiagnosticExtensionCore/HDDatabaseDiagnosticOperation.h>
#import <HealthDiagnosticExtensionCore/HDNanoSyncDiagnosticOperation.h>
#import <HealthDiagnosticExtensionCore/HDDiagnosticOperation.h>
#import <HealthDiagnosticExtensionCore/HDWorkoutCondenserDiagnosticOperation.h>
