#import <MediaFoundation/MediaFoundation.QueueAssetLoader.h>
#import <MediaFoundation/MediaFoundation.ItemLoader.h>
#import <MediaFoundation/MediaFoundation.ItemBufferProducer.h>
#import <MediaFoundation/MediaFoundation.PlayerController.h>
#import <MediaFoundation/MediaFoundation.VideoUserAction.h>
#import <MediaFoundation/PlayerViewControllerBehavior.h>
#import <MediaFoundation/MediaFoundation.PlayerFSM.h>
#import <MediaFoundation/MediaFoundation.JumpToTimeState.h>
#import <MediaFoundation/MediaFoundation.PausedState.h>
#import <MediaFoundation/MediaFoundation.SeekingState.h>
#import <MediaFoundation/MediaFoundation.ChangingQueueState.h>
#import <MediaFoundation/MediaFoundation.ResettingQueueState.h>
#import <MediaFoundation/MediaFoundation.ChangingCurrentItemState.h>
#import <MediaFoundation/MediaFoundation.RouteMetadata.h>
#import <MediaFoundation/MediaFoundation.EndOfQueueState.h>
#import <MediaFoundation/MediaFoundation.TransitionState.h>
#import <MediaFoundation/MediaFoundation.NaturalTransitionState.h>
#import <MediaFoundation/MediaFoundation.FailedTransitionState.h>
#import <MediaFoundation/MediaFoundation.FailedInitialLoadingTransitionState.h>
#import <MediaFoundation/MediaFoundation.SkippingTransitionState.h>
#import <MediaFoundation/MediaFoundation.WaitingForItemTransitionState.h>
#import <MediaFoundation/MediaFoundation.InternalPlaybackStackController.h>
#import <MediaFoundation/MediaFoundation.BackgroundTask.h>
#import <MediaFoundation/MediaFoundation.BackgroundTaskController.h>
#import <MediaFoundation/MediaFoundation.InitialLoadingState.h>
#import <MediaFoundation/MediaFoundation.InitiatingPlaybackState.h>
#import <MediaFoundation/MediaFoundation.PlayingState.h>
#import <MediaFoundation/MediaFoundation.MediaServicesInterruptedState.h>
#import <MediaFoundation/MediaFoundation.MediaServicesResumingState.h>
#import <MediaFoundation/MediaFoundation.InternalPlayerController.h>
#import <MediaFoundation/MediaFoundation.ScanningState.h>
#import <MediaFoundation/MediaFoundation.TransportableState.h>
#import <MediaFoundation/MediaFoundation.InterruptedState.h>
#import <MediaFoundation/MFDescription.h>
#import <MediaFoundation/MFAudioSessionConfiguration.h>
#import <MediaFoundation/MFPlaybackStackControllerImplementation.h>
#import <MediaFoundation/MediaFoundation.State.h>
#import <MediaFoundation/MediaFoundation.EventTime.h>
#import <MediaFoundation/MediaFoundation.IdleState.h>
#import <MediaFoundation/MediaFoundation.EventReporter.h>
#import <MediaFoundation/MediaFoundation.PlaybackStackController.h>
#import <MediaFoundation/MediaFoundation.ErrorResolutionState.h>
#import <MediaFoundation/MediaFoundation.UserEventsMonitor.h>
#import <MediaFoundation/_TtC15MediaFoundationP33_8E60203C4A0D8D08719FEC3D39F6597C26UserEventCompletionMonitor.h>
