#import <InputContext/_ICNamedEntityRecord.h>
#import <InputContext/_ICContactRecord.h>
#import <InputContext/_ICInputContextManager.h>
#import <InputContext/_ICProactiveTrigger.h>
#import <InputContext/_ICPredictedItem.h>
#import <InputContext/_ICPredictionManager.h>
#import <InputContext/_ICContact.h>
#import <InputContext/_ICNullLexiconManager.h>
#import <InputContext/_ICPortraitPredictionSource.h>
#import <InputContext/_ICPortraitLexiconSource.h>
#import <InputContext/_ICLexiconManager.h>
#import <InputContext/_ICInternalSource.h>
#import <InputContext/_ICInputSuggesterPredictionSource.h>
#import <InputContext/_ICSearchContext.h>
#import <InputContext/_ICTransientLexicon.h>
#import <InputContext/_ICLexiconView.h>
#import <InputContext/_ICPortraitUtilities.h>
#import <InputContext/_ICInputContextFactory.h>
#import <InputContext/_ICResultCache.h>
#import <InputContext/_ICLexiconUtilities.h>
#import <InputContext/_ICNamedEntityStore.h>
