/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:46:06 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OADEffectsParent <NSObject>
@required
-(BOOL)hasEffects;
-(id)effects;
-(void)setEffects:(id)arg1;

@end

