/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:46:11 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class WDDocument, NSMutableArray, NSMutableDictionary, WDListDefinition;

@interface WDListDefinitionTable : NSObject {

	WDDocument* mDocument;
	NSMutableArray* mListDefinitions;
	NSMutableDictionary* mListDefinitionMapById;
	NSMutableDictionary* mListDefinitionMapByStyleId;
	WDListDefinition* mNullListDefinition;
	WDListDefinition* mDefaultListDefinition;

}
-(id)definitions;
-(id)initWithDocument:(id)arg1 ;
-(id)description;
-(id)addDefinitionWithDefinitionId:(int)arg1 styleId:(id)arg2 ;
-(id)resolvedDefinitionWithDefinitionId:(int)arg1 ;
-(id)definitionWithDefinitionId:(int)arg1 ;
-(id)definitionWithStyleId:(id)arg1 ;
@end

