#import <AXMediaUtilities/AXMScreenGrabber.h>
#import <AXMediaUtilities/AXMAssetManager.h>
#import <AXMediaUtilities/AXMHorizonDetectorNode.h>
#import <AXMediaUtilities/AXMVisionFeatureColorInfo.h>
#import <AXMediaUtilities/AXMVisionFeatureFaceAttributes.h>
#import <AXMediaUtilities/AXVNEspressoDetectedObject.h>
#import <AXMediaUtilities/AXMSinglePitchTone.h>
#import <AXMediaUtilities/AXMFaceDetectorNode.h>
#import <AXMediaUtilities/AXMImageAestheticsNode.h>
#import <AXMediaUtilities/AXMService.h>
#import <AXMediaUtilities/AXMOutputRequest.h>
#import <AXMediaUtilities/AXMOutputRequestHandle.h>
#import <AXMediaUtilities/AXMDataRegressionModelExponential.h>
#import <AXMediaUtilities/AXShotflowFaceDetection.h>
#import <AXMediaUtilities/AXMModelDetectorNode.h>
#import <AXMediaUtilities/AXMScreenCaptureNode.h>
#import <AXMediaUtilities/AXMTraitDetectorNode.h>
#import <AXMediaUtilities/AXMMobileAssetEvaluationNode.h>
#import <AXMediaUtilities/AXMDescriptionBuilder.h>
#import <AXMediaUtilities/AXMVisionEngine.h>
#import <AXMediaUtilities/_AXMVisionEngineAnalysisTask.h>
#import <AXMediaUtilities/AXMVisionFeatureComparator.h>
#import <AXMediaUtilities/AXMCameraFrameContext.h>
#import <AXMediaUtilities/AXMFunctionTone.h>
#import <AXMediaUtilities/AXMVisionPipelineContext.h>
#import <AXMediaUtilities/AXMTextDetectorNode.h>
#import <AXMediaUtilities/AXMIconVisionEngine.h>
#import <AXMediaUtilities/AXMTaskDispatcher.h>
#import <AXMediaUtilities/AXMTask.h>
#import <AXMediaUtilities/AXElementVision__generated__Input.h>
#import <AXMediaUtilities/AXElementVision__generated__Output.h>
#import <AXMediaUtilities/AXElementVision__generated__.h>
#import <AXMediaUtilities/AXMADSREnvelope.h>
#import <AXMediaUtilities/AXMRectangleDetectorNode.h>
#import <AXMediaUtilities/AXMVisionColor.h>
#import <AXMediaUtilities/AXMVisionColorMarker.h>
#import <AXMediaUtilities/AXMSpeechComponent.h>
#import <AXMediaUtilities/AXMAudioDataSourceMixer.h>
#import <AXMediaUtilities/AXMAVCaptureSessionNode.h>
#import <AXMediaUtilities/AXMAudioSession.h>
#import <AXMediaUtilities/AXMOutputComponent.h>
#import <AXMediaUtilities/AXMVisionResult.h>
#import <AXMediaUtilities/AXMVisionEngineCache.h>
#import <AXMediaUtilities/_AXMPlayerItemLegibleOutput.h>
#import <AXMediaUtilities/AXMAVPlayerItemNode.h>
#import <AXMediaUtilities/AXMImageCaptionModelAssetManager.h>
#import <AXMediaUtilities/AXMVisionFeatureFaceDetectionResult.h>
#import <AXMediaUtilities/AXShotflowDetector.h>
#import <AXMediaUtilities/AXMTaxonomyNode.h>
#import <AXMediaUtilities/AXMPhotoVisionSupport.h>
#import <AXMediaUtilities/AXMNSFWDetectorNode.h>
#import <AXMediaUtilities/AXMGeometryUtilities.h>
#import <AXMediaUtilities/AXMAVUtilities.h>
#import <AXMediaUtilities/AXMCaptureManager.h>
#import <AXMediaUtilities/AXMCaptureSettings.h>
#import <AXMediaUtilities/_AXMCaptureManagerDetectionEngine.h>
#import <AXMediaUtilities/AXMSequenceRequestManager.h>
#import <AXMediaUtilities/Prediction.h>
#import <AXMediaUtilities/AXMAXElementDetectorNode.h>
#import <AXMediaUtilities/AXMLayoutItem.h>
#import <AXMediaUtilities/AXMLayoutSequence.h>
#import <AXMediaUtilities/AXMLayoutLine.h>
#import <AXMediaUtilities/AXMLayoutRegion.h>
#import <AXMediaUtilities/AXMTextLayoutManager.h>
#import <AXMediaUtilities/AXMImageRegistrationNode.h>
#import <AXMediaUtilities/AXMCameraMetadataNode.h>
#import <AXMediaUtilities/AXMCaptureVideoDataOutput.h>
#import <AXMediaUtilities/AXMCompressor.h>
#import <AXMediaUtilities/AXMOutputAction.h>
#import <AXMediaUtilities/AXMSpeechOutputAction.h>
#import <AXMediaUtilities/AXMSoundOutputAction.h>
#import <AXMediaUtilities/AXMOneShotSoundOutputAction.h>
#import <AXMediaUtilities/AXMActiveSoundOutputAction.h>
#import <AXMediaUtilities/AXMHapticOutputAction.h>
#import <AXMediaUtilities/AXMOutputActionHandle.h>
#import <AXMediaUtilities/AXMActiveSoundOutputActionHandle.h>
#import <AXMediaUtilities/AXMPipelineContextInput.h>
#import <AXMediaUtilities/AXMIconClassDetectorNode.h>
#import <AXMediaUtilities/AXMSemanticText.h>
#import <AXMediaUtilities/AXMSemanticTextFactory.h>
#import <AXMediaUtilities/_AXMSemanticTextCursor.h>
#import <AXMediaUtilities/AXMPixelBufferWrapper.h>
#import <AXMediaUtilities/AXMSceneprintBasedNode.h>
#import <AXMediaUtilities/AXMAssetMetadataNode.h>
#import <AXMediaUtilities/AXMDataSonifier.h>
#import <AXMediaUtilities/iconclassification__generated__Input.h>
#import <AXMediaUtilities/iconclassification__generated__Output.h>
#import <AXMediaUtilities/iconclassification__generated__.h>
#import <AXMediaUtilities/_AXMSettingObserver.h>
#import <AXMediaUtilities/AXMSettings.h>
#import <AXMediaUtilities/AXMVisionFeatureAssetMetadata.h>
#import <AXMediaUtilities/AXMVisionFeatureAestheticsResult.h>
#import <AXMediaUtilities/AXMDisplayManager.h>
#import <AXMediaUtilities/AXMDisplay.h>
#import <AXMediaUtilities/AXMDataRegressionModelPower.h>
#import <AXMediaUtilities/AXMDataSummary.h>
#import <AXMediaUtilities/AXMCoreMotionNode.h>
#import <AXMediaUtilities/AXMAddressFormatter.h>
#import <AXMediaUtilities/AXMLiveContinuousTone.h>
#import <AXMediaUtilities/AXShotflowHelpers.h>
#import <AXMediaUtilities/AXMDataRegressionModelSine.h>
#import <AXMediaUtilities/AXMProminentObjectsDetectorNode.h>
#import <AXMediaUtilities/AXMBarcodeNode.h>
#import <AXMediaUtilities/AXMEvaluationNode.h>
#import <AXMediaUtilities/AXShotflowConfiguration.h>
#import <AXMediaUtilities/AXMAXElementVisionEngine.h>
#import <AXMediaUtilities/AXMAudioEffect.h>
#import <AXMediaUtilities/IconPictureInput.h>
#import <AXMediaUtilities/IconPictureOutput.h>
#import <AXMediaUtilities/IconPicture.h>
#import <AXMediaUtilities/AXANFDDetectedObject.h>
#import <AXMediaUtilities/AXMVisionFaceNameHelper.h>
#import <AXMediaUtilities/AXMVisionFeatureFaceLandmarks.h>
#import <AXMediaUtilities/AXMTextDetectionOptions.h>
#import <AXMediaUtilities/AXMVisionAnalysisOptions.h>
#import <AXMediaUtilities/AXMOutputManager.h>
#import <AXMediaUtilities/_AXMOutputRequestTask.h>
#import <AXMediaUtilities/AXMTone.h>
#import <AXMediaUtilities/AXMDataRegressionModelLinear.h>
#import <AXMediaUtilities/AXMSourceNode.h>
#import <AXMediaUtilities/SelectedCheckboxFromIcon__generated__Input.h>
#import <AXMediaUtilities/SelectedCheckboxFromIcon__generated__Output.h>
#import <AXMediaUtilities/SelectedCheckboxFromIcon__generated__.h>
#import <AXMediaUtilities/AXMVisionFeature.h>
#import <AXMediaUtilities/AXMDataPoint.h>
#import <AXMediaUtilities/AXMDataRegressionModel.h>
#import <AXMediaUtilities/AXMCaptionDetectorNode.h>
#import <AXMediaUtilities/AXMSceneDetectorNode.h>
#import <AXMediaUtilities/AXMActiveSound.h>
#import <AXMediaUtilities/AXMSoundComponent.h>
#import <AXMediaUtilities/AXMActiveSoundOutputActionHandleImpl.h>
#import <AXMediaUtilities/AXMHapticComponent.h>
#import <AXMediaUtilities/AXMDataRegressionModelLogarithmic.h>
#import <AXMediaUtilities/AXMVisionEngineNode.h>
#import <AXMediaUtilities/AXMAudioDataSource.h>
#import <AXMediaUtilities/AXMSignificantEventDetectorNode.h>
#import <AXMediaUtilities/AXMDeviceInfo.h>
#import <AXMediaUtilities/AXMImageNode.h>
#import <AXMediaUtilities/AXMVoiceOverVisionEngine.h>
#import <AXMediaUtilities/AXShotflowNetwork.h>
#import <AXMediaUtilities/AXMText.h>
#import <AXMediaUtilities/KeyPitch.h>
#import <AXMediaUtilities/AXMVariablePitchTone.h>
