/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:50:46 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/CryptoTokenKit.framework/CryptoTokenKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSXPCConnection, TKSmartCardATR, NSString, TKSmartCardSlotProxy;

@interface TKSmartCardSlot : NSObject {

	NSXPCConnection* _connection;
	long long _powerState;
	long long _shareState;
	BOOL _securePINVerificationSupported;
	BOOL _securePINChangeSupported;
	long long _state;
	TKSmartCardATR* _ATR;
	NSString* _name;
	long long _maxInputLength;
	long long _maxOutputLength;
	TKSmartCardSlotProxy* _proxy;
	long long _previousState;

}

@property (assign) long long state;                                       //@synthesize state=_state - In the implementation block
@property (retain) TKSmartCardATR * ATR;                                  //@synthesize ATR=_ATR - In the implementation block
@property (nonatomic,readonly) TKSmartCardSlotProxy * proxy;              //@synthesize proxy=_proxy - In the implementation block
@property (readonly) NSObject*<OS_dispatch_queue> queue; 
@property (assign) long long previousState;                               //@synthesize previousState=_previousState - In the implementation block
@property (assign) long long shareState;                                  //@synthesize shareState=_shareState - In the implementation block
@property (assign) long long powerState;                                  //@synthesize powerState=_powerState - In the implementation block
@property (assign) BOOL securePINVerificationSupported;                   //@synthesize securePINVerificationSupported=_securePINVerificationSupported - In the implementation block
@property (assign) BOOL securePINChangeSupported;                         //@synthesize securePINChangeSupported=_securePINChangeSupported - In the implementation block
@property (nonatomic,readonly) NSString * name;                           //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) long long maxInputLength;                  //@synthesize maxInputLength=_maxInputLength - In the implementation block
@property (nonatomic,readonly) long long maxOutputLength;                 //@synthesize maxOutputLength=_maxOutputLength - In the implementation block
-(id)screen;
-(TKSmartCardATR *)ATR;
-(void)invalidate;
-(TKSmartCardSlotProxy *)proxy;
-(long long)powerState;
-(void)dealloc;
-(void)setATR:(TKSmartCardATR *)arg1 ;
-(long long)previousState;
-(void)setPowerState:(long long)arg1 ;
-(void)setState:(long long)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)connectToEndpoint:(id)arg1 synchronous:(BOOL)arg2 reply:(/*^block*/id)arg3 ;
-(id)initWithEndpoint:(id)arg1 error:(id*)arg2 ;
-(long long)shareState;
-(void)setShareState:(long long)arg1 ;
-(void)getAttrib:(unsigned)arg1 reply:(/*^block*/id)arg2 ;
-(void)setAttrib:(unsigned)arg1 data:(id)arg2 reply:(/*^block*/id)arg3 ;
-(id)synchronous:(BOOL)arg1 remoteSlotWithErrorHandler:(/*^block*/id)arg2 ;
-(id)makeSmartCard;
-(id)userInteractionForConfirmation;
-(void)setPreviousState:(long long)arg1 ;
-(long long)state;
-(NSString *)name;
-(void)control:(id)arg1 data:(id)arg2 expectedLength:(unsigned)arg3 reply:(/*^block*/id)arg4 ;
-(id)userInteractionForStringEntry;
-(long long)maxInputLength;
-(long long)maxOutputLength;
-(BOOL)securePINVerificationSupported;
-(void)setSecurePINVerificationSupported:(BOOL)arg1 ;
-(BOOL)securePINChangeSupported;
-(void)setSecurePINChangeSupported:(BOOL)arg1 ;
-(id)description;
@end

