/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:50:36 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/SceneKit.framework/SceneKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SceneKit/SceneKit-Structs.h>
#import <Foundation/NSValue.h>

@interface SCNJSValue : NSValue
+(id)SCNJSExportProtocol;
+(id)valueWithVector3:(SCNVector3)arg1 ;
+(id)valueWithVector4:(SCNVector4)arg1 ;
+(id)valueWithMatrix4:(SCNMatrix4)arg1 ;
-(SCNVector3)vector3;
-(SCNVector4)vector4;
-(SCNMatrix4)matrix4;
@end

