/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:45:33 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIKitCore-Structs.h>
#import <UIKitCore/_UIKeyboardTextSelectionInteraction.h>

@class UITextGestureTuning;

@interface _UIKeyboardBasedTextSelectionInteraction : _UIKeyboardTextSelectionInteraction {

	UITextGestureTuning* _gestureTuning;

}

@property (nonatomic,readonly) UITextGestureTuning * gestureTuning;              //@synthesize gestureTuning=_gestureTuning - In the implementation block
-(void)oneFingerForcePan:(id)arg1 ;
-(void)didMoveToView:(id)arg1 ;
-(id)owner;
-(void)oneFingerForcePress:(id)arg1 ;
-(void)transitionFromBlockMagnifyToBlockSelectWithLocation:(CGPoint)arg1 viaDrag:(BOOL)arg2 ;
-(void)dealloc;
-(BOOL)enclosingScrollViewIsScrolling;
-(void)_createGestureTuningIfNecessary;
-(void)endOneFingerSelectWithExecutionContext:(id)arg1 ;
-(void)_processGestureForCustomHighlighter:(id)arg1 ;
-(void)beginOneFingerSelectWithTranslation:(CGPoint)arg1 executionContext:(id)arg2 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(UITextGestureTuning *)gestureTuning;
-(void)updateOneFingerSelectWithTranslation:(CGPoint)arg1 executionContext:(id)arg2 ;
@end

