/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:45:37 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/_UISearchControllerAnimator.h>

@interface _UISearchControllerATVSearchBarAnimator : _UISearchControllerAnimator {

	BOOL _shouldLayoutTabBar;

}

@property (assign,nonatomic) BOOL shouldLayoutTabBar;              //@synthesize shouldLayoutTabBar=_shouldLayoutTabBar - In the implementation block
-(id)init;
-(void)didRelayoutSearchBarForController:(id)arg1 ;
-(void)didFocusSearchBarForController:(id)arg1 ;
-(void)didUnfocusSearchBarForController:(id)arg1 ;
-(void)willFocusOffscreenViewForController:(id)arg1 withHeading:(unsigned long long)arg2 ;
-(void)updateViewsWithSearchController:(id)arg1 reloadInputViewController:(BOOL)arg2 ;
-(void)_updateLayoutForGridKeyboard:(id)arg1 animated:(BOOL)arg2 ;
-(void)updateViewsWithSearchController:(id)arg1 ;
-(BOOL)shouldLayoutTabBar;
-(void)setShouldLayoutTabBar:(BOOL)arg1 ;
-(void)animateTransition:(id)arg1 ;
@end

