/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:45:09 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/_UITextAttributeDictionaryImplI.h>

@interface _UITextAttributeDictionaryImplM : _UITextAttributeDictionaryImplI
+(BOOL)_isMutable;
+(Class)_ignoringClass;
+(Class)_storageClass;
-(void)removeAllObjects;
-(void)setObject:(id)arg1 forKey:(id)arg2 ;
-(void)removeObjectForKey:(id)arg1 ;
-(void)_removeFallbackFromStorage;
-(void)setFallback:(id)arg1 ;
-(void)setIgnoresFallback:(BOOL)arg1 forKey:(id)arg2 ;
@end

