#import <CoreRoutine/RTPlaceInferenceOptions.h>
#import <CoreRoutine/RTPlaceInference.h>
#import <CoreRoutine/RTStoredLocationEnumerationContext.h>
#import <CoreRoutine/RTVisit.h>
#import <CoreRoutine/RTPredictedLocationOfInterest.h>
#import <CoreRoutine/RTSourceMapsSupportHistoryEntryRoute.h>
#import <CoreRoutine/RTScenarioTrigger.h>
#import <CoreRoutine/RTRoutineManagerExportedObject.h>
#import <CoreRoutine/RTRoutineManager.h>
#import <CoreRoutine/RTMapItem.h>
#import <CoreRoutine/RTAddress.h>
#import <CoreRoutine/RTInferredMapItem.h>
#import <CoreRoutine/RTStoredLocationEnumerationOptions.h>
#import <CoreRoutine/RTLocationOfInterestTransition.h>
#import <CoreRoutine/RTLocationOfInterestEnumerationOptions.h>
#import <CoreRoutine/RTRoutineManagerRegistrantScenarioTrigger.h>
#import <CoreRoutine/RTStoredVisitFetchOptions.h>
#import <CoreRoutine/RTSignalGeneratorOptions.h>
#import <CoreRoutine/RTFingerprint.h>
#import <CoreRoutine/RTTokenBucket.h>
#import <CoreRoutine/RTSourceMapsSupportFavoritePlace.h>
#import <CoreRoutine/RTScenarioTriggerUnsettled.h>
#import <CoreRoutine/RTStoredHintEnumerationOptions.h>
#import <CoreRoutine/RTEnumerationOptions.h>
#import <CoreRoutine/RTVehicleEvent.h>
#import <CoreRoutine/RTScenarioTriggerSettled.h>
#import <CoreRoutine/RTSourceMapsSupportHistoryEntry.h>
#import <CoreRoutine/RTMapItemExtendedAttributes.h>
#import <CoreRoutine/RTEventAgentHelper.h>
#import <CoreRoutine/RTPair.h>
#import <CoreRoutine/RTPredictedDate.h>
#import <CoreRoutine/RTSourceMapsSupportHistoryEntryPlaceDisplay.h>
#import <CoreRoutine/RTLocationOfInterestVisit.h>
#import <CoreRoutine/RTSourceEventKit.h>
#import <CoreRoutine/RTMotionActivity.h>
#import <CoreRoutine/RTSourceCoreRoutineLearnedLocation.h>
#import <CoreRoutine/RTLocationOfInterest.h>
#import <CoreRoutine/RTLocation.h>
#import <CoreRoutine/RTSourceMapsSupport.h>
#import <CoreRoutine/RTWiFiAccessPoint.h>
#import <CoreRoutine/RTSourceCoreRoutineVehicleEvent.h>
#import <CoreRoutine/RTHint.h>
#import <CoreRoutine/RTSource.h>
#import <CoreRoutine/RTAddressSubPremise.h>
#import <CoreRoutine/RTMapServiceOptions.h>
#import <CoreRoutine/RTRoutineManagerRegistrant.h>
#import <CoreRoutine/RTSourceCoreRoutine.h>
#import <CoreRoutine/RTFetchFingerprintsOptions.h>
