/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:50:44 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/FileProviderUI.framework/FileProviderUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIViewController.h>
#import <libobjc.A.dylib/FPUIActionRemoteViewControllerDelegate.h>
#import <libobjc.A.dylib/FPUIActionRemoteContextDelegate.h>
#import <libobjc.A.dylib/FPUIActionControllerProtocol.h>

@protocol FPUIActionExtensionViewControllerProtocol, FPUIActionViewControllerDelegate;
@class NSString, NSArray, _UIResilientRemoteViewContainerViewController, NSError, NSURL;

@interface FPUIActionViewController : UIViewController <FPUIActionRemoteViewControllerDelegate, FPUIActionRemoteContextDelegate, FPUIActionControllerProtocol> {

	id<FPUIActionExtensionViewControllerProtocol> _extensionViewController;
	_UIResilientRemoteViewContainerViewController* _placeholderVC;
	BOOL _displayInline;
	id<FPUIActionViewControllerDelegate> _delegate;
	NSString* _actionTitle;
	NSError* _error;
	NSURL* _authenticationURL;
	/*^block*/id _didLoadRemoteViewControllerCompletionHandler;
	unsigned long long _browserUserInterfaceStyle;
	NSString* _providerIdentifier;
	NSString* _actionIdentifier;
	NSURL* _serverConnectionURL;
	NSArray* _items;
	NSString* _domainIdentifier;

}

@property (nonatomic,readonly) unsigned long long browserUserInterfaceStyle;                    //@synthesize browserUserInterfaceStyle=_browserUserInterfaceStyle - In the implementation block
@property (nonatomic,retain) NSString * providerIdentifier;                                     //@synthesize providerIdentifier=_providerIdentifier - In the implementation block
@property (nonatomic,retain) NSString * actionIdentifier;                                       //@synthesize actionIdentifier=_actionIdentifier - In the implementation block
@property (nonatomic,retain) NSString * actionTitle;                                            //@synthesize actionTitle=_actionTitle - In the implementation block
@property (nonatomic,retain) NSURL * authenticationURL;                                         //@synthesize authenticationURL=_authenticationURL - In the implementation block
@property (nonatomic,copy) NSURL * serverConnectionURL;                                         //@synthesize serverConnectionURL=_serverConnectionURL - In the implementation block
@property (nonatomic,retain) NSArray * items;                                                   //@synthesize items=_items - In the implementation block
@property (nonatomic,retain) NSString * domainIdentifier;                                       //@synthesize domainIdentifier=_domainIdentifier - In the implementation block
@property (assign,nonatomic) BOOL displayInline;                                                //@synthesize displayInline=_displayInline - In the implementation block
@property (nonatomic,retain) NSError * error;                                                   //@synthesize error=_error - In the implementation block
@property (assign,nonatomic,__weak) id<FPUIActionViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) id didLoadRemoteViewControllerCompletionHandler;                     //@synthesize didLoadRemoteViewControllerCompletionHandler=_didLoadRemoteViewControllerCompletionHandler - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)actionControllerForActionIdentifier:(id)arg1 actionTitle:(id)arg2 items:(id)arg3 providerIdentifier:(id)arg4 domainIdentifier:(id)arg5 ;
+(id)actionControllerForAuthenticationUsingURL:(id)arg1 providerIdentifier:(id)arg2 ;
+(id)actionControllerForConnectingToServerURL:(id)arg1 actionTitle:(id)arg2 providerIdentifier:(id)arg3 ;
+(id)actionControllerForError:(id)arg1 providerIdentifier:(id)arg2 ;
+(id)actionControllerForError:(id)arg1 extensionIdentifier:(id)arg2 providerDomainIdentifier:(id)arg3 ;
+(id)actionControllerForInlineError:(id)arg1 providerIdentifier:(id)arg2 ;
-(NSArray *)items;
-(void)setActionIdentifier:(NSString *)arg1 ;
-(void)setDomainIdentifier:(NSString *)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(NSString *)domainIdentifier;
-(NSString *)actionTitle;
-(void)setActionTitle:(NSString *)arg1 ;
-(void)viewDidLoad;
-(NSError *)error;
-(void)setItems:(NSArray *)arg1 ;
-(void)setError:(NSError *)arg1 ;
-(NSString *)actionIdentifier;
-(NSString *)providerIdentifier;
-(void)setDelegate:(id<FPUIActionViewControllerDelegate>)arg1 ;
-(void)setProviderIdentifier:(NSString *)arg1 ;
-(id<FPUIActionViewControllerDelegate>)delegate;
-(void)_dismissViewController;
-(unsigned long long)browserUserInterfaceStyle;
-(void)setAuthenticationURL:(NSURL *)arg1 ;
-(void)setServerConnectionURL:(NSURL *)arg1 ;
-(void)setDisplayInline:(BOOL)arg1 ;
-(id)_getExtensionWithError:(id*)arg1 ;
-(void)_delegateError:(id)arg1 ;
-(BOOL)displayInline;
-(NSURL *)authenticationURL;
-(NSURL *)serverConnectionURL;
-(void)embedViewController:(id)arg1 ;
-(void)_delegateDidFinishWithUserInfo:(id)arg1 error:(id)arg2 ;
-(void)remoteActionControllerDidFinishAction:(id)arg1 error:(id)arg2 ;
-(void)remoteActionContextDidFinishAction:(id)arg1 userInfo:(id)arg2 error:(id)arg3 ;
-(void)remoteActionContext:(id)arg1 didEncounterError:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)effectiveAppearanceDidChange:(id)arg1 ;
-(id)didLoadRemoteViewControllerCompletionHandler;
-(void)setDidLoadRemoteViewControllerCompletionHandler:(id)arg1 ;
@end

