/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:49:58 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/ClockKit.framework/ClockKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ClockKit/ClockKit-Structs.h>
#import <libobjc.A.dylib/NSSecureCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSArray, NSString;

@interface CLKGaugeProvider : NSObject <NSSecureCoding, NSCopying> {

	BOOL _paused;
	BOOL _finalized;
	long long _style;
	NSArray* _gaugeColors;
	NSArray* _gaugeColorLocations;
	NSString* _accessibilityLabel;

}

@property (assign,nonatomic) long long style;                            //@synthesize style=_style - In the implementation block
@property (nonatomic,retain) NSArray * gaugeColors;                      //@synthesize gaugeColors=_gaugeColors - In the implementation block
@property (nonatomic,retain) NSArray * gaugeColorLocations;              //@synthesize gaugeColorLocations=_gaugeColorLocations - In the implementation block
@property (assign,nonatomic) BOOL paused;                                //@synthesize paused=_paused - In the implementation block
@property (assign,nonatomic) BOOL finalized;                             //@synthesize finalized=_finalized - In the implementation block
@property (nonatomic,retain) NSString * accessibilityLabel;              //@synthesize accessibilityLabel=_accessibilityLabel - In the implementation block
+(BOOL)supportsSecureCoding;
+(id)gaugeProviderWithJSONObjectRepresentation:(id)arg1 bundle:(id)arg2 ;
-(NSString *)accessibilityLabel;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setAccessibilityLabel:(NSString *)arg1 ;
-(BOOL)paused;
-(BOOL)validate;
-(id)startUpdatesWithHandler:(/*^block*/id)arg1 ;
-(long long)style;
-(void)finalize;
-(void)setFinalized:(BOOL)arg1 ;
-(id)_init;
-(BOOL)isEqual:(id)arg1 ;
-(BOOL)finalized;
-(id)initWithCoder:(id)arg1 ;
-(void)setPaused:(BOOL)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(unsigned long long)hash;
-(void)setStyle:(long long)arg1 ;
-(void)stopUpdatesForToken:(id)arg1 ;
-(double)progressFractionForNow:(id)arg1 ;
-(BOOL)needsTimerUpdates;
-(NSArray *)gaugeColorLocations;
-(NSArray *)gaugeColors;
-(id)JSONObjectRepresentation;
-(id)initWithJSONObjectRepresentation:(id)arg1 ;
-(void)setGaugeColors:(NSArray *)arg1 ;
-(void)setGaugeColorLocations:(NSArray *)arg1 ;
@end

