#import <Speech/SFAcousticFeature.h>
#import <Speech/SFVoiceAnalytics.h>
#import <Speech/_SFSearchResult.h>
#import <Speech/SFSpeechRecognitionTask.h>
#import <Speech/_SFSpeechRecognitionBlockTask.h>
#import <Speech/_SFSpeechRecognitionDelegateTask.h>
#import <Speech/SFSpeechLanguageModel.h>
#import <Speech/SFSpeechRecognitionResult.h>
#import <Speech/SFSpeechRecognizer.h>
#import <Speech/SFTranscriptionSegment.h>
#import <Speech/SFUtilities.h>
#import <Speech/_SFSearchRequest.h>
#import <Speech/SFSpeechRecognitionRequest.h>
#import <Speech/SFSpeechURLRecognitionRequest.h>
#import <Speech/SFSpeechAudioBufferRecognitionRequest.h>
#import <Speech/SFTranscription.h>
#import <Speech/SFSpeechAssetManager.h>
