/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:41:56 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/AirPlayRoutePrediction.framework/AirPlayRoutePrediction
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _DKKnowledgeQuerying;
@class NSArray, NSString;

@interface ARPHomeControlSuggester : NSObject {

	id<_DKKnowledgeQuerying> _knowledgeStore;
	NSArray* _homeKitEventsSortedByStartDate;
	double _scoreThresholdForMicrolocationSuggestionsConsidered;
	double _highScoreThresholdForMicroLocationSuggestionMerge;
	double _lowScoreThresholdForMicroLocationSuggestionMerge;
	double _highScoreThresholdForTimeBasedSuggestionMerge;
	double _lowScoreThresholdForTimeBasedSuggestionMerge;
	double _scoreSceneBoost;
	NSString* _correlationsSessionFile;

}

@property (nonatomic,readonly) id<_DKKnowledgeQuerying> knowledgeStore;                               //@synthesize knowledgeStore=_knowledgeStore - In the implementation block
@property (nonatomic,retain) NSArray * homeKitEventsSortedByStartDate;                                //@synthesize homeKitEventsSortedByStartDate=_homeKitEventsSortedByStartDate - In the implementation block
@property (assign,nonatomic) double scoreThresholdForMicrolocationSuggestionsConsidered;              //@synthesize scoreThresholdForMicrolocationSuggestionsConsidered=_scoreThresholdForMicrolocationSuggestionsConsidered - In the implementation block
@property (assign,nonatomic) double highScoreThresholdForMicroLocationSuggestionMerge;                //@synthesize highScoreThresholdForMicroLocationSuggestionMerge=_highScoreThresholdForMicroLocationSuggestionMerge - In the implementation block
@property (assign,nonatomic) double lowScoreThresholdForMicroLocationSuggestionMerge;                 //@synthesize lowScoreThresholdForMicroLocationSuggestionMerge=_lowScoreThresholdForMicroLocationSuggestionMerge - In the implementation block
@property (assign,nonatomic) double highScoreThresholdForTimeBasedSuggestionMerge;                    //@synthesize highScoreThresholdForTimeBasedSuggestionMerge=_highScoreThresholdForTimeBasedSuggestionMerge - In the implementation block
@property (assign,nonatomic) double lowScoreThresholdForTimeBasedSuggestionMerge;                     //@synthesize lowScoreThresholdForTimeBasedSuggestionMerge=_lowScoreThresholdForTimeBasedSuggestionMerge - In the implementation block
@property (assign,nonatomic) double scoreSceneBoost;                                                  //@synthesize scoreSceneBoost=_scoreSceneBoost - In the implementation block
@property (nonatomic,copy) NSString * correlationsSessionFile;                                        //@synthesize correlationsSessionFile=_correlationsSessionFile - In the implementation block
+(id)suggester;
+(id)defaultCorrelationsSessionFile;
-(void)setHighScoreThresholdForTimeBasedSuggestionMerge:(double)arg1 ;
-(id)homeKitAccessoriesWithPredicate:(id)arg1 sortStartDateAscending:(BOOL)arg2 ;
-(void)setScoreThresholdForMicrolocationSuggestionsConsidered:(double)arg1 ;
-(NSString *)correlationsSessionFile;
-(id<_DKKnowledgeQuerying>)knowledgeStore;
-(NSArray *)homeKitEventsSortedByStartDate;
-(id)timeBucketFrequencyBasedSuggestionsWithMaxSuggestions:(unsigned long long)arg1 events:(id)arg2 referenceDate:(id)arg3 ;
-(id)homeKitEventsWithPredicate:(id)arg1 sortStartDateAscending:(BOOL)arg2 ;
-(id)suggestionsWithMaxSuggestions:(unsigned long long)arg1 ;
-(id)microlocationBasedsuggestionsWithMaxSuggestions:(unsigned long long)arg1 referenceDate:(id)arg2 correlationsFile:(id)arg3 ;
-(id)frequencybasedSuggestionsWitMaxSuggestions:(unsigned long long)arg1 ;
-(void)setLowScoreThresholdForTimeBasedSuggestionMerge:(double)arg1 ;
-(id)frequencybasedSuggestionsWitMaxSuggestions:(unsigned long long)arg1 events:(id)arg2 useScenes:(BOOL)arg3 ;
-(double)lowScoreThresholdForMicroLocationSuggestionMerge;
-(id)initWithKnowledgeStore:(id)arg1 ;
-(id)timeBasedSuggestionsWithMaxSuggestions:(unsigned long long)arg1 referenceDate:(id)arg2 fallBackToFrequency:(BOOL)arg3 ;
-(double)highScoreThresholdForMicroLocationSuggestionMerge;
-(double)scoreSceneBoost;
-(id)frequencybasedSuggestionsWitMaxSuggestions:(unsigned long long)arg1 events:(id)arg2 ;
-(void)setHighScoreThresholdForMicroLocationSuggestionMerge:(double)arg1 ;
-(id)timeBasedSuggestionsWithMaxSuggestions:(unsigned long long)arg1 referenceDate:(id)arg2 ;
-(void)setHomeKitEventsSortedByStartDate:(NSArray *)arg1 ;
-(id)initWithKnowledgeStore:(id)arg1 scoreThresholdForMicrolocationSuggestionsConsidered:(double)arg2 highScoreThresholdForMicroLocationSuggestionMerge:(double)arg3 lowScoreThresholdForMicroLocationSuggestionMerge:(double)arg4 highScoreThresholdForTimeBasedSuggestionMerge:(double)arg5 lowScoreThresholdForTimeBasedSuggestionMerge:(double)arg6 ;
-(id)suggestionsWithMaxSuggestions:(unsigned long long)arg1 referenceDate:(id)arg2 correlationsFile:(id)arg3 ;
-(void)setLowScoreThresholdForMicroLocationSuggestionMerge:(double)arg1 ;
-(double)scoreThresholdForMicrolocationSuggestionsConsidered;
-(double)lowScoreThresholdForTimeBasedSuggestionMerge;
-(id)homeKitScenesWithPredicate:(id)arg1 sortStartDateAscending:(BOOL)arg2 ;
-(void)setCorrelationsSessionFile:(NSString *)arg1 ;
-(double)highScoreThresholdForTimeBasedSuggestionMerge;
-(void)setScoreSceneBoost:(double)arg1 ;
@end

