#import <GameController/GCDualShockGamepad.h>
#import <GameController/_GCControllerManagerServer.h>
#import <GameController/_GCHapticSyntheticCommand.h>
#import <GameController/_GCMFiGamepadControllerProfile.h>
#import <GameController/_GCIPCRemoteIncomingConnection.h>
#import <GameController/GCDeviceBattery.h>
#import <GameController/GCMouse.h>
#import <GameController/GCDeviceConfigurationEvaluator.h>
#import <GameController/_GCMotionEventHIDAdapter.h>
#import <GameController/_GCMotionEventHIDAdapterDescription.h>
#import <GameController/_GCAppClientConnection.h>
#import <GameController/_GCAppServerConnection.h>
#import <GameController/GCAnalytics.h>
#import <GameController/_GCHIDEventSubject.h>
#import <GameController/GCMouseInput.h>
#import <GameController/GCGamepadSnapshot.h>
#import <GameController/GCMotion.h>
#import <GameController/GCHapticCapabilities.h>
#import <GameController/_GCKeyboardEventHIDAdapter.h>
#import <GameController/_GCKeyboardEventHIDAdapterDescription.h>
#import <GameController/GCMotionXPCProxyClientEndpoint.h>
#import <GameController/GCMotionXPCProxyServerEndpoint.h>
#import <GameController/GCMotionXPCProxyClientEndpointDescription.h>
#import <GameController/_GCHapticLogicalDevice.h>
#import <GameController/GCExtendedGamepadSnapshot.h>
#import <GameController/_GCControllerAxisButtonInput.h>
#import <GameController/_GCControllerManager.h>
#import <GameController/_GCCControllerManagerDescription.h>
#import <GameController/GCControllerSFDelegate.h>
#import <GameController/_GCHapticParameterCurve.h>
#import <GameController/GCLocalPlayerIndicator.h>
#import <GameController/_GCHapticEvent.h>
#import <GameController/GCHapticMotor.h>
#import <GameController/_GCDevicePIDVIDMatchingFilter.h>
#import <GameController/_GCDevicePrimaryUsageMatchingFilter.h>
#import <GameController/_GCDefaultDeviceManager.h>
#import <GameController/_GCHapticPlayer.h>
#import <GameController/GCControllerTouchpad.h>
#import <GameController/GCController.h>
#import <GameController/_GCControllerDescription.h>
#import <GameController/_GCController.h>
#import <GameController/GCEventViewController.h>
#import <GameController/_GCDriverClientConnection.h>
#import <GameController/GCHapticCapabilityGraphNode.h>
#import <GameController/_GCControllerComponentDescription.h>
#import <GameController/_GCAppleTVRemoteControllerProfile.h>
#import <GameController/GCControllerAxisInput.h>
#import <GameController/_GCKeyboardEventImpl.h>
#import <GameController/_GCSetValueEvent.h>
#import <GameController/_GCControllerGestureAwareButtonInput.h>
#import <GameController/_GCHapticDynamicParameter.h>
#import <GameController/GCXboxGamepad.h>
#import <GameController/GCHapticCapabilityGraph.h>
#import <GameController/GCKeyboardAndMouseEventObserver.h>
#import <GameController/_GCMicrosoftXboxControllerProfile.h>
#import <GameController/GCHapticActuator.h>
#import <GameController/GCExtendedGamepad.h>
#import <GameController/GCLightXPCProxyClientEndpoint.h>
#import <GameController/GCLightXPCProxyServerEndpoint.h>
#import <GameController/GCLightXPCProxyClientEndpointDescription.h>
#import <GameController/_GCAssertingProfile.h>
#import <GameController/_GCDefaultLogicalDevice.h>
#import <GameController/GCKeyboardEventData.h>
#import <GameController/GCKeyboardEventObserver.h>
#import <GameController/_GCDefaultPhysicalDevice.h>
#import <GameController/_GCHIDEventUIKitClient.h>
#import <GameController/GCSettingsXPCProxyClientEndpoint.h>
#import <GameController/GCSettingsXPCProxyServerEndpoint.h>
#import <GameController/GCSettingsXPCProxyClientEndpointDescription.h>
#import <GameController/_GCAppleTVRemoteMotionProfile.h>
#import <GameController/_GCSonyDualShockControllerProfile.h>
#import <GameController/GCProductInformation.h>
#import <GameController/_GCIPCRemoteOutgoingConnection.h>
#import <GameController/_GCGamepadEventGamepadHIDAdapter.h>
#import <GameController/_GCGamepadEventGamepadHIDAdapterDescription.h>
#import <GameController/_GCControllerManagerAppClient.h>
#import <GameController/_GCMotionEventImpl.h>
#import <GameController/_GCGamepadEventImpl.h>
#import <GameController/_GCGamepadEventHID.h>
#import <GameController/_GCHIDEventIOKitClient.h>
#import <GameController/GCControllerMBDelegate.h>
#import <GameController/GCControllerButtonInput.h>
#import <GameController/_GCCControllerHIDServiceInfo.h>
#import <GameController/_GCCControllerHIDServiceInfoDescription.h>
#import <GameController/_GCIPCRemoteConnection.h>
#import <GameController/GCControllerMetaDefaultsObserver.h>
#import <GameController/GCControllerSettings.h>
#import <GameController/_GCObservation.h>
#import <GameController/GCMicroGamepadSnapshot.h>
#import <GameController/_GCAppClientProxy.h>
#import <GameController/_GCGamepadEventFusionConfig.h>
#import <GameController/_GCGamepadEventFusion.h>
#import <GameController/_GCGamepadEventFusionDescription.h>
#import <GameController/GCKeyboard.h>
#import <GameController/GCDeviceLight.h>
#import <GameController/_GCGamepadEventKeyboardEventAdapterConfig.h>
#import <GameController/_GCGamepadEventKeyboardEventAdapter.h>
#import <GameController/_GCGamepadEventKeyboardEventAdapterDescription.h>
#import <GameController/_GCHapticClientConnection.h>
#import <GameController/GCDeviceHaptics.h>
#import <GameController/GCControllerElementSettings.h>
#import <GameController/_GCIPCRemoteProcess.h>
#import <GameController/_GCImplicitIPCObjectDescription.h>
#import <GameController/GCKeyboardInput.h>
#import <GameController/GCNotificationOptions.h>
#import <GameController/GCReplayNotificationOptions.h>
#import <GameController/GCNotificationManager.h>
#import <GameController/GCLightbarColor.h>
#import <GameController/GCGamepadUserDefaults.h>
#import <GameController/_GCHapticServerManager.h>
#import <GameController/_GCHapticClientProxy.h>
#import <GameController/FixedParameter.h>
#import <GameController/_GCHapticTokenAndParams.h>
#import <GameController/GCGamepad.h>
#import <GameController/GCMicroGamepad.h>
#import <GameController/GCDeviceCursor.h>
#import <GameController/GCFrontmostApplicationObserver.h>
#import <GameController/_GCDeviceConfiguration.h>
#import <GameController/_GCMutableDeviceConfiguration.h>
#import <GameController/GCControllerElement.h>
#import <GameController/GCPlayerIndicatorXPCProxyClientEndpoint.h>
#import <GameController/GCPlayerIndicatorXPCProxyServerEndpoint.h>
#import <GameController/GCPlayerIndicatorXPCProxyClientEndpointDescription.h>
#import <GameController/GCKeyboardAndMouseManager.h>
#import <GameController/GCControllerCBDelegate.h>
#import <GameController/GCColor.h>
#import <GameController/GCControllerDirectionPad.h>
#import <GameController/GCPhysicalInputProfile.h>
#import <GameController/_GCExtendedMFiControllerProfile.h>
#import <GameController/GCBatteryXPCProxyClientEndpoint.h>
#import <GameController/GCBatteryXPCProxyServerEndpoint.h>
#import <GameController/GCBatteryXPCProxyClientEndpointDescription.h>
#import <GameController/GCMouseEventData.h>
#import <GameController/GCMouseEventObserver.h>
