/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:50:25 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/StoreKit.framework/StoreKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSNumber, NSString, NSError, NSURL, SKPaymentTransaction;

@interface SKDownloadInternal : NSObject {

	NSNumber* _downloadID;
	NSString* _productID;
	long long _state;
	float _progress;
	NSError* _error;
	NSURL* _contentURL;
	double _timeRemaining;
	NSNumber* _contentLength;
	NSString* _contentVersion;
	SKPaymentTransaction* _transaction;

}
@end

