/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:39:57 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/CoreWiFi.framework/CoreWiFi
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreWiFi/CoreWiFi-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSUUID, NSString, NSDate, NSArray;

@interface CWFAutoJoinStatus : NSObject <NSCopying, NSSecureCoding> {

	BOOL _result;
	NSUUID* _UUID;
	NSString* _interfaceName;
	NSDate* _startedAt;
	NSDate* _endedAt;
	NSArray* _joinAttempts;
	long long _trigger;
	long long _state;

}

@property (nonatomic,copy) NSUUID * UUID;                         //@synthesize UUID=_UUID - In the implementation block
@property (nonatomic,copy) NSString * interfaceName;              //@synthesize interfaceName=_interfaceName - In the implementation block
@property (nonatomic,copy) NSDate * startedAt;                    //@synthesize startedAt=_startedAt - In the implementation block
@property (nonatomic,copy) NSDate * endedAt;                      //@synthesize endedAt=_endedAt - In the implementation block
@property (nonatomic,copy) NSArray * joinAttempts;                //@synthesize joinAttempts=_joinAttempts - In the implementation block
@property (assign,nonatomic) long long trigger;                   //@synthesize trigger=_trigger - In the implementation block
@property (assign,nonatomic) long long state;                     //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) BOOL result;                         //@synthesize result=_result - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setEndedAt:(NSDate *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(long long)trigger;
-(NSDate *)startedAt;
-(NSDate *)endedAt;
-(void)setStartedAt:(NSDate *)arg1 ;
-(BOOL)result;
-(void)setJoinAttempts:(NSArray *)arg1 ;
-(NSUUID *)UUID;
-(id)__descriptionForAutoJoinTrigger:(long long)arg1 ;
-(void)setState:(long long)arg1 ;
-(BOOL)isEqualToAutoJoinStatus:(id)arg1 ;
-(id)init;
-(NSArray *)joinAttempts;
-(void)setInterfaceName:(NSString *)arg1 ;
-(void)setResult:(BOOL)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)__descriptionForAutoJoinState:(long long)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setUUID:(NSUUID *)arg1 ;
-(NSString *)interfaceName;
-(void)setTrigger:(long long)arg1 ;
-(unsigned long long)hash;
-(long long)state;
-(id)description;
@end

