/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:36:35 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class HKInteractiveChartOverlayViewController, NSMutableArray;

@interface _HKInteractiveChartOverlayWaitForCacheData : NSObject {

	HKInteractiveChartOverlayViewController* _overlayController;
	NSMutableArray* _waitForDataSources;

}

@property (assign,nonatomic,__weak) HKInteractiveChartOverlayViewController * overlayController;              //@synthesize overlayController=_overlayController - In the implementation block
@property (nonatomic,retain) NSMutableArray * waitForDataSources;                                             //@synthesize waitForDataSources=_waitForDataSources - In the implementation block
-(void)setOverlayController:(HKInteractiveChartOverlayViewController *)arg1 ;
-(HKInteractiveChartOverlayViewController *)overlayController;
-(id)initWithOverlayController:(id)arg1 ;
-(void)addWaitForDataSource:(id)arg1 graphSeriesContext:(id)arg2 timeScope:(long long)arg3 startDate:(id)arg4 endDate:(id)arg5 priorityDelegate:(id)arg6 completion:(/*^block*/id)arg7 ;
-(id)_findDataSource:(id)arg1 ;
-(NSMutableArray *)waitForDataSources;
-(void)removeWaitForDataSource:(id)arg1 ;
-(void)setWaitForDataSources:(NSMutableArray *)arg1 ;
@end

