#import <IDSFoundation/IDSLocalDeliverySocketOpenedMetric.h>
#import <IDSFoundation/IDSLocalMessageDeliveryServiceNotCompatibleMetric.h>
#import <IDSFoundation/IDSOutgoingMessageCheckpointTrace.h>
#import <IDSFoundation/IDSGroupSessionParticipantUpdate.h>
#import <IDSFoundation/IDSCloudKitContainer.h>
#import <IDSFoundation/IDSMPFullDeviceIdentityContainer.h>
#import <IDSFoundation/IDSMPPublicDeviceIdentityContainer.h>
#import <IDSFoundation/IDSPNRMetric.h>
#import <IDSFoundation/IDSSessionDeclineSentMetric.h>
#import <IDSFoundation/IDSPopupPrompt.h>
#import <IDSFoundation/IDSFTGL.h>
#import <IDSFoundation/IDSCourierServerBag.h>
#import <IDSFoundation/IDSCloudMessagingLinkReEstablishedMetric.h>
#import <IDSFoundation/IDSRegisteredDevice.h>
#import <IDSFoundation/IDSSessionReinitiateConnectedMetric.h>
#import <IDSFoundation/IDSMessage.h>
#import <IDSFoundation/IDSGroupSessionActiveParticipant.h>
#import <IDSFoundation/IDSDestinationComposite.h>
#import <IDSFoundation/IDSServiceDelegateProperties.h>
#import <IDSFoundation/IDSTCPLink.h>
#import <IDSFoundation/IDSPublicAccountIdentity.h>
#import <IDSFoundation/IDSAccountIdentity.h>
#import <IDSFoundation/IDSDestinationEngram.h>
#import <IDSFoundation/IDSSessionInvitationSentMetric.h>
#import <IDSFoundation/IDSSessionCanceledMetric.h>
#import <IDSFoundation/IDSHandle.h>
#import <IDSFoundation/IDSQuickRelayMetric.h>
#import <IDSFoundation/IDSServiceProperties.h>
#import <IDSFoundation/IDSNonFTGL.h>
#import <IDSFoundation/IDSDeliveryContext.h>
#import <IDSFoundation/IDSRegistrationCertificate.h>
#import <IDSFoundation/IDSRegistrationKeychainReader.h>
#import <IDSFoundation/IDSTransactionQueueTransaction.h>
#import <IDSFoundation/IDSTransactionQueue.h>
#import <IDSFoundation/IDSNegativeInfo.h>
#import <IDSFoundation/IDSRateLimiter.h>
#import <IDSFoundation/IDSMMCSAccessRequestMessage.h>
#import <IDSFoundation/IDSCellularLinkMonitor.h>
#import <IDSFoundation/IDSCloudKitKeyValueStore.h>
#import <IDSFoundation/IDSAccountKeyHistory.h>
#import <IDSFoundation/IDSEndpointCapabilities.h>
#import <IDSFoundation/IDSLocalMessageSentMetric.h>
#import <IDSFoundation/IDSSessionDeclineReceivedMetric.h>
#import <IDSFoundation/IDSBaseSocketPairConnection.h>
#import <IDSFoundation/IDSGlobalLinkBlocks.h>
#import <IDSFoundation/IDSGlobalLink.h>
#import <IDSFoundation/IDSPublicDeviceIdentity.h>
#import <IDSFoundation/IDSDeviceIdentity.h>
#import <IDSFoundation/IDSMagnetDataCorruptionRecoveryTimeInMsMetric.h>
#import <IDSFoundation/IDSQRParticipantStreams.h>
#import <IDSFoundation/IDSDestinationStrings.h>
#import <IDSFoundation/IDSPushHandlerContext.h>
#import <IDSFoundation/IDSPushHandler.h>
#import <IDSFoundation/IDSLocalMessageRTTMetric.h>
#import <IDSFoundation/IDSAWDLogger.h>
#import <IDSFoundation/IDSCKContainer.h>
#import <IDSFoundation/IDSCKDatabase.h>
#import <IDSFoundation/IDSCKRecord.h>
#import <IDSFoundation/IDSCKRecordID.h>
#import <IDSFoundation/IDSCKQuery.h>
#import <IDSFoundation/IDSCKDatabaseOperation.h>
#import <IDSFoundation/IDSCKModifyRecordsOperation.h>
#import <IDSFoundation/IDSCKQueryOperation.h>
#import <IDSFoundation/IDSCKRecordZoneID.h>
#import <IDSFoundation/IDSCKRecordZone.h>
#import <IDSFoundation/IDSCKServerChangeToken.h>
#import <IDSFoundation/IDSCKFetchRecordZoneChangesOptions.h>
#import <IDSFoundation/IDSCKFetchRecordZoneChangesOperation.h>
#import <IDSFoundation/IDSCKFetchRecordsOperation.h>
#import <IDSFoundation/IDSCKModifyRecordZonesOperation.h>
#import <IDSFoundation/IDSCKFetchRecordZonesOperation.h>
#import <IDSFoundation/IDSCKNotification.h>
#import <IDSFoundation/IDSCKRecordZoneNotification.h>
#import <IDSFoundation/IDSCKNotificationInfo.h>
#import <IDSFoundation/IDSCKQuerySubscription.h>
#import <IDSFoundation/IDSCKRecordZoneSubscription.h>
#import <IDSFoundation/IDSCKModifySubscriptionsOperation.h>
#import <IDSFoundation/IDSCKSubscription.h>
#import <IDSFoundation/IDSCKAccountInfo.h>
#import <IDSFoundation/IDSURI.h>
#import <IDSFoundation/IDSGlobalLinkMessage.h>
#import <IDSFoundation/IDSDelegateInfo.h>
#import <IDSFoundation/IDSStunMessage.h>
#import <IDSFoundation/IDSIncomingMessageCheckpointTrace.h>
#import <IDSFoundation/IDSOTRSessionNegotiationMetric.h>
#import <IDSFoundation/IDSNGMFullDeviceIdentity.h>
#import <IDSFoundation/IDSNGMPublicDeviceIdentity.h>
#import <IDSFoundation/IDSNGMProtocolVersion.h>
#import <IDSFoundation/IDSNGMKeyRollingTicket.h>
#import <IDSFoundation/IDSNGMMessageHasher.h>
#import <IDSFoundation/IDSWiFiSetupAttemptMetric.h>
#import <IDSFoundation/IDSNWPathUtils.h>
#import <IDSFoundation/IDSMessageContext.h>
#import <IDSFoundation/IDSMPConversationKey.h>
#import <IDSFoundation/IDSSessionReinitiateRequestedMetric.h>
#import <IDSFoundation/IDSMPFullLegacyIdentity.h>
#import <IDSFoundation/IDSMPPublicLegacyIdentity.h>
#import <IDSFoundation/IDSServerBag.h>
#import <IDSFoundation/IDSCertifiedDeliveryReplayKey.h>
#import <IDSFoundation/IDSDestinationSentinelSelfAlias.h>
#import <IDSFoundation/IDSSessionCancelSentMetric.h>
#import <IDSFoundation/IDSAuthenticationCertificate.h>
#import <IDSFoundation/IDSAWDLogging.h>
#import <IDSFoundation/IDSLocalDeliveryMessageSentMetric.h>
#import <IDSFoundation/IDSServerCertificate.h>
#import <IDSFoundation/IDSGFTGL.h>
#import <IDSFoundation/IDSTapToRadarRequest.h>
#import <IDSFoundation/IDSTapToRadarContext.h>
#import <IDSFoundation/IDSTapToRadar.h>
#import <IDSFoundation/IDSAutoBugCapture.h>
#import <IDSFoundation/IDSQRAllocationMetric.h>
#import <IDSFoundation/IDSDestinationURI.h>
#import <IDSFoundation/IDSSessionReinitiateStartedMetric.h>
#import <IDSFoundation/IDSCloudKitKeyElectionStore.h>
#import <IDSFoundation/IDSCloudKitKeyElectionStoreItem.h>
#import <IDSFoundation/IDSLocalDeliveryMessageDeliveredMetric.h>
#import <IDSFoundation/IDSSockAddrWrapper.h>
#import <IDSFoundation/IDSRegistrationAuthenticationParametersReceivedMetric.h>
#import <IDSFoundation/IDSSessionAcceptReceivedMetric.h>
#import <IDSFoundation/IDSSOSMetric.h>
#import <IDSFoundation/IDSWiProxConnectionSuccessMetric.h>
#import <IDSFoundation/IDSPeerMessageCheckpointTrace.h>
#import <IDSFoundation/IDSEndpoint.h>
#import <IDSFoundation/IDSCloudKitTransportLog.h>
#import <IDSFoundation/IDSCloudKitTransportLogMessage.h>
#import <IDSFoundation/IDSCloudKitTransportLogChangeToken.h>
#import <IDSFoundation/IDSWRMLinkRecommendationMetric.h>
#import <IDSFoundation/IDSOpportunisticData.h>
#import <IDSFoundation/IDSSocketPairMessage.h>
#import <IDSFoundation/IDSSocketPairDataMessage.h>
#import <IDSFoundation/IDSSocketPairDictionaryMessage.h>
#import <IDSFoundation/IDSSocketPairHandshake.h>
#import <IDSFoundation/IDSSocketPairEncryptedMessage.h>
#import <IDSFoundation/IDSSocketPairOTREncryptedMessage.h>
#import <IDSFoundation/IDSSocketPairOTRMessage.h>
#import <IDSFoundation/IDSSocketPairAckMessage.h>
#import <IDSFoundation/IDSSocketPairKeepAliveMessage.h>
#import <IDSFoundation/IDSSocketPairAppAckMessage.h>
#import <IDSFoundation/IDSSocketPairSessionInvitationMessage.h>
#import <IDSFoundation/IDSSocketPairSessionAcceptMessage.h>
#import <IDSFoundation/IDSSocketPairSessionDeclineMessage.h>
#import <IDSFoundation/IDSSocketPairSessionCancelMessage.h>
#import <IDSFoundation/IDSSocketPairSessionMessage.h>
#import <IDSFoundation/IDSSocketPairSessionReinitiateMessage.h>
#import <IDSFoundation/IDSSocketPairSessionEndMessage.h>
#import <IDSFoundation/IDSSocketPairSMSTextMessage.h>
#import <IDSFoundation/IDSSocketPairSMSTextDownloadMessage.h>
#import <IDSFoundation/IDSSocketPairSMSOutgoing.h>
#import <IDSFoundation/IDSSocketPairSMSDownloadOutgoing.h>
#import <IDSFoundation/IDSSocketPairSMSDeliveryReceipt.h>
#import <IDSFoundation/IDSSocketPairSMSReadReceipt.h>
#import <IDSFoundation/IDSSocketPairSMSFailure.h>
#import <IDSFoundation/IDSSocketPairProxyOutgoingNiceMessage.h>
#import <IDSFoundation/IDSSocketPairProxyIncomingNiceMessage.h>
#import <IDSFoundation/IDSSocketPairTextMessage.h>
#import <IDSFoundation/IDSSocketPairDeliveryReceipt.h>
#import <IDSFoundation/IDSSocketPairReadReceipt.h>
#import <IDSFoundation/IDSSocketPairAttachmentMessage.h>
#import <IDSFoundation/IDSSocketPairPlayedReceipt.h>
#import <IDSFoundation/IDSSocketPairSavedReceipt.h>
#import <IDSFoundation/IDSSocketPairReflectedDeliveryReceipt.h>
#import <IDSFoundation/IDSSocketPairGenericCommandMessage.h>
#import <IDSFoundation/IDSSocketPairGenericGroupMessageCommand.h>
#import <IDSFoundation/IDSSocketPairLocationShareOfferCommand.h>
#import <IDSFoundation/IDSSocketPairExpiredAckMessage.h>
#import <IDSFoundation/IDSSocketPairErrorMessage.h>
#import <IDSFoundation/IDSSocketPairProtobufMessage.h>
#import <IDSFoundation/IDSSocketPairFragmentedMessage.h>
#import <IDSFoundation/IDSSocketPairResourceTransferMessage.h>
#import <IDSFoundation/IDSSocketPairResourceTransferReceiver.h>
#import <IDSFoundation/IDSSocketPairResourceTransferSender.h>
#import <IDSFoundation/IDSSocketPairServiceMapMessage.h>
#import <IDSFoundation/IDSConversationGroupCypher.h>
#import <IDSFoundation/IDSSOSLogger.h>
#import <IDSFoundation/IDSDestinationDefaultPairedDevice.h>
#import <IDSFoundation/IDSLegacyDeviceMessageProtectionCypher.h>
#import <IDSFoundation/IDSLocalMessageDeliveryConnectionResetMetric.h>
#import <IDSFoundation/IDSDestination.h>
#import <IDSFoundation/IDSSessionEndedMetric.h>
#import <IDSFoundation/IDSSessionInvitationReceivedMetric.h>
#import <IDSFoundation/IDSCertifiedDeliveryReceiptMessage.h>
#import <IDSFoundation/IDSQueryKeyTransparencyContext.h>
#import <IDSFoundation/IDSRegistrationAccountStatusMetric.h>
#import <IDSFoundation/IDSCertifiedDeliveryContext.h>
#import <IDSFoundation/IDSStunCandidate.h>
#import <IDSFoundation/IDSMPFullAccountIdentity.h>
#import <IDSFoundation/IDSMPPublicAccountIdentity.h>
#import <IDSFoundation/IDSMPConversationGroup.h>
#import <IDSFoundation/IDSMPConversationGroupSponsorPair.h>
#import <IDSFoundation/IDSSendParameters.h>
#import <IDSFoundation/IDSQuickRelaySessionInfo.h>
#import <IDSFoundation/IDSMPFullAccountIdentityCluster.h>
#import <IDSFoundation/IDSMPPublicAccountIdentityCluster.h>
#import <IDSFoundation/IDSFoundationLog.h>
#import <IDSFoundation/IDSMagnetCorruptionMetric.h>
#import <IDSFoundation/IDSSessionStartedMetric.h>
#import <IDSFoundation/IDSCTPNRValidationMechanism.h>
#import <IDSFoundation/IDSCTPNRResponseData.h>
#import <IDSFoundation/IDSCTPNRInfo.h>
#import <IDSFoundation/IDSCTPNR.h>
#import <IDSFoundation/IDSMessageToDelete.h>
#import <IDSFoundation/IDSRemoteURLConnection.h>
#import <IDSFoundation/IDSWRMMetricContainer.h>
#import <IDSFoundation/IDSWRMExchange.h>
#import <IDSFoundation/IDSCTSIM.h>
#import <IDSFoundation/IDSCTAdapterCache.h>
#import <IDSFoundation/IDSCTAdapter.h>
#import <IDSFoundation/IDSStunConnectionDataController.h>
#import <IDSFoundation/IDSInterfaceAddress.h>
#import <IDSFoundation/IDSStunCandidatePair.h>
#import <IDSFoundation/IDSIDSServerBag.h>
#import <IDSFoundation/IDSMPIdentity.h>
#import <IDSFoundation/IDSWiProxDidSendDataMetric.h>
#import <IDSFoundation/IDSDependencyProvider.h>
#import <IDSFoundation/IDSXPCConnectionWrapper.h>
#import <IDSFoundation/IDSMMCSDownloadAuth.h>
#import <IDSFoundation/IDSCloudKitGroupServer.h>
#import <IDSFoundation/IDSDeliveryControllerTimeMetric.h>
#import <IDSFoundation/IDSBaseMessage.h>
#import <IDSFoundation/IDSRTCLogger.h>
#import <IDSFoundation/IDSMPFullDeviceIdentity.h>
#import <IDSFoundation/IDSMPPublicDeviceIdentity.h>
#import <IDSFoundation/IDSUDPLink.h>
#import <IDSFoundation/IDSSessionCompleted.h>
#import <IDSFoundation/IDSWiProxDidConnectToPeerMetric.h>
#import <IDSFoundation/IDSLocalDeliveryMessageReceivedMetric.h>
#import <IDSFoundation/IDSSessionInfoMetadataSerializer.h>
#import <IDSFoundation/IDSCoreAnalyticsLogger.h>
#import <IDSFoundation/IDSPayloadInspector.h>
#import <IDSFoundation/IDSAggregateMessageSendCheckpointTrace.h>
#import <IDSFoundation/IDSProtobuf.h>
#import <IDSFoundation/IDSMPFullServiceIdentityAdmin.h>
#import <IDSFoundation/IDSMPPublicServiceIdentityAdmin.h>
#import <IDSFoundation/IDSMPFullServiceIdentitySigning.h>
#import <IDSFoundation/IDSMPPublicServiceIdentitySigning.h>
#import <IDSFoundation/IDSKeyTransparencyTrustedDeviceVerificationMetric.h>
#import <IDSFoundation/IDSLocalMessageTimedOutMetric.h>
#import <IDSFoundation/IDSMissingMessageMetric.h>
#import <IDSFoundation/IDSKeyTransparencyTrustedDeviceEnrollmentMetric.h>
#import <IDSFoundation/IDSWiProxDidDisconnectFromPeerMetric.h>
#import <IDSFoundation/IDSSessionAcceptSentMetric.h>
#import <IDSFoundation/IDSWiProxConnectionFailedMetric.h>
#import <IDSFoundation/IDSSysdiagnoseLogCollector.h>
#import <IDSFoundation/IDSLogFormatter.h>
#import <IDSFoundation/IDSCurrentServerTime.h>
#import <IDSFoundation/IDSCurrentServerTimePair.h>
#import <IDSFoundation/_IDSCurrentServerTimeProvider.h>
#import <IDSFoundation/IDSEngramKeyFetchMetric.h>
#import <IDSFoundation/IDSDestinationDevice.h>
#import <IDSFoundation/IDSEndpointTransparencyState.h>
#import <IDSFoundation/IDSRemoteCredential.h>
#import <IDSFoundation/IDSRegistrationCompletedMetric.h>
#import <IDSFoundation/IDSDestinationPushToken.h>
#import <IDSFoundation/IDSLocalDeliverySocketClosedMetric.h>
#import <IDSFoundation/IDSStallDetector.h>
#import <IDSFoundation/IDSOpportunisticOptions.h>
#import <IDSFoundation/IDSSessionConnectedMetric.h>
#import <IDSFoundation/IDSRegistrationControlChosenMetric.h>
