/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:50:01 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/WebKit.framework/WebKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WebKit/WebKit-Structs.h>
#import <WebKit/WKObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface WKNSURLRequest : WKObject <NSCopying>
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)URL;
-(id)_web_createTarget;
@end

