#import <iTunesCloud/ICMusicSubscriptionStatusCache.h>
#import <iTunesCloud/ICJSSign.h>
#import <iTunesCloud/ICJSSignConfiguration.h>
#import <iTunesCloud/ICIAMImpressionNode.h>
#import <iTunesCloud/ICUnfairLock.h>
#import <iTunesCloud/ICDelegateToken.h>
#import <iTunesCloud/ICAuthorizeMachineResponse.h>
#import <iTunesCloud/ICMusicSubscriptionRequest.h>
#import <iTunesCloud/ICSAPSession.h>
#import <iTunesCloud/ICStoreRequestContext.h>
#import <iTunesCloud/ICDelegateAccountStoreOptions.h>
#import <iTunesCloud/ICIAMApplicationMessage.h>
#import <iTunesCloud/ICAuthenticationUtilities.h>
#import <iTunesCloud/ICRadioLibraryArtistContentReference.h>
#import <iTunesCloud/ICCloudClientCloudService.h>
#import <iTunesCloud/ICStoreFileAssetInfo.h>
#import <iTunesCloud/ICSAPSessionSignDataOperation.h>
#import <iTunesCloud/ICStorePlatformRequestOperation.h>
#import <iTunesCloud/ICPlayActivityFeedSerialization.h>
#import <iTunesCloud/ICStoreFinanceItemMetadata.h>
#import <iTunesCloud/ICMusicSubscriptionCarrierBundlingEligibilityResponse.h>
#import <iTunesCloud/ICRadioPlaybackHistory.h>
#import <iTunesCloud/ICMutableRadioPlaybackHistory.h>
#import <iTunesCloud/ICRadioStoreContentReference.h>
#import <iTunesCloud/ICSQLiteStatement.h>
#import <iTunesCloud/ICAgeVerificationManager.h>
#import <iTunesCloud/ICInAppMessageManager.h>
#import <iTunesCloud/ICRemoteRequestOperationExecutionResponse.h>
#import <iTunesCloud/ICSubscriptionRedownloadRequest.h>
#import <iTunesCloud/ICDelegationConsumerNetService.h>
#import <iTunesCloud/ICMachineDataProvisionOperation.h>
#import <iTunesCloud/ICMediaAssetDownloadRequest.h>
#import <iTunesCloud/ICMediaAssetDownloadSessionCache.h>
#import <iTunesCloud/ICURLSessionManager.h>
#import <iTunesCloud/ICPushNotificationMessage.h>
#import <iTunesCloud/ICCloudClient.h>
#import <iTunesCloud/ICAsyncBlockOperation.h>
#import <iTunesCloud/ICRemoteRequestOperationController.h>
#import <iTunesCloud/ICDeveloperTokenDefaultProvider.h>
#import <iTunesCloud/ICStoreMediaResponseItem.h>
#import <iTunesCloud/ICRadioFetchMetadataRequest.h>
#import <iTunesCloud/ICMusicRestoreBagConfiguration.h>
#import <iTunesCloud/ICCloudServiceStatusRemoteMonitoring.h>
#import <iTunesCloud/ICLibraryAuthServiceClientTokenResponse.h>
#import <iTunesCloud/ICLibraryAuthServiceClientTokenResult.h>
#import <iTunesCloud/ICLibraryAuthServiceClientTokenIdentifier.h>
#import <iTunesCloud/ICUserIdentity.h>
#import <iTunesCloud/ICLibraryAuthServiceClientTokenRequest.h>
#import <iTunesCloud/ICURLBagProvider.h>
#import <iTunesCloud/ICMusicSubscriptionStatusResponse.h>
#import <iTunesCloud/ICLibraryAuthServiceBulkClientTokenRequest.h>
#import <iTunesCloud/ICMusicSubscriptionAccountlessPlaybackRequest.h>
#import <iTunesCloud/ICDelegationConsumerServiceProtocolHandler.h>
#import <iTunesCloud/ICAMSBagValuePromise.h>
#import <iTunesCloud/ICMusicSubscriptionPlaybackRequestOperation.h>
#import <iTunesCloud/ICMusicSubscriptionPlaybackResponseItem.h>
#import <iTunesCloud/ICStorePlatformOfferAsset.h>
#import <iTunesCloud/ICURLBagMescalConfiguration.h>
#import <iTunesCloud/ICPBDGSPlayerDelegateInfoToken.h>
#import <iTunesCloud/ICDelegateAccountStore.h>
#import <iTunesCloud/ICStorageManager.h>
#import <iTunesCloud/ICUserCredentialResponse.h>
#import <iTunesCloud/ICAsyncOperation.h>
#import <iTunesCloud/ICFPLeaseSyncSession.h>
#import <iTunesCloud/ICUserAuthenticationValidationRequest.h>
#import <iTunesCloud/ICNanoPairedDeviceStatusMonitor.h>
#import <iTunesCloud/ICLibraryAuthServiceBulkClientTokenResponse.h>
#import <iTunesCloud/ICDelegationProviderService.h>
#import <iTunesCloud/ICUserIdentityStoreACAccountBackend.h>
#import <iTunesCloud/ICUserIdentityProperties.h>
#import <iTunesCloud/ICMutableUserIdentityProperties.h>
#import <iTunesCloud/ICIAMSerialCheckRequest.h>
#import <iTunesCloud/ICHTTPArchive.h>
#import <iTunesCloud/ICMusicKitRequestContext.h>
#import <iTunesCloud/ICConnectionConfiguration.h>
#import <iTunesCloud/ICMusicSubscriptionRecommendationsRequest.h>
#import <iTunesCloud/ICUserVerificationContext.h>
#import <iTunesCloud/ICMusicSubscriptionLeaseStatus.h>
#import <iTunesCloud/ICPushNotificationsRegisterAPNSTokenRequest.h>
#import <iTunesCloud/ICSiriAddToAccousticHistoryRequest.h>
#import <iTunesCloud/ICLibraryAuthServiceClientTokenStatus.h>
#import <iTunesCloud/ICStorePlatformRequest.h>
#import <iTunesCloud/ICUserNotificationBuilder.h>
#import <iTunesCloud/ICStorePlatformMetadata.h>
#import <iTunesCloud/ICMusicSubscriptionStatusRequestOperation.h>
#import <iTunesCloud/ICURLSession.h>
#import <iTunesCloud/ICMusicRestoreRequest.h>
#import <iTunesCloud/ICInAppMessageEntry.h>
#import <iTunesCloud/ICIAMApplicationMessageSyncCommand.h>
#import <iTunesCloud/ICAMSBagAdapter.h>
#import <iTunesCloud/ICDelegationConsumerServiceSessionRequestInfo.h>
#import <iTunesCloud/ICDelegateAccountStoreServiceListener.h>
#import <iTunesCloud/ICFPSAPContext.h>
#import <iTunesCloud/ICIAMSynchronizeMessagesResponse.h>
#import <iTunesCloud/ICFPContentInfo.h>
#import <iTunesCloud/ICRadioPlaybackHistoryStore.h>
#import <iTunesCloud/ICPlayActivityController.h>
#import <iTunesCloud/_ICPlayActivityEndpointRevisionInformation.h>
#import <iTunesCloud/_ICPlayActivityFlushSessionInformation.h>
#import <iTunesCloud/ICPushNotificationsDisableTypesRequest.h>
#import <iTunesCloud/ICStoreArtworkSizeInfo.h>
#import <iTunesCloud/ICStoreArtworkInfo.h>
#import <iTunesCloud/ICSuzeLeaseSession.h>
#import <iTunesCloud/ICMediaRedownloadRequest.h>
#import <iTunesCloud/ICUserIdentityStoreCoding.h>
#import <iTunesCloud/ICIAMLogEventRequest.h>
#import <iTunesCloud/ICStoreURLRequestBuilderProperties.h>
#import <iTunesCloud/ICStoreFileAssetFairPlayInfo.h>
#import <iTunesCloud/ICMusicUserTokenFetchRequest.h>
#import <iTunesCloud/ICPBDGSStartDelegationRequest.h>
#import <iTunesCloud/ICDeviceInfo.h>
#import <iTunesCloud/ICFlushPlayActivityEventsOperation.h>
#import <iTunesCloud/ICIAMTriggerCondition.h>
#import <iTunesCloud/ICIAMImage.h>
#import <iTunesCloud/ICInAppMessageMetadataEntry.h>
#import <iTunesCloud/ICMachineDataSyncOperation.h>
#import <iTunesCloud/ICURLBagRadioConfiguration.h>
#import <iTunesCloud/ICAgeVerifier.h>
#import <iTunesCloud/ICSQLiteConnectionOptions.h>
#import <iTunesCloud/ICRadioFetchMetadataResponse.h>
#import <iTunesCloud/ICPlayActivityDebugLogOperation.h>
#import <iTunesCloud/ICURLRequest.h>
#import <iTunesCloud/ICPBDGSFinishDelegationRequest.h>
#import <iTunesCloud/ICIAMMessagePresentationTrigger.h>
#import <iTunesCloud/ICCloudItemIDList.h>
#import <iTunesCloud/ICUserIdentityStoreTestingBackend.h>
#import <iTunesCloud/ICMusicAccountNotificationsSettingsRequestOperation.h>
#import <iTunesCloud/ICIAMMetricEvent.h>
#import <iTunesCloud/ICMusicRestoreRequestParameters.h>
#import <iTunesCloud/ICDelegationConsumerService.h>
#import <iTunesCloud/ICDelegationConsumerServiceRequest.h>
#import <iTunesCloud/ICRadioLibraryAlbumContentReference.h>
#import <iTunesCloud/ICRadioStationProviderResource.h>
#import <iTunesCloud/ICAgeVerificationState.h>
#import <iTunesCloud/ICMusicSubscriptionCarrierBundlingEligibilityOperation.h>
#import <iTunesCloud/ICValueHistory.h>
#import <iTunesCloud/_ICValueHistoryItem.h>
#import <iTunesCloud/ICIAMLocalNotification.h>
#import <iTunesCloud/ICFPStreamContext.h>
#import <iTunesCloud/ICStoreRadioStreamAssetInfo.h>
#import <iTunesCloud/ICStoreDialogResponseHandler.h>
#import <iTunesCloud/ICStoreDialogResponseHandlerConfiguration.h>
#import <iTunesCloud/ICDeviceSetupStatusMonitor.h>
#import <iTunesCloud/ICMediaRedownloadResponse.h>
#import <iTunesCloud/ICIAMApplicationMessageSyncResponse.h>
#import <iTunesCloud/ICPAPlayModeDictionary.h>
#import <iTunesCloud/ICACAccountVerificationOperation.h>
#import <iTunesCloud/ICDispatchOnce.h>
#import <iTunesCloud/ICRequestContext.h>
#import <iTunesCloud/ICInAppMessageConfiguration.h>
#import <iTunesCloud/ICMusicAccountNotificationsSettingsManager.h>
#import <iTunesCloud/ICRadioStationTrack.h>
#import <iTunesCloud/ICDelegationServiceConnection.h>
#import <iTunesCloud/_ICDelegationServiceConnectionPendingRequestContext.h>
#import <iTunesCloud/ICCloudContentTastePBFusePreferences.h>
#import <iTunesCloud/ICCloudAddReferral.h>
#import <iTunesCloud/ICIAMMessageAction.h>
#import <iTunesCloud/ICInAppReportEventRequest.h>
#import <iTunesCloud/ICMusicSubscriptionLeasePlaybackRequest.h>
#import <iTunesCloud/ICStoreURLRequest.h>
#import <iTunesCloud/ICDelegateAccountStoreXPCWriter.h>
#import <iTunesCloud/ICMusicSubscriptionStatusRequest.h>
#import <iTunesCloud/ICPlayActivityTable.h>
#import <iTunesCloud/ICMusicSubscriptionFairPlayKeyStatus.h>
#import <iTunesCloud/ICPlayActivityEvent.h>
#import <iTunesCloud/ICMutablePlayActivityEvent.h>
#import <iTunesCloud/ICMusicSubscriptionStatusCacheKey.h>
#import <iTunesCloud/ICIAMMessageContent.h>
#import <iTunesCloud/ICMachineDataEraseOperation.h>
#import <iTunesCloud/ICRemoveMediaDRMOperation.h>
#import <iTunesCloud/ICMusicKitURLResponse.h>
#import <iTunesCloud/ICRemoteRequestOperationExecutionContext.h>
#import <iTunesCloud/ICUserVerificationOperation.h>
#import <iTunesCloud/ICSQLiteRow.h>
#import <iTunesCloud/ICRadioGetTracksRequest.h>
#import <iTunesCloud/ICIAMMessageRule.h>
#import <iTunesCloud/ICCloudServerListenerEndpointProvider.h>
#import <iTunesCloud/ICSuzeLeaseRequest.h>
#import <iTunesCloud/ICPAPlayActivityEnqueuerProperties.h>
#import <iTunesCloud/ICPAPlayActivityEvent.h>
#import <iTunesCloud/ICPlayActivityEventContainerIDs.h>
#import <iTunesCloud/ICMutablePlayActivityEventContainerIDs.h>
#import <iTunesCloud/ICDelegationServicePairingSession.h>
#import <iTunesCloud/ICURLBagMonitor.h>
#import <iTunesCloud/ICBook.h>
#import <iTunesCloud/ICRadioLikeRequest.h>
#import <iTunesCloud/ICAuthorizeMachineURLRequest.h>
#import <iTunesCloud/ICDelegationConsumerServiceSessionRequestResult.h>
#import <iTunesCloud/ICPBDGSStartDelegationResponse.h>
#import <iTunesCloud/ICAddToWishListResponse.h>
#import <iTunesCloud/ICMusicKitURLResponseHandler.h>
#import <iTunesCloud/ICPBDGSResponse.h>
#import <iTunesCloud/ICAuthorizeMachineRequest.h>
#import <iTunesCloud/ICLibraryAuthServiceClientTokenProvider.h>
#import <iTunesCloud/ICSQLitePreparedStatement.h>
#import <iTunesCloud/ICPrivacyInfo.h>
#import <iTunesCloud/ICUserCredentialRequest.h>
#import <iTunesCloud/ICRadioLikeResponse.h>
#import <iTunesCloud/ICStoreHLSAssetInfo.h>
#import <iTunesCloud/ICPBDGSPlayerInfoContextToken.h>
#import <iTunesCloud/ICMusicSubscriptionLeaseSession.h>
#import <iTunesCloud/ICKeyedSharedInstanceManager.h>
#import <iTunesCloud/ICCloudClientAvailabilityService.h>
#import <iTunesCloud/ICMediaAVAssetDownloadOptions.h>
#import <iTunesCloud/ICCloudContentTastePBFuseItemPreference.h>
#import <iTunesCloud/ICPushNotificationsResponse.h>
#import <iTunesCloud/ICInAppMessageStore.h>
#import <iTunesCloud/ICSuzeLeaseResponse.h>
#import <iTunesCloud/ICSAPSessionPrepareFairPlayContextOperation.h>
#import <iTunesCloud/ICRadioLibraryTrackContentReference.h>
#import <iTunesCloud/ICDelegationPlayInfoRequest.h>
#import <iTunesCloud/ICDelegationPlayInfoTokenRequest.h>
#import <iTunesCloud/ICDefaults.h>
#import <iTunesCloud/ICMusicSubscriptionPlaybackURLRequest.h>
#import <iTunesCloud/ICRadioPlaybackHistoryItem.h>
#import <iTunesCloud/ICMutableRadioPlaybackHistoryItem.h>
#import <iTunesCloud/ICDelegationProviderServiceAssertion.h>
#import <iTunesCloud/ICPlayActivityEnqueuerProperties.h>
#import <iTunesCloud/ICMutablePlayActivityEnqueuerProperties.h>
#import <iTunesCloud/ICSAPSessionAbstractOperation.h>
#import <iTunesCloud/ICUserNotificationContext.h>
#import <iTunesCloud/ICUserNotificationManager.h>
#import <iTunesCloud/ICAddToWishListRequest.h>
#import <iTunesCloud/ICStorePlatformResponseGroup.h>
#import <iTunesCloud/ICSetParentalControlRequestOperation.h>
#import <iTunesCloud/ICIAMLogEventResponse.h>
#import <iTunesCloud/ICSQLiteQueryResults.h>
#import <iTunesCloud/ICCloudServiceStatusMonitor.h>
#import <iTunesCloud/ICPBDGSFinishDelegationResponse.h>
#import <iTunesCloud/ICPBDGSMessage.h>
#import <iTunesCloud/ICPBDGSRequest.h>
#import <iTunesCloud/ICURLResponseHandler.h>
#import <iTunesCloud/ICCloudContentTasteRequestListener.h>
#import <iTunesCloud/ICCloudAvailabilityController.h>
#import <iTunesCloud/ICMusicUserTokenCache.h>
#import <iTunesCloud/ICBuyProductRequest.h>
#import <iTunesCloud/ICDelegationProviderServiceSession.h>
#import <iTunesCloud/ICStoreURLResponseAuthenticationProvider.h>
#import <iTunesCloud/ICRadioGetTracksResponse.h>
#import <iTunesCloud/ICRadioResponse.h>
#import <iTunesCloud/ICDelegationPlayInfoRequestOperation.h>
#import <iTunesCloud/ICDelegationPlayInfoResponseToken.h>
#import <iTunesCloud/ICIAMParameter.h>
#import <iTunesCloud/ICPurchaseRedownloadRequest.h>
#import <iTunesCloud/ICInAppMessageSyncRequest.h>
#import <iTunesCloud/ICUserIdentityContext.h>
#import <iTunesCloud/ICRemoteRequestOperationExecuting.h>
#import <iTunesCloud/ICDeveloperTokenFetchRequest.h>
#import <iTunesCloud/ICDelegationServiceSecuritySettings.h>
#import <iTunesCloud/ICDelegationNetServiceTXTRecord.h>
#import <iTunesCloud/ICStoreDialogResponse.h>
#import <iTunesCloud/ICStoreDialogResponseButton.h>
#import <iTunesCloud/ICStoreDialogResponseButtonAction.h>
#import <iTunesCloud/ICMusicSubscriptionStatusController.h>
#import <iTunesCloud/ICDelegationConsumerServiceSession.h>
#import <iTunesCloud/ICStorePlatformResponse.h>
#import <iTunesCloud/ICInAppMessageEventEntry.h>
#import <iTunesCloud/ICSecureKeyDeliveryResponse.h>
#import <iTunesCloud/ICTelephonyController.h>
#import <iTunesCloud/ICURLBag.h>
#import <iTunesCloud/ICDelegationProviderServiceProtocolHandler.h>
#import <iTunesCloud/ICRadioStationMetadata.h>
#import <iTunesCloud/ICDelegateAccountStoreSQLWriter.h>
#import <iTunesCloud/ICURLResponseAuthenticationProvider.h>
#import <iTunesCloud/ICSecurityInfo.h>
#import <iTunesCloud/ICSagaGetAccountStatusRequest.h>
#import <iTunesCloud/ICSongDownloadDoneRequest.h>
#import <iTunesCloud/ICRemoteRequestOperation.h>
#import <iTunesCloud/ICMusicSubscriptionLeaseController.h>
#import <iTunesCloud/_ICMusicSubscriptionLeaseIdentityCacheKey.h>
#import <iTunesCloud/ICDAAPPropertyInfo.h>
#import <iTunesCloud/ICIAMSynchronizeMessagesRequest.h>
#import <iTunesCloud/ICDelegateAccountStoreSchema.h>
#import <iTunesCloud/ICMusicKitURLRequest.h>
#import <iTunesCloud/ICSAPSessionVerifySignatureOperation.h>
#import <iTunesCloud/ICMusicSubscriptionStatusRemoteRequesting.h>
#import <iTunesCloud/ICUserVerificationRequest.h>
#import <iTunesCloud/ICMusicSubscriptionStatusMonitor.h>
#import <iTunesCloud/ICDelegateAccountStoreReader.h>
#import <iTunesCloud/ICRadioURLRequest.h>
#import <iTunesCloud/ICStoreURLResponseHandler.h>
#import <iTunesCloud/ICPBDGSPlayerInfoContextRequestToken.h>
#import <iTunesCloud/ICRequestOperation.h>
#import <iTunesCloud/ICSuzeLeaseSessionConfiguration.h>
#import <iTunesCloud/ICMatchRedownloadRequest.h>
#import <iTunesCloud/ICHTTPCookieStore.h>
#import <iTunesCloud/ICMusicAccountNotificationsSettingsSwitch.h>
#import <iTunesCloud/ICUserIdentityStore.h>
#import <iTunesCloud/ICMachineDataActionHandler.h>
#import <iTunesCloud/ICStoreVideoArtworkInfo.h>
#import <iTunesCloud/ICRadioTrackInfoContentReference.h>
#import <iTunesCloud/ICRadioContentReference.h>
#import <iTunesCloud/ICStorePlatformOffer.h>
#import <iTunesCloud/ICDelegationProviderNetService.h>
#import <iTunesCloud/ICSQLiteConnection.h>
#import <iTunesCloud/ICURLResponse.h>
#import <iTunesCloud/ICURLBagLibraryDAAPConfiguration.h>
#import <iTunesCloud/ICMusicSubscriptionFairPlayController.h>
#import <iTunesCloud/ICMusicSubscriptionPlaybackResponse.h>
#import <iTunesCloud/ICMachineDataOperation.h>
#import <iTunesCloud/ICSecureKeyDeliveryRequest.h>
#import <iTunesCloud/ICSecureKeyDeliveryRequestOperation.h>
#import <iTunesCloud/ICEnvironmentMonitor.h>
#import <iTunesCloud/ICADIUtilities.h>
#import <iTunesCloud/ICADIProvisionSession.h>
#import <iTunesCloud/ICUserCredentialProvider.h>
#import <iTunesCloud/_ICUserCredentialProviderRequestSession.h>
#import <iTunesCloud/ICLocalStoreAccountProperties.h>
#import <iTunesCloud/ICMutableLocalStoreAccountProperties.h>
#import <iTunesCloud/ICPlayActivityEventItemIDs.h>
#import <iTunesCloud/ICMutablePlayActivityEventItemIDs.h>
#import <iTunesCloud/ICMusicSubscriptionStatus.h>
#import <iTunesCloud/ICMutableMusicSubscriptionStatus.h>
#import <iTunesCloud/ICMusicSubscriptionStatusTerms.h>
#import <iTunesCloud/ICWiFiManager.h>
#import <iTunesCloud/ICClientInfo.h>
#import <iTunesCloud/ICMutableClientInfo.h>
#import <iTunesCloud/ICIAMSerialCheckResponse.h>
#import <iTunesCloud/ICNetworkConstraints.h>
#import <iTunesCloud/ICMutableNetworkConstraints.h>
#import <iTunesCloud/ICMusicAccountNotificationsSettingsResponse.h>
#import <iTunesCloud/ICPushNotificationsEnableTypesRequest.h>
