/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:42:40 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/JetEngine.framework/JetEngine
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/_TtP9JetEngineP33_F1A6C53E38508B046E9AEC1C2D18BD5C18JSBagObjectExports_.h>

@interface JetEngine.JSBagObject : NSObject <_TtP9JetEngineP33_F1A6C53E38508B046E9AEC1C2D18BD5C18JSBagObjectExports_> {

	 bag;

}
-(id)url:(id)arg1 ;
-(void)registerBagKeys:(id)arg1 ;
-(id)string:(id)arg1 ;
-(id)dictionary:(id)arg1 ;
-(id)init;
-(id)boolean:(id)arg1 ;
-(id)integer:(id)arg1 ;
-(id)array:(id)arg1 ;
-(id)double:(id)arg1 ;
@end

