/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:49:58 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/PencilKit.framework/PencilKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <PencilKit/PencilKit-Structs.h>
@class PKDrawing, NSDate, NSString, NSArray, CHTextInputTargetContentInfo, CHTokenizedTextResult;

@interface PKTextInputDebugLogEntry : NSObject {

	PKDrawing* _inputDrawing;
	BOOL _inputContainsInProgressStroke;
	NSDate* _entryDate;
	NSString* _recognitionLocaleIdentifier;
	NSArray* _inputTargets;
	CHTextInputTargetContentInfo* _inputTargetContentInfo;
	NSString* _inputTargetElementType;
	CHTokenizedTextResult* _tokenizedTextResult;
	NSString* _resultCommittedText;
	NSString* _resultTopTranscription;
	long long _resultCommittedTokenColumnCount;
	NSString* _resultTypeDescription;
	NSString* _resultCommitReason;
	double _resultRecognitionDuration;
	NSRange _resultAffectedRange;

}

@property (nonatomic,retain) NSDate * entryDate;                                                 //@synthesize entryDate=_entryDate - In the implementation block
@property (nonatomic,copy) NSString * recognitionLocaleIdentifier;                               //@synthesize recognitionLocaleIdentifier=_recognitionLocaleIdentifier - In the implementation block
@property (nonatomic,retain) PKDrawing * inputDrawing;                                           //@synthesize inputDrawing=_inputDrawing - In the implementation block
@property (assign,nonatomic) BOOL inputContainsInProgressStroke;                                 //@synthesize inputContainsInProgressStroke=_inputContainsInProgressStroke - In the implementation block
@property (nonatomic,copy) NSArray * inputTargets;                                               //@synthesize inputTargets=_inputTargets - In the implementation block
@property (nonatomic,retain) CHTextInputTargetContentInfo * inputTargetContentInfo;              //@synthesize inputTargetContentInfo=_inputTargetContentInfo - In the implementation block
@property (nonatomic,copy) NSString * inputTargetElementType;                                    //@synthesize inputTargetElementType=_inputTargetElementType - In the implementation block
@property (nonatomic,retain) CHTokenizedTextResult * tokenizedTextResult;                        //@synthesize tokenizedTextResult=_tokenizedTextResult - In the implementation block
@property (nonatomic,copy) NSString * resultCommittedText;                                       //@synthesize resultCommittedText=_resultCommittedText - In the implementation block
@property (nonatomic,copy) NSString * resultTopTranscription;                                    //@synthesize resultTopTranscription=_resultTopTranscription - In the implementation block
@property (assign,nonatomic) long long resultCommittedTokenColumnCount;                          //@synthesize resultCommittedTokenColumnCount=_resultCommittedTokenColumnCount - In the implementation block
@property (assign,nonatomic) NSRange resultAffectedRange;                                        //@synthesize resultAffectedRange=_resultAffectedRange - In the implementation block
@property (nonatomic,copy) NSString * resultTypeDescription;                                     //@synthesize resultTypeDescription=_resultTypeDescription - In the implementation block
@property (nonatomic,copy) NSString * resultCommitReason;                                        //@synthesize resultCommitReason=_resultCommitReason - In the implementation block
@property (assign,nonatomic) double resultRecognitionDuration;                                   //@synthesize resultRecognitionDuration=_resultRecognitionDuration - In the implementation block
+(id)mediumDescriptionForResultQueryItem:(id)arg1 ;
+(id)_mutableDictionaryRepresentationForResultQueryItem:(id)arg1 detailLevel:(long long)arg2 ;
+(id)_referenceSubstringForTargetContentInfo:(id)arg1 resultAffectedRange:(NSRange)arg2 targetContentLevel:(long long)arg3 localeIdentifier:(id)arg4 ;
+(id)_minimalReferenceString:(id)arg1 rangeOfInterest:(NSRange)arg2 tokenSearchDistance:(long long)arg3 localeIdentifier:(id)arg4 ;
+(id)loggedDateFormatter;
-(void)setEntryDate:(NSDate *)arg1 ;
-(id)minimalDescription;
-(NSDate *)entryDate;
-(NSString *)recognitionLocaleIdentifier;
-(id)description;
-(void)setRecognitionLocaleIdentifier:(NSString *)arg1 ;
-(CHTextInputTargetContentInfo *)inputTargetContentInfo;
-(id)mediumDescription;
-(PKDrawing *)inputDrawing;
-(id)dictionaryRepresentationWithTargetContentLevel:(long long)arg1 ;
-(NSArray *)inputTargets;
-(id)referenceSubstringWithTargetContentLevel:(long long)arg1 ;
-(NSString *)resultCommittedText;
-(NSString *)resultTopTranscription;
-(NSRange)resultAffectedRange;
-(NSString *)resultTypeDescription;
-(BOOL)_isResultTypeText;
-(id)dictionaryRepresentationWithDetailLevel:(long long)arg1 targetContentLevel:(long long)arg2 ;
-(void)setInputDrawing:(PKDrawing *)arg1 ;
-(BOOL)inputContainsInProgressStroke;
-(void)setInputContainsInProgressStroke:(BOOL)arg1 ;
-(void)setInputTargets:(NSArray *)arg1 ;
-(void)setInputTargetContentInfo:(CHTextInputTargetContentInfo *)arg1 ;
-(NSString *)inputTargetElementType;
-(void)setInputTargetElementType:(NSString *)arg1 ;
-(CHTokenizedTextResult *)tokenizedTextResult;
-(void)setTokenizedTextResult:(CHTokenizedTextResult *)arg1 ;
-(void)setResultCommittedText:(NSString *)arg1 ;
-(void)setResultTopTranscription:(NSString *)arg1 ;
-(long long)resultCommittedTokenColumnCount;
-(void)setResultCommittedTokenColumnCount:(long long)arg1 ;
-(void)setResultAffectedRange:(NSRange)arg1 ;
-(void)setResultTypeDescription:(NSString *)arg1 ;
-(NSString *)resultCommitReason;
-(void)setResultCommitReason:(NSString *)arg1 ;
-(double)resultRecognitionDuration;
-(void)setResultRecognitionDuration:(double)arg1 ;
@end

