#import <CoreImage/AutoCropper.h>
#import <CoreImage/CIBilateralGridHash.h>
#import <CoreImage/CIBilateralSolverCPU.h>
#import <CoreImage/CIBilateralSolverGPU.h>
#import <CoreImage/CIAccordionFoldTransition.h>
#import <CoreImage/CIClamp.h>
#import <CoreImage/CIAffineClamp.h>
#import <CoreImage/CISimpleTile.h>
#import <CoreImage/CIAffineTile.h>
#import <CoreImage/CIAffineTransform.h>
#import <CoreImage/CIASGPercent.h>
#import <CoreImage/CIASG50Percent.h>
#import <CoreImage/CIASG66Percent.h>
#import <CoreImage/CIASG75Percent.h>
#import <CoreImage/CIASG80Percent.h>
#import <CoreImage/CIASG60Percent.h>
#import <CoreImage/CIAppleSmithGossettScale.h>
#import <CoreImage/CIAreaHistogram.h>
#import <CoreImage/CIPercentileRed.h>
#import <CoreImage/CIBarcodeDescriptor.h>
#import <CoreImage/CIQRCodeDescriptor.h>
#import <CoreImage/CIAztecCodeDescriptor.h>
#import <CoreImage/CIPDF417CodeDescriptor.h>
#import <CoreImage/CIDataMatrixCodeDescriptor.h>
#import <CoreImage/CIBarcodeDetector.h>
#import <CoreImage/CIBarsSwipeTransition.h>
#import <CoreImage/CICheapBilateral.h>
#import <CoreImage/CIBitmapContext.h>
#import <CoreImage/CIBlendModeFilter.h>
#import <CoreImage/CIMultiplyBlendMode.h>
#import <CoreImage/CIScreenBlendMode.h>
#import <CoreImage/CIOverlayBlendMode.h>
#import <CoreImage/CIDarkenBlendMode.h>
#import <CoreImage/CILightenBlendMode.h>
#import <CoreImage/CIColorDodgeBlendMode.h>
#import <CoreImage/CIColorBurnBlendMode.h>
#import <CoreImage/CIHardLightBlendMode.h>
#import <CoreImage/CISoftLightBlendMode.h>
#import <CoreImage/CIDifferenceBlendMode.h>
#import <CoreImage/CIExclusionBlendMode.h>
#import <CoreImage/CIPDFNonSeparableBlendMode.h>
#import <CoreImage/CIHueBlendMode.h>
#import <CoreImage/CISaturationBlendMode.h>
#import <CoreImage/CIColorBlendMode.h>
#import <CoreImage/CILuminosityBlendMode.h>
#import <CoreImage/CISubtractBlendMode.h>
#import <CoreImage/CIDivideBlendMode.h>
#import <CoreImage/CILinearBurnBlendMode.h>
#import <CoreImage/CILinearDodgeBlendMode.h>
#import <CoreImage/CIVividLightBlendMode.h>
#import <CoreImage/CILinearLightBlendMode.h>
#import <CoreImage/CIPinLightBlendMode.h>
#import <CoreImage/CIHardMixBlendMode.h>
#import <CoreImage/CIMix.h>
#import <CoreImage/CIBlendWithMask.h>
#import <CoreImage/CIBlendWithRedMask.h>
#import <CoreImage/CIBlendWithBlueMask.h>
#import <CoreImage/CIBlendWithAlphaMask.h>
#import <CoreImage/CIBloom.h>
#import <CoreImage/CIGloom.h>
#import <CoreImage/CIBoxBlur.h>
#import <CoreImage/CIBumpDistortion.h>
#import <CoreImage/CIBumpDistortionLinear.h>
#import <CoreImage/CIBurstActionClassifier.h>
#import <CoreImage/CIBurstClusterDivider.h>
#import <CoreImage/CIBurstFaceConfigEntry.h>
#import <CoreImage/CIBurstFaceScoreEntry.h>
#import <CoreImage/CIBurstFaceInfo.h>
#import <CoreImage/CIBurstImageFaceAnalysisContext.h>
#import <CoreImage/CIBurstImageSet.h>
#import <CoreImage/InpaintingMultiresolutionFilter.h>
#import <CoreImage/InpaintingGeneralHelpers.h>
#import <CoreImage/CIBurstImageSetInternal.h>
#import <CoreImage/CIBurstFaceStat.h>
#import <CoreImage/CIBurstImageStat.h>
#import <CoreImage/CIBurstThumbnailCluster.h>
#import <CoreImage/CIBurstYUVImage.h>
#import <CoreImage/CICMYKHalftone.h>
#import <CoreImage/CICameraCalibrationLensCorrection.h>
#import <CoreImage/CICheapBlur.h>
#import <CoreImage/CICheatBlur.h>
#import <CoreImage/CICheckerboardGenerator.h>
#import <CoreImage/CICircleGenerator.h>
#import <CoreImage/CICircleSplashDistortion.h>
#import <CoreImage/CICircularWrap.h>
#import <CoreImage/CIColor.h>
#import <CoreImage/CIColorBalance.h>
#import <CoreImage/CIColorClamp.h>
#import <CoreImage/CIColorControls.h>
#import <CoreImage/CIHueAdjust.h>
#import <CoreImage/CIColorCube.h>
#import <CoreImage/CIColorCubeWithColorSpace.h>
#import <CoreImage/CIColorCubesMixedWithMask.h>
#import <CoreImage/CIColorCurves.h>
#import <CoreImage/CIColorThreshold.h>
#import <CoreImage/CIColorThresholdOtsu.h>
#import <CoreImage/CIColorMonochrome.h>
#import <CoreImage/CIPalettize.h>
#import <CoreImage/CIDither.h>
#import <CoreImage/CIDesaturateShadows.h>
#import <CoreImage/CIColorMap.h>
#import <CoreImage/CISingleChannelColorMap.h>
#import <CoreImage/CIColorMatrix.h>
#import <CoreImage/CIColorInvert.h>
#import <CoreImage/CIColorPolynomial.h>
#import <CoreImage/CIColorPolynomialInverse.h>
#import <CoreImage/CIColorCrossPolynomial.h>
#import <CoreImage/CIColorPosterize.h>
#import <CoreImage/CIFusionDelta.h>
#import <CoreImage/CIFusionTwoImagesDelta.h>
#import <CoreImage/CILineOverlay.h>
#import <CoreImage/CISpotColor.h>
#import <CoreImage/CIComicEffect.h>
#import <CoreImage/_CICompositeFilter.h>
#import <CoreImage/CISourceOverCompositing.h>
#import <CoreImage/CISourceInCompositing.h>
#import <CoreImage/CISourceOutCompositing.h>
#import <CoreImage/CISourceAtopCompositing.h>
#import <CoreImage/CIAdditionCompositing.h>
#import <CoreImage/CIMultiplyCompositing.h>
#import <CoreImage/CIMinimumCompositing.h>
#import <CoreImage/CIMaximumCompositing.h>
#import <CoreImage/CIPlusDarkerCompositing.h>
#import <CoreImage/CIPlusLighterCompositing.h>
#import <CoreImage/CIConstantColorGenerator.h>
#import <CoreImage/CIContext.h>
#import <CoreImage/CIContextCache.h>
#import <CoreImage/InpaintingExecutionContext.h>
#import <CoreImage/CIConvolutionProcessor.h>
#import <CoreImage/CIConvolution3X3.h>
#import <CoreImage/CIConvolution5X5.h>
#import <CoreImage/CIConvolution7X7.h>
#import <CoreImage/CIConvolution9Horizontal.h>
#import <CoreImage/CIConvolution9Vertical.h>
#import <CoreImage/CICopyMachineTransition.h>
#import <CoreImage/CIPredictionModel.h>
#import <CoreImage/CICoreMLKernel.h>
#import <CoreImage/CIFeatureProviderMultiArray.h>
#import <CoreImage/CIFeatureProviderImage.h>
#import <CoreImage/CICoreMLProcessorImageArray.h>
#import <CoreImage/CICoreMLModelFilter.h>
#import <CoreImage/CICrop.h>
#import <CoreImage/CICrystallize.h>
#import <CoreImage/CIDepthOfField.h>
#import <CoreImage/CIDetector.h>
#import <CoreImage/CIConvolution.h>
#import <CoreImage/CIBokehBlur.h>
#import <CoreImage/CIDiscBlur.h>
#import <CoreImage/CIRingBlur.h>
#import <CoreImage/CIDisintegrateWithMaskTransition.h>
#import <CoreImage/CIInpaintingFilter.h>
#import <CoreImage/CIDisparityRefinement.h>
#import <CoreImage/CIDisparitySmoothing.h>
#import <CoreImage/CIDisparitySmoothingProcessor.h>
#import <CoreImage/CIDisplacementDistortion.h>
#import <CoreImage/CIDissolveTransition.h>
#import <CoreImage/CIDocumentEnhancer.h>
#import <CoreImage/CIPaperWash.h>
#import <CoreImage/CIContrastEnhancer.h>
#import <CoreImage/CIDroste.h>
#import <CoreImage/CheapRandomness.h>
#import <CoreImage/RadialFalloffFilter.h>
#import <CoreImage/PercentileClipProcessor_RGBA8_CPU.h>
#import <CoreImage/HistoClip_RGBA8_CPU.h>
#import <CoreImage/ConvexFillProcessor.h>
#import <CoreImage/CIConvexFill.h>
#import <CoreImage/CISeedFillProcessor.h>
#import <CoreImage/CISeedFill.h>
#import <CoreImage/CICircularityDescriptor.h>
#import <CoreImage/RedEyeSpecular.h>
#import <CoreImage/RedEyeRecolor.h>
#import <CoreImage/RedPupilLocalizer.h>
#import <CoreImage/RedEyeFace.h>
#import <CoreImage/CIDualRedEyeRepairSession.h>
#import <CoreImage/CIRedEyeRaw.h>
#import <CoreImage/CIDualRedEyeRepairTuning.h>
#import <CoreImage/CIEdgePreserveUpsampleFilter.h>
#import <CoreImage/CIEdgePreserveUpsampleRGFilter.h>
#import <CoreImage/CIEdgeWork.h>
#import <CoreImage/CIEdges.h>
#import <CoreImage/CIGaborGradients.h>
#import <CoreImage/CIExposureAdjust.h>
#import <CoreImage/CIFaceBalance.h>
#import <CoreImage/CIFaceMaskApply.h>
#import <CoreImage/CIFaceMaskDelta.h>
#import <CoreImage/CIFaceMaskCalculator.h>
#import <CoreImage/CIFaceMaskKernel.h>
#import <CoreImage/CIFaceSegmentationFilter.h>
#import <CoreImage/FBSProcessor.h>
#import <CoreImage/FBSProcessorCPU.h>
#import <CoreImage/FBSProcessorGPU.h>
#import <CoreImage/CIFastBilateralSolver.h>
#import <CoreImage/CIFeature.h>
#import <CoreImage/CIFaceFeature.h>
#import <CoreImage/CIRectangleFeature.h>
#import <CoreImage/CIQRCodeFeature.h>
#import <CoreImage/CITextFeature.h>
#import <CoreImage/CIFilter.h>
#import <CoreImage/CIFilterClassAttributes.h>
#import <CoreImage/CIFilterClassCategories.h>
#import <CoreImage/CIFilterClassDefaults.h>
#import <CoreImage/CIFilterClassInfo.h>
#import <CoreImage/CIFilterShape.h>
#import <CoreImage/CIFlashTransition.h>
#import <CoreImage/CIFocalPlaneProcessor.h>
#import <CoreImage/CIFocalPlanePreprocessorInternal.h>
#import <CoreImage/CIFocalPlaneNative.h>
#import <CoreImage/CIFocalPlane.h>
#import <CoreImage/CIGVNode.h>
#import <CoreImage/CGRenderer.h>
#import <CoreImage/PDFRenderer.h>
#import <CoreImage/PNGRenderer.h>
#import <CoreImage/DOTRenderer.h>
#import <CoreImage/CIModifyBlurmap.h>
#import <CoreImage/CIGammaAdjust.h>
#import <CoreImage/CIGaussianBlur.h>
#import <CoreImage/CIGaussianBlurXY.h>
#import <CoreImage/CIGenericMetalProcessorSingleChannel.h>
#import <CoreImage/CIGenericMetalProcessor.h>
#import <CoreImage/CIGlassDistortion.h>
#import <CoreImage/CIRadialGradient.h>
#import <CoreImage/CILinearGradient.h>
#import <CoreImage/CISmoothLinearGradient.h>
#import <CoreImage/CIGaussianGradient.h>
#import <CoreImage/CIHueSaturationValueGradient.h>
#import <CoreImage/CIGuidedFilter.h>
#import <CoreImage/_CIScreenFilter.h>
#import <CoreImage/CIDotScreen.h>
#import <CoreImage/CIHatchedScreen.h>
#import <CoreImage/CILineScreen.h>
#import <CoreImage/CICircularScreen.h>
#import <CoreImage/CIHeightFieldFromMask.h>
#import <CoreImage/CIHighlightShadowAdjust.h>
#import <CoreImage/CIHistogramDisplayFilter.h>
#import <CoreImage/CIHoleDistortion.h>
#import <CoreImage/CIImage.h>
#import <CoreImage/CIImageAccumulator.h>
#import <CoreImage/CIImageProcessorInOut.h>
#import <CoreImage/CIImageProcessorOutput.h>
#import <CoreImage/CIImageProcessorInput.h>
#import <CoreImage/CIImageProcessorKernel.h>
#import <CoreImage/CIImageRowReader.h>
#import <CoreImage/CIFileSaverProcessor.h>
#import <CoreImage/CIImageWriter.h>
#import <CoreImage/CIIntegralImageProcessorGPU.h>
#import <CoreImage/CIIntegralImageProcessorCPU.h>
#import <CoreImage/CIIntegralImage.h>
#import <CoreImage/CIKaleidoscope.h>
#import <CoreImage/CIKernel.h>
#import <CoreImage/CIColorKernel.h>
#import <CoreImage/CIWarpKernel.h>
#import <CoreImage/CIBlendKernel.h>
#import <CoreImage/CILabDeltaE.h>
#import <CoreImage/CILanczosScaleTransform.h>
#import <CoreImage/CIGlassLozenge.h>
#import <CoreImage/CITorusLensDistortion.h>
#import <CoreImage/CILensModelCalculatorCPU.h>
#import <CoreImage/CILensModelCalculator.h>
#import <CoreImage/CILensModelApply.h>
#import <CoreImage/CILensModelKernelMetalProcessor.h>
#import <CoreImage/CILenticularHaloGenerator.h>
#import <CoreImage/CILightTunnel.h>
#import <CoreImage/CILocalContrast.h>
#import <CoreImage/CILocalLightMapPrepare.h>
#import <CoreImage/CILocalLightFilter.h>
#import <CoreImage/CILumaMap.h>
#import <CoreImage/CIXRay.h>
#import <CoreImage/CIThermal.h>
#import <CoreImage/CIMaskToAlpha.h>
#import <CoreImage/CIMaskedVariableBlur.h>
#import <CoreImage/CIMattingRGBDProcessor.h>
#import <CoreImage/CIMattingSolverInternal.h>
#import <CoreImage/CIMattingSolver.h>
#import <CoreImage/CIMedianProcessor.h>
#import <CoreImage/CIMedianFilter.h>
#import <CoreImage/CIMeshGenerator.h>
#import <CoreImage/CIMetalConverter.h>
#import <CoreImage/CIMetalProcessor.h>
#import <CoreImage/CIMetalWrapper.h>
#import <CoreImage/CIMinimumComponent.h>
#import <CoreImage/CIMaximumComponent.h>
#import <CoreImage/CIMirror.h>
#import <CoreImage/CIModTransition.h>
#import <CoreImage/CIMorphology.h>
#import <CoreImage/CICheapMorphology.h>
#import <CoreImage/CIMorphologyMinimum.h>
#import <CoreImage/CIMorphologyMaximum.h>
#import <CoreImage/CIMorphologyGradient.h>
#import <CoreImage/CIMorphologyLaplacian.h>
#import <CoreImage/CIPseudoMedian.h>
#import <CoreImage/CIMorphologyProcessor.h>
#import <CoreImage/CIMorphologyRectangle.h>
#import <CoreImage/CIMorphologyRectangleMaximum.h>
#import <CoreImage/CIMorphologyRectangleMinimum.h>
#import <CoreImage/CIMotionBlur.h>
#import <CoreImage/CIZoomBlur.h>
#import <CoreImage/CIOpTile.h>
#import <CoreImage/CIOpacity.h>
#import <CoreImage/CIPageCurlTransition.h>
#import <CoreImage/CIPageCurlWithShadowTransition.h>
#import <CoreImage/CIParallelogramTile.h>
#import <CoreImage/CIPerspectiveTransformWithExtent.h>
#import <CoreImage/CIPerspectiveTransform.h>
#import <CoreImage/CIPerspectiveTile.h>
#import <CoreImage/CIPerspectiveCorrection.h>
#import <CoreImage/CIPhotoEffect.h>
#import <CoreImage/CIPhotoEffectNoir.h>
#import <CoreImage/CIPhotoEffectChrome.h>
#import <CoreImage/CIPhotoEffectFade.h>
#import <CoreImage/CIPhotoEffectInstant.h>
#import <CoreImage/CIPhotoEffectMono.h>
#import <CoreImage/CIPhotoEffectProcess.h>
#import <CoreImage/CIPhotoEffectTonal.h>
#import <CoreImage/CIPhotoEffectTransfer.h>
#import <CoreImage/CIPhotoEffectStageMono.h>
#import <CoreImage/CIPhotoEffect3D.h>
#import <CoreImage/CIPhotoEffect3DVivid.h>
#import <CoreImage/CIPhotoEffect3DVividWarm.h>
#import <CoreImage/CIPhotoEffect3DVividCool.h>
#import <CoreImage/CIPhotoEffect3DDramatic.h>
#import <CoreImage/CIPhotoEffect3DDramaticWarm.h>
#import <CoreImage/CIPhotoEffect3DDramaticCool.h>
#import <CoreImage/CIPhotoEffect3DSilverplate.h>
#import <CoreImage/CIPhotoEffect3DCommercial.h>
#import <CoreImage/CIPhotoEffect3DNoir.h>
#import <CoreImage/CIPhotoGrain.h>
#import <CoreImage/CIPinchDistortion.h>
#import <CoreImage/CIPixellate.h>
#import <CoreImage/CIHexagonalPixellate.h>
#import <CoreImage/CIPointillize.h>
#import <CoreImage/CIBlurmapSmoothing.h>
#import <CoreImage/CIPortraitBlurNoise.h>
#import <CoreImage/CIPortraitBlurDirectionalBlur.h>
#import <CoreImage/CIPortraitBlur.h>
#import <CoreImage/CIPortraitBlurPreProcess.h>
#import <CoreImage/CIHighlightRecoveryProcessor.h>
#import <CoreImage/CISDOFHighlightRecovery.h>
#import <CoreImage/CIHighlightRecovery.h>
#import <CoreImage/CIPortraitAntialias.h>
#import <CoreImage/CISparseRendererPreFiltering.h>
#import <CoreImage/CISparseRenderer.h>
#import <CoreImage/CIPortraitBlurV2.h>
#import <CoreImage/CIPortraitBlurCombiner.h>
#import <CoreImage/CIPremultiply.h>
#import <CoreImage/CIUnpremultiply.h>
#import <CoreImage/InpaintingTilingFilter.h>
#import <CoreImage/CIRAWFilterImpl.h>
#import <CoreImage/CIRAWTemperatureAdjust.h>
#import <CoreImage/CIRAWGamutMapping.h>
#import <CoreImage/CIPerspectiveAutoCalc.h>
#import <CoreImage/CIRandomGenerator.h>
#import <CoreImage/CIRectangleDetector.h>
#import <CoreImage/CIRectangleGenerator.h>
#import <CoreImage/CIRoundedRectangleGenerator.h>
#import <CoreImage/CIRedEyeCorrection.h>
#import <CoreImage/CIRedEyeCorrections.h>
#import <CoreImage/InpaintingSinglePassFilter.h>
#import <CoreImage/CIRedEyeRepair3.h>
#import <CoreImage/CIFaceCoreDetector.h>
#import <CoreImage/CIReductionFilter.h>
#import <CoreImage/CIAreaAverage.h>
#import <CoreImage/CIColumnAverage.h>
#import <CoreImage/CIRowAverage.h>
#import <CoreImage/CIAreaMinMax.h>
#import <CoreImage/CIAreaMaximum.h>
#import <CoreImage/CIAreaMinimum.h>
#import <CoreImage/CIAreaMaximumAlpha.h>
#import <CoreImage/CIAreaMinimumAlpha.h>
#import <CoreImage/CIAreaMinMaxRed.h>
#import <CoreImage/CIAreaMinMaxNormalize.h>
#import <CoreImage/CIAreaMinMaxRedNormalize.h>
#import <CoreImage/CIKMeans.h>
#import <CoreImage/CIAreaCentroid.h>
#import <CoreImage/CIAreaRedCentroid.h>
#import <CoreImage/CIAreaRedRadialCentroid.h>
#import <CoreImage/CICircularMaskFromPointImage.h>
#import <CoreImage/CIPaletteCentroid.h>
#import <CoreImage/CITileFilter.h>
#import <CoreImage/CITile2Filter.h>
#import <CoreImage/CIFourfoldRotatedTile.h>
#import <CoreImage/CISixfoldRotatedTile.h>
#import <CoreImage/CITwelvefoldReflectedTile.h>
#import <CoreImage/CIFourfoldTranslatedTile.h>
#import <CoreImage/CIGlideReflectedTile.h>
#import <CoreImage/CIEightfoldReflectedTile.h>
#import <CoreImage/CIFourfoldReflectedTile.h>
#import <CoreImage/CISixfoldReflectedTile.h>
#import <CoreImage/CIRenderDestination.h>
#import <CoreImage/CIRenderInfo.h>
#import <CoreImage/CIRenderTask.h>
#import <CoreImage/CIRippleTransition.h>
#import <CoreImage/CISRGBToneCurveToLinear.h>
#import <CoreImage/CILinearToSRGBToneCurve.h>
#import <CoreImage/CISaliencyMapKernel.h>
#import <CoreImage/CISaliencyMapFilter.h>
#import <CoreImage/CISampleNearest.h>
#import <CoreImage/CISampler.h>
#import <CoreImage/CISepiaTone.h>
#import <CoreImage/CIShadedMaterial.h>
#import <CoreImage/CIPerspectiveAutoCalcV2.h>
#import <CoreImage/CINoiseReduction.h>
#import <CoreImage/CIProSharpenEdges.h>
#import <CoreImage/CISharpenLuminance.h>
#import <CoreImage/CISkyAndGrassAdjust.h>
#import <CoreImage/CISmartBlackAndWhite.h>
#import <CoreImage/CISmartToneFilter.h>
#import <CoreImage/CISmartColorFilter.h>
#import <CoreImage/InpaintingImageHelpers.h>
#import <CoreImage/CIBicubicScaleTransform.h>
#import <CoreImage/CISoftCubicUpsample.h>
#import <CoreImage/CISpotLight.h>
#import <CoreImage/CIStarShineGenerator.h>
#import <CoreImage/CIStraightenFilter.h>
#import <CoreImage/CIStretch.h>
#import <CoreImage/CIStretchCrop.h>
#import <CoreImage/CINinePartStretched.h>
#import <CoreImage/CINinePartTiled.h>
#import <CoreImage/CIStripesGenerator.h>
#import <CoreImage/CISunbeamsGenerator.h>
#import <CoreImage/CISwipeTransition.h>
#import <CoreImage/CITemperatureAndTint.h>
#import <CoreImage/CIWhitePointAdjust.h>
#import <CoreImage/CIFalseColor.h>
#import <CoreImage/CITextDetector.h>
#import <CoreImage/CITextImageGenerator.h>
#import <CoreImage/CIAttributedTextImageGenerator.h>
#import <CoreImage/CIToneCurve.h>
#import <CoreImage/CITriangleKaleidoscope.h>
#import <CoreImage/CITriangleTile.h>
#import <CoreImage/CITwirlDistortion.h>
#import <CoreImage/CIUnsharpMask.h>
#import <CoreImage/CIVNFeature.h>
#import <CoreImage/CIVNDetector.h>
#import <CoreImage/CIVNFaceDetector.h>
#import <CoreImage/CIVNRectFeature.h>
#import <CoreImage/CIVNRectDetector.h>
#import <CoreImage/CIVariableBoxBlur.h>
#import <CoreImage/InpaintingEspressoExecutionResources.h>
#import <CoreImage/InpaintingEspressoHelpers.h>
#import <CoreImage/CIVector.h>
#import <CoreImage/CIVibrance.h>
#import <CoreImage/CIVignette.h>
#import <CoreImage/CIVignetteEffect.h>
#import <CoreImage/CIPerspectiveAutoCalcV1.h>
#import <CoreImage/CIVortexDistortion.h>
#import <CoreImage/CIWrapMirror.h>
#import <CoreImage/CIDepthToDisparity.h>
#import <CoreImage/CIDisparityToDepth.h>
#import <CoreImage/CIDepthDisparityConverter.h>
#import <CoreImage/CISegmentationFusion.h>
#import <CoreImage/CILensModelApplyV3.h>
#import <CoreImage/CIDisparityWeightsV3.h>
#import <CoreImage/CIDisparityPreprocV3.h>
#import <CoreImage/CIDisparityRefinementSparseSamplerV3.h>
#import <CoreImage/CIDisparityRefinementAntialiasV3.h>
#import <CoreImage/CIDisparityRefinementV3.h>
#import <CoreImage/CIDepthEffectMakeBlurMap.h>
#import <CoreImage/CIDepthEffectApplyBlurMap.h>
#import <CoreImage/CIDepthEffect.h>
#import <CoreImage/CIDepthBlurEffect.h>
#import <CoreImage/CUIScaleClampFilter.h>
#import <CoreImage/CUIInnerGlowOrShadowFilter.h>
#import <CoreImage/CUIOuterGlowOrShadowFilter.h>
#import <CoreImage/CUIShapeEffectBlur1.h>
#import <CoreImage/CUIOuterBevelEmbossFilter.h>
#import <CoreImage/CUIInnerBevelEmbossFilter.h>
#import <CoreImage/CIEnhancementCalculation.h>
#import <CoreImage/CIEnhancementCalculator.h>
#import <CoreImage/CIEnhancementHistogram.h>
#import <CoreImage/CIAutoEnhanceFace.h>
#import <CoreImage/XFocalPlane.h>
#import <CoreImage/RedEyeGlintFinder.h>
#import <CoreImage/XMattingBoxTensorFilter.h>
#import <CoreImage/XMattingRGBDFilter.h>
#import <CoreImage/XMattingRGBFilter.h>
#import <CoreImage/XMattingSolver.h>
#import <CoreImage/RedEyeMinMorphology.h>
#import <CoreImage/RedEyeMaxMorphology.h>
#import <CoreImage/RedEyeDifference.h>
#import <CoreImage/RedEyeGradient.h>
#import <CoreImage/RedEyeChannel.h>
#import <CoreImage/CIRedEyeRepair.h>
#import <CoreImage/CIColorAbsoluteDifference.h>
#import <CoreImage/InpaintingMembraneGeneration.h>
#import <CoreImage/InpaintingFullPipelineFilter.h>
#import <CoreImage/CIKernelLibrary.h>
#import <CoreImage/InpaintingVImageWrapper.h>
#import <CoreImage/CIBlurmapRefinementThreshold.h>
#import <CoreImage/CIBlurmapRefinementLinearMapping.h>
#import <CoreImage/CIBlurmapRefinementDistanceDelta.h>
#import <CoreImage/CIPerspectiveRotate.h>
#import <CoreImage/CIKeystoneCorrection.h>
#import <CoreImage/CIKeystoneCorrectionCombined.h>
#import <CoreImage/CIKeystoneCorrectionHorizontal.h>
#import <CoreImage/CIKeystoneCorrectionVertical.h>
