/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:35:54 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <libobjc.A.dylib/SXConditionValidationContext.h>
@class NSString;


@protocol SXConditionValidationContext <NSObject>
@property (nonatomic,readonly) CGSize viewportSize; 
@property (nonatomic,readonly) long long horizontalSizeClass; 
@property (nonatomic,readonly) long long verticalSizeClass; 
@property (nonatomic,readonly) NSString * contentSizeCategory; 
@property (nonatomic,readonly) unsigned long long numberOfColumns; 
@property (nonatomic,readonly) BOOL testing; 
@property (nonatomic,readonly) unsigned long long viewingLocation; 
@property (getter=isBundleSubscriber,nonatomic,readonly) BOOL bundleSubscriber; 
@property (getter=isBundleTrialEligible,nonatomic,readonly) BOOL bundleTrialEligible; 
@property (getter=isChannelSubscriber,nonatomic,readonly) BOOL channelSubscriber; 
@property (nonatomic,readonly) long long userInterfaceStyle; 
@property (nonatomic,readonly) double contentScaleFactor; 
@property (nonatomic,readonly) unsigned long long newsletterSubscriptionStatus; 
@required
-(double)contentScaleFactor;
-(CGSize)viewportSize;
-(long long)userInterfaceStyle;
-(BOOL)isBundleSubscriber;
-(NSString *)contentSizeCategory;
-(unsigned long long)numberOfColumns;
-(long long)verticalSizeClass;
-(BOOL)testing;
-(long long)horizontalSizeClass;
-(unsigned long long)newsletterSubscriptionStatus;
-(unsigned long long)viewingLocation;
-(BOOL)isChannelSubscriber;
-(BOOL)isBundleTrialEligible;

@end


@class NSString, SXLayoutOptions;

@interface SXConditionValidationContext : NSObject <SXConditionValidationContext> {

	SXLayoutOptions* _layoutOptions;

}

@property (nonatomic,readonly) SXLayoutOptions * layoutOptions;                                    //@synthesize layoutOptions=_layoutOptions - In the implementation block
@property (nonatomic,readonly) CGSize viewportSize; 
@property (nonatomic,readonly) long long horizontalSizeClass; 
@property (nonatomic,readonly) long long verticalSizeClass; 
@property (nonatomic,readonly) NSString * contentSizeCategory; 
@property (nonatomic,readonly) unsigned long long numberOfColumns; 
@property (nonatomic,readonly) BOOL testing; 
@property (nonatomic,readonly) unsigned long long viewingLocation; 
@property (getter=isBundleSubscriber,nonatomic,readonly) BOOL bundleSubscriber; 
@property (getter=isBundleTrialEligible,nonatomic,readonly) BOOL bundleTrialEligible; 
@property (getter=isChannelSubscriber,nonatomic,readonly) BOOL channelSubscriber; 
@property (nonatomic,readonly) long long userInterfaceStyle; 
@property (nonatomic,readonly) double contentScaleFactor; 
@property (nonatomic,readonly) unsigned long long newsletterSubscriptionStatus; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(SXLayoutOptions *)layoutOptions;
-(double)contentScaleFactor;
-(CGSize)viewportSize;
-(long long)userInterfaceStyle;
-(BOOL)isBundleSubscriber;
-(NSString *)contentSizeCategory;
-(unsigned long long)numberOfColumns;
-(long long)verticalSizeClass;
-(BOOL)testing;
-(long long)horizontalSizeClass;
-(id)initWithLayoutOptions:(id)arg1 ;
-(unsigned long long)newsletterSubscriptionStatus;
-(unsigned long long)viewingLocation;
-(BOOL)isChannelSubscriber;
-(BOOL)isBundleTrialEligible;
@end

