#import <SafariShared/WBSAutoplayQuirkWhitelistManager.h>
#import <SafariShared/WBSPasswordBreachConfigurationBagSnapshotTransformer.h>
#import <SafariShared/WBSFormControlMetadataProperty.h>
#import <SafariShared/WBSFormControlMetadata.h>
#import <SafariShared/WBSMutableFormControlMetadata.h>
#import <SafariShared/WBSAddressBookMatch.h>
#import <SafariShared/WBSHistoryServiceURLCompletion.h>
#import <SafariShared/WBSHistoryUniversalPredicate.h>
#import <SafariShared/WBSBookmarkAndHistoryCompletionMatch.h>
#import <SafariShared/WBSCache.h>
#import <SafariShared/WBSPasswordBreachStore.h>
#import <SafariShared/WBSCleanupHandler.h>
#import <SafariShared/WBSPasswordBreachConfiguration.h>
#import <SafariShared/WBSCloudBookmarksMigrationCoordinator.h>
#import <SafariShared/WBSCredentialMatchResult.h>
#import <SafariShared/WBSPasswordBreachTestCredentialSource.h>
#import <SafariShared/WBSCloudHistory.h>
#import <SafariShared/WBSQuerySuggestion.h>
#import <SafariShared/WBSCredentialIdentityMatch.h>
#import <SafariShared/WBSPasswordWarningTopFraudTargets.h>
#import <SafariShared/WBSPasswordWarningTopFraudTargetsTransformer.h>
#import <SafariShared/WBSCloudHistoryConfiguration.h>
#import <SafariShared/WBSCloudHistoryFetchResult.h>
#import <SafariShared/WBSAutomaticReaderActivationManager.h>
#import <SafariShared/WBSContentBlockerStatisticsSQLiteStore.h>
#import <SafariShared/WBSContentBlockerStatisticsFirstParty.h>
#import <SafariShared/WBSCloudHistoryMergeOperation.h>
#import <SafariShared/WBSHistoryServiceTombstone.h>
#import <SafariShared/WBSCloudHistoryPushAgent.h>
#import <SafariShared/WBSCloudHistoryPushAgentProxy.h>
#import <SafariShared/WBSCloudHistoryStore.h>
#import <SafariShared/WBSCloudHistoryVisit.h>
#import <SafariShared/WBSAutomaticBugCaptureManager.h>
#import <SafariShared/WBSPasswordWordList.h>
#import <SafariShared/WBSCloudTab.h>
#import <SafariShared/WBSCloudTabCloseRequest.h>
#import <SafariShared/WBSCloudTabDevice.h>
#import <SafariShared/WBSCloudTabStore.h>
#import <SafariShared/WBSCoalescedAsynchronousWriter.h>
#import <SafariShared/WBSProcessProxyOverride.h>
#import <SafariShared/WBSUserAgentQuirksSnapshot.h>
#import <SafariShared/WBSCompletionQuery.h>
#import <SafariShared/WBSContactAutoFillSet.h>
#import <SafariShared/WBSContactsEntry.h>
#import <SafariShared/WBSUserAgentQuirksSnapshotTransformer.h>
#import <SafariShared/WBSCloudHistoryServiceProxy.h>
#import <SafariShared/WBSContactsHelper.h>
#import <SafariShared/WBSCredentialMatch.h>
#import <SafariShared/WBSHistoryServiceDatabaseProxy.h>
#import <SafariShared/WBSCreditCardData.h>
#import <SafariShared/WBSPasswordBreachChecker.h>
#import <SafariShared/WBSHistoryServiceVisit.h>
#import <SafariShared/WBSPasswordBreachQueuedPassword.h>
#import <SafariShared/WBSCreditCardDataController.h>
#import <SafariShared/WBSCreditCardFormatter.h>
#import <SafariShared/WBSPasswordBreachKeychainCredentialSource.h>
#import <SafariShared/WBSPasswordBreachHelper.h>
#import <SafariShared/WBSSafariSandboxBroker.h>
#import <SafariShared/WBSCyclerBookmarkLeafRepresentation.h>
#import <SafariShared/WBSBrowserTabCompletionMatch.h>
#import <SafariShared/WBSCyclerBookmarkListRepresentation.h>
#import <SafariShared/WBSCyclerBookmarkOperationContext.h>
#import <SafariShared/WBSCyclerBookmarkRepresentation.h>
#import <SafariShared/WBSHistoryServiceStore.h>
#import <SafariShared/WBSPasswordBreachManager.h>
#import <SafariShared/WBSCyclerBookmarksTestSuite.h>
#import <SafariShared/WBSCyclerCloudKitMigrationTestSuite.h>
#import <SafariShared/WBSPasswordWarning.h>
#import <SafariShared/WBSPerSitePreferenceTimeout.h>
#import <SafariShared/WBSPerSitePreferenceManager.h>
#import <SafariShared/WBSCyclerConnectionManager.h>
#import <SafariShared/WBSCyclerCreateBookmarkOperation.h>
#import <SafariShared/WBSSearchImpressionAnalyticsRecorder.h>
#import <SafariShared/WBSCyclerDeleteBookmarkOperation.h>
#import <SafariShared/WBSPerSitePreference.h>
#import <SafariShared/WBSCyclerModifyBookmarkOperation.h>
#import <SafariShared/WBSCyclerMoveBookmarkOperation.h>
#import <SafariShared/WBSCyclerOperation.h>
#import <SafariShared/WBSPasswordImportedCredential.h>
#import <SafariShared/WBSCyclerRandomnessUtilities.h>
#import <SafariShared/WBSTabDialogCancellationExemption.h>
#import <SafariShared/WBSCyclerService.h>
#import <SafariShared/WBSCyclerServiceProxy.h>
#import <SafariShared/WBSHistoryServicePendingVisit.h>
#import <SafariShared/WBSCyclerStatus.h>
#import <SafariShared/WBSCyclerTestRunner.h>
#import <SafariShared/WBSHistoryVisitIdentifier.h>
#import <SafariShared/WBSCyclerTestSuiteBookmarkAuxiliary.h>
#import <SafariShared/WBSCyclerTestTargetProxyController.h>
#import <SafariShared/WBSDistributedNotificationObserver.h>
#import <SafariShared/WBSEncryptedCloudKeyValueStore.h>
#import <SafariShared/WBSFileLockPOSIX.h>
#import <SafariShared/WBSFileLockFactoryPOSIX.h>
#import <SafariShared/_WBSFieldLabelPatternMatcherFactory.h>
#import <SafariShared/WBSFormAutoFillClassificationToCorrectionsTransformer.h>
#import <SafariShared/WBSFormAutoFillCorrectionManager.h>
#import <SafariShared/WBSCrowdsourcedFeedbackDomainNormalizer.h>
#import <SafariShared/WBSFormAutoFillCorrectionSet.h>
#import <SafariShared/WBSBrowserTabCompletionInfo.h>
#import <SafariShared/WBSBrowserTabCompletionProvider.h>
#import <SafariShared/WBSFormAutoFillCorrectionsHistoryObserver.h>
#import <SafariShared/WBSFormAutoFillCorrectionsSQLiteStore.h>
#import <SafariShared/WBSFormAutoFillItem.h>
#import <SafariShared/WBSDigitalHealthManager.h>
#import <SafariShared/WBSHistorySessionWithItems.h>
#import <SafariShared/WBSSetInt64.h>
#import <SafariShared/WBSFormAutoFillMetadataCorrector.h>
#import <SafariShared/WBSPasswordBreachConfigurationBag.h>
#import <SafariShared/WBSFormAutoFillParsecCrowdsourcedCorrectionsProcessor.h>
#import <SafariShared/WBSPasswordWarningManager.h>
#import <SafariShared/WBSFormAutoFillParsecDomainPolicyProvider.h>
#import <SafariShared/WBSFormAutoFillParsecFeedbackProcessor.h>
#import <SafariShared/WBSResultRanker.h>
#import <SafariShared/WBSPasswordEvaluator.h>
#import <SafariShared/WBSFormDataController.h>
#import <SafariShared/WBSPersistentPropertyListStore.h>
#import <SafariShared/WBSFormFieldClassificationCorrector.h>
#import <SafariShared/WBSFormFieldFingerprinter.h>
#import <SafariShared/WBSPasswordBreachConfigurationDictionaryUnpacker.h>
#import <SafariShared/WBSPasswordPatternPartialSolution.h>
#import <SafariShared/WBSPasswordPatternMatchSolver.h>
#import <SafariShared/WBSFormMetadata.h>
#import <SafariShared/WBSFormMetadataController.h>
#import <SafariShared/WBSPasswordSetWordList.h>
#import <SafariShared/WBSGeolocationPreferenceManager.h>
#import <SafariShared/WBSPasswordWordListCollection.h>
#import <SafariShared/WBSFormToABBinder.h>
#import <SafariShared/WBSFrequentlyVisitedSiteCandidate.h>
#import <SafariShared/WBSFrequentlyVisitedSitesBannedURLStore.h>
#import <SafariShared/WBSFrequentlyVisitedSitesController.h>
#import <SafariShared/WBSSafariSandboxBrokerConnection.h>
#import <SafariShared/WBSHistory.h>
#import <SafariShared/WBSHistoryAccessSession.h>
#import <SafariShared/WBSCredentialMatchCriteria.h>
#import <SafariShared/WBSHistoryAccessSessionProxy.h>
#import <SafariShared/WBSHistoryConnection.h>
#import <SafariShared/WBSTabOrderManager.h>
#import <SafariShared/WBSTabOrderInsertionHint.h>
#import <SafariShared/WBSHistoryConnectionProxy.h>
#import <SafariShared/WBSHistoryDatabaseAccessBroker.h>
#import <SafariShared/WBSHistoryDeletionPlan.h>
#import <SafariShared/WBSPasswordBreachHelperListener.h>
#import <SafariShared/WBSHistoryItem.h>
#import <SafariShared/WBSPasswordBreachHelperProxy.h>
#import <SafariShared/WBSHistoryNotification.h>
#import <SafariShared/WBSProtectionSpaceMatch.h>
#import <SafariShared/WBSHistoryService.h>
#import <SafariShared/WBSAllowedLegacyTLSHostManager.h>
#import <SafariShared/WBSHistoryServiceItem.h>
#import <SafariShared/WBSHistorySession.h>
#import <SafariShared/WBSHistorySessionController.h>
#import <SafariShared/WBSHistoryTopicTag.h>
#import <SafariShared/WBSHistorySessionIntervalCache.h>
#import <SafariShared/WBSReaderConfigurationManager.h>
#import <SafariShared/WBSHistoryVisitsNeedingRecomputedVisitCountsPredicate.h>
#import <SafariShared/WBSHistoryTag.h>
#import <SafariShared/WBSHistoryTombstone.h>
#import <SafariShared/WBSHistoryTagDatabaseController.h>
#import <SafariShared/WBSHistoryVisitsInRedirectChainPredicate.h>
#import <SafariShared/WBSPasswordBreachNotificationManager.h>
#import <SafariShared/WBSWellKnownURLResponseCodeReliabilityChecker.h>
#import <SafariShared/WBSHistoryURLCompletionDataStore.h>
#import <SafariShared/WBSHistoryURLCompletionMatchData.h>
#import <SafariShared/WBSHistoryVisitsAndTombstonesInSyncWindowPredicate.h>
#import <SafariShared/WBSHistoryURLCompletionSession.h>
#import <SafariShared/WBSHistoryVisit.h>
#import <SafariShared/WBSHistoryCrypto.h>
#import <SafariShared/WBSDomainWhitelistSnapshot.h>
#import <SafariShared/WBSJSCallbackHandler.h>
#import <SafariShared/WBSSmartHistorySearcher.h>
#import <SafariShared/WBSSingleCreditCardData.h>
#import <SafariShared/WBSDispatchSourceTimer.h>
#import <SafariShared/WBSPasswordBreachQueuedPasswordBagManager.h>
#import <SafariShared/WBSPasswordBreachResults.h>
#import <SafariShared/WBSMultiRoundAutoFillManager.h>
#import <SafariShared/WBSClass.h>
#import <SafariShared/WBSPasswordLexiconWordList.h>
#import <SafariShared/WBSPasswordBreachRequestManager.h>
#import <SafariShared/WBSAutoplayQuirkWhitelistSnapshot.h>
#import <SafariShared/WBSReaderAvailabilityCheckResult.h>
#import <SafariShared/WBSHistoryServiceURLRepresentation.h>
#import <SafariShared/WBSAsynchronousRequestHelper.h>
#import <SafariShared/WBSPasswordWarningStore.h>
#import <SafariShared/WBSTabDialogCancellationContext.h>
#import <SafariShared/WBSHistoryTagsPredicate.h>
#import <SafariShared/WBSScopeTimeoutHandler.h>
#import <SafariShared/WBSPasswordOrderedSetWordList.h>
#import <SafariShared/WBSDomainWhitelistSnapshotTransformer.h>
#import <SafariShared/WBSOpenSearchDescription.h>
#import <SafariShared/WBSPasswordBreachCredential.h>
#import <SafariShared/WBSOpenSearchSchemaFetcher.h>
#import <SafariShared/WBSOpenSearchURLTemplateParameter.h>
#import <SafariShared/WBSOpenSearchURLTemplate.h>
#import <SafariShared/WBSReaderNavigationPolicyDecider.h>
#import <SafariShared/WBSPasswordBreachConfigurationBagLoader.h>
#import <SafariShared/WBSRecentHistoryTopicTagController.h>
#import <SafariShared/WBSParsecModel.h>
#import <SafariShared/WBSPasswordEvaluation.h>
#import <SafariShared/WBSMemoryPressureMonitor.h>
#import <SafariShared/WBSOneShotTimer.h>
#import <SafariShared/WBSPasswordWordListEntry.h>
#import <SafariShared/WBSHistoryServiceForTesting.h>
#import <SafariShared/WBSHistoryServiceDatabase.h>
#import <SafariShared/WBSDomainWhitelistManager.h>
#import <SafariShared/WBSHistoryServiceDatabaseDelegateProxy.h>
#import <SafariShared/WBSHistoryServiceDatabaseDelegateWeakProxy.h>
#import <SafariShared/WBSParsecSchema.h>
#import <SafariShared/_WBSParsecArraySchema.h>
#import <SafariShared/_WBSParsecDictionarySchema.h>
#import <SafariShared/WBSTabDialog.h>
#import <SafariShared/WBSHistoryServiceEvent.h>
#import <SafariShared/WBSHistoryVisitsMatchingOriginsPredicate.h>
#import <SafariShared/WBSPasswordBreachBloomFilter.h>
#import <SafariShared/WBSPasswordPatternMatcher.h>
#import <SafariShared/WBSHistoryVisitsInTimeRangePredicate.h>
#import <SafariShared/WBSPasswordBreachContext.h>
#import <SafariShared/WBSAutoplayPreferenceManager.h>
#import <SafariShared/WBSHistoryServiceURLCompletionMatchEntry.h>
#import <SafariShared/WBSHistoryServiceURLCompletionMatchData.h>
#import <SafariShared/WBSContentBlockersPreferenceManager.h>
#import <SafariShared/WBSPageZoomPreferenceManager.h>
#import <SafariShared/WBSHistoryVisitsWithItemsPredicate.h>
#import <SafariShared/WBSPasswordAutoFillUtilities.h>
#import <SafariShared/WBSPeriodicActivityScheduler.h>
#import <SafariShared/WBSPerSitePreferencesSQLiteStore.h>
#import <SafariShared/WBSPerSitePreferenceValueInformation.h>
#import <SafariShared/WBSHistorySQLiteSchema.h>
#import <SafariShared/WBSQuickWebsiteSearchController.h>
#import <SafariShared/WBSQuickWebsiteSearchProvider.h>
#import <SafariShared/WBSRadarNewProblemURLBuilder.h>
#import <SafariShared/WBSReaderResources.h>
#import <SafariShared/WBSHistoryServiceObject.h>
#import <SafariShared/WBSReaderFont.h>
#import <SafariShared/WBSHistoryObjectCache.h>
#import <SafariShared/WBSReaderFontDownloadManager.h>
#import <SafariShared/WBSReaderFontManager.h>
#import <SafariShared/WBSPasswordBreachResultRecord.h>
#import <SafariShared/WBSReaderLocalizedFonts.h>
#import <SafariShared/WBSDictionaryInt64.h>
#import <SafariShared/WBSRecentlyUsedAutoFillSet.h>
#import <SafariShared/WBSRecentWebSearchEntry.h>
#import <SafariShared/WBSRecentWebSearchesController.h>
#import <SafariShared/WBSRemoteHistoryItem.h>
#import <SafariShared/WBSRemoteHistorySession.h>
#import <SafariShared/WBSRemoteHistoryVisit.h>
#import <SafariShared/WBSHistoryItemToTagPairsPredicate.h>
#import <SafariShared/WBSCertificateWarningPageContext.h>
#import <SafariShared/_WBSSafariCyclerConfigurationCommand.h>
#import <SafariShared/WBSSafariCyclerConfigurationTool.h>
#import <SafariShared/WBSSameDocumentNavigationToHistoryVisitCorrelator.h>
#import <SafariShared/WBSUserMediaPermissionController.h>
#import <SafariShared/WBSSearchHelperConnectionManager.h>
#import <SafariShared/WBSPasswordBreachCryptographicOperations.h>
#import <SafariShared/WBSHistoryVisitsWithIDPredicate.h>
#import <SafariShared/WBSHistoryVisitsMatchingTimesPredicate.h>
#import <SafariShared/WBSHistoryContextController.h>
#import <SafariShared/WBSPasswordBreachResultQuery.h>
#import <SafariShared/WBSUserMediaCapturePolicyEntry.h>
#import <SafariShared/WBSUserAgentQuirksManager.h>
#import <SafariShared/WBSTabDialogInformation.h>
#import <SafariShared/WBSTabDialogManager.h>
#import <SafariShared/WBSAutoplayQuirkWhitelistSnapshotTransformer.h>
#import <SafariShared/WBSTopHitCompletionMatch.h>
#import <SafariShared/WBSPasswordPatternMatch.h>
#import <SafariShared/WBSPasswordPickerHintStringGenerator.h>
#import <SafariShared/WBSURLCompletionDatabase.h>
#import <SafariShared/WBSURLCompletionHistorySnapshot.h>
#import <SafariShared/WBSURLCompletionMatch.h>
#import <SafariShared/WBSHistoryConnectionProxyForTesting.h>
#import <SafariShared/WBSTabCompletionMatch.h>
#import <SafariShared/WBSURLCompletionMatchSnapshot.h>
#import <SafariShared/WBSURLCompletionSessionProxy.h>
#import <SafariShared/WBSURLCompletionUserTypedString.h>
#import <SafariShared/WBSURLSuffixChecker.h>
#import <SafariShared/WBSAppleAccountInformationProvider.h>
#import <SafariShared/WBSUserTypedFormString.h>
