/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:36:08 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ACDPreferences : NSObject
+(id)sharedPreferences;
-(void)setObject:(id)arg1 forKey:(id)arg2 ;
-(void)reset;
-(double)serverTimeoutInterval;
-(id)objectForKey:(id)arg1 ;
-(void)synchronize;
@end

