#import <HealthDaemon/HDBinarySampleEntity.h>
#import <HealthDaemon/_HDBinarySampleEntityEncoder.h>
#import <HealthDaemon/HDCloudSyncParallelOperation.h>
#import <HealthDaemon/HDCodableFHIRIdentifier.h>
#import <HealthDaemon/HDMockProfile.h>
#import <HealthDaemon/HDMockPrimaryProfile.h>
#import <HealthDaemon/HDPrimaryProfile.h>
#import <HealthDaemon/_HDEventsCollectionAssertion.h>
#import <HealthDaemon/HDWorkoutEventsManager.h>
#import <HealthDaemon/HDCloudSyncValidateSubscriptionsOperation.h>
#import <HealthDaemon/HDDocumentQueryServer.h>
#import <HealthDaemon/HDCodableMedicationDispenseRecord.h>
#import <HealthDaemon/HDWorkoutRouteDataSource.h>
#import <HealthDaemon/HDDemoDataAudiogramSampleGenerator.h>
#import <HealthDaemon/HDSQLiteDatabase.h>
#import <HealthDaemon/HDNanoRegistryPairedDeviceCapabilityProvider.h>
#import <HealthDaemon/HDCloudSyncRecord.h>
#import <HealthDaemon/HDProcedureRecordEntity.h>
#import <HealthDaemon/_HDProcedureRecordEntityEncoder.h>
#import <HealthDaemon/HDNSOperatingSystemVersion.h>
#import <HealthDaemon/HDDatabaseControlServer.h>
#import <HealthDaemon/HDSerialQueueBlockDispatcher.h>
#import <HealthDaemon/HDCloudSyncChangeRecord.h>
#import <HealthDaemon/HDCrossTrainerData.h>
#import <HealthDaemon/HDCodableError.h>
#import <HealthDaemon/HDCodableLocationDatum.h>
#import <HealthDaemon/HDSimpleGraphObject.h>
#import <HealthDaemon/HDCodableRoutineLocation.h>
#import <HealthDaemon/HDXPCProcess.h>
#import <HealthDaemon/HDXPCAlarm.h>
#import <HealthDaemon/HDCodableReferenceRangeList.h>
#import <HealthDaemon/HDCloudSyncManagerMedicalIDSyncTask.h>
#import <HealthDaemon/HDSeriesQuantityDataAggregator.h>
#import <HealthDaemon/_HDSeriesQuantityDataAggregationState.h>
#import <HealthDaemon/HDCodableDeletedSample.h>
#import <HealthDaemon/HDCloudSyncPipelineStagePush.h>
#import <HealthDaemon/HDEnhancedFTMSData.h>
#import <HealthDaemon/HDStatisticsQueryServer.h>
#import <HealthDaemon/HDDataProvenanceEntity.h>
#import <HealthDaemon/HDCloudSyncCodableLog.h>
#import <HealthDaemon/HDCodableRoutinePredictedLocation.h>
#import <HealthDaemon/HDSQLiteQueryPlan.h>
#import <HealthDaemon/HDSQLiteQueryPlanRow.h>
#import <HealthDaemon/HDWorkoutBuilderEventEntity.h>
#import <HealthDaemon/HDCloudSyncPipelineStageDescribe.h>
#import <HealthDaemon/HDCodableSyncAnchorRangeMap.h>
#import <HealthDaemon/HDCodableTinkerPairingResponse.h>
#import <HealthDaemon/HDProfileAuthorizationEntity.h>
#import <HealthDaemon/HDDiagnosticTestReportEntity.h>
#import <HealthDaemon/_HDDiagnosticTestReportEntityEncoder.h>
#import <HealthDaemon/HDCodableNanoSyncActivationRestore.h>
#import <HealthDaemon/HDFitnessMachineManager.h>
#import <HealthDaemon/HDCloudSyncPrepareForSharingOperation.h>
#import <HealthDaemon/HDCategorySampleEntity.h>
#import <HealthDaemon/_HDCategorySampleEntityEncoder.h>
#import <HealthDaemon/HDDemoDataFoodObject.h>
#import <HealthDaemon/HDWorkoutBuilderStatisticsCalculatorEntity.h>
#import <HealthDaemon/HDWorkoutPlugin.h>
#import <HealthDaemon/HDCodableRoutineLocationResponse.h>
#import <HealthDaemon/HDLiveDataCollectorBuffer.h>
#import <HealthDaemon/HDDeviceInformationService.h>
#import <HealthDaemon/HDCodableConditionRecord.h>
#import <HealthDaemon/HDHealthStoreProviderServer.h>
#import <HealthDaemon/HDAuthorizationStoreResetServer.h>
#import <HealthDaemon/HDLocationManager.h>
#import <HealthDaemon/HDCloudSyncPreparePushZoneForStoreOperation.h>
#import <HealthDaemon/HDCloudSyncPushSequenceOperation.h>
#import <HealthDaemon/HDAWDHealthKitAchievement.h>
#import <HealthDaemon/HDHealthServiceOOBInfo.h>
#import <HealthDaemon/HDClinicalGatewayEntity.h>
#import <HealthDaemon/HDDemoDataFoodSampleGenerator.h>
#import <HealthDaemon/HDCloudSyncDeleteZonesOperation.h>
#import <HealthDaemon/HDCodableSharingSetupMetadata.h>
#import <HealthDaemon/HDCodableRatioValue.h>
#import <HealthDaemon/HDCodableStartWorkoutAppResponse.h>
#import <HealthDaemon/HDCloudSyncUpdateLocalAnchorsOperation.h>
#import <HealthDaemon/HDCodableMetadataKeyValuePair.h>
#import <HealthDaemon/HDMedicationRecordEntity.h>
#import <HealthDaemon/_HDMedicationRecordEntityEncoder.h>
#import <HealthDaemon/HDBackgroundObservationServerExtensionManager.h>
#import <HealthDaemon/_HDDeleteSourcesWithUUIDsEntry.h>
#import <HealthDaemon/HDPassiveQuantityDataAggregator.h>
#import <HealthDaemon/HDGatedActivity.h>
#import <HealthDaemon/HDDeletedObjectEntity.h>
#import <HealthDaemon/HDTinkerProfile.h>
#import <HealthDaemon/HDCodableMedicationDosage.h>
#import <HealthDaemon/HDCodableNanoSyncAnchor.h>
#import <HealthDaemon/HDQueryManager.h>
#import <HealthDaemon/_HDProcessQueryCollection.h>
#import <HealthDaemon/_HDQueryDatabaseAccessBlock.h>
#import <HealthDaemon/HDSQLiteEntityIndex.h>
#import <HealthDaemon/HDHeartRateMeasurement.h>
#import <HealthDaemon/HDAWDHealthKitCoachingFeatureGroup.h>
#import <HealthDaemon/HDMedicalIDDataManager.h>
#import <HealthDaemon/HDSourceQueryServer.h>
#import <HealthDaemon/HDMockIDSDevice.h>
#import <HealthDaemon/HDDatabaseCoalescedWritePool.h>
#import <HealthDaemon/_HDDatabasePendingWriteRecord.h>
#import <HealthDaemon/HDSortedSampleIterator.h>
#import <HealthDaemon/HDIndoorBikeData.h>
#import <HealthDaemon/HDCloudSyncPipelineStagePrepareForSync.h>
#import <HealthDaemon/HDDemoDataReproductiveHealthSampleGenerator.h>
#import <HealthDaemon/HDFitnessMachineService.h>
#import <HealthDaemon/HDSQLiteDatabaseColumnSchema.h>
#import <HealthDaemon/HDSQLiteDatabaseTableSchema.h>
#import <HealthDaemon/HDSQLiteDatabaseIndexSchema.h>
#import <HealthDaemon/HDSQLiteDatabaseSchema.h>
#import <HealthDaemon/HDMockWorkoutDataDestination.h>
#import <HealthDaemon/HDMedicationOrderEntity.h>
#import <HealthDaemon/_HDMedicationOrderEntityEncoder.h>
#import <HealthDaemon/HDNanoUserDefaultsSyncEntity.h>
#import <HealthDaemon/HDUnprotectedNanoUserDefaultsSyncEntity.h>
#import <HealthDaemon/HDProtectedNanoUserDefaultsSyncEntity.h>
#import <HealthDaemon/HDDeepBreathingSessionServer.h>
#import <HealthDaemon/HDActivityStatisticsQueryServer.h>
#import <HealthDaemon/HDCodableAuthorizationResponseMessage.h>
#import <HealthDaemon/HDSourceEntity.h>
#import <HealthDaemon/_HDSourceEncoder.h>
#import <HealthDaemon/HDSourceSyncEntity.h>
#import <HealthDaemon/HDNanoSyncManager.h>
#import <HealthDaemon/HDRemoteAuthorizationRequestContext.h>
#import <HealthDaemon/HDRemoteRoutineRequestContext.h>
#import <HealthDaemon/HDRemoteStartWorkoutAppRequestContext.h>
#import <HealthDaemon/HDRemoteCompanionUserNotificationRequestContext.h>
#import <HealthDaemon/HDRemoteTinkerOptInRequestContext.h>
#import <HealthDaemon/HDRemoteTinkerPairingRequestContext.h>
#import <HealthDaemon/HDRemoteTinkerEndToEndCloudSyncRequestContext.h>
#import <HealthDaemon/HDWorkoutBuilderSampleQueryServer.h>
#import <HealthDaemon/_HDCarouselSessionAssertion.h>
#import <HealthDaemon/_HDDisableAOTAssertion.h>
#import <HealthDaemon/HDCarouselServicesManager.h>
#import <HealthDaemon/HDCloudSyncCodableMedicalID.h>
#import <HealthDaemon/HDStaticSyncControlServer.h>
#import <HealthDaemon/HDUnknownRecordEntity.h>
#import <HealthDaemon/_HDUnknownRecordEntityEncoder.h>
#import <HealthDaemon/HDSQLiteJoinClause.h>
#import <HealthDaemon/HDClinicalAccountEntity.h>
#import <HealthDaemon/HDDatabaseCorruptionTTRPrompter.h>
#import <HealthDaemon/_HDDefaultDatabaseCorruptionDataSource.h>
#import <HealthDaemon/HDDemoDataGeneratorState.h>
#import <HealthDaemon/_HDBackgroundRunningAssertion.h>
#import <HealthDaemon/HDBackgroundWorkoutRunner.h>
#import <HealthDaemon/HDUserCharacteristicsManager.h>
#import <HealthDaemon/HDUserCharacteristicSyncEntity.h>
#import <HealthDaemon/HDAWDHealthKitConcurrentCalendarItem.h>
#import <HealthDaemon/HDCloudSyncLookupParticipantOperation.h>
#import <HealthDaemon/HDCodableStartWorkoutAppRequest.h>
#import <HealthDaemon/HDAlarmEventEntity.h>
#import <HealthDaemon/HDClientAuthorizationOracle.h>
#import <HealthDaemon/HDFHIRCredentialEntity.h>
#import <HealthDaemon/HDCloudSyncDeleteRecordsOperation.h>
#import <HealthDaemon/HDContributorEntity.h>
#import <HealthDaemon/HDHealthRecordsNotificationManagerMigrationOperation.h>
#import <HealthDaemon/HDBackgroundTask.h>
#import <HealthDaemon/HDBackgroundTaskClient.h>
#import <HealthDaemon/HDBackgroundTaskScheduler.h>
#import <HealthDaemon/HDCloudSyncManagerAcceptSharesTask.h>
#import <HealthDaemon/HDCodableSourceAuthorization.h>
#import <HealthDaemon/HDDiffPrivReporter.h>
#import <HealthDaemon/HDWorkoutBuilderStatisticsDataSource.h>
#import <HealthDaemon/HDHealthPeripheral.h>
#import <HealthDaemon/HDHeartRateVariabilityDataAggregator.h>
#import <HealthDaemon/HDCloudSyncCoordinator.h>
#import <HealthDaemon/HDDemoDataStatisticsSampleGenerator.h>
#import <HealthDaemon/HDHealthRecordsNotificationManager.h>
#import <HealthDaemon/HDOriginalFHIRResourceLastSeenEntity.h>
#import <HealthDaemon/HDWorkoutBuilderPersistedConfiguration.h>
#import <HealthDaemon/HDHeartRateSummaryQueryServer.h>
#import <HealthDaemon/HDCloudSyncSessionContext.h>
#import <HealthDaemon/HDAssociationEntity.h>
#import <HealthDaemon/_HDAssociationInsertionContext.h>
#import <HealthDaemon/_HDAssociationInsertionJournalEntry.h>
#import <HealthDaemon/HDAssociationSyncEntity.h>
#import <HealthDaemon/HDPendingAssociationEntity.h>
#import <HealthDaemon/HDAssociationEntityAssociationPredicate.h>
#import <HealthDaemon/HDAssociationEntityAssociationExistsPredicate.h>
#import <HealthDaemon/HDAssociationEntityIsAssociatedPredicate.h>
#import <HealthDaemon/_HDCorrelationInsertionJournalEntry.h>
#import <HealthDaemon/HDHealthServiceCharacteristic.h>
#import <HealthDaemon/HDCloudSyncRemoveInvalidShareParticipantsOperation.h>
#import <HealthDaemon/HDCodableCoverageRecord.h>
#import <HealthDaemon/HDCloudSyncMedicalIDRecord.h>
#import <HealthDaemon/HDDemoDataBaseSampleGenerator.h>
#import <HealthDaemon/HDDemoDataBaseSampleGeneratorObjectCollection.h>
#import <HealthDaemon/HDStaticSyncTask.h>
#import <HealthDaemon/HDStaticSyncExportTask.h>
#import <HealthDaemon/HDStaticSyncImportTask.h>
#import <HealthDaemon/_HDStaticSyncSession.h>
#import <HealthDaemon/_HDStaticSyncStore.h>
#import <HealthDaemon/HDXPCListener.h>
#import <HealthDaemon/HDCloudSyncCodableRegistry.h>
#import <HealthDaemon/HDCodableMedicalCoding.h>
#import <HealthDaemon/HDTinkerPairedUserInfo.h>
#import <HealthDaemon/HDHealthStoreClient.h>
#import <HealthDaemon/HDWorkoutSessionTaskServer.h>
#import <HealthDaemon/HDSourceStoreServer.h>
#import <HealthDaemon/HDCodableObjectCollection.h>
#import <HealthDaemon/HDCloudSyncCreateZonesOperation.h>
#import <HealthDaemon/HDCodableMedicalIDData.h>
#import <HealthDaemon/HDCloudSyncMedicalIDFetchOperation.h>
#import <HealthDaemon/HDPIIRedactor.h>
#import <HealthDaemon/HDAWDHealthKitWorkout.h>
#import <HealthDaemon/HDOriginalFHIRResourceEntity.h>
#import <HealthDaemon/HDCloudSyncAddSharingParticipantOperation.h>
#import <HealthDaemon/HDCloudSyncRepository.h>
#import <HealthDaemon/HDCloudSyncObserverTaskServer.h>
#import <HealthDaemon/HDCodableRoutinePredictedLocationsResponse.h>
#import <HealthDaemon/HDCloudSyncRequestDataUploadOperation.h>
#import <HealthDaemon/HDCloudSyncZoneIdentifier.h>
#import <HealthDaemon/HDCloudSyncZone.h>
#import <HealthDaemon/HDAlarmEvent.h>
#import <HealthDaemon/HDDatabaseMigrationTransaction.h>
#import <HealthDaemon/HDConceptIndexResetOperation.h>
#import <HealthDaemon/HDUnitPreferencesManager.h>
#import <HealthDaemon/HDUnitPreferencesSyncEntity.h>
#import <HealthDaemon/HDCodableEmergencyContact.h>
#import <HealthDaemon/HDDeviceStoreServer.h>
#import <HealthDaemon/HDCloudSyncCodableProfileIdentifier.h>
#import <HealthDaemon/HDAppSubscription.h>
#import <HealthDaemon/HDOnboardingCompletionManager.h>
#import <HealthDaemon/HDOnboardingCompletionJournalOperation.h>
#import <HealthDaemon/HDFitnessMachineDataCollector.h>
#import <HealthDaemon/HDCloudSyncPipelineStageAcceptShares.h>
#import <HealthDaemon/HDStairClimberData.h>
#import <HealthDaemon/HDSecondaryDevicePairingAgentTaskServer.h>
#import <HealthDaemon/HDSecondaryDevicePairingRequest.h>
#import <HealthDaemon/HDDaemon.h>
#import <HealthDaemon/HDSampleEntity.h>
#import <HealthDaemon/_HDSampleEntityEncoder.h>
#import <HealthDaemon/_HDSampleTypesDeletionEntry.h>
#import <HealthDaemon/HDDaemonConnectionManager.h>
#import <HealthDaemon/HDCodableMedicalRecord.h>
#import <HealthDaemon/HDContributorManager.h>
#import <HealthDaemon/HDIDSPersistentDictionary.h>
#import <HealthDaemon/HDHeartRateControlPoint.h>
#import <HealthDaemon/HDRegionAvailability.h>
#import <HealthDaemon/HDRegionAvailabilityComparator.h>
#import <HealthDaemon/HDWorkoutCondenserControlServer.h>
#import <HealthDaemon/HDCodableAuthorization.h>
#import <HealthDaemon/HDCodableFHIRResource.h>
#import <HealthDaemon/HDDiagnosticManager.h>
#import <HealthDaemon/HDCloudSyncSequenceRecord.h>
#import <HealthDaemon/HDCodableReferenceRange.h>
#import <HealthDaemon/HDUserNotification.h>
#import <HealthDaemon/HDMetadataKeyEntity.h>
#import <HealthDaemon/HDMedicalIDDataMigrator.h>
#import <HealthDaemon/HDDatabaseLegacyJournalFile.h>
#import <HealthDaemon/HDFeatureAvailabilityManager.h>
#import <HealthDaemon/HDCodableFHIRResourceForAPI.h>
#import <HealthDaemon/HDSimpleGraphNode.h>
#import <HealthDaemon/HDCodableNanoSyncChange.h>
#import <HealthDaemon/HDConceptIndexEntity.h>
#import <HealthDaemon/HDCloudSyncDataUploadRequestRecord.h>
#import <HealthDaemon/HDAnchoredObjectQueryServer.h>
#import <HealthDaemon/HDDatabase.h>
#import <HealthDaemon/HDDatabaseVFS.h>
#import <HealthDaemon/HDMigrationManager.h>
#import <HealthDaemon/HDCodableCompanionUserNotificationResponse.h>
#import <HealthDaemon/_HDMirroredProgress.h>
#import <HealthDaemon/HDDemoDataSleepSampleGenerator.h>
#import <HealthDaemon/HDCloudSyncManagerResetTask.h>
#import <HealthDaemon/HDSourceOrderManager.h>
#import <HealthDaemon/_HDCachedSourceOrder.h>
#import <HealthDaemon/_HDSourceOrderTransactionCache.h>
#import <HealthDaemon/HDAppSubscriptionManager.h>
#import <HealthDaemon/HDQuantitySeriesEditorTaskServer.h>
#import <HealthDaemon/HDAWDHealthKitStandHourEvent.h>
#import <HealthDaemon/HDCodableTimestampedKeyValuePair.h>
#import <HealthDaemon/HDAWDHealthKitRoutineTransitionEvent.h>
#import <HealthDaemon/HDDataProvenanceCache.h>
#import <HealthDaemon/HDTreadmillData.h>
#import <HealthDaemon/HDSmoothingTask.h>
#import <HealthDaemon/HDWorkoutLocationSmoother.h>
#import <HealthDaemon/HDRemoteFeatureAvailabilityAssetManager.h>
#import <HealthDaemon/HDEntitlementStoreServer.h>
#import <HealthDaemon/HDCreateWorkoutOperation.h>
#import <HealthDaemon/HDCloudSyncStoreRecord.h>
#import <HealthDaemon/HDMockDaemon.h>
#import <HealthDaemon/HDWorkoutBuilderAssociatedSeriesEntity.h>
#import <HealthDaemon/HDCodableMedicalCodingList.h>
#import <HealthDaemon/HDAWDHealthKitBatteryStateEvent.h>
#import <HealthDaemon/HDSyncEntityIdentifier.h>
#import <HealthDaemon/HDCodableCompanionUserNotificationRequest.h>
#import <HealthDaemon/HDHealthOntologyCountryConfiguration.h>
#import <HealthDaemon/HDClinicalAuthorizationSessionEntity.h>
#import <HealthDaemon/HDCodableDiagnosticTestResult.h>
#import <HealthDaemon/HDCloudSyncValidatePushTargetOperation.h>
#import <HealthDaemon/HDProcessStateManager.h>
#import <HealthDaemon/_HDProcessInfo.h>
#import <HealthDaemon/HDDataEntity.h>
#import <HealthDaemon/_HDDataEntityEncoder.h>
#import <HealthDaemon/_HDDataInsertionJournalEntry.h>
#import <HealthDaemon/_HDDataBatchInsertionJournalEntry.h>
#import <HealthDaemon/_HDDataDeletionJournalEntry.h>
#import <HealthDaemon/HDCodableTinkerOptInRequest.h>
#import <HealthDaemon/HDActiveDataAggregator.h>
#import <HealthDaemon/HDDataAggregationState.h>
#import <HealthDaemon/HDDataAggregationResult.h>
#import <HealthDaemon/_HDAggregationStateKey.h>
#import <HealthDaemon/HDCurrentActivityCacheDemoQueryServer.h>
#import <HealthDaemon/HDDeviceQueryServer.h>
#import <HealthDaemon/HDDemoDataSleepParameters.h>
#import <HealthDaemon/HDDemoDataPerson.h>
#import <HealthDaemon/HDDemoDataWorkoutPrototype.h>
#import <HealthDaemon/HDQuantityDatumPassthroughAggregator.h>
#import <HealthDaemon/HDCodableCompanionUserNotificationConfiguration.h>
#import <HealthDaemon/HDIDSParticipant.h>
#import <HealthDaemon/HDCalorimetryDataCollector.h>
#import <HealthDaemon/HDAWDHealthKitDatabaseLastWeekUsageEvent.h>
#import <HealthDaemon/HDCloudSyncPipelineStageRegisterSubscriptions.h>
#import <HealthDaemon/HDCodableWorkoutEvent.h>
#import <HealthDaemon/HDServiceConnectionManager.h>
#import <HealthDaemon/HDSampleTypesQueryServer.h>
#import <HealthDaemon/HDActivityAWDActivityCompanionSharingEvent.h>
#import <HealthDaemon/HDSyncStoreEntity.h>
#import <HealthDaemon/HDCloudSyncAcceptSharesOperation.h>
#import <HealthDaemon/HDExtendedDatabaseTransaction.h>
#import <HealthDaemon/HDAWDHealthKitWristOnSettings.h>
#import <HealthDaemon/HDActivitySummaryBuilder.h>
#import <HealthDaemon/HDCodableMetadataDictionary.h>
#import <HealthDaemon/HDSwimmingWorkoutEventCollector.h>
#import <HealthDaemon/HDAWDHealthKitAchievementStatistics.h>
#import <HealthDaemon/HDInsertCodableContributorsOperation.h>
#import <HealthDaemon/HDNanoPairingEntity.h>
#import <HealthDaemon/HDDemoDataActivitySampleGenerator.h>
#import <HealthDaemon/_HDDemoDataActivityWorkoutState.h>
#import <HealthDaemon/HDDataEntityInsertionContext.h>
#import <HealthDaemon/HDDemoDataMobilitySampleGenerator.h>
#import <HealthDaemon/HDLiveWorkoutDataSource.h>
#import <HealthDaemon/HDOnboardingCompletionEntity.h>
#import <HealthDaemon/HDOnboardingCompletionEntityEncoder.h>
#import <HealthDaemon/HDOnboardingCompletionSyncEntity.h>
#import <HealthDaemon/HDAsynchronousTaskTree.h>
#import <HealthDaemon/HDAsynchronousTask.h>
#import <HealthDaemon/HDWorkoutEntity.h>
#import <HealthDaemon/_HDWorkoutEntityEncoder.h>
#import <HealthDaemon/HDActivityCacheActiveSourceCalculator.h>
#import <HealthDaemon/HDHeartRateService.h>
#import <HealthDaemon/HDCloudSyncPipeline.h>
#import <HealthDaemon/HDEntityEncoder.h>
#import <HealthDaemon/HDSessionAssertionWrapper.h>
#import <HealthDaemon/HDSessionAssertionGroup.h>
#import <HealthDaemon/HDCodableBinarySample.h>
#import <HealthDaemon/_HDFTMProducerMetricTracker.h>
#import <HealthDaemon/HDFitnessMachineDataProducer.h>
#import <HealthDaemon/HDCloudSyncPipelineStageWaitForDeviceToDeviceEncryptionAvailability.h>
#import <HealthDaemon/HDMetadataValueEntity.h>
#import <HealthDaemon/HDMetadataValueStatement.h>
#import <HealthDaemon/HDMetadataValueEntityPredicate.h>
#import <HealthDaemon/HDAWDHealthKitClinicalOntologyIndexingEvent.h>
#import <HealthDaemon/HDCurrentActivitySummaryHelper.h>
#import <HealthDaemon/HDDataProvenanceManager.h>
#import <HealthDaemon/_HDDataProvenanceKey.h>
#import <HealthDaemon/_HDAppAssertion.h>
#import <HealthDaemon/HDSeriesSampleEntity.h>
#import <HealthDaemon/HDQuantityDatum.h>
#import <HealthDaemon/HDQuantityAggregationResult.h>
#import <HealthDaemon/HDAWDHealthKitWristEvent.h>
#import <HealthDaemon/HDSeriesBuilderServer.h>
#import <HealthDaemon/HDSourceManager.h>
#import <HealthDaemon/HDCloudSyncPipelineStageReset.h>
#import <HealthDaemon/HDAssertion.h>
#import <HealthDaemon/HDCloudSyncCodableSequence.h>
#import <HealthDaemon/HDKeyValueDomainTaskServer.h>
#import <HealthDaemon/HDXPCEventPublisher.h>
#import <HealthDaemon/HDCloudSyncDisableSyncLocallyOperation.h>
#import <HealthDaemon/HDCloudSyncSaveRepairedRecordsOperation.h>
#import <HealthDaemon/HDCodableCoverageClassification.h>
#import <HealthDaemon/HDInsertValuesToQuantitySampleSeriesOperation.h>
#import <HealthDaemon/HDSleepAlarmAWDSleepAlarmMonthlyConsistencyEvent.h>
#import <HealthDaemon/HDAppExtensionAssertion.h>
#import <HealthDaemon/HDJournalChapterEnumerator.h>
#import <HealthDaemon/HDCodableNanoSyncStatus.h>
#import <HealthDaemon/HDFitnessMachineCharacteristicField.h>
#import <HealthDaemon/HDFitnessMachineCharacteristicUInt8Field.h>
#import <HealthDaemon/HDFitnessMachineCharacteristicUInt16Field.h>
#import <HealthDaemon/HDFitnessMachineCharacteristicInt16Field.h>
#import <HealthDaemon/HDFitnessMachineCharacteristicUInt24Field.h>
#import <HealthDaemon/HDFitnessMachineCharacteristicDoubleField.h>
#import <HealthDaemon/HDConceptIndexEntry.h>
#import <HealthDaemon/HDCloudSyncManagerStatusTask.h>
#import <HealthDaemon/HDCurrentActivitySummaryQueryServer.h>
#import <HealthDaemon/HDActivityAWDActivityExerciseMinuteHour.h>
#import <HealthDaemon/HDCloudSyncPushStoreOperation.h>
#import <HealthDaemon/HDDemoDataGeneratorConfiguration.h>
#import <HealthDaemon/HDCodableAuthorizationCompleteMessage.h>
#import <HealthDaemon/HDSQLiteEntityForeignKey.h>
#import <HealthDaemon/HDCoreMotionDataCollector.h>
#import <HealthDaemon/HDNanoSyncSession.h>
#import <HealthDaemon/HDSQLiteEntity.h>
#import <HealthDaemon/HDCloudSyncPullChangeRecordOperation.h>
#import <HealthDaemon/HDGymKitDataSource.h>
#import <HealthDaemon/HDDefaultWorkoutSessionController.h>
#import <HealthDaemon/HDProfile.h>
#import <HealthDaemon/HDWorkoutEventEntity.h>
#import <HealthDaemon/HDCloudSyncFinishOwnerTakeoverOperation.h>
#import <HealthDaemon/HDAllergyRecordEntity.h>
#import <HealthDaemon/_HDAllergyRecordEntityEncoder.h>
#import <HealthDaemon/HDHeartbeatDatum.h>
#import <HealthDaemon/HDHeartbeatSequenceSensorDatum.h>
#import <HealthDaemon/HDHeartbeatSequenceDataAggregator.h>
#import <HealthDaemon/HDActivityCacheManager.h>
#import <HealthDaemon/HDWorkoutRouteBuilderServer.h>
#import <HealthDaemon/HDFitnessMachineDataCharacteristicBase.h>
#import <HealthDaemon/HDMedicalIDStoreTaskServer.h>
#import <HealthDaemon/HDDatabaseTransactionContext.h>
#import <HealthDaemon/HDMutableDatabaseTransactionContext.h>
#import <HealthDaemon/HDCloudSyncCodableRegisteredStore.h>
#import <HealthDaemon/HDDatabaseJournal.h>
#import <HealthDaemon/HDDevicelessProfile.h>
#import <HealthDaemon/HDSyncSession.h>
#import <HealthDaemon/HDActiveQuantityDataAggregator.h>
#import <HealthDaemon/HDAWDHealthKitNotificationView.h>
#import <HealthDaemon/HDSeriesBuilderEntity.h>
#import <HealthDaemon/HDFreezeSeriesOperation.h>
#import <HealthDaemon/HDQuietModeManager.h>
#import <HealthDaemon/_HDDataEntitySyncMessageBuilder.h>
#import <HealthDaemon/HDFitnessMachineSimulatorSupport.h>
#import <HealthDaemon/_HDAWDPeriodicAction.h>
#import <HealthDaemon/HDAWDSubmissionManager.h>
#import <HealthDaemon/_HDSleepReportResult.h>
#import <HealthDaemon/_HDSleepReportBuilder.h>
#import <HealthDaemon/HDElectrocardiogramQueryServer.h>
#import <HealthDaemon/HDDNDModeAssertionService.h>
#import <HealthDaemon/_HDSQLiteEntityColumn.h>
#import <HealthDaemon/HDCodableCodedValue.h>
#import <HealthDaemon/HDDataEntityDeletionContext.h>
#import <HealthDaemon/HDCodableMedicationOrder.h>
#import <HealthDaemon/HDQuantitySeriesManager.h>
#import <HealthDaemon/HDWorkoutPluginDaemonExtension.h>
#import <HealthDaemon/HDAuthorizationManager.h>
#import <HealthDaemon/_HDAuthorizationRequest.h>
#import <HealthDaemon/_HDAuthorizationRequestGroup.h>
#import <HealthDaemon/_HDObjectAuthorizationRequest.h>
#import <HealthDaemon/_HDObjectAuthorizationPromptSession.h>
#import <HealthDaemon/_HDRemoteAuthorizationRecord.h>
#import <HealthDaemon/_HDRemoteAuthorizationRequestRecord.h>
#import <HealthDaemon/HDDatabaseChangesQueryServer.h>
#import <HealthDaemon/HDCodableSharingSetupInvitationToken.h>
#import <HealthDaemon/HDCloudSyncMasterRecord.h>
#import <HealthDaemon/HDNanoSyncControlServer.h>
#import <HealthDaemon/HDAWDHealthKitActivityRingEvent.h>
#import <HealthDaemon/HDAssertionManager.h>
#import <HealthDaemon/_HDAssertionRecord.h>
#import <HealthDaemon/HDDemoDataAudioExposureSampleGenerator.h>
#import <HealthDaemon/HDFitnessMachineStatus.h>
#import <HealthDaemon/HDCodableSource.h>
#import <HealthDaemon/HDCloudSyncMedicalIDPushOperation.h>
#import <HealthDaemon/_HDAlertSuppressorAssertion.h>
#import <HealthDaemon/HDAlertSuppressor.h>
#import <HealthDaemon/HDElectrocardiogramSessionServer.h>
#import <HealthDaemon/HDCloudSyncOwnerIdentifier.h>
#import <HealthDaemon/HDTinkerPrivacyAlertCoordinator.h>
#import <HealthDaemon/HDCodableStaticSyncChangeSet.h>
#import <HealthDaemon/HDBodySensorLocation.h>
#import <HealthDaemon/HDXPCEventManager.h>
#import <HealthDaemon/HDDemoDataHealthDocumentSampleGenerator.h>
#import <HealthDaemon/HDAppLauncher.h>
#import <HealthDaemon/HDClientKeepAliveAssertion.h>
#import <HealthDaemon/HDDemoDataBloodSampleGenerator.h>
#import <HealthDaemon/HDCodableCoverageClassificationList.h>
#import <HealthDaemon/HDAnalyticsWriter.h>
#import <HealthDaemon/HDFitnessFriendActivitySnapshotEntity.h>
#import <HealthDaemon/_HDFitnessFriendActivitySnapshotEntityEncoder.h>
#import <HealthDaemon/HDCloudSyncManager.h>
#import <HealthDaemon/_HDSortedSampleIteratorInternalPager.h>
#import <HealthDaemon/HDCloudSyncSynchronizeProfilesOperation.h>
#import <HealthDaemon/HDCodableEntityIdentifier.h>
#import <HealthDaemon/HDPairedSyncManager.h>
#import <HealthDaemon/HDCloudSyncPipelineStageCheckForRequiredProfileDeletion.h>
#import <HealthDaemon/HDMedicationDispenseRecordEntity.h>
#import <HealthDaemon/_HDMedicationDispenseRecordEntityEncoder.h>
#import <HealthDaemon/HDCloudSyncFilterZonesOperation.h>
#import <HealthDaemon/HDConceptStoreTaskServer.h>
#import <HealthDaemon/HDDatabaseJournalDatabase.h>
#import <HealthDaemon/HDCodableDevice.h>
#import <HealthDaemon/HDDiagnosticTestResultEntity.h>
#import <HealthDaemon/_HDDiagnosticTestResultEntityEncoder.h>
#import <HealthDaemon/HDWatchAppStateMonitor.h>
#import <HealthDaemon/HDCloudSyncTarget.h>
#import <HealthDaemon/HDProfileStoreServer.h>
#import <HealthDaemon/HDSampleCountQueryServer.h>
#import <HealthDaemon/HDObserverQueryServer.h>
#import <HealthDaemon/HDContributorReference.h>
#import <HealthDaemon/HDUnknownHealthService.h>
#import <HealthDaemon/HDAWDHealthKitApplicationLaunchEvent.h>
#import <HealthDaemon/HDConceptIndexManager.h>
#import <HealthDaemon/HDCloudSyncDeleteSequenceOperation.h>
#import <HealthDaemon/HDCloudSyncPipelineStage.h>
#import <HealthDaemon/HDMedicalIDSyncEntity.h>
#import <HealthDaemon/HDDatabaseMigrationStep.h>
#import <HealthDaemon/HDActivityAWDActivityAchievementCountEvent.h>
#import <HealthDaemon/HDSQLiteMetaEntity.h>
#import <HealthDaemon/HDMaintenanceWorkCoordinatorBlockDispatcher.h>
#import <HealthDaemon/HDDemoDataGeneratorWorkoutConfiguration.h>
#import <HealthDaemon/_HDHeartRateRecoveryAssertion.h>
#import <HealthDaemon/HDHeartRateRecoveryManager.h>
#import <HealthDaemon/HDCodableQuantitySeriesDatum.h>
#import <HealthDaemon/HDWorkoutBuilderAssociatedObjectEntity.h>
#import <HealthDaemon/HDNotificationManager.h>
#import <HealthDaemon/HDCodableQuantitySample.h>
#import <HealthDaemon/HDSynchronousTaskGroup.h>
#import <HealthDaemon/HDAWDHealthKitRoutineLocation.h>
#import <HealthDaemon/HDCodableCategorySample.h>
#import <HealthDaemon/HDHeartbeatSeriesQueryServer.h>
#import <HealthDaemon/HDCodableActivityCache.h>
#import <HealthDaemon/HDDatabaseTransactionStatistics.h>
#import <HealthDaemon/HDDatabaseTransactionContextStatistics.h>
#import <HealthDaemon/HDDataCollectorAggregatorRecord.h>
#import <HealthDaemon/HDDataCollectorMultiplexer.h>
#import <HealthDaemon/HDCodableMedicalDateInterval.h>
#import <HealthDaemon/HDCodableCoding.h>
#import <HealthDaemon/HDDataOriginProvenance.h>
#import <HealthDaemon/HDTMockCMNatalieData.h>
#import <HealthDaemon/HDTMockCMNatalimeter.h>
#import <HealthDaemon/HDMaintenanceWorkCoordinator.h>
#import <HealthDaemon/HDMaintenanceOperation.h>
#import <HealthDaemon/_HDMaintenanceWorkCoordinatorAsynchronousOperation.h>
#import <HealthDaemon/_HDMaintenanceWorkCoordinatorSynchronousOperation.h>
#import <HealthDaemon/HDCodableOnboardingCompletion.h>
#import <HealthDaemon/HDHealthStoreEndpoint.h>
#import <HealthDaemon/HDHealthStoreErrorEndpoint.h>
#import <HealthDaemon/HDCodableClinicalRecord.h>
#import <HealthDaemon/HDDemoDataFoodDatabase.h>
#import <HealthDaemon/HDCloudSyncControlTaskServer.h>
#import <HealthDaemon/HDCodableMedicationRecord.h>
#import <HealthDaemon/HDWorkoutSessionEventEntity.h>
#import <HealthDaemon/HDCloudSyncManagerDisableAndDeleteTask.h>
#import <HealthDaemon/HDCodableTinkerEndToEndCloudSyncRequest.h>
#import <HealthDaemon/HDWorkoutRouteQueryServer.h>
#import <HealthDaemon/HDCloudSyncCodableStore.h>
#import <HealthDaemon/HDCodableSemanticDate.h>
#import <HealthDaemon/HDGymKitMetricsDataSource.h>
#import <HealthDaemon/HDUnitStringEntity.h>
#import <HealthDaemon/HDAWDHealthKitNotificationResponseFlags.h>
#import <HealthDaemon/HDCodableAllergyRecord.h>
#import <HealthDaemon/HDCodableActivityStatisticsQuantityInfo.h>
#import <HealthDaemon/HDFitnessMachinePairingManager.h>
#import <HealthDaemon/HDFitnessFriendAchievementEntity.h>
#import <HealthDaemon/_HDFitnessFriendAchievementEntityEncoder.h>
#import <HealthDaemon/HDHealthEntity.h>
#import <HealthDaemon/HDPluginManager.h>
#import <HealthDaemon/HDAWDHealthKitRoutineLocationVisitEvent.h>
#import <HealthDaemon/HDDemoDataHeartSampleGenerator.h>
#import <HealthDaemon/HDDiagnosticStoreServer.h>
#import <HealthDaemon/HDStatisticsCalculatorEntity.h>
#import <HealthDaemon/HDQuantitySeriesBuilderTaskServer.h>
#import <HealthDaemon/HDQueryControlServer.h>
#import <HealthDaemon/HDCloudSyncPipelineStageDisableSyncLocally.h>
#import <HealthDaemon/HDCodableNanoSyncChangeSet.h>
#import <HealthDaemon/HDClinicalDeletedAccountEntity.h>
#import <HealthDaemon/HDCloudSyncManagerSyncTask.h>
#import <HealthDaemon/HDActivityCacheDataSource.h>
#import <HealthDaemon/HDXPCAlarmScheduler.h>
#import <HealthDaemon/HDXPCAlarmEvent.h>
#import <HealthDaemon/HDCodableLocationSeries.h>
#import <HealthDaemon/HDCloudSyncShareParticipantManagerTaskServer.h>
#import <HealthDaemon/HDDemoDataBodySampleGenerator.h>
#import <HealthDaemon/HDCodableClinicalDeletedAccount.h>
#import <HealthDaemon/HDLocationSeriesSampleEntity.h>
#import <HealthDaemon/_HDLocationSeriesSampleEntityEncoder.h>
#import <HealthDaemon/_HDLocationInsertionJournalEntry.h>
#import <HealthDaemon/HDHealthOntologyConfiguration.h>
#import <HealthDaemon/HDQuantitySampleSeriesEntity.h>
#import <HealthDaemon/HDSeriesFreezeResult.h>
#import <HealthDaemon/_HDQuantitySampleSeriesEntityEncoder.h>
#import <HealthDaemon/HDSimpleGraphDatabase.h>
#import <HealthDaemon/HDQueryServerClientState.h>
#import <HealthDaemon/HDMetadataManager.h>
#import <HealthDaemon/HDCodableAllergyReaction.h>
#import <HealthDaemon/HDCloudSyncOperationConfiguration.h>
#import <HealthDaemon/HDDataTypeSourceOrderEntity.h>
#import <HealthDaemon/HDDataTypeSourceOrderSyncEntity.h>
#import <HealthDaemon/HDMultiTypeSortedSampleIterator.h>
#import <HealthDaemon/HDSleepScheduleEntity.h>
#import <HealthDaemon/_HDSleepScheduleEntityEncoder.h>
#import <HealthDaemon/_HDStatisticsSyntheticQuantityType.h>
#import <HealthDaemon/HDAnalyticsSubmissionCoordinator.h>
#import <HealthDaemon/HDPassiveDataAggregator.h>
#import <HealthDaemon/HDReadAuthorizationStatus.h>
#import <HealthDaemon/HDFitnessMachineConnectionInitiatorServer.h>
#import <HealthDaemon/HDDataAggregator.h>
#import <HealthDaemon/HDDataAggregatorConfiguration.h>
#import <HealthDaemon/HDDataCollectorState.h>
#import <HealthDaemon/HDDataCollectorRecord.h>
#import <HealthDaemon/HDDataCollectorSensorDatum.h>
#import <HealthDaemon/HDAgeGatingManager.h>
#import <HealthDaemon/HDCodableCategoryDomainDictionary.h>
#import <HealthDaemon/HDAWDHealthKitWeeklySummaryDetail.h>
#import <HealthDaemon/HDCodableRoutineRequestMessage.h>
#import <HealthDaemon/HDFitnessMachineSession.h>
#import <HealthDaemon/_HDUserDefaultUpdatedJournalEntry.h>
#import <HealthDaemon/_HDUserDefaultRemovedJournalEntry.h>
#import <HealthDaemon/_HDSetCharacteristicJournalEntry.h>
#import <HealthDaemon/_HDActivityCacheUpdateJournalEntry.h>
#import <HealthDaemon/_HDAchievementInsertionJournalEntry.h>
#import <HealthDaemon/_HDAchievementProgressLocalJournalEntry.h>
#import <HealthDaemon/HDCloudSyncPipelineStageMedicalID.h>
#import <HealthDaemon/HDCodableCDADocumentSample.h>
#import <HealthDaemon/HDContentProtectionManager.h>
#import <HealthDaemon/_HDContentProtectionObserverWrapper.h>
#import <HealthDaemon/HDAWDHealthKitExperimentalCondition.h>
#import <HealthDaemon/HDCodableDiagnosticTestReport.h>
#import <HealthDaemon/HDAuthorizationStoreWriteServer.h>
#import <HealthDaemon/HDCloudSyncContext.h>
#import <HealthDaemon/HDCodableClinicalGateway.h>
#import <HealthDaemon/HDDataManager.h>
#import <HealthDaemon/_HDDataManagerDeletionJournalEntry.h>
#import <HealthDaemon/HDDataDeletionConfiguration.h>
#import <HealthDaemon/HDAuthorizationServer.h>
#import <HealthDaemon/HDCloudSyncOperation.h>
#import <HealthDaemon/HDActivitySummaryQueryServer.h>
#import <HealthDaemon/HDCloudSyncRemoveSharingParticipantsOperation.h>
#import <HealthDaemon/_HDDataFaker.h>
#import <HealthDaemon/_HDDemoDataModule.h>
#import <HealthDaemon/_HDDemoOdometerModule.h>
#import <HealthDaemon/_HDDemoSwimmingModule.h>
#import <HealthDaemon/_HDDemoStepDataModule.h>
#import <HealthDaemon/_HDDemoCalorieDataModule.h>
#import <HealthDaemon/_HDDemoHeartRateDataModule.h>
#import <HealthDaemon/HDKeyValueDomain.h>
#import <HealthDaemon/HDMultiTypeSampleQueryServer.h>
#import <HealthDaemon/HDSQLiteVFS.h>
#import <HealthDaemon/HDQueryServer.h>
#import <HealthDaemon/HDHealthOntologyManagerConceptSampleRelationship.h>
#import <HealthDaemon/HDHealthOntologyManager.h>
#import <HealthDaemon/HDAudioExposureAggregator.h>
#import <HealthDaemon/HDSimpleGraphRelationship.h>
#import <HealthDaemon/HDQuantitySampleValueEnumerator.h>
#import <HealthDaemon/HDFreezeQuantitySampleSeriesOperation.h>
#import <HealthDaemon/_HDHealthServiceDataUpdate.h>
#import <HealthDaemon/HDNanoHealthNotification.h>
#import <HealthDaemon/HDWorkoutObserverServer.h>
#import <HealthDaemon/HDCodableCodedQuantity.h>
#import <HealthDaemon/HDFitnessMachineSessionRecoveryConfiguration.h>
#import <HealthDaemon/HDCodableQuantity.h>
#import <HealthDaemon/HDActivityAWDActivityFitnessDailyEvent.h>
#import <HealthDaemon/HDJournalableOperation.h>
#import <HealthDaemon/HDCloudSyncCodableChange.h>
#import <HealthDaemon/HDCodableECGSample.h>
#import <HealthDaemon/HDSyncPredicate.h>
#import <HealthDaemon/HDDiscardWorkoutOperation.h>
#import <HealthDaemon/HDCodableProcedureRecord.h>
#import <HealthDaemon/HDCodableObjectAuthorization.h>
#import <HealthDaemon/HDCloudSyncFetchChangeRecordsForZonesOperation.h>
#import <HealthDaemon/HDSleepAlarmAWDSleepAlarmStatistics.h>
#import <HealthDaemon/HDProfileManager.h>
#import <HealthDaemon/HDObjectAuthorizationEntity.h>
#import <HealthDaemon/HDObjectAuthorizationSyncEntity.h>
#import <HealthDaemon/HDObjectAuthorizationRecord.h>
#import <HealthDaemon/HDObjectAuthorizationJournalEntry.h>
#import <HealthDaemon/HDCodableWorkout.h>
#import <HealthDaemon/HDSimpleGraphAttribute.h>
#import <HealthDaemon/HDCodableProvenance.h>
#import <HealthDaemon/HDQuantitySeriesSampleQueryServer.h>
#import <HealthDaemon/HDCodableClinicalAccount.h>
#import <HealthDaemon/HDDataExternalSyncIdentifierEntity.h>
#import <HealthDaemon/HDDataExternalSyncIdentifierEntityPredicate.h>
#import <HealthDaemon/HDCloudSyncShareToParticipantOperation.h>
#import <HealthDaemon/HDSkiingWorkoutEventCollector.h>
#import <HealthDaemon/HDVaccinationRecordEntity.h>
#import <HealthDaemon/_HDVaccinationRecordEntityEncoder.h>
#import <HealthDaemon/HDCodableMessageVersion.h>
#import <HealthDaemon/HDCodableGeneratedObjectCollection.h>
#import <HealthDaemon/HDCodableObjectSourceAuthorization.h>
#import <HealthDaemon/HDCloudSyncStore.h>
#import <HealthDaemon/HDOdometerDataCollector.h>
#import <HealthDaemon/HDJournalEntry.h>
#import <HealthDaemon/HDCloudSyncDisableAndDeleteOperation.h>
#import <HealthDaemon/HDCloudSyncMedicalIDPersistOperation.h>
#import <HealthDaemon/HDActivityCacheEntity.h>
#import <HealthDaemon/_HDActivityCacheEntityEncoder.h>
#import <HealthDaemon/HDNotificationStoreServer.h>
#import <HealthDaemon/HDOntologyLifecycleManager.h>
#import <HealthDaemon/HDGymKitWorkoutSessionController.h>
#import <HealthDaemon/HDDistinctByKeyPathsIterator.h>
#import <HealthDaemon/HDMedicalRecordEntity.h>
#import <HealthDaemon/_HDMedicalRecordEntityEncoder.h>
#import <HealthDaemon/HDCloudSyncPipelineStagePrepareForSharing.h>
#import <HealthDaemon/HDDatabaseSchemaManager.h>
#import <HealthDaemon/HDCloudSyncRepairStoreRecordsOperation.h>
#import <HealthDaemon/HDConditionRecordEntity.h>
#import <HealthDaemon/_HDConditionRecordEntityEncoder.h>
#import <HealthDaemon/HDBatteryService.h>
#import <HealthDaemon/HDActivityAWDActivityCompanionInvitationEvent.h>
#import <HealthDaemon/HDAWDHealthKitIngestionLatencyEvent.h>
#import <HealthDaemon/HDDemoDataGenerator.h>
#import <HealthDaemon/HDCloudSyncResetOperation.h>
#import <HealthDaemon/HDCodableAllergyReactionList.h>
#import <HealthDaemon/HDPowerSavingModeManager.h>
#import <HealthDaemon/HDCodableRoutineScenarioTriggeredRequest.h>
#import <HealthDaemon/HDCodableTinkerEndToEndCloudSyncResponse.h>
#import <HealthDaemon/HDAuthorizationStoreReadServer.h>
#import <HealthDaemon/HDCodableCorrelation.h>
#import <HealthDaemon/HDRestorableAlarmScheduler.h>
#import <HealthDaemon/HDAccountOwnerEntity.h>
#import <HealthDaemon/_HDAccountOwnerEntityEncoder.h>
#import <HealthDaemon/HDDeviceManager.h>
#import <HealthDaemon/HDCodableRoutineResponseMessage.h>
#import <HealthDaemon/HDWorkoutSessionConfiguration.h>
#import <HealthDaemon/HDStatisticsCollectionQueryServer.h>
#import <HealthDaemon/_HDStatisticsCollectionQueryPendingQuantity.h>
#import <HealthDaemon/_HDStatisticsCollectionQueryPendingSeries.h>
#import <HealthDaemon/HDTaskServerRegistry.h>
#import <HealthDaemon/HDActivityCacheStatisticsBuilder.h>
#import <HealthDaemon/HDCloudSyncCompoundOperation.h>
#import <HealthDaemon/HDStepClimberData.h>
#import <HealthDaemon/HDCodableSyncAnchorRange.h>
#import <HealthDaemon/HDSleepAlarmAWDSleepAlarmNightEvent.h>
#import <HealthDaemon/HDStatisticsCollectionCalculatorDefaultSourceOrderProvider.h>
#import <HealthDaemon/HDLegacyClinicalCredentialManager.h>
#import <HealthDaemon/HDDaemonSyncEntityManager.h>
#import <HealthDaemon/HDDateRangeQueryServer.h>
#import <HealthDaemon/HDSeriesQuantityEventObserver.h>
#import <HealthDaemon/HDHFDataStore.h>
#import <HealthDaemon/HDInsertDeleteAndAssociateObjectsOperation.h>
#import <HealthDaemon/HDOntologyAssetManager.h>
#import <HealthDaemon/HDMedicalIDSetupStatusTaskServer.h>
#import <HealthDaemon/HDCloudSyncStartSequenceOperation.h>
#import <HealthDaemon/HDCloudSyncPipelineStageDisableAndDelete.h>
#import <HealthDaemon/HDCloudSyncManagerShowTask.h>
#import <HealthDaemon/HDAWDHealthKitNotificationEvent.h>
#import <HealthDaemon/HDCodableContributor.h>
#import <HealthDaemon/HDCorrelationQueryServer.h>
#import <HealthDaemon/HDAutoBugCaptureReporter.h>
#import <HealthDaemon/HDCorrelationSampleEntity.h>
#import <HealthDaemon/_HDCorrelationSampleEntityEncoder.h>
#import <HealthDaemon/HDQuantityDistributionCalculator.h>
#import <HealthDaemon/HDAWDHealthKitCoachingEvent.h>
#import <HealthDaemon/HDCloudSyncDeleteEmptyZonesOperation.h>
#import <HealthDaemon/HDWorkoutBuilderEntity.h>
#import <HealthDaemon/HDWorkoutBuilderAssociatedSamplePredicate.h>
#import <HealthDaemon/HDWorkoutBuilderAssociatedSampleTemporaryTableEntity.h>
#import <HealthDaemon/HDDemoDataFormula.h>
#import <HealthDaemon/HDQuantitySampleSeriesDataEnumerator.h>
#import <HealthDaemon/HDServiceEntity.h>
#import <HealthDaemon/_HDServiceEntityEncoder.h>
#import <HealthDaemon/HDCodableDateComponents.h>
#import <HealthDaemon/HDSyncAnchorMap.h>
#import <HealthDaemon/HDDataCollector.h>
#import <HealthDaemon/HDLiveDataCollector.h>
#import <HealthDaemon/HDAggregateDataCollector.h>
#import <HealthDaemon/HDDatabasePruningManager.h>
#import <HealthDaemon/HDConceptIndexManagerState.h>
#import <HealthDaemon/HDRestorableAlarm.h>
#import <HealthDaemon/HDCodableVaccinationRecord.h>
#import <HealthDaemon/HDCodableMedicalCodingListList.h>
#import <HealthDaemon/HDFitnessMachineConnectionServer.h>
#import <HealthDaemon/HDFitnessFriendWorkoutEntity.h>
#import <HealthDaemon/_HDFitnessFriendWorkoutEntityEncoder.h>
#import <HealthDaemon/HDAWDHealthKitClinicalOntologyDownloadEvent.h>
#import <HealthDaemon/HDDemoDataSymptomsSampleGenerator.h>
#import <HealthDaemon/HDDemoManager.h>
#import <HealthDaemon/HDSQLitePredicate.h>
#import <HealthDaemon/HDSQLiteFalsePredicate.h>
#import <HealthDaemon/HDSQLiteTruePredicate.h>
#import <HealthDaemon/HDSQLitePropertyPredicate.h>
#import <HealthDaemon/HDSQLiteComparisonPredicate.h>
#import <HealthDaemon/_HDSQLiteComparisonPredicateLikeWithEscape.h>
#import <HealthDaemon/_HDSQLiteComparisonPredicateIfNull.h>
#import <HealthDaemon/_HDSQLiteComparisonPredicateCoalesce.h>
#import <HealthDaemon/HDSQLiteContainsPredicate.h>
#import <HealthDaemon/HDSQLiteNullPredicate.h>
#import <HealthDaemon/HDSQLiteCompoundPredicate.h>
#import <HealthDaemon/HDSQLiteRawPredicate.h>
#import <HealthDaemon/HDSQLiteJoinPredicate.h>
#import <HealthDaemon/HDStatisticsCollectionCalculator.h>
#import <HealthDaemon/HDBatchedQueryServer.h>
#import <HealthDaemon/HDClinicalRecordEntity.h>
#import <HealthDaemon/_HDClinicalRecordEntityEncoder.h>
#import <HealthDaemon/HDCloudSyncUpdateSharingStatusOperation.h>
#import <HealthDaemon/HDDataEntityEnumerator.h>
#import <HealthDaemon/HDCurrentActivityCacheQueryServer.h>
#import <HealthDaemon/_HDHealthServiceWriteOperation.h>
#import <HealthDaemon/HDHealthService.h>
#import <HealthDaemon/HDConceptIndexer.h>
#import <HealthDaemon/HDDaemonTransaction.h>
#import <HealthDaemon/HDFeatureAvailabilityStoreServer.h>
#import <HealthDaemon/HDDemoDataManager.h>
#import <HealthDaemon/HDAppleExerciseTimeDataAggregator.h>
#import <HealthDaemon/HDBackgroundObservationServerExtension.h>
#import <HealthDaemon/HDCodableWorkoutConfiguration.h>
#import <HealthDaemon/HDWorkoutRouteBuilderEntity.h>
#import <HealthDaemon/HDCodableRoutineLocationRequest.h>
#import <HealthDaemon/HDDevicePowerMonitor.h>
#import <HealthDaemon/HDCloudSyncPullSequenceOperation.h>
#import <HealthDaemon/HDCloudSyncManagerTask.h>
#import <HealthDaemon/HDCloudSyncManagerTaskQueue.h>
#import <HealthDaemon/HDCloudSyncPipelineStageFetch.h>
#import <HealthDaemon/HDWorkoutSessionEntity.h>
#import <HealthDaemon/HDCloudSyncLeaveAllSharesOperation.h>
#import <HealthDaemon/HDActivityCacheHeartRateStatisticsBuilder.h>
#import <HealthDaemon/HDWorkoutBasicDataSource.h>
#import <HealthDaemon/HDCloudSyncSession.h>
#import <HealthDaemon/HDTTRPromptController.h>
#import <HealthDaemon/HDEurotasService.h>
#import <HealthDaemon/HDCloudSyncRegisterSubscriptionsOperation.h>
#import <HealthDaemon/HDWorkoutBuilderServer.h>
#import <HealthDaemon/HDActivityDemoDataStore.h>
#import <HealthDaemon/HDKeyValueEntity.h>
#import <HealthDaemon/HDProtectedKeyValueEntity.h>
#import <HealthDaemon/HDUnprotectedKeyValueEntity.h>
#import <HealthDaemon/_HDKeyValueEntityEncoder.h>
#import <HealthDaemon/HDKeyValueSyncEntity.h>
#import <HealthDaemon/HDUserDefaultsSyncEntity.h>
#import <HealthDaemon/_HDKeyValueJournalEntry.h>
#import <HealthDaemon/HDIDSMessageCenter.h>
#import <HealthDaemon/HDIDSOutgoingRequest.h>
#import <HealthDaemon/HDIDSIncomingRequest.h>
#import <HealthDaemon/HDIDSIncomingResponse.h>
#import <HealthDaemon/HDIDSOutgoingResponse.h>
#import <HealthDaemon/HDIDSPBMapping.h>
#import <HealthDaemon/HDIDSMessagePersistentContext.h>
#import <HealthDaemon/HDWorkoutSessionControllerEntity.h>
#import <HealthDaemon/HDCloudSyncDetectSyncDisabledOperation.h>
#import <HealthDaemon/HDAWDHealthKitUserCharacteristics.h>
#import <HealthDaemon/HDQuantityDistributionQueryServer.h>
#import <HealthDaemon/_HDQuantityDateIntervals.h>
#import <HealthDaemon/_HDQuantityIntervalPair.h>
#import <HealthDaemon/_HDSeriesFreezeJournalEntry.h>
#import <HealthDaemon/HDCodableCodedValueCollection.h>
#import <HealthDaemon/HDCodableInspectableValue.h>
#import <HealthDaemon/HDFitnessMachineConnection.h>
#import <HealthDaemon/HDCodableHealthObject.h>
#import <HealthDaemon/HDCodableSleepSchedule.h>
#import <HealthDaemon/HDContributorSyncEntity.h>
#import <HealthDaemon/HDCurrentActivitySummaryDemoQueryServer.h>
#import <HealthDaemon/HDCloudSyncShareSetupMetadata.h>
#import <HealthDaemon/HDDaemonSyncEngine.h>
#import <HealthDaemon/HDWorkoutManager.h>
#import <HealthDaemon/HDDatabaseMigrator.h>
#import <HealthDaemon/HDCodableRoutineLocationVisit.h>
#import <HealthDaemon/HDDeletedSampleEntity.h>
#import <HealthDaemon/_HDDeletedSampleEntityEncoder.h>
#import <HealthDaemon/_HDDeletedSampleInsertionJournalEntry.h>
#import <HealthDaemon/HDCodableTinkerPairingRequest.h>
#import <HealthDaemon/HDActivityAWDActivitySharingSnapshotEvent.h>
#import <HealthDaemon/HDLocationDataCollector.h>
#import <HealthDaemon/HDActivitySummaryQueryHelper.h>
#import <HealthDaemon/HDSyncAnchorEntity.h>
#import <HealthDaemon/HDWorkoutSessionServer.h>
#import <HealthDaemon/HDWorkoutEventCollector.h>
#import <HealthDaemon/HDAutoPauseWorkoutEventCollector.h>
#import <HealthDaemon/HDCloudSyncMedicalIDMergeOperation.h>
#import <HealthDaemon/HDCloudSyncPipelineStagePull.h>
#import <HealthDaemon/HDCloudSyncRegistryRecord.h>
#import <HealthDaemon/HDDataCollectionManager.h>
#import <HealthDaemon/HDDataCollectionObserverState.h>
#import <HealthDaemon/_HDDataCollectionObserverWrapper.h>
#import <HealthDaemon/HDDataCollectionAssertion.h>
#import <HealthDaemon/HDCloudSyncIgnoredErrorsOperation.h>
#import <HealthDaemon/HDCloudSyncCloudState.h>
#import <HealthDaemon/HDAWDHealthKitActivityCacheEvent.h>
#import <HealthDaemon/HDSampleQueryDescription.h>
#import <HealthDaemon/HDDemoDataOtherAndAdditionalSampleGenerator.h>
#import <HealthDaemon/HDStandardTaskServer.h>
#import <HealthDaemon/HDCloudSyncStoreEntity.h>
#import <HealthDaemon/_HDCloudSyncStorePersistableState.h>
#import <HealthDaemon/HDCloudSyncPipelineStageLeaveShares.h>
#import <HealthDaemon/HDCodableMedicalDate.h>
#import <HealthDaemon/HDHeartDailyAnalytics.h>
#import <HealthDaemon/HDSchoolTimeObserver.h>
#import <HealthDaemon/HDClientDataCollectionTaskServer.h>
#import <HealthDaemon/HDAppAssertionManager.h>
#import <HealthDaemon/HDCodableInspectableValueCollection.h>
#import <HealthDaemon/HDDatabaseValueCache.h>
#import <HealthDaemon/HDDatabaseValueCacheTransactionStorage.h>
#import <HealthDaemon/HDNanoSyncStore.h>
#import <HealthDaemon/HDSQLiteOrderingTerm.h>
#import <HealthDaemon/HDHealthStoreServer.h>
#import <HealthDaemon/HDIDSReachabilityOperation.h>
#import <HealthDaemon/HDNanoSyncRestoreSession.h>
#import <HealthDaemon/HDFitnessMachineStateTimer.h>
#import <HealthDaemon/HDFitnessMachineStateTimers.h>
#import <HealthDaemon/HDHealthServicesServer.h>
#import <HealthDaemon/HDCodableFitnessFriendWorkout.h>
#import <HealthDaemon/HDPedometerDataCollector.h>
#import <HealthDaemon/HDAWDHealthKitExperimentalConditionEvent.h>
#import <HealthDaemon/HDCloudSyncSubscriptionRecord.h>
#import <HealthDaemon/HDSQLiteStatement.h>
#import <HealthDaemon/HDWorkoutCondenser.h>
#import <HealthDaemon/_HDWorkoutCondensationConfiguration.h>
#import <HealthDaemon/_HDWorkoutCondenserBufferDatum.h>
#import <HealthDaemon/_HDWorkoutCondenserAnalyticsAccumulator.h>
#import <HealthDaemon/HDClientDataCollectionObservationStateMonitor.h>
#import <HealthDaemon/HDCodableFitnessFriendAchievement.h>
#import <HealthDaemon/HDCodableFHIRIdentifierList.h>
#import <HealthDaemon/HDXPCClient.h>
#import <HealthDaemon/HDCodableMedicationDosageList.h>
#import <HealthDaemon/HDCodableClinicalContact.h>
#import <HealthDaemon/HDDemoDataPathologySampleGenerator.h>
#import <HealthDaemon/HDDemoData.h>
#import <HealthDaemon/HDCloudSyncPipelineStageRequestDataUpload.h>
#import <HealthDaemon/HDCodableUnknownRecord.h>
#import <HealthDaemon/HDPowerAssertion.h>
#import <HealthDaemon/HDCodableNanoSyncMessage.h>
#import <HealthDaemon/HDGymKitSettings.h>
#import <HealthDaemon/HDSQLiteQuery.h>
#import <HealthDaemon/HDSQLiteQueryDescriptor.h>
#import <HealthDaemon/HDCodableAuthorizationRequestMessage.h>
#import <HealthDaemon/HDCoverageRecordEntity.h>
#import <HealthDaemon/_HDCoverageRecordEntityEncoder.h>
#import <HealthDaemon/HDDataCollectorConfiguration.h>
#import <HealthDaemon/HDDaemonSyncMessageHandler.h>
#import <HealthDaemon/HDSharedDataPrivacyNotification.h>
#import <HealthDaemon/HDTaskServerEndpoint.h>
#import <HealthDaemon/HDCodableStringList.h>
#import <HealthDaemon/HDCodableFitnessFriendActivitySnapshot.h>
#import <HealthDaemon/HDCloudSyncHandleMissingManateeIdentityOperation.h>
#import <HealthDaemon/HDCloudSyncFetchZonesOperation.h>
#import <HealthDaemon/HDIdentifierTable.h>
#import <HealthDaemon/HDHealthServiceManager.h>
#import <HealthDaemon/_HDHealthServiceDiscoveryInfo.h>
#import <HealthDaemon/_HDHealthServiceConnectionInfo.h>
#import <HealthDaemon/HDSQLiteStatementCache.h>
#import <HealthDaemon/_HDSQLiteStatementCacheStorage.h>
#import <HealthDaemon/HDCloudSyncConditionalOperation.h>
#import <HealthDaemon/HDSQLiteDatabasePool.h>
#import <HealthDaemon/_HDSQLiteDatabaseWrapper.h>
#import <HealthDaemon/HDSharedDataOptInNotification.h>
#import <HealthDaemon/HDCDASampleEntity.h>
#import <HealthDaemon/_HDCDASampleEntityEncoder.h>
#import <HealthDaemon/HDCloudSyncMarkAllOwnersDisabledOperation.h>
#import <HealthDaemon/HDCloudSyncFetchHeaderRecordsOperation.h>
#import <HealthDaemon/HDDatabaseTransaction.h>
#import <HealthDaemon/HDAppSubscriptionEntity.h>
#import <HealthDaemon/HDAppSubscriptionAppLaunchEntity.h>
#import <HealthDaemon/HDStatisticsCollectionCalculatorDefaultDataSource.h>
#import <HealthDaemon/HDCodableObjectAssociation.h>
#import <HealthDaemon/HDDataSyncEntity.h>
#import <HealthDaemon/HDSampleSyncEntity.h>
#import <HealthDaemon/HDActivityCacheSyncEntity.h>
#import <HealthDaemon/HDCategorySampleSyncEntity.h>
#import <HealthDaemon/HDNotificationCategorySampleSyncEntity.h>
#import <HealthDaemon/HDCorrelationSampleSyncEntity.h>
#import <HealthDaemon/HDQuantitySampleSyncEntity.h>
#import <HealthDaemon/HDWorkoutSyncEntity.h>
#import <HealthDaemon/HDLocationSeriesSyncEntity.h>
#import <HealthDaemon/HDDeletedSampleSyncEntity.h>
#import <HealthDaemon/HDCDASampleSyncEntity.h>
#import <HealthDaemon/HDBinarySampleSyncEntity.h>
#import <HealthDaemon/HDFitnessFriendActivitySnapshotSyncEntity.h>
#import <HealthDaemon/HDFitnessFriendAchievementSyncEntity.h>
#import <HealthDaemon/HDFitnessFriendWorkoutSyncEntity.h>
#import <HealthDaemon/HDSleepScheduleSyncEntity.h>
#import <HealthDaemon/HDECGSampleSyncEntity.h>
#import <HealthDaemon/HDCloudSyncPullStoreOperation.h>
#import <HealthDaemon/HDSQLiteCheckConstraint.h>
#import <HealthDaemon/HDSQLiteRawCheckConstraint.h>
#import <HealthDaemon/_HDSyncAnchorRangeBox.h>
#import <HealthDaemon/HDSyncAnchorRangeMap.h>
#import <HealthDaemon/HDQuantitySampleStatisticsEntity.h>
#import <HealthDaemon/HDCloudSyncComputeTargetsOperation.h>
#import <HealthDaemon/HDPeriodicActivity.h>
#import <HealthDaemon/HDHeartEventSensorDatum.h>
#import <HealthDaemon/HDHeartEventDataAggregator.h>
#import <HealthDaemon/HDTachycardiaDataAggregator.h>
#import <HealthDaemon/HDBradycardiaDataAggregator.h>
#import <HealthDaemon/HDCloudSyncPipelineStageAddSharingParticipant.h>
#import <HealthDaemon/HDCloudSyncManagerRepositoryTask.h>
#import <HealthDaemon/HDCloudSyncValidateZonesOperation.h>
#import <HealthDaemon/HDECGSampleEntity.h>
#import <HealthDaemon/_HDECGSampleEntityEncoder.h>
#import <HealthDaemon/HDWorkoutControlServer.h>
#import <HealthDaemon/HDDeviceEntity.h>
#import <HealthDaemon/HDDeviceSyncEntity.h>
#import <HealthDaemon/HDGymKitWorkoutAnalyticEvent.h>
#import <HealthDaemon/HDFitnessMachineAnalyticsCollector.h>
#import <HealthDaemon/_HDCoreMotionAssertion.h>
#import <HealthDaemon/HDCoreMotionWorkoutInterface.h>
#import <HealthDaemon/HDSampleQueryServer.h>
#import <HealthDaemon/HDCloudSyncPipelineStageRemoveSharingParticipants.h>
#import <HealthDaemon/HDCodableSample.h>
#import <HealthDaemon/HDCodableObjectTypeSourceOrder.h>
#import <HealthDaemon/HDCodableAccountOwner.h>
#import <HealthDaemon/HDFirstPartyWorkoutSessionController.h>
#import <HealthDaemon/HDBTLEHeartRateDataCollector.h>
#import <HealthDaemon/HDSourceRevision.h>
#import <HealthDaemon/HDWorkoutBuilderDataSourceEntity.h>
#import <HealthDaemon/HDDemoDataMindfulnessSampleGenerator.h>
#import <HealthDaemon/HDAWDHealthKitCoachingFeatures.h>
#import <HealthDaemon/HDDemoDataVitalsSampleGenerator.h>
#import <HealthDaemon/HDAWDHealthKitActivityCache.h>
#import <HealthDaemon/HDHeartRateDataAggregator.h>
#import <HealthDaemon/HDHeartRateSensorDatum.h>
#import <HealthDaemon/HDCodableTinkerOptInResponse.h>
#import <HealthDaemon/HDEurotasData.h>
#import <HealthDaemon/HDQuantitySampleEntity.h>
#import <HealthDaemon/_HDQuantitySampleEntityEncoder.h>
#import <HealthDaemon/HDCloudSyncManagerPipelineTask.h>
#import <HealthDaemon/HDAuthorizationEntity.h>
#import <HealthDaemon/HDAuthorizationSyncEntity.h>
#import <HealthDaemon/HDAuthorizationBackupSyncEntity.h>
#import <HealthDaemon/HDAWDHealthKitWorkoutSessionEvent.h>
#import <HealthDaemon/HDCloudSyncSeizeAbandonedStoresOperation.h>
