/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:42:50 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <VideosUI/VideosUI-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface VUICardViewLayoutRecord : NSObject <NSCopying> {

	long long _layoutType;
	long long _gridStyle;
	long long _gridType;

}

@property (assign,nonatomic) long long layoutType;              //@synthesize layoutType=_layoutType - In the implementation block
@property (assign,nonatomic) long long gridStyle;               //@synthesize gridStyle=_gridStyle - In the implementation block
@property (assign,nonatomic) long long gridType;                //@synthesize gridType=_gridType - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(long long)layoutType;
-(BOOL)isEqual:(id)arg1 ;
-(void)setLayoutType:(long long)arg1 ;
-(long long)gridType;
-(long long)gridStyle;
-(void)setGridStyle:(long long)arg1 ;
-(void)setGridType:(long long)arg1 ;
@end

