#import <CMCapture/BWStillImageMetalSDOFRenderer.h>
#import <CMCapture/BWStreamingCVAFilterRendererParameters.h>
#import <CMCapture/BWMatteMediaSuppressionNode.h>
#import <CMCapture/FigMetalExecutionStatus.h>
#import <CMCapture/FigMetalContext.h>
#import <CMCapture/BWStillImageProcessorConfiguration.h>
#import <CMCapture/BWStillImageProcessorOutputRouter.h>
#import <CMCapture/BWStillImageProcessorInput.h>
#import <CMCapture/BWStillImageProcessorController.h>
#import <CMCapture/BWInferenceSchedulerResourceCoordinator.h>
#import <CMCapture/BWVisionInferenceAdapter.h>
#import <CMCapture/BWPhotoDecompressorNode.h>
#import <CMCapture/BWInferenceSchedulerFramebufferBuilder.h>
#import <CMCapture/BWBackPressureNode.h>
#import <CMCapture/BWFaceSegmentsWithLandmarksInferenceConfiguration.h>
#import <CMCapture/BWIrisMovieInfoAndCallback.h>
#import <CMCapture/BWIrisMovieGenerator.h>
#import <CMCapture/BWInferenceSimpleStorage.h>
#import <CMCapture/BWStillImageFocusPixelDisparityNode.h>
#import <CMCapture/BWSimpleCache.h>
#import <CMCapture/BWIrisStillImageMovieMetadataCache.h>
#import <CMCapture/BWMeaningfulSubjectTrackingContext.h>
#import <CMCapture/FigCaptureSphereEndStopCalibrationContext.h>
#import <CMCapture/BWColorLookupCacheEntry.h>
#import <CMCapture/BWInferenceRequirement.h>
#import <CMCapture/BWOverCaptureFanOutNode.h>
#import <CMCapture/BWParallelSplitterNode.h>
#import <CMCapture/BWStillImageCaptureSettings.h>
#import <CMCapture/BWStillImageCaptureStreamSettings.h>
#import <CMCapture/BWStillImageCaptureMetadata.h>
#import <CMCapture/BWInferenceVideoFormatRequirements.h>
#import <CMCapture/BWInferenceVideoFormat.h>
#import <CMCapture/BWPortraitHDRStagingNode.h>
#import <CMCapture/BWMonochromeEffectNode.h>
#import <CMCapture/BWBravoStreamSelector.h>
#import <CMCapture/FigCaptureDeferredPhotoProcessorRequest.h>
#import <CMCapture/BWInferenceVideoScalingProvider.h>
#import <CMCapture/BWInferenceSchedulerGraphInputNode.h>
#import <CMCapture/FigM2MController.h>
#import <CMCapture/FigUtlFaceDetection.h>
#import <CMCapture/BWRenderListAnimator.h>
#import <CMCapture/BWStillImageNodeConfiguration.h>
#import <CMCapture/BWAttachedMediaSwapNode.h>
#import <CMCapture/BWIntermediateJPEGCompressedBufferAssociatedSemaphore.h>
#import <CMCapture/BWIntermediateJPEGCompressor.h>
#import <CMCapture/BWMetadataTimeMachineRequest.h>
#import <CMCapture/BWMetadataTimeMachineMetadataRequest.h>
#import <CMCapture/BWMetadataTimeMachineWaitRequest.h>
#import <CMCapture/BWMetadataTimeMachine.h>
#import <CMCapture/FigCaptureAPSSphereInteractionCalibrationContext.h>
#import <CMCapture/BWPixelTransferNode.h>
#import <CMCapture/BWVideoProcessingInferenceAdapter.h>
#import <CMCapture/BWPearlPortraitSceneMonitor.h>
#import <CMCapture/FigBWNodeRenderObserver.h>
#import <CMCapture/BWPhotosCurationInferenceConfiguration.h>
#import <CMCapture/BWVisionInferenceConfiguration.h>
#import <CMCapture/BWPixelBufferPool.h>
#import <CMCapture/BWNode.h>
#import <CMCapture/BWUBInferenceControllerConfiguration.h>
#import <CMCapture/BWUBInferenceControllerInput.h>
#import <CMCapture/BWUBInferenceController.h>
#import <CMCapture/BWAttachedMediaSplitNode.h>
#import <CMCapture/BWRedEyeReductionControllerInput.h>
#import <CMCapture/BWRedEyeReductionRequest.h>
#import <CMCapture/BWRedEyeReductionController.h>
#import <CMCapture/FigStillImageSharedProcessingResources.h>
#import <CMCapture/BWAdaptiveBracketingFrameParameters.h>
#import <CMCapture/BWInferenceCloneVideoRequirement.h>
#import <CMCapture/FigCameraViewfinderStream.h>
#import <CMCapture/FigCaptureBaseStillImageSinkPipelineConfiguration.h>
#import <CMCapture/BWMetadataObjectFormat.h>
#import <CMCapture/FigNSXPCConnection.h>
#import <CMCapture/FigCameraViewfinderRemote.h>
#import <CMCapture/FigCameraViewfinderSessionRemote.h>
#import <CMCapture/BWFileCoordinatorNode.h>
#import <CMCapture/BWPreviewStitcherNode.h>
#import <CMCapture/BWVisionInferenceContext.h>
#import <CMCapture/BWPreviewTimeMachineSinkNode.h>
#import <CMCapture/BWLandmarksInferenceConfiguration.h>
#import <CMCapture/BWPhotoDecompressor.h>
#import <CMCapture/FigCaptureMovieFileSinkPipelineConfiguration.h>
#import <CMCapture/FigCaptureMovieFileSinkHeadPipelineConfiguration.h>
#import <CMCapture/FigCaptureMovieFileSinkHeadPipeline.h>
#import <CMCapture/FigCaptureMovieFileSinkMiddlePipelineConfiguration.h>
#import <CMCapture/FigCaptureMovieFileSinkMiddlePipeline.h>
#import <CMCapture/FigCaptureMovieFileSinkTailPipelineConfiguration.h>
#import <CMCapture/FigCaptureMovieFileSinkTailPipeline.h>
#import <CMCapture/FigCaptureMovieFileSinkPipeline.h>
#import <CMCapture/InterceptConfig.h>
#import <CMCapture/CMMTLCommandQueue.h>
#import <CMCapture/CMMTLCommandBuffer.h>
#import <CMCapture/BWDeferredProcessingSourceNode.h>
#import <CMCapture/BWStillImageScalerNode.h>
#import <CMCapture/BWMRCNode.h>
#import <CMCapture/BWDeferredContainerPixelBufferPool.h>
#import <CMCapture/BWFigVideoCaptureSynchronizedStreamsGroup.h>
#import <CMCapture/BWPipelineStage.h>
#import <CMCapture/BWGNRNode.h>
#import <CMCapture/BWMeaningfulSubjectTracker.h>
#import <CMCapture/BWInferenceCompressedVideoRequirement.h>
#import <CMCapture/FigCameraViewfinder.h>
#import <CMCapture/FigCameraViewfinderSession.h>
#import <CMCapture/BWCoreImageFilterRendererParameters.h>
#import <CMCapture/BWQuickTimeMovieFileSinkNode.h>
#import <CMCapture/FigCaptureCameraCalibrationDataSinkPipeline.h>
#import <CMCapture/BWStreamingFilterNode.h>
#import <CMCapture/BWMattingInferenceStorage.h>
#import <CMCapture/FigCaptureVisionDataSinkPipeline.h>
#import <CMCapture/BWAudioFormat.h>
#import <CMCapture/BWStillImageMetalBlurMapRenderer.h>
#import <CMCapture/BWMetalColorCubeRendererParameters.h>
#import <CMCapture/FigCaptureThermalMonitor.h>
#import <CMCapture/FigCameraUsageListener.h>
#import <CMCapture/BWPhotoEncoderNode.h>
#import <CMCapture/BWInferenceConfiguration.h>
#import <CMCapture/FigCaptureStillImageSettings.h>
#import <CMCapture/FigCaptureIrisStillImageSettings.h>
#import <CMCapture/FigCaptureIrisPreparedSettings.h>
#import <CMCapture/BWInferenceSingleBufferPoolProvider.h>
#import <CMCapture/BWStillImageMultiCameraDoserNode.h>
#import <CMCapture/BWStillImageProcessingSettings.h>
#import <CMCapture/BWStillImageConditionalRouterConfiguration.h>
#import <CMCapture/BWStillImageConditionalRouterLandmarksConfiguration.h>
#import <CMCapture/BWStillImageConditionalRouterPersonSegmentationAndMattingConfiguration.h>
#import <CMCapture/BWStillImageConditionalRouterUBConfiguration.h>
#import <CMCapture/BWStillImageConditionalRouterInferenceConfiguration.h>
#import <CMCapture/BWStillImageConditionalRouterOverCaptureConfiguration.h>
#import <CMCapture/BWStillImageConditionalRouterNode.h>
#import <CMCapture/BWFaceTrackingNode.h>
#import <CMCapture/FigCaptureSessionParsedCameraSourceConfiguration.h>
#import <CMCapture/FigCaptureSessionParsedMicSourceConfiguration.h>
#import <CMCapture/FigCaptureSessionParsedPreviewSinkConfiguration.h>
#import <CMCapture/FigCaptureSessionParsedStillImageSinkConfiguration.h>
#import <CMCapture/FigCaptureSessionParsedVideoDataSinkConfiguration.h>
#import <CMCapture/FigCaptureSessionParsedVisionDataSinkConfiguration.h>
#import <CMCapture/FigCaptureSessionParsedDepthDataSinkConfiguration.h>
#import <CMCapture/FigCaptureSessionParsedMetadataSinkConfiguration.h>
#import <CMCapture/FigCaptureSessionParsedMovieFileSinkConfiguration.h>
#import <CMCapture/FigCaptureSessionParsedConfiguration.h>
#import <CMCapture/BWInferenceDataRequirement.h>
#import <CMCapture/BWStats.h>
#import <CMCapture/BWMovingWindowStats.h>
#import <CMCapture/BWLimitedGMErrorLogger.h>
#import <CMCapture/BWVideoQualityMetrics.h>
#import <CMCapture/FigCapturePowerMonitor.h>
#import <CMCapture/BWIrisStagingNode.h>
#import <CMCapture/BWDataBufferPool.h>
#import <CMCapture/BWIrisMovieInfo.h>
#import <CMCapture/BWSceneClassifierSinkNode.h>
#import <CMCapture/BWStillImageDisparitySplitterNode.h>
#import <CMCapture/FigCaptureCalibrationMonitor.h>
#import <CMCapture/FigCapturePointCloudDataSinkPipeline.h>
#import <CMCapture/BWInferenceResult.h>
#import <CMCapture/BWBravoPortraitSceneMonitorV2.h>
#import <CMCapture/BWVideoSDOFSplitNode.h>
#import <CMCapture/FigCaptureDeferredProcessingJob.h>
#import <CMCapture/FigCaptureDeferredProcessingEngine.h>
#import <CMCapture/FigWiredMemory.h>
#import <CMCapture/BWAudioConverterNode.h>
#import <CMCapture/BWSinkNode.h>
#import <CMCapture/BWInferenceMediaRequirement.h>
#import <CMCapture/BWFigVideoCaptureStream.h>
#import <CMCapture/BWNodeMessage.h>
#import <CMCapture/BWNodeSampleBufferMessage.h>
#import <CMCapture/BWNodeConfigurationLiveMessage.h>
#import <CMCapture/BWNodeEndOfDataMessage.h>
#import <CMCapture/BWNodeErrorMessage.h>
#import <CMCapture/BWNodeDroppedSampleMessage.h>
#import <CMCapture/BWNodeStillImageReferenceFrameBracketedCaptureSequenceNumberMessage.h>
#import <CMCapture/BWNodeStillImagePrewarmMessage.h>
#import <CMCapture/BWNodeInput.h>
#import <CMCapture/BWNodeInputMediaConfiguration.h>
#import <CMCapture/BWNodeInputMediaProperties.h>
#import <CMCapture/BWInferenceSynchronizerNode.h>
#import <CMCapture/BWVideoProcessingInferenceStorage.h>
#import <CMCapture/BWRamp.h>
#import <CMCapture/FigCaptureSourceFormat.h>
#import <CMCapture/FigCaptureSourceVideoFormat.h>
#import <CMCapture/FigCaptureSourceDepthDataFormat.h>
#import <CMCapture/FigCaptureSourceCompanionFormat.h>
#import <CMCapture/FigCaptureClientSessionMonitor.h>
#import <CMCapture/BWMultiFilterThumbnailNode.h>
#import <CMCapture/FigCaptureAutoFocusPositionSensorCalibrationIStopZEstimateDeltaHistory.h>
#import <CMCapture/FigCaptureAutoFocusPositionSensorCalibrationContext.h>
#import <CMCapture/BWSpringSimulation.h>
#import <CMCapture/BWUBAdaptiveBracketingParameters.h>
#import <CMCapture/BWUBProcessorInput.h>
#import <CMCapture/BWUBSemanticRenderingInput.h>
#import <CMCapture/BWUBProcessorRequest.h>
#import <CMCapture/BWUBProcessorControllerConfiguration.h>
#import <CMCapture/BWUBProcessorController.h>
#import <CMCapture/BWNRFAdaptiveBracketingParameters.h>
#import <CMCapture/BWNRFProcessorInput.h>
#import <CMCapture/BWNRFSemanticRenderingInput.h>
#import <CMCapture/BWNRFProcessorCompletionStatus.h>
#import <CMCapture/BWNRFProcessorRequest.h>
#import <CMCapture/BWNRFProcessorControllerConfiguration.h>
#import <CMCapture/BWNRFProcessorController.h>
#import <CMCapture/BWStillImageCameraCalibrationDataNode.h>
#import <CMCapture/BWStillImageTurnstileNode.h>
#import <CMCapture/BWDeferredContainerPixelBufferWrapper.h>
#import <CMCapture/BWDeferredContainerPixelBufferPoolWrapper.h>
#import <CMCapture/BWDeferredContainerManagerBase.h>
#import <CMCapture/BWDeferredCaptureContainerManager.h>
#import <CMCapture/BWDeferredProcessingContainerManager.h>
#import <CMCapture/BWStillImageCaptureDelegateCallbackInfo.h>
#import <CMCapture/BWStillImageCoordinatorNode.h>
#import <CMCapture/BWStreamingCVAFilterRendererAnimator.h>
#import <CMCapture/BWFileSinkNode.h>
#import <CMCapture/FigCameraViewfinderLocal.h>
#import <CMCapture/FigCameraViewfinderSessionLocal.h>
#import <CMCapture/BWVideoDefringingNode.h>
#import <CMCapture/BWMeteorHeadroomNode.h>
#import <CMCapture/BWStreamingCVAFilterRenderer.h>
#import <CMCapture/FigCaptureVideoThumbnailSinkPipeline.h>
#import <CMCapture/BWStillImageCaptureStreamFrameCounters.h>
#import <CMCapture/BWStillImageFrameCoordinatorNode.h>
#import <CMCapture/FigCaptureSourceStreamsContainer.h>
#import <CMCapture/BWDepthRotatorNode.h>
#import <CMCapture/BWVariableFrameRateParameters.h>
#import <CMCapture/BWVariableFrameRateSelector.h>
#import <CMCapture/BWRGBPersonSegmentationInferenceConfiguration.h>
#import <CMCapture/BWMotionAttachmentsNode.h>
#import <CMCapture/FigCapturePipeline.h>
#import <CMCapture/FigCaptureSourcePipeline.h>
#import <CMCapture/FigCaptureSinkPipeline.h>
#import <CMCapture/FigCaptureRemoteQueueSinkPipeline.h>
#import <CMCapture/BWDeferredMetadataCache.h>
#import <CMCapture/BWDetectedFacesRingBuffer.h>
#import <CMCapture/BWDetectedObjectsInfoRingBuffer.h>
#import <CMCapture/BWEspressoInferenceStorage.h>
#import <CMCapture/BWNodeOutput.h>
#import <CMCapture/BWNodeOutputMediaConfiguration.h>
#import <CMCapture/BWNodeOutputMediaProperties.h>
#import <CMCapture/BWInferenceMetadataRequirement.h>
#import <CMCapture/BWMattingInferenceProvider.h>
#import <CMCapture/FigCaptureStillImageUnifiedBracketingSinkPipelineConfiguration.h>
#import <CMCapture/FigCaptureStillImageUnifiedBracketingSinkPipeline.h>
#import <CMCapture/BWStillImageDualPhotoFacePropagatorNode.h>
#import <CMCapture/FigIOSurfaceData.h>
#import <CMCapture/BWStreamingCameraCalibrationDataNode.h>
#import <CMCapture/FigCaptureCameraSourcePipelineConfiguration.h>
#import <CMCapture/FigCaptureCameraSourcePipeline.h>
#import <CMCapture/BWAggdDataReporter.h>
#import <CMCapture/BWEspressoInferenceContext.h>
#import <CMCapture/BWStereoFusionNode.h>
#import <CMCapture/FigMetalHistogram.h>
#import <CMCapture/BWRedEyeReducerNode.h>
#import <CMCapture/BWNoiseReducerNode.h>
#import <CMCapture/FigCaptureSessionObservatory.h>
#import <CMCapture/FigCaptureSessionProxy.h>
#import <CMCapture/BWPersonSegmentationConfiguration.h>
#import <CMCapture/BWCrossoverNode.h>
#import <CMCapture/BWMeaningfulSubjectDetectionContext.h>
#import <CMCapture/BWFigCaptureStream.h>
#import <CMCapture/FigMetalAllocatorMetadata.h>
#import <CMCapture/FigMetalUtils.h>
#import <CMCapture/FigMetalAllocatorDescriptor.h>
#import <CMCapture/FigMetalTextureDescriptor.h>
#import <CMCapture/FigMetalNoAliasingAllocator.h>
#import <CMCapture/FigMetalBufferAllocator.h>
#import <CMCapture/FigMetalHeapAllocator.h>
#import <CMCapture/FigMetalAllocator.h>
#import <CMCapture/FigMetalTextureStub.h>
#import <CMCapture/BWInferenceSchedulerGraph.h>
#import <CMCapture/BWStillImageFilterNode.h>
#import <CMCapture/BWSlaveFrameSynchronizerNode.h>
#import <CMCapture/BWMetadataFormat.h>
#import <CMCapture/BWStillImageCaptureStreamFrameCounts.h>
#import <CMCapture/BWStillImageTimeMachineFrameCoordinatorNode.h>
#import <CMCapture/BWStillImageBufferRouterNode.h>
#import <CMCapture/BWInferenceSchedulerFramebuffer.h>
#import <CMCapture/FigCaptureSessionActiveCameraCaptureSource.h>
#import <CMCapture/BWFigCaptureSession.h>
#import <CMCapture/BWVideoOrientationTimeMachineItem.h>
#import <CMCapture/BWVideoOrientationTimeMachine.h>
#import <CMCapture/FigCaptureStillImageSinkPipelineConfiguration.h>
#import <CMCapture/FigCaptureStillImageSinkPipeline.h>
#import <CMCapture/BWInferenceDataDependency.h>
#import <CMCapture/BWNodeEnumerator.h>
#import <CMCapture/BWDepthFirstEnumerator.h>
#import <CMCapture/BWReverseDepthFirstEnumerator.h>
#import <CMCapture/BWBreadthFirstEnumerator.h>
#import <CMCapture/BWReverseBreadthFirstEnumerator.h>
#import <CMCapture/BWSISNode.h>
#import <CMCapture/BWFigCaptureSynchronizedStreamsGroup.h>
#import <CMCapture/BWOverCaptureAttachedMediaSplitNode.h>
#import <CMCapture/FigCaptureMachPortSendRight.h>
#import <CMCapture/BWUBNode.h>
#import <CMCapture/BWMotionDataTimeMachine.h>
#import <CMCapture/BWInferenceSchedulerJobList.h>
#import <CMCapture/BWInferenceVideoRequirement.h>
#import <CMCapture/BWCameraInfoMetadataNode.h>
#import <CMCapture/BWMotionDataPreserver.h>
#import <CMCapture/BWFigCaptureDeviceClient.h>
#import <CMCapture/BWFigCaptureDeviceVendor.h>
#import <CMCapture/BWMattingV2InferenceProvider.h>
#import <CMCapture/FigSmartcamDiagnostics.h>
#import <CMCapture/FigCaptureDisplayLayoutMonitor.h>
#import <CMCapture/BWFanOutNode.h>
#import <CMCapture/BWDepthSynchronizerNode.h>
#import <CMCapture/BWInferenceProviderStorage.h>
#import <CMCapture/BWRenderListParameters.h>
#import <CMCapture/BWSceneClassifierFrameGateNode.h>
#import <CMCapture/BWFrameStatistics.h>
#import <CMCapture/BWFrameStatisticsByPortType.h>
#import <CMCapture/BWSphereModeSelector.h>
#import <CMCapture/FigCapturePixelConverter.h>
#import <CMCapture/BWVideoDepthNode.h>
#import <CMCapture/FigCaptureLockScreenPrewarmingMonitor.h>
#import <CMCapture/BWMetalColorCubeRenderer.h>
#import <CMCapture/BWUBCaptureParameters.h>
#import <CMCapture/BWStillImageTimeMachine.h>
#import <CMCapture/BWStereoDisparityProcessorInput.h>
#import <CMCapture/BWStereoDisparityRequest.h>
#import <CMCapture/BWStereoDisparityProcessorControllerConfiguration.h>
#import <CMCapture/BWStereoDisparityProcessorController.h>
#import <CMCapture/BWPointCloudFormatRequirements.h>
#import <CMCapture/BWPointCloudFormat.h>
#import <CMCapture/BWDeferredContainer.h>
#import <CMCapture/BWDeferredCaptureContainer.h>
#import <CMCapture/BWDeferredProcessingContainer.h>
#import <CMCapture/BWRingBuffer.h>
#import <CMCapture/BWMotionSampleRingBuffer.h>
#import <CMCapture/BWDeviceMotionActivityDetector.h>
#import <CMCapture/FigCaptureSessionConfiguration.h>
#import <CMCapture/FigCaptureConnectionConfiguration.h>
#import <CMCapture/FigVideoCaptureConnectionConfiguration.h>
#import <CMCapture/FigAudioCaptureConnectionConfiguration.h>
#import <CMCapture/FigMetadataObjectCaptureConnectionConfiguration.h>
#import <CMCapture/FigMetadataItemCaptureConnectionConfiguration.h>
#import <CMCapture/FigDepthDataCaptureConnectionConfiguration.h>
#import <CMCapture/FigVisionDataCaptureConnectionConfiguration.h>
#import <CMCapture/FigPointCloudDataCaptureConnectionConfiguration.h>
#import <CMCapture/FigCameraCalibrationDataCaptureConnectionConfiguration.h>
#import <CMCapture/FigCaptureSourceConfiguration.h>
#import <CMCapture/FigCaptureSinkConfiguration.h>
#import <CMCapture/FigCaptureVideoPreviewSinkConfiguration.h>
#import <CMCapture/FigCaptureVideoThumbnailSinkConfiguration.h>
#import <CMCapture/FigCaptureAudioPreviewSinkConfiguration.h>
#import <CMCapture/FigCaptureStillImageSinkConfiguration.h>
#import <CMCapture/FigCaptureMovieFileSinkConfiguration.h>
#import <CMCapture/FigCaptureAudioFileSinkConfiguration.h>
#import <CMCapture/FigCaptureVideoDataSinkConfiguration.h>
#import <CMCapture/FigCaptureAudioDataSinkConfiguration.h>
#import <CMCapture/FigCaptureMetadataObjectSinkConfiguration.h>
#import <CMCapture/FigCaptureMetadataItemGroupSinkConfiguration.h>
#import <CMCapture/FigCaptureInternalSinkConfiguration.h>
#import <CMCapture/FigCapturePointCloudDataSinkConfiguration.h>
#import <CMCapture/FigCaptureIrisSinkConfiguration.h>
#import <CMCapture/FigCaptureDepthDataSinkConfiguration.h>
#import <CMCapture/FigCaptureVisionDataSinkConfiguration.h>
#import <CMCapture/FigCaptureCameraCalibrationDataSinkConfiguration.h>
#import <CMCapture/FigCaptureSessionConfigurationKeyedUnarchiverDelegate.h>
#import <CMCapture/BWCameraCalibrationDataFormat.h>
#import <CMCapture/BWStillImageProcessorCoordinator.h>
#import <CMCapture/FigCaptureAutoFocusCalibrationContext.h>
#import <CMCapture/BWCoreAnalyticsReporter.h>
#import <CMCapture/BWStillImageCaptureAnalyticsPayload.h>
#import <CMCapture/BWMovieFileOutputAnalyticsPayload.h>
#import <CMCapture/BWIOSurfaceCompressionStatisticsAnalyticsPayload.h>
#import <CMCapture/BWStreamingSessionAnalyticsPayload.h>
#import <CMCapture/BWStartupCalibrationAnalyticsPayload.h>
#import <CMCapture/BWTOFAssistedAutoFocusEstimatorAnalyticsPayload.h>
#import <CMCapture/BWDeferredCaptureAnalyticsPayload.h>
#import <CMCapture/BWDeferredProcessingAnalyticsPayload.h>
#import <CMCapture/BWLivePhotoMovieAnalyticsPayload.h>
#import <CMCapture/BWObjectRingBuffer.h>
#import <CMCapture/BWObjectRingBufferThreadSafe.h>
#import <CMCapture/FigCaptureVISPipeline.h>
#import <CMCapture/BWStillImageSampleBufferSinkNode.h>
#import <CMCapture/BWPersonSemanticsConfiguration.h>
#import <CMCapture/BWVideoCompressorNode.h>
#import <CMCapture/BWRenderList.h>
#import <CMCapture/FigCaptureSessionMovieFileSinkPipeline.h>
#import <CMCapture/FigCaptureSessionPreviewSinkPipeline.h>
#import <CMCapture/FigCaptureSessionPreparedBracket.h>
#import <CMCapture/FigCaptureStillImageSinkPipelineSessionStorage.h>
#import <CMCapture/FigCaptureSessionPipelines.h>
#import <CMCapture/BWVISNode.h>
#import <CMCapture/BWInferenceBufferingNode.h>
#import <CMCapture/BWInferenceResultRingBuffers.h>
#import <CMCapture/BWFigCaptureISPProcessingSession.h>
#import <CMCapture/FigIrisAutoTrimmerMotionSample.h>
#import <CMCapture/BWEspressoInferenceProvider.h>
#import <CMCapture/BWStreamStartStopState.h>
#import <CMCapture/BWStreamStartStopSynchronizer.h>
#import <CMCapture/BWSynchronizerNode.h>
#import <CMCapture/FigCameraViewfinderServer.h>
#import <CMCapture/FigUtlROIProcessor.h>
#import <CMCapture/BWInferenceSchedulerInference.h>
#import <CMCapture/BWVideoProcessingInferenceProvider.h>
#import <CMCapture/BWAutoFocusPositionSensorMonitor.h>
#import <CMCapture/BWDepthConverterNode.h>
#import <CMCapture/BWVisionInferenceStorage.h>
#import <CMCapture/FigCaptureMetadataSourcePipeline.h>
#import <CMCapture/FigCapturePreviewSinkPipelineConfiguration.h>
#import <CMCapture/FigCapturePreviewSinkPipeline.h>
#import <CMCapture/BWFrameRateGovernorNode.h>
#import <CMCapture/BWDroppedSample.h>
#import <CMCapture/BWEspressoInferenceAdapter.h>
#import <CMCapture/BWColorLookupCache.h>
#import <CMCapture/BWMultiStreamCameraSourceNodeConfiguration.h>
#import <CMCapture/BWMultiStreamCameraSourceNode.h>
#import <CMCapture/BWMetadataSourceNode.h>
#import <CMCapture/BWVideoFormatRequirements.h>
#import <CMCapture/BWVideoFormat.h>
#import <CMCapture/BWInferenceSchedulerConnection.h>
#import <CMCapture/BWCoreImageFilterRenderer.h>
#import <CMCapture/BWInferenceScheduler.h>
#import <CMCapture/BWMeaningfulSubjectTrackingNode.h>
#import <CMCapture/BWMattingV2InferenceConfiguration.h>
#import <CMCapture/BWStillImageSettings.h>
#import <CMCapture/BWFormatRequirements.h>
#import <CMCapture/BWFormat.h>
#import <CMCapture/FigCaptureSessionServerKeyedUnarchiverDelegate.h>
#import <CMCapture/BWStillImagePortraitMetadataNode.h>
#import <CMCapture/BWVisionLandmarkDetector.h>
#import <CMCapture/BWHDRNode.h>
#import <CMCapture/FigCaptureRecordingSettings.h>
#import <CMCapture/FigCaptureMovieFileRecordingSettings.h>
#import <CMCapture/FigCaptureAudioFileRecordingSettings.h>
#import <CMCapture/FigCaptureImageMotionDetector.h>
#import <CMCapture/BWCameraStreamingMonitor.h>
#import <CMCapture/BWNodeConnection.h>
#import <CMCapture/BWAudioSourceNode.h>
#import <CMCapture/BWRenderListProcessor.h>
#import <CMCapture/FigCoreMotionDelegate.h>
#import <CMCapture/BWInferenceEngine.h>
#import <CMCapture/BWMemoryPool.h>
#import <CMCapture/BWPreviewHistogramNode.h>
#import <CMCapture/BWCoreMotionMetadataSourceNode.h>
#import <CMCapture/BWCaptureDeferredPhotoProcessor.h>
#import <CMCapture/FigCaptureCalibrationContext.h>
#import <CMCapture/BWAudioFileSinkNode.h>
#import <CMCapture/BWTimeSkew.h>
#import <CMCapture/BWIrisDiscontinuity.h>
#import <CMCapture/BWIrisSequenceAdjuster.h>
#import <CMCapture/BWDeferredIntermediate.h>
#import <CMCapture/BWDeferredBufferIntermediate.h>
#import <CMCapture/BWDeferredDataIntermediate.h>
#import <CMCapture/BWDeferredArrayIntermediate.h>
#import <CMCapture/BWDeferredDictionaryIntermediate.h>
#import <CMCapture/BWDeferredMetadataIntermediate.h>
#import <CMCapture/BWFigCaptureDevice.h>
#import <CMCapture/BWTrackedFace.h>
#import <CMCapture/BWSingleCameraPortraitSceneMonitor.h>
#import <CMCapture/BWInferenceSchedulerScaler.h>
#import <CMCapture/BWNoiseReductionAndSharpeningParameters.h>
#import <CMCapture/BWGraph.h>
#import <CMCapture/BWInferenceDependencyProvider.h>
#import <CMCapture/BWZoomCommandHandler.h>
#import <CMCapture/BWZoomDelayBuffer.h>
#import <CMCapture/BWZoomRange.h>
#import <CMCapture/BWFigVideoCaptureDevice.h>
#import <CMCapture/BWSensorConfiguration.h>
#import <CMCapture/BWFunnelNode.h>
#import <CMCapture/BWImageQueueSinkNode.h>
#import <CMCapture/FigIrisAutoTrimmer.h>
#import <CMCapture/BWVideoOrientationMetadataNode.h>
#import <CMCapture/BWDeferredProcessorControllerInput.h>
#import <CMCapture/BWDeferredProcessorRequest.h>
#import <CMCapture/BWDeferredProcessorController.h>
#import <CMCapture/BWParallelJoinerNode.h>
#import <CMCapture/BWInferenceScalingRequirement.h>
#import <CMCapture/FigMomentCaptureSettings.h>
#import <CMCapture/BWCameraParameters.h>
#import <CMCapture/BWNodeError.h>
#import <CMCapture/FigCaptureSystemPressureMonitor.h>
#import <CMCapture/FigCaptureMetadataSinkPipelineConfiguration.h>
#import <CMCapture/FigCaptureMetadataSinkPipeline.h>
#import <CMCapture/BWPendingIrisRecordingRequest.h>
#import <CMCapture/BWDeepFusionProcessorInput.h>
#import <CMCapture/BWDeepFusionProcessorRequest.h>
#import <CMCapture/BWDeepFusionProcessorControllerConfiguration.h>
#import <CMCapture/BWDeepFusionProcessorController.h>
#import <CMCapture/FigStateMachine.h>
#import <CMCapture/BWBoxedOutputDetectionTimingInfo.h>
#import <CMCapture/BWFaceDetectionNode.h>
#import <CMCapture/BWTrackedSurface.h>
#import <CMCapture/BWObjectLifetimeTracker.h>
#import <CMCapture/BWIOSurfacePoller.h>
#import <CMCapture/BWIOSurfaceTracking.h>
#import <CMCapture/BWMonocularDepthConfiguration.h>
#import <CMCapture/BWImageControlModeTransitionMonitor.h>
#import <CMCapture/BWStillImageBravoDisparityNode.h>
#import <CMCapture/FigWeakReference.h>
#import <CMCapture/FigDelegateStorage.h>
#import <CMCapture/BWBravoPortraitSceneMonitor.h>
#import <CMCapture/BWInferenceNode.h>
#import <CMCapture/FigCaptureDepthDataPipelineConfiguration.h>
#import <CMCapture/FigCaptureDepthDataPipeline.h>
#import <CMCapture/BWVisionInferenceProvider.h>
#import <CMCapture/BWRemoteQueueSinkNode.h>
#import <CMCapture/FigCaptureAudioFileSinkPipeline.h>
#import <CMCapture/BWMattingInferenceConfiguration.h>
#import <CMCapture/FigCaptureMicSourcePipelineConfiguration.h>
#import <CMCapture/FigCaptureMicSourcePipeline.h>
#import <CMCapture/BWBracketSettings.h>
#import <CMCapture/BWInferenceLazyVideoRequirement.h>
#import <CMCapture/FigFlatToNSDictionaryWrapper.h>
#import <CMCapture/FigFlatToNSDictionaryWrapperKeyEnumerator.h>
#import <CMCapture/FigCaptureVideoDataSinkPipelineConfiguration.h>
#import <CMCapture/FigCaptureVideoDataSinkPipeline.h>
#import <CMCapture/BWPhotoManifest.h>
#import <CMCapture/BWPhotoDescriptor.h>
#import <CMCapture/BWSourceNode.h>
#import <CMCapture/FigCaptureSphereCalibrationContext.h>
#import <CMCapture/FigCaptureAudioDataSinkPipeline.h>
#import <CMCapture/BWInferenceDepthScalingProvider.h>
