#import <MediaRemote/_MRVideoThumbnailRequestProtobuf.h>
#import <MediaRemote/MRLegacyController.h>
#import <MediaRemote/_MRPlaybackQueueRequestProtobuf.h>
#import <MediaRemote/MRPlaybackSession.h>
#import <MediaRemote/_MRGameControllerPropertiesMessageProtobuf.h>
#import <MediaRemote/MRClientUpdatesConfigMessage.h>
#import <MediaRemote/MRAVOutputDeviceDescription.h>
#import <MediaRemote/_MRLyricsEventProtobuf.h>
#import <MediaRemote/_MRAudioDataBlockProtobuf.h>
#import <MediaRemote/MRCoreUtilsSystemPairingSession.h>
#import <MediaRemote/MRMessageReplyIdentifier.h>
#import <MediaRemote/MRProtocolMessageQueue.h>
#import <MediaRemote/MRMessageData.h>
#import <MediaRemote/MRPendingMessageQueue.h>
#import <MediaRemote/_MRSetNowPlayingPlayerMessageProtobuf.h>
#import <MediaRemote/_MRGetVolumeControlCapabilitiesMessageProtobuf.h>
#import <MediaRemote/MRModifyOutputContextRequestMessage.h>
#import <MediaRemote/MRUpdateOutputDevicesMessage.h>
#import <MediaRemote/MRRemoveOutputDevicesMessage.h>
#import <MediaRemote/MRRemoveFromParentGroupMessage.h>
#import <MediaRemote/MRUpdateActiveSystemEndpointMessage.h>
#import <MediaRemote/MRUpdateEndpointsMessage.h>
#import <MediaRemote/MRRemoveEndpointsMessage.h>
#import <MediaRemote/MRConcreteEndpoint.h>
#import <MediaRemote/MRAudioBuffer.h>
#import <MediaRemote/_MRPromptForRouteAuthorizationMessageProtobuf.h>
#import <MediaRemote/_MRSupportedCommandsProtobuf.h>
#import <MediaRemote/MRSetStateMessage.h>
#import <MediaRemote/MRSetReadyStateMessage.h>
#import <MediaRemote/MRSetConnectionStateMessage.h>
#import <MediaRemote/MRSetHiliteModeMessage.h>
#import <MediaRemote/MRWakeDeviceMessage.h>
#import <MediaRemote/MRSetNowPlayingClientMessage.h>
#import <MediaRemote/MRSetNowPlayingPlayerMessage.h>
#import <MediaRemote/MRRemoveClientMessage.h>
#import <MediaRemote/MRRemovePlayerMessage.h>
#import <MediaRemote/MRUpdateClientMessage.h>
#import <MediaRemote/MRUpdatePlayerMessage.h>
#import <MediaRemote/MRUpdateContentItemMessage.h>
#import <MediaRemote/MRUpdateContentItemArtworkMessage.h>
#import <MediaRemote/MRSetDefaultSupportedCommandsMessage.h>
#import <MediaRemote/_MRSetStateMessageProtobuf.h>
#import <MediaRemote/_MRLanguageOptionProtobuf.h>
#import <MediaRemote/_MRNowPlayingInfoProtobuf.h>
#import <MediaRemote/_MRAudioTimeProtobuf.h>
#import <MediaRemote/_MRReceivedCommandProtobuf.h>
#import <MediaRemote/MRGameControllerMessage.h>
#import <MediaRemote/MRGameControllerPropertiesMessage.h>
#import <MediaRemote/MRRegisterGameControllerMessage.h>
#import <MediaRemote/MRRegisterGameControllerResponseMessage.h>
#import <MediaRemote/MRUnregisterGameControllerMessage.h>
#import <MediaRemote/MRRegisterForGameControllerEventsMessage.h>
#import <MediaRemote/_MRGetKeyboardSessionProtobuf.h>
#import <MediaRemote/_MRContentItemProtobuf.h>
#import <MediaRemote/MRContentItemMetadata.h>
#import <MediaRemote/_MRReceivedCommandAppOptionsProtobuf.h>
#import <MediaRemote/MRAVLocalEndpoint.h>
#import <MediaRemote/MRAVDistantOutputDevice.h>
#import <MediaRemote/MRAVRoutingDiscoverySessionWrapper.h>
#import <MediaRemote/_MRSetRecordingStateMessageProtobuf.h>
#import <MediaRemote/_MRAVRouteQueryProtobuf.h>
#import <MediaRemote/_MRGetVolumeResultMessageProtobuf.h>
#import <MediaRemote/_MRUpdateActiveSystemEndpointMessageProtobuf.h>
#import <MediaRemote/_MRVolumeControlCapabilitiesDidChangeMessageProtobuf.h>
#import <MediaRemote/MRIDSInputStream.h>
#import <MediaRemote/MRIDSOutputStream.h>
#import <MediaRemote/_MRSendVirtualTouchEventMessageProtobuf.h>
#import <MediaRemote/MRAVOutputDevice.h>
#import <MediaRemote/MRAVExternalOutputDevice.h>
#import <MediaRemote/MRAVDistantExternalDeviceMetadata.h>
#import <MediaRemote/MRAVMutableDistantExternalDeviceMetadata.h>
#import <MediaRemote/MRDistantExternalDevice.h>
#import <MediaRemote/MRLanguageOption.h>
#import <MediaRemote/_MRContentItemMetadataProtobuf.h>
#import <MediaRemote/_MRDiagnosticProtobuf.h>
#import <MediaRemote/MRDeviceInfoMessage.h>
#import <MediaRemote/MRDeviceInfoUpdateMessage.h>
#import <MediaRemote/_MRSendCommandResultMessageProtobuf.h>
#import <MediaRemote/MRMediaRemoteService.h>
#import <MediaRemote/MRSetVolumeMessage.h>
#import <MediaRemote/MRGetKeyboardSessionMessage.h>
#import <MediaRemote/_MRGetStateMessageProtobuf.h>
#import <MediaRemote/_MRPlayerClientPropertiesMessageProtobuf.h>
#import <MediaRemote/_MRVoiceInputDeviceDescriptorProtobuf.h>
#import <MediaRemote/MROrigin.h>
#import <MediaRemote/_MRAudioBufferProtobuf.h>
#import <MediaRemote/MRIDSConnectivityManager.h>
#import <MediaRemote/MRArtwork.h>
#import <MediaRemote/_MRAVOutputDeviceSourceInfoProtobuf.h>
#import <MediaRemote/MRProtobufSerialization.h>
#import <MediaRemote/_MRPlaybackQueueCapabilitiesProtobuf.h>
#import <MediaRemote/MRGetVoiceInputDevicesMessage.h>
#import <MediaRemote/MRGetVoiceInputDevicesResponseMessage.h>
#import <MediaRemote/MRRegisterVoiceInputDeviceMessage.h>
#import <MediaRemote/MRRegisterVoiceInputDeviceResponseMessage.h>
#import <MediaRemote/MRSetRecordingStateMessage.h>
#import <MediaRemote/MRSendVoiceInputMessage.h>
#import <MediaRemote/_MROriginClientPropertiesMessageProtobuf.h>
#import <MediaRemote/MROutputContextDataSource.h>
#import <MediaRemote/MRExternalOutputContextDataSource.h>
#import <MediaRemote/MROutputContextController.h>
#import <MediaRemote/MRNowPlayingState.h>
#import <MediaRemote/MRAVBufferedInputStream.h>
#import <MediaRemote/MRAVBufferedOutputStream.h>
#import <MediaRemote/MRAVOutputContext.h>
#import <MediaRemote/MRAVOutputContextModification.h>
#import <MediaRemote/MRDeviceInfo.h>
#import <MediaRemote/MRExternalJSONClientConnection.h>
#import <MediaRemote/MRSetDiscoveryModeMessage.h>
#import <MediaRemote/_MRSetDiscoveryModeProtobufMessage.h>
#import <MediaRemote/MRRegisterHIDDeviceResultMessage.h>
#import <MediaRemote/MRTransactionMessage.h>
#import <MediaRemote/MRExternalDeviceManager.h>
#import <MediaRemote/_MRRemoveClientMessageProtobuf.h>
#import <MediaRemote/MRPlaybackSessionMigrateRequest.h>
#import <MediaRemote/_MRRemoveOutputDevicesMessageProtobuf.h>
#import <MediaRemote/MRAVXPCPipeTransport.h>
#import <MediaRemote/MRAVOutputDeviceSourceInfo.h>
#import <MediaRemote/MRPlayerPath.h>
#import <MediaRemote/MRNetServiceTransport.h>
#import <MediaRemote/_MRCryptoPairingMessageProtobuf.h>
#import <MediaRemote/_MRAVEndpointDescriptorProtobuf.h>
#import <MediaRemote/MRWeakProxy.h>
#import <MediaRemote/_MRPromptForRouteAuthorizationResponseMessageProtobuf.h>
#import <MediaRemote/_MRGenericMessageProtobuf.h>
#import <MediaRemote/_MRTextInputMessageProtobuf.h>
#import <MediaRemote/MRNowPlayingRequest.h>
#import <MediaRemote/MRTelevisionDevice.h>
#import <MediaRemote/MRGetVolumeMessage.h>
#import <MediaRemote/MRGetVolumeResultMessage.h>
#import <MediaRemote/MRVolumeDidChangeMessage.h>
#import <MediaRemote/MRGetVolumeControlCapabilitiesMessage.h>
#import <MediaRemote/MRGetVolumeControlCapabilitiesResultMessage.h>
#import <MediaRemote/MRLegacyVolumeControlCapabilitiesDidChangeMessage.h>
#import <MediaRemote/MRVolumeControlCapabilitiesDidChangeMessage.h>
#import <MediaRemote/_MRVirtualTouchDeviceDescriptorProtobuf.h>
#import <MediaRemote/MRRemoteControl.h>
#import <MediaRemote/MROSTransaction.h>
#import <MediaRemote/_MRUpdateContentItemMessageProtobuf.h>
#import <MediaRemote/MRAVEndpointObserver.h>
#import <MediaRemote/MRCryptoPairingSession.h>
#import <MediaRemote/MRAVDistantRoutingDiscoverySession.h>
#import <MediaRemote/_MRPlaybackSessionMigrateRequestProtobuf.h>
#import <MediaRemote/MRPlayerClientPropertiesMessage.h>
#import <MediaRemote/MROriginClientPropertiesMessage.h>
#import <MediaRemote/MRExternalDevice.h>
#import <MediaRemote/MRTransportExternalDevice.h>
#import <MediaRemote/MRJSONTransportExternalDevice.h>
#import <MediaRemote/_MRRemovePlayerMessageProtobuf.h>
#import <MediaRemote/_MRSendLyricsEventMessageProtobuf.h>
#import <MediaRemote/_MRVolumeControlAvailabilityProtobuf.h>
#import <MediaRemote/_MRSendCommandMessageProtobuf.h>
#import <MediaRemote/_MRSendHIDReportMessageProtobuf.h>
#import <MediaRemote/MRSendCommandMessage.h>
#import <MediaRemote/_MRTextEditingAttributesProtobuf.h>
#import <MediaRemote/_MRClientUpdatesConfigurationProtobuf.h>
#import <MediaRemote/MRExternalDeviceMessageMetrics.h>
#import <MediaRemote/MRExternalDeviceMessageMetricsEntry.h>
#import <MediaRemote/_MRUpdateContentItemArtworkMessageProtobuf.h>
#import <MediaRemote/MRPromptForRouteAuthorizationMessage.h>
#import <MediaRemote/MRPromptForRouteAuthorizationResponseMessage.h>
#import <MediaRemote/MRPresentRouteAuthorizationStatusMessage.h>
#import <MediaRemote/MRSendVirtualTouchEventMessage.h>
#import <MediaRemote/MRSendPackedVirtualTouchEventMessage.h>
#import <MediaRemote/_MRTransactionMessageProtobuf.h>
#import <MediaRemote/MRNowPlayingOriginClientRequests.h>
#import <MediaRemote/MRNowPlayingClientRequests.h>
#import <MediaRemote/_MRGameControllerDigitizerProtobuf.h>
#import <MediaRemote/_MRAVModifyOutputContextRequestProtobuf.h>
#import <MediaRemote/MRLegacySendHIDEventMessage.h>
#import <MediaRemote/MRCoreUtilsPairingSession.h>
#import <MediaRemote/MRIDSTransport.h>
#import <MediaRemote/MRAVClusterController.h>
#import <MediaRemote/MRCryptoPairingIdentity.h>
#import <MediaRemote/MRVirtualVoiceInputDevice.h>
#import <MediaRemote/_MRSetArtworkMessageProtobuf.h>
#import <MediaRemote/MRXPCConnection.h>
#import <MediaRemote/MRAudioDataBlock.h>
#import <MediaRemote/MRMutableAudioDataBlock.h>
#import <MediaRemote/MRExternalDevicePairingSession.h>
#import <MediaRemote/MRMediaRemoteServiceClient.h>
#import <MediaRemote/_MRLyricsTokenProtobuf.h>
#import <MediaRemote/MRSendButtonEventMessage.h>
#import <MediaRemote/MRAVDistantEndpoint.h>
#import <MediaRemote/_MRSetHiliteModeMessageProtobuf.h>
#import <MediaRemote/_MRCommandInfoProtobuf.h>
#import <MediaRemote/_MRSendButtonEventMessageProtobuf.h>
#import <MediaRemote/MRGetRemoteTextInputSessionMessage.h>
#import <MediaRemote/_MROriginProtobuf.h>
#import <MediaRemote/_MRKeyboardMessageProtobuf.h>
#import <MediaRemote/_MRPlaybackSessionRequestProtobuf.h>
#import <MediaRemote/_MRPlaybackSessionProtobuf.h>
#import <MediaRemote/MRPlaybackQueueRequestMessage.h>
#import <MediaRemote/_MRAVOutputDeviceDescriptorProtobuf.h>
#import <MediaRemote/_MRMediaRemoteMessageProtobuf.h>
#import <MediaRemote/_MRRegisterVoiceInputDeviceMessageProtobuf.h>
#import <MediaRemote/_MRVirtualTouchEventProtobuf.h>
#import <MediaRemote/MRPlaybackSessionRequest.h>
#import <MediaRemote/_MRRegisterGameControllerMessageProtobuf.h>
#import <MediaRemote/_MRNowPlayingClientProtobuf.h>
#import <MediaRemote/MRNotificationClient.h>
#import <MediaRemote/MRNotification.h>
#import <MediaRemote/MRUserSettings.h>
#import <MediaRemote/MRPlaybackQueueRequest.h>
#import <MediaRemote/_MRAVAirPlaySecuritySettingsProtobuf.h>
#import <MediaRemote/MRAVOutputDeviceTransport.h>
#import <MediaRemote/_MRGameControllerPropertiesProtobuf.h>
#import <MediaRemote/MRContentItemRequest.h>
#import <MediaRemote/_MRSendPackedVirtualTouchEventMessageProtobuf.h>
#import <MediaRemote/_MRAudioStreamPacketDescriptionProtobuf.h>
#import <MediaRemote/MRExternalDeviceController.h>
#import <MediaRemote/_MRPlaybackSessionMigrateRequestMessageProtobuf.h>
#import <MediaRemote/MRAVOutputContextTransport.h>
#import <MediaRemote/MRExternalDeviceTransport.h>
#import <MediaRemote/_MRRegisterHIDDeviceResultMessageProtobuf.h>
#import <MediaRemote/MRNotificationServiceClient.h>
#import <MediaRemote/_MRPlaybackSessionMigrateEndMessageProtobuf.h>
#import <MediaRemote/_MRUpdatePlayerMessageProtobuf.h>
#import <MediaRemote/_MRGameControllerAccelerationProtobuf.h>
#import <MediaRemote/_MRVolumeDidChangeMessageProtobuf.h>
#import <MediaRemote/_MRPlaybackSessionResponseMessageProtobuf.h>
#import <MediaRemote/_MRTelevisionControllerBlockCallback.h>
#import <MediaRemote/MRTelevisionController.h>
#import <MediaRemote/MRCommandInfo.h>
#import <MediaRemote/_MRSetReadyStateMessageProtobuf.h>
#import <MediaRemote/_MRPlaybackSessionMigrateResponseMessageProtobuf.h>
#import <MediaRemote/_MRRemoteTextInputMessageProtobuf.h>
#import <MediaRemote/MRAVRoutingDiscoverySessionConfiguration.h>
#import <MediaRemote/MRAVRoutingDiscoverySession.h>
#import <MediaRemote/MRCompositeMessage.h>
#import <MediaRemote/_MRTransactionPacketProtobuf.h>
#import <MediaRemote/_MRPlaybackQueueContextProtobuf.h>
#import <MediaRemote/_MRGetVolumeControlCapabilitiesResultMessageProtobuf.h>
#import <MediaRemote/_MRSetConnectionStateMessageProtobuf.h>
#import <MediaRemote/_MRGetRemoteTextInputSessionProtobuf.h>
#import <MediaRemote/MRAVRoutingClientController.h>
#import <MediaRemote/_MRAudioFormatSettingsProtobuf.h>
#import <MediaRemote/MRIDSDiscoverySession.h>
#import <MediaRemote/_MRCommandOptionsProtobuf.h>
#import <MediaRemote/MRSendCommandResultMessage.h>
#import <MediaRemote/_MRPlaybackSessionMigrateRequestEventProtobuf.h>
#import <MediaRemote/_MRUpdateActiveSystemEndpointRequestProtobuf.h>
#import <MediaRemote/MRBlockGuard.h>
#import <MediaRemote/MRCryptoPairingSessionBlockDelegate.h>
#import <MediaRemote/_MRPresentRouteAuthorizationStatusMessageProtobuf.h>
#import <MediaRemote/_MRPlaybackSessionMigrateBeginMessageProtobuf.h>
#import <MediaRemote/MRAVVirtualOutputDevice.h>
#import <MediaRemote/_MRGetVolumeMessageProtobuf.h>
#import <MediaRemote/MRContentItem.h>
#import <MediaRemote/_MRNotificationMessageProtobuf.h>
#import <MediaRemote/MRTransactionPacket.h>
#import <MediaRemote/MRTransactionPacketAccumulator.h>
#import <MediaRemote/MRTransactionPacketizer.h>
#import <MediaRemote/MRTransactionSource.h>
#import <MediaRemote/MRTransactionDestination.h>
#import <MediaRemote/MRClient.h>
#import <MediaRemote/MRNotificationMessage.h>
#import <MediaRemote/MRSetArtworkMessage.h>
#import <MediaRemote/MRProtocolMessage.h>
#import <MediaRemote/MRSupportedProtocolMessages.h>
#import <MediaRemote/_MRUpdateClientMessageProtobuf.h>
#import <MediaRemote/_MRTransactionPacketsProtobuf.h>
#import <MediaRemote/_MRDeviceInfoMessageProtobuf.h>
#import <MediaRemote/MRRegisterHIDDeviceMessage.h>
#import <MediaRemote/MRSendLyricsEventMessage.h>
#import <MediaRemote/_MRSendHIDEventMessageProtobuf.h>
#import <MediaRemote/MRPlaybackSessionRequestMessage.h>
#import <MediaRemote/MRPlaybackSessionResponseMessage.h>
#import <MediaRemote/MRPlaybackSessionMigrateRequestMessage.h>
#import <MediaRemote/MRPlaybackSessionMigrateResponseMessage.h>
#import <MediaRemote/MRPlaybackSessionMigrateBeginMessage.h>
#import <MediaRemote/MRPlaybackSessionMigrateEndMessage.h>
#import <MediaRemote/MRRemoteTextInputMessage.h>
#import <MediaRemote/_MRTextInputTraitsProtobuf.h>
#import <MediaRemote/MRNowPlayingPlayerClientCallbacks.h>
#import <MediaRemote/MRUpdateActiveSystemEndpointResponse.h>
#import <MediaRemote/MRUpdateActiveSystemEndpointRequest.h>
#import <MediaRemote/MRNowPlayingPlayerPathInvalidationHandler.h>
#import <MediaRemote/_MRRegisterGameControllerResponseMessageProtobuf.h>
#import <MediaRemote/MRIDSClientConnection.h>
#import <MediaRemote/MRColorComponents.h>
#import <MediaRemote/MRAVEndpoint.h>
#import <MediaRemote/MRPlaybackQueueSubscriptionController.h>
#import <MediaRemote/MRPlaybackQueueClient.h>
#import <MediaRemote/MRPlayerPathDictionaryKey.h>
#import <MediaRemote/MRAVConcreteOutputDevice.h>
#import <MediaRemote/MRAVClusterOutputDevice.h>
#import <MediaRemote/MRPlayer.h>
#import <MediaRemote/_MRRegisterForGameControllerEventsMessageProtobuf.h>
#import <MediaRemote/_MRRemoveEndpointsMessageProtobuf.h>
#import <MediaRemote/_MRGameControllerButtonsProtobuf.h>
#import <MediaRemote/MRNowPlayingPlayerClientRequests.h>
#import <MediaRemote/MRNowPlayingArtwork.h>
#import <MediaRemote/MRNowPlayingArtworkImage.h>
#import <MediaRemote/MRNowPlayingOriginClient.h>
#import <MediaRemote/MRNowPlayingClient.h>
#import <MediaRemote/_MRPlaybackSessionRequestMessageProtobuf.h>
#import <MediaRemote/MRGenericMessage.h>
#import <MediaRemote/MRVVIClient.h>
#import <MediaRemote/MRGameControllerDaemonProxy.h>
#import <MediaRemote/MRGameControllerDelayedEvents.h>
#import <MediaRemote/MRGameControllerDelayedEvent.h>
#import <MediaRemote/MRNowPlayingPlayerClient.h>
#import <MediaRemote/MRProtocolClientConnection.h>
#import <MediaRemote/MRAVConcreteEndpoint.h>
#import <MediaRemote/_MRGetVoiceInputDevicesResponseMessageProtobuf.h>
#import <MediaRemote/MRKeyboardMessage.h>
#import <MediaRemote/_MRWakeDeviceMessageProtobuf.h>
#import <MediaRemote/MREmulatedGameController.h>
#import <MediaRemote/_MRLyricsItemProtobuf.h>
#import <MediaRemote/MRPlaybackQueue.h>
#import <MediaRemote/MRExternalClientConnection.h>
#import <MediaRemote/MRTextInputMessage.h>
#import <MediaRemote/_MRLanguageOptionGroupProtobuf.h>
#import <MediaRemote/_MRSetVolumeMessageProtobuf.h>
#import <MediaRemote/_MRVoiceInputDevice.h>
#import <MediaRemote/MRNowPlayingOriginClientManager.h>
#import <MediaRemote/MRLanguageOptionGroup.h>
#import <MediaRemote/_MRColorProtobuf.h>
#import <MediaRemote/_MRRegisterVoiceInputDeviceResponseMessageProtobuf.h>
#import <MediaRemote/_MRUpdateOutputDevicesMessageProtobuf.h>
#import <MediaRemote/_MRSetNowPlayingClientMessageProtobuf.h>
#import <MediaRemote/_MRUpdateEndpointsMessageProtobuf.h>
#import <MediaRemote/MRCryptoPairingMessage.h>
#import <MediaRemote/_MRGetVoiceInputDevicesMessageProtobuf.h>
#import <MediaRemote/_MRNowPlayingPlayerProtobuf.h>
#import <MediaRemote/_MRUnregisterGameControllerMessageProtobuf.h>
#import <MediaRemote/MRVirtualTouchDeviceDescriptor.h>
#import <MediaRemote/MRMutableVirtualTouchDeviceDescriptor.h>
#import <MediaRemote/MRTextEditingAttributes.h>
#import <MediaRemote/MRMutableTextEditingAttributes.h>
#import <MediaRemote/MRTextEditingSession.h>
#import <MediaRemote/MRMutableTextEditingSession.h>
#import <MediaRemote/MRAVReconnaissanceSession.h>
#import <MediaRemote/MRAVLightweightReconnaissanceSession.h>
#import <MediaRemote/_MRGameControllerMessageProtobuf.h>
#import <MediaRemote/_MRSendVoiceInputMessageProtobuf.h>
#import <MediaRemote/_MRPlaybackQueueProtobuf.h>
#import <MediaRemote/MRAVOutputDeviceInputStream.h>
#import <MediaRemote/MRAVOutputDeviceOutputStream.h>
#import <MediaRemote/_MRVideoThumbnailProtobuf.h>
#import <MediaRemote/MRAVConcreteRoutingDiscoverySession.h>
#import <MediaRemote/MRAVConcreteRoutingDiscoverySession_APSync.h>
#import <MediaRemote/MRAVInputStream.h>
#import <MediaRemote/MRAVOutputStream.h>
#import <MediaRemote/MRApplicationActivity.h>
#import <MediaRemote/MRMutableApplicationActivity.h>
#import <MediaRemote/_MRRegisterHIDDeviceMessageProtobuf.h>
#import <MediaRemote/_MRTransactionKeyProtobuf.h>
#import <MediaRemote/_MRNowPlayingPlayerPathProtobuf.h>
#import <MediaRemote/_MRGameControllerMotionProtobuf.h>
#import <MediaRemote/MRPasscodeCredentials.h>
#import <MediaRemote/MRProtocolMessageLogger.h>
#import <MediaRemote/MRVirtualVoiceInputDeviceDescriptor.h>
#import <MediaRemote/MRMutableVirtualVoiceInputDeviceDescriptor.h>
