/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:50:11 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/HealthKit.framework/HealthKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSMutableIndexSet, NSIndexSet;

@interface HKHeartRateSummaryStatisticsBucket : NSObject <NSSecureCoding> {

	NSMutableIndexSet* _heartRatesInBeatsPerMinute;
	long long _bucketIndex;

}

@property (nonatomic,readonly) long long bucketIndex;                                //@synthesize bucketIndex=_bucketIndex - In the implementation block
@property (nonatomic,readonly) NSIndexSet * heartRatesInBeatsPerMinute;              //@synthesize heartRatesInBeatsPerMinute=_heartRatesInBeatsPerMinute - In the implementation block
+(BOOL)supportsSecureCoding;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(unsigned long long)hash;
-(long long)bucketIndex;
-(NSIndexSet *)heartRatesInBeatsPerMinute;
-(id)initWithBucketIndex:(long long)arg1 ;
-(void)addHeartRateInBeatsPerMinute:(long long)arg1 ;
-(id)description;
@end

