/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:38:38 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/BMStoreData.h>
#import <libobjc.A.dylib/ATXProtoBufWrapper.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class ATXPredictionDeviceStateContext, ATXPredictionTimeContext, ATXPredictionLocationMotionContext, ATXPredictionAmbientLightContext, ATXPredictionUserContext, NSString;

@interface ATXPredictionContext : NSObject <BMStoreData, ATXProtoBufWrapper, NSSecureCoding> {

	BOOL _isOverridden;
	ATXPredictionDeviceStateContext* _deviceStateContext;
	ATXPredictionTimeContext* _timeContext;
	ATXPredictionLocationMotionContext* _locationMotionContext;
	ATXPredictionAmbientLightContext* _ambientLightContext;
	ATXPredictionUserContext* _userContext;

}

@property (nonatomic,retain) ATXPredictionDeviceStateContext * deviceStateContext;                    //@synthesize deviceStateContext=_deviceStateContext - In the implementation block
@property (nonatomic,retain) ATXPredictionTimeContext * timeContext;                                  //@synthesize timeContext=_timeContext - In the implementation block
@property (nonatomic,retain) ATXPredictionLocationMotionContext * locationMotionContext;              //@synthesize locationMotionContext=_locationMotionContext - In the implementation block
@property (nonatomic,retain) ATXPredictionAmbientLightContext * ambientLightContext;                  //@synthesize ambientLightContext=_ambientLightContext - In the implementation block
@property (nonatomic,retain) ATXPredictionUserContext * userContext;                                  //@synthesize userContext=_userContext - In the implementation block
@property (nonatomic,readonly) BOOL isOverridden;                                                     //@synthesize isOverridden=_isOverridden - In the implementation block
@property (nonatomic,readonly) unsigned dataVersion; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)supportsSecureCoding;
+(id)eventWithData:(id)arg1 dataVersion:(unsigned)arg2 ;
-(void)setUserContext:(ATXPredictionUserContext *)arg1 ;
-(id)serialize;
-(BOOL)isOverridden;
-(id)json;
-(unsigned)dataVersion;
-(ATXPredictionUserContext *)userContext;
-(id)encodeAsProto;
-(id)initWithProto:(id)arg1 ;
-(id)jsonDict;
-(ATXPredictionAmbientLightContext *)ambientLightContext;
-(id)proto;
-(ATXPredictionLocationMotionContext *)locationMotionContext;
-(BOOL)checkAndReportDecodingFailureIfNeededForid:(id)arg1 key:(id)arg2 coder:(id)arg3 errorDomain:(id)arg4 errorCode:(long long)arg5 ;
-(id)initWithDeviceStateContext:(id)arg1 timeContext:(id)arg2 locationMotionContext:(id)arg3 ambientLightContext:(id)arg4 userContext:(id)arg5 ;
-(id)initWithProtoData:(id)arg1 ;
-(id)initWithDeviceStateContext:(id)arg1 timeContext:(id)arg2 locationMotionContext:(id)arg3 ambientLightContext:(id)arg4 userContext:(id)arg5 isOverridden:(BOOL)arg6 ;
-(BOOL)isEqualToATXPredictionContext:(id)arg1 ;
-(void)setLocationMotionContext:(ATXPredictionLocationMotionContext *)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(ATXPredictionTimeContext *)timeContext;
-(ATXPredictionDeviceStateContext *)deviceStateContext;
-(void)setTimeContext:(ATXPredictionTimeContext *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setDeviceStateContext:(ATXPredictionDeviceStateContext *)arg1 ;
-(void)updateWithInjectedContext:(id)arg1 ;
-(void)setAmbientLightContext:(ATXPredictionAmbientLightContext *)arg1 ;
-(NSString *)description;
@end

