#import <CameraUI/CAMFullscreenViewfinder.h>
#import <CameraUI/CAMMachineReadableCodeIndicatorView.h>
#import <CameraUI/CAMModeDialItem.h>
#import <CameraUI/CAMFeedbackController.h>
#import <CameraUI/CAMExposureBiasSlider.h>
#import <CameraUI/CAMCreativeCameraButton.h>
#import <CameraUI/CAMViewfinderFlipTransition.h>
#import <CameraUI/CAMIdleController.h>
#import <CameraUI/CAMOrientationUtilities.h>
#import <CameraUI/CAMZoomSlider.h>
#import <CameraUI/CAMRampToVideoZoomFactorCommand.h>
#import <CameraUI/CAMPanoramaConfiguration.h>
#import <CameraUI/CAMQueryVideoDimensionsCommand.h>
#import <CameraUI/CAMBottomBar.h>
#import <CameraUI/CAMCaptureEncodingUtilities.h>
#import <CameraUI/CAMLevelIndicatorView.h>
#import <CameraUI/CAMTransientAsset.h>
#import <CameraUI/CAMSetVideoOrientationCommand.h>
#import <CameraUI/CAMLowLightModeCommand.h>
#import <CameraUI/CAMPreviewFilteredRenderingEnabledCommand.h>
#import <CameraUI/CAMDisabledModeOverlayView.h>
#import <CameraUI/CAMDialGradientView.h>
#import <CameraUI/CAMPortraitModeDescriptionOverlayPrimaryVibrancyEffectView.h>
#import <CameraUI/CAMZoomControlUtilities.h>
#import <CameraUI/CAMAdditiveAnimator.h>
#import <CameraUI/CAMAdditiveAnimation.h>
#import <CameraUI/CAMVideoLivePhotoMetadataWritingEnabledCommand.h>
#import <CameraUI/CAMStopVideoRecordingCommand.h>
#import <CameraUI/CAMPanoramaLevelView.h>
#import <CameraUI/CAMStillImageDepthDataDeliveryEnabledCommand.h>
#import <CameraUI/CAMCameraRollTestHarness.h>
#import <CameraUI/CAMCaptureEngineDevice.h>
#import <CameraUI/CAMIOSurfaceWrapper.h>
#import <CameraUI/CAMDisplayLinkTarget.h>
#import <CameraUI/CAMApplication.h>
#import <CameraUI/CAMVideoRecordingCameraSelectionBehaviorCommand.h>
#import <CameraUI/CAMCounterRotatingLayer.h>
#import <CameraUI/CAMPanoramaPaintingStatus.h>
#import <CameraUI/CAMSecureWindow.h>
#import <CameraUI/CAMTouchingGestureRecognizer.h>
#import <CameraUI/CAMCaptureMetadataUtilities.h>
#import <CameraUI/CAMPreviewContainerMaskingView.h>
#import <CameraUI/CAMStillImageCaptureCommand.h>
#import <CameraUI/CAMIrisVideoJob.h>
#import <CameraUI/CAMPowerController.h>
#import <CameraUI/CAMControlDrawer.h>
#import <CameraUI/CAMIntensityButton.h>
#import <CameraUI/CAMFaceDrivenImageProcessingCommand.h>
#import <CameraUI/CAMExposureResult.h>
#import <CameraUI/CAMLowLightTimelapseCommand.h>
#import <CameraUI/CAMNebulaKeepAliveController.h>
#import <CameraUI/CAMVideoConfigurationStatusIndicator.h>
#import <CameraUI/CAMPanoramaConfigurationCommand.h>
#import <CameraUI/CAMTorchPattern.h>
#import <CameraUI/CAMStillImagePortraitEffectsMatteDeliveryEnabledCommand.h>
#import <CameraUI/CAMTransientPairedVideo.h>
#import <CameraUI/CAMLedger.h>
#import <CameraUI/CAMLowLightStatusIndicator.h>
#import <CameraUI/CAMPanoramaRetainedBufferHintCommand.h>
#import <CameraUI/CAMPortraitModeInstructionLabel.h>
#import <CameraUI/CAMPanoramaEncodingCommand.h>
#import <CameraUI/CAMCTMInitiateCaptureCommand.h>
#import <CameraUI/CAMStillImageCaptureResolvedSettings.h>
#import <CameraUI/CAMPendingLocalPersistenceWrapper.h>
#import <CameraUI/CAMMotionController.h>
#import <CameraUI/CAMZoomControl.h>
#import <CameraUI/CAMLowLightConfigurationCommand.h>
#import <CameraUI/CAMFlipButton.h>
#import <CameraUI/CAMVideoRecordOrientationCommand.h>
#import <CameraUI/CAMCaptureCoordinationInfo.h>
#import <CameraUI/CAMUserPreferences.h>
#import <CameraUI/CAMSpatialOverCaptureEnabledCommand.h>
#import <CameraUI/CAMFocusLockBadge.h>
#import <CameraUI/CAMViewfinderTransitionController.h>
#import <CameraUI/CAMViewfinderViewController.h>
#import <CameraUI/CAMImageWell.h>
#import <CameraUI/CAMFaceResult.h>
#import <CameraUI/CAMGridView.h>
#import <CameraUI/CAMStillImagePersistenceCoordinator.h>
#import <CameraUI/CAMTimelapseJPEGReader.h>
#import <CameraUI/CAMMomentCaptureSettings.h>
#import <CameraUI/CAMMutableMomentCaptureSettings.h>
#import <CameraUI/CAMNebulaDaemonConnectionManager.h>
#import <CameraUI/CAMModeAndDeviceCommand.h>
#import <CameraUI/CAMCaptureCommandContext.h>
#import <CameraUI/CAMFilterButton.h>
#import <CameraUI/CAMPanoramaViewController.h>
#import <CameraUI/CAMPausePairedVideoRecordingCommand.h>
#import <CameraUI/CAMTransientImageWell.h>
#import <CameraUI/CAMFlashBadge.h>
#import <CameraUI/CAMLivePhotoButton.h>
#import <CameraUI/CAMBufferObservance.h>
#import <CameraUI/CAMTimerIndicatorView.h>
#import <CameraUI/CAMPriorityNotificationCenterEntry.h>
#import <CameraUI/CAMPriorityNotificationCenter.h>
#import <CameraUI/CAMConflictingControlConfiguration.h>
#import <CameraUI/CAMCameraRollController.h>
#import <CameraUI/CAMImagePickerCameraViewController.h>
#import <CameraUI/CAMVideoStabilizationCommand.h>
#import <CameraUI/CAMVideoCaptureResponse.h>
#import <CameraUI/CAMFocusResult.h>
#import <CameraUI/CAMCallStatusMonitor.h>
#import <CameraUI/CAMMirrorOutputVideoCommand.h>
#import <CameraUI/CAMClosedViewfinderController.h>
#import <CameraUI/CAMVideoHDRCommand.h>
#import <CameraUI/CAMAnalyticsPreferencesEvent.h>
#import <CameraUI/CAMPanoramaDirectionCommand.h>
#import <CameraUI/CAMVideoThumbnailOutputConfiguration.h>
#import <CameraUI/CAMPreviewFiltersCommand.h>
#import <CameraUI/CAMElapsedTimeView.h>
#import <CameraUI/CAMVideoRecordFaceMetadataCommand.h>
#import <CameraUI/CAMViewfinderOpenAndCloseTransition.h>
#import <CameraUI/CAMRealtimeMetadataCommand.h>
#import <CameraUI/CAMTimerButton.h>
#import <CameraUI/CAMColorSpaceCommand.h>
#import <CameraUI/CAMSpring.h>
#import <CameraUI/CAMCompositeSpring.h>
#import <CameraUI/CAMTrackingSpring.h>
#import <CameraUI/CAMImageControlModeCommand.h>
#import <CameraUI/CAMLowLightInstructionLabel.h>
#import <CameraUI/CAMFullscreenModeSelector.h>
#import <CameraUI/CAMLegibilityViewHelper.h>
#import <CameraUI/CAMNebulaUtilities.h>
#import <CameraUI/CAMControlStatusIndicator.h>
#import <CameraUI/CAMVideoCaptureRequest.h>
#import <CameraUI/CAMMutableVideoCaptureRequest.h>
#import <CameraUI/CAMPerformanceTestHarness.h>
#import <CameraUI/CAMLivePhotoAnimationCache.h>
#import <CameraUI/CAMVideoFramerateCommand.h>
#import <CameraUI/CAMMessagesPhotosButton.h>
#import <CameraUI/CAMAutoFPSVideoCommand.h>
#import <CameraUI/CAMSlashView.h>
#import <CameraUI/CAMEffectsPreviewVideoDataOutputEnabledCommand.h>
#import <CameraUI/CAMApertureStatusIndicator.h>
#import <CameraUI/CAMButtonLabel.h>
#import <CameraUI/CAMPreviewDepthDataDeliveryEnabledCommand.h>
#import <CameraUI/CAMLivePhotoBadge.h>
#import <CameraUI/CAMFilterStatusIndicator.h>
#import <CameraUI/CAMVideoLocalPersistenceResult.h>
#import <CameraUI/CAMModeDial.h>
#import <CameraUI/CAMCTMVideoCaptureEnabledCommand.h>
#import <CameraUI/CAMDeviceSwitchTestHarness.h>
#import <CameraUI/CAMPreviewAlignmentModel.h>
#import <CameraUI/CAMIrisDiskUtilities.h>
#import <CameraUI/CAMCaptureMovieFileOutput.h>
#import <CameraUI/CAMCaptureRequest.h>
#import <CameraUI/CUShutterButton.h>
#import <CameraUI/CAMShutterButtonContrastBackground.h>
#import <CameraUI/CAMPanoramaProcessor.h>
#import <CameraUI/CAMPreciseTimer.h>
#import <CameraUI/CAMDisabledPreviewController.h>
#import <CameraUI/CAMPreferencesUtilities.h>
#import <CameraUI/CAMTimelapseState.h>
#import <CameraUI/CAMHistogramResult.h>
#import <CameraUI/CAMFocusLockWithLensPositionCommand.h>
#import <CameraUI/CAMBarsAccessibilityHUDManager.h>
#import <CameraUI/CAMRemoteShutterController.h>
#import <CameraUI/CAMShutterIndicatorView.h>
#import <CameraUI/CAMZoomFactorLabel.h>
#import <CameraUI/CAMIrisVideoControllerJob.h>
#import <CameraUI/CAMIrisVideoController.h>
#import <CameraUI/CAMStartVideoRecordingCommand.h>
#import <CameraUI/CAMUpdateFocusAndExposureForStopVideoRecordingCommand.h>
#import <CameraUI/CAMSystemPressureMitigationCommand.h>
#import <CameraUI/CAMFlashStatusIndicator.h>
#import <CameraUI/CAMPersistenceResponse.h>
#import <CameraUI/CAMModeSelectTitleView.h>
#import <CameraUI/CAMCTMDescriptionOverlayView.h>
#import <CameraUI/CAMCaptureCallbackReceipt.h>
#import <CameraUI/CAMZoomButton.h>
#import <CameraUI/CAMPersistenceController.h>
#import <CameraUI/CAMPortraitModeDescriptionOverlayView.h>
#import <CameraUI/CAMLevelViewModel.h>
#import <CameraUI/CAMExposureBiasSliderThumb.h>
#import <CameraUI/CAMTimelapseBackendSessionContext.h>
#import <CameraUI/CAMUserPreferenceOverrides.h>
#import <CameraUI/CAMResponsiveShutterEnabledCommand.h>
#import <CameraUI/CAMLevelCrosshair.h>
#import <CameraUI/CAMCaptureRequestInfo.h>
#import <CameraUI/CAMViewfinderView.h>
#import <CameraUI/CAMHighResolutionStillImageCommand.h>
#import <CameraUI/CAMDirectionalIndicator.h>
#import <CameraUI/CAMViewfinderReticleView.h>
#import <CameraUI/CAMStillImageFilteredRenderingEnabledCommand.h>
#import <CameraUI/CAMZoomButtonPlatter.h>
#import <CameraUI/CAMNebulaDaemonProxyManager.h>
#import <CameraUI/CAMSubjectIndicatorView.h>
#import <CameraUI/CAMSubjectAreaChangeMonitoringCommand.h>
#import <CameraUI/CAMPanoramaUtilities.h>
#import <CameraUI/CAMSnapshotView.h>
#import <CameraUI/CAMDeviceSwitchAnimationTestHarness.h>
#import <CameraUI/CAMReviewViewController.h>
#import <CameraUI/CAMProtectionController.h>
#import <CameraUI/CAMFocusIndicatorView.h>
#import <CameraUI/CAMExposureCommand.h>
#import <CameraUI/CAMVideoThumbnailOutputEnabledCommand.h>
#import <CameraUI/CAMVideoPersistenceResponse.h>
#import <CameraUI/CAMMachineReadableCodeLoggingController.h>
#import <CameraUI/CAMIntensityStatusIndicator.h>
#import <CameraUI/CAMReviewViewControllerContainerView.h>
#import <CameraUI/CAMInterfaceModulationView.h>
#import <CameraUI/CAMStageLightAnimator.h>
#import <CameraUI/CAMFlashButton.h>
#import <CameraUI/CAMKeyValueCoalescer.h>
#import <CameraUI/CAMPendingRemotePersistenceWrapper.h>
#import <CameraUI/CAMBufferObservanceChange.h>
#import <CameraUI/CAMReviewButton.h>
#import <CameraUI/CAMNebulaIrisBackendController.h>
#import <CameraUI/CAMBlinkAndSmileDetectionCommand.h>
#import <CameraUI/CAMLowLightBoostCommand.h>
#import <CameraUI/CAMMetalView.h>
#import <CameraUI/CAMVideoThumbnailOutputConfigurationCommand.h>
#import <CameraUI/CAMCaptureCapabilities.h>
#import <CameraUI/CUCaptureController.h>
#import <CameraUI/CAMQuadraHighResolutionStillImageCommand.h>
#import <CameraUI/CAMControlDrawerButton.h>
#import <CameraUI/CAMControlDrawerCustomButton.h>
#import <CameraUI/CAMControlDrawerMenuItem.h>
#import <CameraUI/CAMControlDrawerMenuButton.h>
#import <CameraUI/CAMDrawerFlashButton.h>
#import <CameraUI/CAMDrawerLivePhotoButton.h>
#import <CameraUI/CAMDrawerAspectRatioButton.h>
#import <CameraUI/CAMDrawerTimerButton.h>
#import <CameraUI/CAMDrawerFilterButton.h>
#import <CameraUI/CAMDrawerHDRButton.h>
#import <CameraUI/CAMDrawerApertureButton.h>
#import <CameraUI/CAMDrawerIntensityButton.h>
#import <CameraUI/CAMDrawerExposureButton.h>
#import <CameraUI/CAMDrawerLowLightButton.h>
#import <CameraUI/CAMZoomDial.h>
#import <CameraUI/CAMTimelapseStabilizationCommand.h>
#import <CameraUI/CAMKeepAliveController.h>
#import <CameraUI/CAMTimelapseController.h>
#import <CameraUI/CAMMachineReadableCodeResult.h>
#import <CameraUI/CAMAnalyticsEvent.h>
#import <CameraUI/CAMSlashMaskView.h>
#import <CameraUI/CAMPreviewLayerEnabledCommand.h>
#import <CameraUI/CAMFocusCommand.h>
#import <CameraUI/CAMCameraReviewAdapter.h>
#import <CameraUI/CAMPreviewAlignmentGuide.h>
#import <CameraUI/CAMTransientImageManagerRequest.h>
#import <CameraUI/CAMTransientImageManager.h>
#import <CameraUI/CAMPreviewConfigurationCommand.h>
#import <CameraUI/CAMTimelapseCaptureRateCommand.h>
#import <CameraUI/CAMFocusIndicatorRectView.h>
#import <CameraUI/CAMUpdateFocusAndExposureForStartVideoRecordingCommand.h>
#import <CameraUI/CAMVideoPreviewView.h>
#import <CameraUI/CAMAspectCropUtilities.h>
#import <CameraUI/CAMStillImageCaptureResult.h>
#import <CameraUI/CAMFormattingManager.h>
#import <CameraUI/CAMCaptureCommand.h>
#import <CameraUI/CAMCaptureRequestIntervalometer.h>
#import <CameraUI/CAMPanoramaArrowView.h>
#import <CameraUI/CAMUtilityBar.h>
#import <CameraUI/CAMCTMCancelMomentCaptureCommand.h>
#import <CameraUI/CAMStartPanoramaCommand.h>
#import <CameraUI/CAMMemoizationCache.h>
#import <CameraUI/CAMVideoPersistenceCoordinator.h>
#import <CameraUI/CAMHDRButton.h>
#import <CameraUI/CAMEffectFilterManager.h>
#import <CameraUI/CAMCaptureResponse.h>
#import <CameraUI/CAMFaceIndicatorView.h>
#import <CameraUI/CAMStillImageCaptureResponse.h>
#import <CameraUI/CAMBurstController.h>
#import <CameraUI/CAMTorchPatternController.h>
#import <CameraUI/CAMWhiteBalanceCommand.h>
#import <CameraUI/CAMFocusAtCenterForVideoRecordingCommand.h>
#import <CameraUI/CAMTorchCommand.h>
#import <CameraUI/CAMModeSwitchTestHarness.h>
#import <CameraUI/CAMTimelapseSettings.h>
#import <CameraUI/CAMFlashCommand.h>
#import <CameraUI/CAMPortraitApertureCommand.h>
#import <CameraUI/CAMExpandableMenuButton.h>
#import <CameraUI/CAMPreparePhotoSettingsCommand.h>
#import <CameraUI/CAMStereoAudioCaptureCommand.h>
#import <CameraUI/CAMShallowDepthOfFieldBadge.h>
#import <CameraUI/CAMStillImagePersistenceResponse.h>
#import <CameraUI/CAMDeferredProcessingEnabledCommand.h>
#import <CameraUI/CAMCameraViewControllerContainerView.h>
#import <CameraUI/CAMVideoCaptureResult.h>
#import <CameraUI/CAMPanoramaLabel.h>
#import <CameraUI/CAMSetVideoZoomFactorCommand.h>
#import <CameraUI/CAMIrisVideoRecordingCommand.h>
#import <CameraUI/CAMShutterUtilities.h>
#import <CameraUI/CAMTimelapseStabilizationMovieWriter.h>
#import <CameraUI/CAMPhysicalCaptureRecognizer.h>
#import <CameraUI/CAMMetalContext.h>
#import <CameraUI/CAMBufferKeyValueObserverObservance.h>
#import <CameraUI/CAMBufferKeyValueObserverObservanceChange.h>
#import <CameraUI/CAMVideoHDRSuspensionCommand.h>
#import <CameraUI/CAMTimerStatusIndicator.h>
#import <CameraUI/CAMZoomSliderUtilities.h>
#import <CameraUI/CAMUserPreferencesMigrator.h>
#import <CameraUI/CAMStillImageCaptureRequest.h>
#import <CameraUI/CAMMutableStillImageCaptureRequest.h>
#import <CameraUI/CAMPanoramaView.h>
#import <CameraUI/CAMModeIndicatorView.h>
#import <CameraUI/CAMQRCodeInstructionLabel.h>
#import <CameraUI/CAMTimelapseShutterRingView.h>
#import <CameraUI/CAMPhotoQualityPrioritizationConfigurationCommand.h>
#import <CameraUI/CAMControlStatusBar.h>
#import <CameraUI/CAMIntervalometerTestHarness.h>
#import <CameraUI/CAMBurstIndicatorView.h>
#import <CameraUI/CAMTopBar.h>
#import <CameraUI/CAMNebulaDaemon.h>
#import <CameraUI/CAMPreviewView.h>
#import <CameraUI/CAMBadgeTray.h>
#import <CameraUI/CAMLocationController.h>
#import <CameraUI/CAMTimelapsePlaceholderResult.h>
#import <CameraUI/CAMCVCStillImageResultCoordinator.h>
#import <CameraUI/CAMThumbnailGenerator.h>
#import <CameraUI/CAMSampleBufferVideoFormatOutputCommand.h>
#import <CameraUI/CAMPanoramaPreviewView.h>
#import <CameraUI/CAMInstructionLabel.h>
#import <CameraUI/CAMNonDestructiveCropAspectRatioCommand.h>
#import <CameraUI/CAMGraphConfigurationInspectionCommand.h>
#import <CameraUI/CAMZoomDialDotsView.h>
#import <CameraUI/CAMFramerateIndicatorView.h>
#import <CameraUI/CAMQueryTimelapseDimensionsCommand.h>
#import <CameraUI/CAMShutterButtonRingView.h>
#import <CameraUI/CAMCaptureEngine.h>
#import <CameraUI/CAMTimelapseDiskUtilities.h>
#import <CameraUI/CAMCaptureConversions.h>
#import <CameraUI/CAMCaptureGraphConfiguration.h>
#import <CameraUI/CAMTimelapseMovieWriter.h>
#import <CameraUI/CAMCTMEndCaptureCommand.h>
#import <CameraUI/CAMPreviewViewController.h>
#import <CameraUI/CAMCaptureConfiguration.h>
#import <CameraUI/CAMBurstAnalysisResult.h>
#import <CameraUI/CAMModeAndDeviceConfigurationChangeListener.h>
#import <CameraUI/CAMModeAndDeviceConfigurationTestHarness.h>
#import <CameraUI/CAMNonDestructiveCropEnabledCommand.h>
#import <CameraUI/CAMDynamicShutterGestureRecognizer.h>
#import <CameraUI/CAMDynamicShutterControl.h>
#import <CameraUI/CAMVideoCorruptor.h>
#import <CameraUI/CAMPortraitLightingEffectStrengthCommand.h>
#import <CameraUI/CAMLiquidShutterRenderer.h>
#import <CameraUI/CAMZoomControlButtonMaskView.h>
#import <CameraUI/CAMFilterNameBadge.h>
#import <CameraUI/CAMCancelVideoZoomRampCommand.h>
#import <CameraUI/CAMNebulaSecondaryState.h>
#import <CameraUI/CAMBurstSession.h>
#import <CameraUI/CAMExposureSlider.h>
#import <CameraUI/CAMBufferNotificationObservance.h>
#import <CameraUI/CAMBufferNotificationObservanceChange.h>
#import <CameraUI/CAMStopPanoramaCommand.h>
#import <CameraUI/CAMBuffer.h>
#import <CameraUI/CAMBodyObjectResult.h>
#import <CameraUI/CAMExposureTargetBiasCommand.h>
#import <CameraUI/CAMPanoramaCaptureRequest.h>
#import <CameraUI/CAMMutablePanoramaCaptureRequest.h>
#import <CameraUI/CAMStageLightOverlayView.h>
#import <CameraUI/CAMAnalyticsCaptureEvent.h>
#import <CameraUI/CAMObservable.h>
#import <CameraUI/CAMLivePhotoStatusIndicator.h>
#import <CameraUI/CAMURLConfigurationRequest.h>
#import <CameraUI/CAMLowLightSlider.h>
#import <CameraUI/CAMStorageController.h>
#import <CameraUI/CAMHDRSuggestionMonitoringCommand.h>
#import <CameraUI/CAMStillImagePreviewQualityFilteredRenderingEnabledCommand.h>
#import <CameraUI/CAMExposureBiasStatusIndicatorTickMarksView.h>
#import <CameraUI/CAMExposureBiasStatusIndicator.h>
#import <CameraUI/CAMApplicationDelegate.h>
#import <CameraUI/CAMPrepareStillImageCaptureCommand.h>
#import <CameraUI/CAMAnimationDelegate.h>
#import <CameraUI/CAMAnimationHelper.h>
#import <CameraUI/CAMHDRBadge.h>
#import <CameraUI/CAMTimelapseBackendController.h>
#import <CameraUI/CAMPhysicalCaptureNotifier.h>
#import <CameraUI/CAMPanoramaOutput.h>
#import <CameraUI/CAMDescriptionOverlayView.h>
#import <CameraUI/CAMAnalyticsIgnoredShutterEvent.h>
#import <CameraUI/CAMHDRStatusIndicator.h>
#import <CameraUI/CAMStillImageLocalPersistenceResult.h>
#import <CameraUI/CAMTransientDataSource.h>
#import <CameraUI/CAMCameraViewController.h>
#import <CameraUI/CAMFullscreenViewfinderLayout.h>
