/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:50:42 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/CoreData.framework/CoreData
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _NSPersistenceUtilities : NSObject
+(void)initialize;
+(unsigned long long)attributeTypeForXMLInfo:(id)arg1 ;
+(BOOL)_setURL:(id)arg1 forPersistentStore:(id)arg2 withCoordinator:(id)arg3 ;
@end

