/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:36:41 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SleepDaemon.framework/SleepDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/HDSPSleepScheduleStateObserver.h>
#import <libobjc.A.dylib/HDSPSleepTracker.h>

@protocol HDSPSleepTrackerDelegate, HKSPQueueBackedScheduler;
@class HDSPEnvironment, HKSPSleepScheduleModel, NSString;

@interface HDSPTimeInBedTracker : NSObject <HDSPSleepScheduleStateObserver, HDSPSleepTracker> {

	HDSPEnvironment* _environment;
	id<HDSPSleepTrackerDelegate> _delegate;
	id<HKSPQueueBackedScheduler> _sleepIntervalScheduler;

}

@property (nonatomic,readonly) id<HKSPQueueBackedScheduler> sleepIntervalScheduler;              //@synthesize sleepIntervalScheduler=_sleepIntervalScheduler - In the implementation block
@property (nonatomic,readonly) BOOL isTimeInBedTrackingEnabled; 
@property (nonatomic,readonly) HKSPSleepScheduleModel * sleepScheduleModel; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) id<HDSPSleepTrackerDelegate> delegate;                       //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,__weak,readonly) HDSPEnvironment * environment;                             //@synthesize environment=_environment - In the implementation block
-(id)initWithEnvironment:(id)arg1 ;
-(void)sleepScheduleStateDidChange:(unsigned long long)arg1 previousState:(unsigned long long)arg2 reason:(unsigned long long)arg3 ;
-(void)environmentWillBecomeReady:(id)arg1 ;
-(HKSPSleepScheduleModel *)sleepScheduleModel;
-(id)computeSleepIntervalsForInterval:(id)arg1 ;
-(id)_createSleepSessionWithEndDate:(id)arg1 endReason:(unsigned long long)arg2 ;
-(void)setDelegate:(id<HDSPSleepTrackerDelegate>)arg1 ;
-(id<HKSPQueueBackedScheduler>)sleepIntervalScheduler;
-(BOOL)isTimeInBedTrackingEnabled;
-(id)_computeSessionMetadataForInterval:(id)arg1 ;
-(id<HDSPSleepTrackerDelegate>)delegate;
-(HDSPEnvironment *)environment;
-(void)_endSleepSessionWithReason:(unsigned long long)arg1 ;
-(id)processedSessionForSession:(id)arg1 ;
-(id)_computeSleepSessionStartBeforeDate:(id)arg1 ;
@end

