/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:50:55 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/Frameworks/WatchKit.framework/WatchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SPError : NSObject
+(id)errorWithCode:(long long)arg1 ;
+(id)errorWithCode:(long long)arg1 additionalDescription:(id)arg2 ;
+(BOOL)isValidationErrorCode:(long long)arg1 ;
@end

