#import <WiFiVelocity/W5BluetoothDevice.h>
#import <WiFiVelocity/W5DiagnosticsTestRequest.h>
#import <WiFiVelocity/W5PowerStatus.h>
#import <WiFiVelocity/W5Status.h>
#import <WiFiVelocity/W5Event.h>
#import <WiFiVelocity/W5WiFiChannel.h>
#import <WiFiVelocity/W5LogItemReceipt.h>
#import <WiFiVelocity/W5WiFiStatus.h>
#import <WiFiVelocity/W5BluetoothStatus.h>
#import <WiFiVelocity/W5WiFiLinkQualityUpdate.h>
#import <WiFiVelocity/W5WiFiPreferredNetwork.h>
#import <WiFiVelocity/W5DebugConfiguration.h>
#import <WiFiVelocity/W5WiFiScanResult.h>
#import <WiFiVelocity/W5NetworkStatus.h>
#import <WiFiVelocity/W5PingResult.h>
#import <WiFiVelocity/W5Peer.h>
#import <WiFiVelocity/W5LogItemRequest.h>
#import <WiFiVelocity/W5Client.h>
#import <WiFiVelocity/W5DiagnosticsTestResult.h>
#import <WiFiVelocity/W5AWDLStatus.h>
