#import <SiriInstrumentation/LTSchemaASRSpeechTranslationEvent.h>
#import <SiriInstrumentation/SISchemaAcousticProfile.h>
#import <SiriInstrumentation/SISchemaActiveAudioDevice.h>
#import <SiriInstrumentation/SISchemaActiveStatus.h>
#import <SiriInstrumentation/SISchemaAggregatedMetrics.h>
#import <SiriInstrumentation/SISchemaAnyEvent.h>
#import <SiriInstrumentation/LCServiceApplicationConfiguration.h>
#import <SiriInstrumentation/SISchemaAudioFirstBufferRecorded.h>
#import <SiriInstrumentation/SISchemaAudioStopRecording.h>
#import <SiriInstrumentation/SIServiceBatchInfo.h>
#import <SiriInstrumentation/LTSchemaBatchTranslationEvent.h>
#import <SiriInstrumentation/LCServiceBlackListedField.h>
#import <SiriInstrumentation/LCServiceBlacklistedFields.h>
#import <SiriInstrumentation/SISchemaCarPlayHeadUnitContext.h>
#import <SiriInstrumentation/SISchemaCarPlayInvocationContext.h>
#import <SiriInstrumentation/SISchemaCasinoRelationship.h>
#import <SiriInstrumentation/LCServiceCategoryConfiguration.h>
#import <SiriInstrumentation/SISchemaClientEvent.h>
#import <SiriInstrumentation/SISchemaClientEventMetadata.h>
#import <SiriInstrumentation/SISchemaClientFlow.h>
#import <SiriInstrumentation/SISchemaClientTransportEventMetadata.h>
#import <SiriInstrumentation/LCServiceConfigurationRequest.h>
#import <SiriInstrumentation/LCServiceConfigurationResponse.h>
#import <SiriInstrumentation/SISchemaConversationTrace.h>
#import <SiriInstrumentation/SISchemaDailyDeviceStatus.h>
#import <SiriInstrumentation/SISchemaDeviceDynamicContext.h>
#import <SiriInstrumentation/SISchemaDeviceFixedContext.h>
#import <SiriInstrumentation/SIServiceDeviceUploadInfo.h>
#import <SiriInstrumentation/SISchemaDialogOutput.h>
#import <SiriInstrumentation/SISchemaDictationAlternativeSelected.h>
#import <SiriInstrumentation/SISchemaDictationAlternativesPresent.h>
#import <SiriInstrumentation/SISchemaDictationAlternativesViewed.h>
#import <SiriInstrumentation/SISchemaDictationContext.h>
#import <SiriInstrumentation/SISchemaDictationEndPointCancel.h>
#import <SiriInstrumentation/SISchemaDictationEndPointStop.h>
#import <SiriInstrumentation/SISchemaDictationTranscriptionMetadata.h>
#import <SiriInstrumentation/LTSchemaDisambiguationSpeechTranslationEvent.h>
#import <SiriInstrumentation/SISchemaEnabledStatus.h>
#import <SiriInstrumentation/SISchemaEnrolledUserState.h>
#import <SiriInstrumentation/LTSchemaError.h>
#import <SiriInstrumentation/SISchemaHardwareInterfaceIdentifier.h>
#import <SiriInstrumentation/SISchemaHomeKitAccessoryResponse.h>
#import <SiriInstrumentation/SIServiceInstrumentationBatch.h>
#import <SiriInstrumentation/SIServiceInstrumentationBatchResponse.h>
#import <SiriInstrumentation/SISchemaInvocation.h>
#import <SiriInstrumentation/LTSchemaLIDSpeechTranslationEvent.h>
#import <SiriInstrumentation/SISchemaLanguageProfile.h>
#import <SiriInstrumentation/LTSchemaLocaleConfidence.h>
#import <SiriInstrumentation/SISchemaLocaleIdentifier.h>
#import <SiriInstrumentation/SISchemaLocation.h>
#import <SiriInstrumentation/LCServiceLoggingConfiguration.h>
#import <SiriInstrumentation/LCServiceLoggingParameters.h>
#import <SiriInstrumentation/LTSchemaMTClientEvent.h>
#import <SiriInstrumentation/LTSchemaMTSpeechTranslationEvent.h>
#import <SiriInstrumentation/SISchemaMultiUserState.h>
#import <SiriInstrumentation/PETSchemaPET1Key.h>
#import <SiriInstrumentation/PETSchemaPETAggregatedMessage.h>
#import <SiriInstrumentation/PETSchemaPETAggregationKey.h>
#import <SiriInstrumentation/PETSchemaPETDistribution.h>
#import <SiriInstrumentation/PETSchemaPETMetadata.h>
#import <SiriInstrumentation/PETSchemaPETRawMessage.h>
#import <SiriInstrumentation/PETSchemaPETUpload.h>
#import <SiriInstrumentation/SISchemaPersonalization.h>
#import <SiriInstrumentation/SISchemaPunchOut.h>
#import <SiriInstrumentation/SISchemaRawSpeechProfileData.h>
#import <SiriInstrumentation/SISchemaRedactableString.h>
#import <SiriInstrumentation/LTSchemaSafariFeedbackEvent.h>
#import <SiriInstrumentation/SISchemaServerEvent.h>
#import <SiriInstrumentation/SISchemaServerEventMetadata.h>
#import <SiriInstrumentation/SISchemaServerGeneratedDismissal.h>
#import <SiriInstrumentation/SIServiceServerUploadInfo.h>
#import <SiriInstrumentation/SISchemaSiriCue.h>
#import <SiriInstrumentation/SISchemaSiriResponseContext.h>
#import <SiriInstrumentation/SISchemaSiriUISettings.h>
#import <SiriInstrumentation/SISchemaSpeechResultSelected.h>
#import <SiriInstrumentation/SISchemaSpeechTranscription.h>
#import <SiriInstrumentation/LTSchemaSpeechTranslationEvent.h>
#import <SiriInstrumentation/LTSchemaTTSSpeechTranslationEvent.h>
#import <SiriInstrumentation/LTSchemaTask.h>
#import <SiriInstrumentation/SISchemaTextToSpeechBegin.h>
#import <SiriInstrumentation/SISchemaTextToSpeechEnd.h>
#import <SiriInstrumentation/SISchemaTurnInteraction.h>
#import <SiriInstrumentation/SISchemaUIStateDismissed.h>
#import <SiriInstrumentation/SISchemaUIStatePresenting.h>
#import <SiriInstrumentation/SISchemaUIStateTransition.h>
#import <SiriInstrumentation/SISchemaUUFRCompletion.h>
#import <SiriInstrumentation/SISchemaUUFRFatalError.h>
#import <SiriInstrumentation/SISchemaUUFRPresented.h>
#import <SiriInstrumentation/SISchemaUUFRSaid.h>
#import <SiriInstrumentation/SISchemaUUFRShown.h>
#import <SiriInstrumentation/SISchemaUserDataContainer.h>
#import <SiriInstrumentation/SISchemaUserSpeechDuration.h>
#import <SiriInstrumentation/SISchemaUserViewRegionInteraction.h>
#import <SiriInstrumentation/SISchemaViewContainer.h>
#import <SiriInstrumentation/SISchemaVoiceTriggerMetrics.h>
