/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:37:47 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/AccessibilityUI.framework/AccessibilityUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_xpc_object, OS_dispatch_queue;
@class NSObject, AXAccessQueue, NSMutableDictionary, NSHashTable;

@interface AXUIClientConnection : NSObject {

	BOOL _connected;
	NSObject*<OS_xpc_object> _xpcConnection;
	AXAccessQueue* _connectionAccessQueue;
	NSMutableDictionary* _registeredClients;
	AXAccessQueue* _registeredClientsAccessQueue;
	NSHashTable* _stateObservers;
	NSObject*<OS_dispatch_queue> _stateObserverQueue;

}

@property (nonatomic,retain) NSObject*<OS_xpc_object> xpcConnection;                       //@synthesize xpcConnection=_xpcConnection - In the implementation block
@property (nonatomic,retain) AXAccessQueue * connectionAccessQueue;                        //@synthesize connectionAccessQueue=_connectionAccessQueue - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * registeredClients;                      //@synthesize registeredClients=_registeredClients - In the implementation block
@property (nonatomic,retain) AXAccessQueue * registeredClientsAccessQueue;                 //@synthesize registeredClientsAccessQueue=_registeredClientsAccessQueue - In the implementation block
@property (assign,getter=isConnected,nonatomic) BOOL connected;                            //@synthesize connected=_connected - In the implementation block
@property (nonatomic,retain) NSHashTable * stateObservers;                                 //@synthesize stateObservers=_stateObservers - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> stateObserverQueue;              //@synthesize stateObserverQueue=_stateObserverQueue - In the implementation block
+(id)sharedClientConnection;
-(void)setXpcConnection:(NSObject*<OS_xpc_object>)arg1 ;
-(void)setConnected:(BOOL)arg1 ;
-(BOOL)isConnected;
-(NSObject*<OS_dispatch_queue>)stateObserverQueue;
-(NSObject*<OS_xpc_object>)xpcConnection;
-(void)setConnectionAccessQueue:(AXAccessQueue *)arg1 ;
-(void)setStateObserverQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)performBlockWithXPCConnection:(/*^block*/id)arg1 ;
-(void)unregisterConnectionStateObserver:(id)arg1 ;
-(id)_clientWithIdentifier:(id)arg1 ;
-(id)init;
-(void)setRegisteredClients:(NSMutableDictionary *)arg1 ;
-(void)registerConnectionStateObserver:(id)arg1 ;
-(NSHashTable *)stateObservers;
-(AXAccessQueue *)registeredClientsAccessQueue;
-(void)setRegisteredClientsAccessQueue:(AXAccessQueue *)arg1 ;
-(void)unregisterClient:(id)arg1 withIdentifier:(id)arg2 ;
-(void)setStateObservers:(NSHashTable *)arg1 ;
-(void)_broadcastConnectedStateChange;
-(void)registerClient:(id)arg1 withIdentifier:(id)arg2 ;
-(AXAccessQueue *)connectionAccessQueue;
-(NSMutableDictionary *)registeredClients;
@end

