/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:36:53 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/VFX.framework/VFX
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ECS.Scheduler : _UKNOWN_SUPERCLASS_ {

	 entityManager;
	 lock;
	 currentJobID;
	 recurrentJobs;
	 orderedRecurrentJobs;
	 remainingJobsForThisFrame;
	 pendingJobsToEnqueueForThisFrame;
	 pendingJobsToEnqueueForThisFrameOnly;
	 groupsToUnregister;
	 needsRescheduling;
	 needsReschedulingForThisFrame;
	 dependenciesByJob;
	 schedulerEventsRecordedDuringLastFrame;
	 queriesRecordedDuringLastFrame;
	 schedulerEventsRecordedDuringThisFrame;
	 queriesRecordedDuringThisFrame;
	 simulationTimeScale;

}
@end

