#import <VFX/VFXREScene.h>
#import <VFX/VFX.VFXScene.h>
#import <VFX/_TtCC3VFX8VFXSceneP33_DBE3D0EF7607B52568E80C840F179BF911BindingImpl.h>
#import <VFX/comAppleVfxConfetti.h>
#import <VFX/VFX.VFXRenderer.h>
#import <VFX/VFX.VFXView.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration10SubContext.h>
#import <VFX/VFXCore.DepthPrepareSystem.h>
#import <VFX/VFXCore.ParticleDefaultRenderSystem.h>
#import <VFX/VFXCore.ParticleMeshRenderSystem.h>
#import <VFX/VFXCore.ParticleRibbonSystem.h>
#import <VFX/VFXCore.TexturePool.h>
#import <VFX/VFXCore.GPUHelper.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration11TemplateSet.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration13ParameterBase.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration11ParameterIn.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration12ParameterOut.h>
#import <VFX/_TtCF7VFXCore25objCAppendOnDestroyActionFTP_FT_T__T_L_7Deleter.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration10BaseObject.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration12ContextEntry.h>
#import <VFX/VFXCore.RotateActionSystem.h>
#import <VFX/VFXCore.SineMoveSystem.h>
#import <VFX/VFXCore.SineYWaveSystem.h>
#import <VFX/VFXCore.TransientPushSystem.h>
#import <VFX/VFXCore.VoxelizationSystem.h>
#import <VFX/VFXCore.DebugVoxelSystem.h>
#import <VFX/VFXCore.DisplayLinkTarget.h>
#import <VFX/VFXCore.DisplayClock.h>
#import <VFX/VFXCore.CameraSystem.h>
#import <VFX/VFXCore.PrepareRenderSystem.h>
#import <VFX/VFXCore.CameraUISystem.h>
#import <VFX/VFXCore.LODSystem.h>
#import <VFX/VFXCore.GenericLODSystem.h>
#import <VFX/VFXCore.ScatteringComputeSystem.h>
#import <VFX/VFXCore.ScatteringRenderSystem.h>
#import <VFX/VFXCore.ScriptCodeGen.h>
#import <VFX/VFXCore.MetalScriptCodeGen.h>
#import <VFX/VFXCore.CScriptCodeGen.h>
#import <VFX/VFXCore.SwiftScriptCodeGen.h>
#import <VFX/VFXCore.LegacyParticleRenderSystem.h>
#import <VFX/VFXCore.LegacyParticleEmitterSystem.h>
#import <VFX/VFXCore.PointCacheGeneratorSystem.h>
#import <VFX/_TtCV7VFXCore17PointCacheEmitter6System.h>
#import <VFX/VFXCore.DeferredRendering.h>
#import <VFX/VFXCore.TransformBucket.h>
#import <VFX/VFXCore.MaterialBucket.h>
#import <VFX/VFXCore.RenderBuckets.h>
#import <VFX/VFXCore.MeshRenderSystem.h>
#import <VFX/VFXCore.OpaqueRenderPass.h>
#import <VFX/VFXCore.TransparentRenderPass.h>
#import <VFX/VFXCore.ParticleFlockingAlignOrientationSystem.h>
#import <VFX/VFXCore.ParticleFlockingAlignVelocityOnPlaneSystem.h>
#import <VFX/VFXCore.ParticleFlockingConstrainToAreaSystem.h>
#import <VFX/VFXCore.ParticleFlockingConstrainToPlaneSystem.h>
#import <VFX/VFXCore.ParticleFlockingFlyTowardsAreaSystem.h>
#import <VFX/VFXCore.ParticleFlockingSolverData.h>
#import <VFX/VFXCore.ParticleFlockingSolverSystem.h>
#import <VFX/VFXCore.ParticleFlockingSpeedControlSystem.h>
#import <VFX/VFXCore.ParticleComputeNeighbors.h>
#import <VFX/VFXCore.ParticleUpdateAABB.h>
#import <VFX/VFXCore.ParticleLifeUpdateAndDieSystem.h>
#import <VFX/VFXCore.PostProcessSystem.h>
#import <VFX/VFXCore.VortexSystem.h>
#import <VFX/VFXCore.CullingSystem.h>
#import <VFX/VFXCore.CullGroupDisposeSystem.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration11MetadataSet.h>
#import <VFX/VFXCore.NavigationSystem.h>
#import <VFX/VFXCore.LensBlurPassSystem.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration17CodeSourceSnippet.h>
#import <VFX/VFXCore.DeferredVoxelConeTracingSystem.h>
#import <VFX/VFXCore.ClampBoxSystem.h>
#import <VFX/VFXCore.GlobalClampBoxSystem.h>
#import <VFX/VFXCore.ParticleContinousSpawnSystem.h>
#import <VFX/_TtCV7VFXCore25ParticleSpawnOverDistance6System.h>
#import <VFX/VFXCore.ParticleVariableSpawnSystem.h>
#import <VFX/VFXCore.ParticleBurstSpawnSystem.h>
#import <VFX/VFXCore.ParticlePeriodicBurstSpawnSystem.h>
#import <VFX/_TtCV7VFXCore16ParticleSubSpawn6System.h>
#import <VFX/VFXCore.ParticleSubSpawnAddStateSystem.h>
#import <VFX/VFXCore.ParticleSubSpawnSystem.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration17CustomCodeSnippet.h>
#import <VFX/VFXCore.ParticleFluidSolver2DEmitterSystem.h>
#import <VFX/VFXCore.ParticleFluidSolver2DSolverData.h>
#import <VFX/VFXCore.ParticleFluidSolver2DSolverSystem.h>
#import <VFX/VFXCore.GraphCodeGen.h>
#import <VFX/_TtCV7VFXCore20GraphScriptingConfig6System.h>
#import <VFX/_TtCV7VFXCore20GraphScriptingConfig9GPUSystem.h>
#import <VFX/VFXCore.EmitterPrepareRuntime.h>
#import <VFX/VFXCore.ParticleEmitterTransport.h>
#import <VFX/_TtCV7VFXCore21ParticleColorOverLife6System.h>
#import <VFX/_TtCV7VFXCore21ParticleColorOverLife9GPUSystem.h>
#import <VFX/_TtCV7VFXCore20ParticleSizeOverLife6System.h>
#import <VFX/_TtCV7VFXCore20ParticleSizeOverLife9GPUSystem.h>
#import <VFX/_TtCV7VFXCore23ParticleOpacityOverLife6System.h>
#import <VFX/_TtCV7VFXCore23ParticleOpacityOverLife9GPUSystem.h>
#import <VFX/_TtCV7VFXCore25ParticleColorOverVelocity6System.h>
#import <VFX/_TtCV7VFXCore27ParticleOpacityOverVelocity6System.h>
#import <VFX/_TtCV7VFXCore23OrientationOverVelocity6System.h>
#import <VFX/_TtCV7VFXCore24ParticleSizeOverVelocity6System.h>
#import <VFX/_TtCV7VFXCore24ParticleColorOverTexture6System.h>
#import <VFX/_TtCV7VFXCore23ParticleSizeOverTexture6System.h>
#import <VFX/_TtCV7VFXCore27ParticlePositionOverTexture6System.h>
#import <VFX/_TtCV7VFXCore25ParticleColorOverPosition6System.h>
#import <VFX/VFXCore.ParticleOpacityEvolutionSystem.h>
#import <VFX/_TtCV7VFXCore21OrientationConstraint6System.h>
#import <VFX/VFXCore.ParticleAngleEvolutionSystem.h>
#import <VFX/_TtCV7VFXCore29ParticleTextureFrameEvolution9GPUSystem.h>
#import <VFX/VFXCore.ParticleTextureFrameEvolutionSystem.h>
#import <VFX/_TtCV7VFXCore13ParticleForce9GPUSystem.h>
#import <VFX/VFXCore.ParticleForceSystem.h>
#import <VFX/_TtCV7VFXCore12ParticleDrag9GPUSystem.h>
#import <VFX/VFXCore.ParticleDragSystem.h>
#import <VFX/_TtCV7VFXCore13ParticleNoise9GPUSystem.h>
#import <VFX/VFXCore.ParticleNoiseSystem.h>
#import <VFX/VFXCore.AttachSystem.h>
#import <VFX/VFXCore.ProjectorSystem.h>
#import <VFX/_TtCV7VFXCore26ParticleTargetFromPosition6System.h>
#import <VFX/VFXCore.DistanceConstraintSystem.h>
#import <VFX/_TtCV7VFXCore17ParticleIntegrate6System.h>
#import <VFX/_TtCV7VFXCore17ParticleIntegrate9GPUSystem.h>
#import <VFX/VFXCore.PrivateHeap.h>
#import <VFX/VFXCore.NewBufferPool.h>
#import <VFX/VFXCore.BufferPool.h>
#import <VFX/VFXCore.ParticleRibbonTrailsSystem.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration7Context.h>
#import <VFX/_TtCCO7VFXCore14CodeGeneration7Context14GenerationData.h>
#import <VFX/VFXCore.VFXCoreView.h>
#import <VFX/VFXCore.SkyboxSystem.h>
#import <VFX/VFXCore.RenderGraphSystem.h>
#import <VFX/VFXCore.ParticlePrepareGPUSystem.h>
#import <VFX/VFXCore.ParticleGPUDownload.h>
#import <VFX/VFXCore.NavigationConfiguration.h>
#import <VFX/VFXCore.ConvexMeshGeometry.h>
#import <VFX/VFXCore.TriangleMeshGeometry.h>
#import <VFX/VFXCore.HeightFieldGeometry.h>
#import <VFX/VFXCore.PBRMaterial.h>
#import <VFX/VFXCore.PropertyDescription.h>
#import <VFX/VFXCore.SkeletonData.h>
#import <VFX/VFXCore.SkeletonAnimation.h>
#import <VFX/VFXCore.SkeletonAnimationSystem.h>
#import <VFX/VFXCore.SkeletonSystem.h>
#import <VFX/VFXCore.SkinningSystem.h>
#import <VFX/VFXCore.LODResource.h>
#import <VFX/VFXCore.MeshFileSystem.h>
#import <VFX/VFXREDrawCall.h>
#import <VFX/VFXREManager.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration7Library.h>
#import <VFX/VFXCore.BoidsRenderSystem.h>
#import <VFX/VFXCore.ProfilerViewerSystem.h>
#import <VFX/VFXCore.ParticleSphereAttractorSystem.h>
#import <VFX/VFXCore.ParticleSDFAttractorSystem.h>
#import <VFX/_TtCV7VFXCore24ParticleLocalBoxCollider6System.h>
#import <VFX/_TtCV7VFXCore15ParticleCollide9CPUSystem.h>
#import <VFX/_TtCV7VFXCore15ParticleCollide9GPUSystem.h>
#import <VFX/VFXCore.AnimationComputeLocalTimeSystem.h>
#import <VFX/VFXCore.BasicAnimationSystem.h>
#import <VFX/VFXCore.KeyframeAnimationSystem.h>
#import <VFX/VFXCore.LookAtSystem.h>
#import <VFX/_TtCV7VFXCore19ParticleGrowEmitter6System.h>
#import <VFX/_TtCV7VFXCore13ParticleSetID6System.h>
#import <VFX/_TtCV7VFXCore16ParticleMassInit6System.h>
#import <VFX/_TtCV7VFXCore16ParticleLifeInit6System.h>
#import <VFX/_TtCV7VFXCore20ParticleVelocityInit6System.h>
#import <VFX/_TtCV7VFXCore23ParticleOrientationInit6System.h>
#import <VFX/_TtCV7VFXCore27ParticleAngularVelocityInit6System.h>
#import <VFX/_TtCV7VFXCore16ParticleSizeInit6System.h>
#import <VFX/_TtCV7VFXCore17ParticlePivotInit6System.h>
#import <VFX/_TtCV7VFXCore17ParticleAngleInit6System.h>
#import <VFX/_TtCV7VFXCore25ParticleAngleVelocityInit6System.h>
#import <VFX/_TtCV7VFXCore24ParticleTextureFrameInit6System.h>
#import <VFX/_TtCV7VFXCore17ParticleColorInit6System.h>
#import <VFX/VFXCore.EmitterShapeSystem.h>
#import <VFX/_TtCV7VFXCore30ParticleTargetFromPositionInit6System.h>
#import <VFX/_TtCV7VFXCore14ParticlePhysic6System.h>
#import <VFX/VFXCore.VectorRenderSystemRenderPipelineStates.h>
#import <VFX/VFXCore.VectorRenderSystem.h>
#import <VFX/VFXCore.DebugCullingSystem.h>
#import <VFX/VFXCore.DebugLODSystem.h>
#import <VFX/VFXCore.DebugVFXSystem.h>
#import <VFX/VFXCore.WireframeLayerSystem.h>
#import <VFX/VFXCore.DebugShaderSystem.h>
#import <VFX/VFXCore.DebugDrawingSystem.h>
#import <VFX/VFXCore.DebugInfoSystem.h>
#import <VFX/VFXCore.IBLGeneratorSystem.h>
#import <VFX/VFXCore.MDLImporter.h>
#import <VFX/VFXCore.UpdateWorldAABBSystem.h>
#import <VFX/VFXCore.TextureSystem.h>
#import <VFX/VFXCore.TextureDownloadSystem.h>
#import <VFX/VFXCore.TextureDiscardSystem.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration9Resources.h>
#import <VFX/VFXCore.SDFFileSystem.h>
#import <VFX/VFXCore.SDFGeneratorSystem.h>
#import <VFX/VFXCore.DebugSDFColliderSystem.h>
#import <VFX/VFXCore.MTLLibraryWatcher.h>
#import <VFX/VFXCore.ShaderPool.h>
#import <VFX/VFXCore.BloomPassSystem.h>
#import <VFX/VFXCore.VectorFieldFileSystem.h>
#import <VFX/VFXCore.VectorFieldDebugRenderSystem.h>
#import <VFX/VFXCore.ParticleVectorFieldSystem.h>
#import <VFX/VFXCore.HierarchySystem.h>
#import <VFX/VFXCore.LastTransformSystem.h>
#import <VFX/VFXCore.StaticToFixedSystem.h>
#import <VFX/VFXCore.KeyframeTimelineRuntime.h>
#import <VFX/VFXCore.KeyframeTimeline.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration11ContextExit.h>
#import <VFX/VFXCore.RenderCommandEncoder.h>
#import <VFX/VFXCore.PerformanceCounterRecorder.h>
#import <VFX/VFXCore.Renderer.h>
#import <VFX/VFXCore.RendererPreUpdateSystem.h>
#import <VFX/VFXCore.RendererPostUpdateSystem.h>
#import <VFX/VFXCore.KillShapeSystem.h>
#import <VFX/VFXCore.SceneKitAssetSystem.h>
#import <VFX/VFXCore.SceneKitSystem.h>
#import <VFX/VFXCore.EmitterScriptRunner.h>
#import <VFX/VFXCore.ScriptBuilderSystem.h>
#import <VFX/VFXCore.DrawCallDisposeSystem.h>
#import <VFX/VFXCore.ScriptManagerDebugSystem.h>
#import <VFX/VFXCore.StatisticsUISystem.h>
#import <VFX/VFXCore.CompositeSystem.h>
#import <VFX/VFXCore.iOSPlatform.h>
#import <VFX/VFXCore.macOSPlatform.h>
#import <VFX/VFXCore.watchOSPlatform.h>
#import <VFX/VFXCore.tvOSPlatform.h>
#import <VFX/_TtCV7VFXCore18ParticleInitScript6System.h>
#import <VFX/VFXCore.VFXSaver.h>
#import <VFX/VFXCore.VFXLoader.h>
#import <VFX/VFXCore.AssetContainer.h>
#import <VFX/VFXCore.AssetManager.h>
#import <VFX/VFXCore.VertexLayout.h>
#import <VFX/VFXCore.AttributeTable.h>
#import <VFX/VFXCore.Mesh.h>
#import <VFX/_TtCO7VFXCore14CodeGeneration11CodeSnippet.h>
#import <VFX/VFXCore.Material.h>
#import <VFX/VFXCore.CustomMaterial.h>
#import <VFX/VFXCore.SpriteMaterial.h>
#import <VFX/MetalBuffer.h>
#import <VFX/FramebufferDescriptor.h>
#import <VFX/MetalContext.h>
#import <VFX/ECSBundleLocator.h>
#import <VFX/ECS.InputEvent.h>
#import <VFX/ECS.InputClearSystem.h>
#import <VFX/_TtC3ECSP33_9DEAB319C58FB7C02B2A098E48C157E69XcodeInfo.h>
#import <VFX/ECS.XcodeCommandBuilder.h>
#import <VFX/ECS.ObjectReader.h>
#import <VFX/_TtC3ECSP33_83682B33CF2DD64B57A89285DAFFAE8A13SourceWatcher.h>
#import <VFX/ECS.CodeReloader.h>
#import <VFX/ECS.CodeLoader.h>
#import <VFX/_TtC3ECSP33_30BEBEFDF7AEA16C222FB8F16DF0D65A15SwiftCodeLoader.h>
#import <VFX/_TtC3ECSP33_30BEBEFDF7AEA16C222FB8F16DF0D65A11CCodeLoader.h>
#import <VFX/ECS.MetalToolchainCodeLoader.h>
#import <VFX/_TtC3ECSP33_30BEBEFDF7AEA16C222FB8F16DF0D65A18MetalAPICodeLoader.h>
#import <VFX/ECS.SymbolReloader.h>
#import <VFX/ECS.CommandQueue.h>
#import <VFX/ECS.EventDisposeSystem.h>
#import <VFX/ECS.ComponentRegistry.h>
#import <VFX/ECS.ComponentsDataChunk.h>
#import <VFX/ECS.WakeUpEvent.h>
#import <VFX/ECS.GenericComponentSystem.h>
#import <VFX/ECS.ECSDebugSystem.h>
#import <VFX/ECS.EntityClass.h>
#import <VFX/ECS.EntityFamily.h>
#import <VFX/ECS.EntityManager.h>
#import <VFX/ECS.SerializationContext.h>
#import <VFX/ECS.QueryManager.h>
#import <VFX/ECS.Scheduler.h>
#import <VFX/ECS.DispatchApplyScheduler.h>
#import <VFX/ECS.Logger.h>
#import <VFX/ECS.HeapAllocator.h>
#import <VFX/ECS.FrameAllocator.h>
#import <VFX/ECS.StackAllocator.h>
#import <VFX/ECS.StringDumper.h>
#import <VFX/ECS.Bitset.h>
#import <VFX/ECS.ImguiInstance.h>
#import <VFX/_TtCZFO3ECS5ImGui6testUIFT_T_L_10TestObject.h>
#import <VFX/ECS.RuntimeThread.h>
#import <VFX/ECS.FrameProfiler.h>
#import <VFX/_TtCFVV3ECS8Metadata5Class34_propertyDescriptionsAndStartPointFT_GSqTGSaVVS_8Property11Description_GSqVs5Int32___L_11NameAndType.h>
#import <VFX/_TtCFVV3ECS8Metadata6Struct20propertyDescriptionsFT_GSqGSaVVS_8Property11Description__L_11NameAndType.h>
#import <VFX/ECS.SceneComponentStorage.h>
#import <VFX/ECS.ClassComponentStorage.h>
#import <VFX/ECS.WorkerComponentStorage.h>
#import <VFX/ECS.SchedulerDebugSystem.h>
#import <VFX/ECS.EngineTuningSystem.h>
#import <VFX/ECS.EntityInspectorSystem.h>
#import <VFX/ECS.ImGuiDebugSystem.h>
#import <VFX/Smoky.SMKFluidSolver2D.h>
#import <VFX/Smoky.SMKMarchingSquares.h>
