#import <PhotosImagingFoundation/IPAOrientationOperator.h>
#import <PhotosImagingFoundation/IPAScaleOperator.h>
#import <PhotosImagingFoundation/IPAPendingAutoSettings.h>
#import <PhotosImagingFoundation/IPAAutoSettings.h>
#import <PhotosImagingFoundation/IPAManualAutoSettings.h>
#import <PhotosImagingFoundation/IPARemoveAutoSettings.h>
#import <PhotosImagingFoundation/IPAAdjustmentVersion.h>
#import <PhotosImagingFoundation/IPAPhotoAdjustmentPipeline.h>
#import <PhotosImagingFoundation/IPAAdjustmentVersionInfo.h>
#import <PhotosImagingFoundation/IPAStraightenOperator.h>
#import <PhotosImagingFoundation/IPAVideoPlaybackSettings.h>
#import <PhotosImagingFoundation/IPAVideoAdjustmentStack.h>
#import <PhotosImagingFoundation/IPACropOperator.h>
#import <PhotosImagingFoundation/IPAAdjustment.h>
#import <PhotosImagingFoundation/IPAEditDescription.h>
#import <PhotosImagingFoundation/IPAPhotoAdjustmentStack.h>
#import <PhotosImagingFoundation/IPAMetadata.h>
#import <PhotosImagingFoundation/IPALocalPreviewSizeRegistry.h>
#import <PhotosImagingFoundation/IPAVideoAdjustment.h>
#import <PhotosImagingFoundation/IPAAffineImageTransform.h>
#import <PhotosImagingFoundation/IPAPhotoAdjustment.h>
#import <PhotosImagingFoundation/IPARectArray.h>
#import <PhotosImagingFoundation/IPAMutableRectArray.h>
#import <PhotosImagingFoundation/IPAAdjustmentSerialization.h>
#import <PhotosImagingFoundation/IPAAdjustmentStackSerializer.h>
#import <PhotosImagingFoundation/IPAPhotoAdjustmentStackSerializer.h>
#import <PhotosImagingFoundation/IPAVideoAdjustmentStackSerializer.h>
#import <PhotosImagingFoundation/IPAImageSizePolicy.h>
#import <PhotosImagingFoundation/IPAOriginalSizePolicy.h>
#import <PhotosImagingFoundation/IPAScaleImageSizePolicy.h>
#import <PhotosImagingFoundation/IPABestFitImageSizePolicy.h>
#import <PhotosImagingFoundation/IPABestFitImageWidthPolicy.h>
#import <PhotosImagingFoundation/IPABestFitImageHeightPolicy.h>
#import <PhotosImagingFoundation/IPAShortestEdgeImageSizePolicy.h>
#import <PhotosImagingFoundation/IPABestFitTotalPixelCountImageSizePolicy.h>
#import <PhotosImagingFoundation/IPABestFitEvenTotalPixelCountImageSizePolicy.h>
#import <PhotosImagingFoundation/IPABestFitEvenWidthTotalPixelCountImageSizePolicy.h>
#import <PhotosImagingFoundation/IPABestFitShortSideWithLongSideLimit.h>
#import <PhotosImagingFoundation/IPAAggregateLargestImageSizePolicy.h>
#import <PhotosImagingFoundation/IPAGeometryOperator.h>
#import <PhotosImagingFoundation/IPAIdentityOperator.h>
#import <PhotosImagingFoundation/IPAEditOperation.h>
#import <PhotosImagingFoundation/IPARegion.h>
#import <PhotosImagingFoundation/IPAMutableRegion.h>
#import <PhotosImagingFoundation/IPAImageGeometry.h>
#import <PhotosImagingFoundation/IPAPreviewSizeRegistry.h>
#import <PhotosImagingFoundation/IPAPreviewSizePolicy.h>
#import <PhotosImagingFoundation/IPAGeometryOperatorSequence.h>
#import <PhotosImagingFoundation/IPAPerspectiveOperator.h>
#import <PhotosImagingFoundation/IPAPerspectiveTransform.h>
#import <PhotosImagingFoundation/IPAVideoAdjustmentStackSerializer_v10.h>
#import <PhotosImagingFoundation/IPAPhotoAdjustmentStackSerializer_v10.h>
#import <PhotosImagingFoundation/IPAVideoAdjustmentStackSerializer_SLM_v11.h>
#import <PhotosImagingFoundation/IPASerializationManager.h>
#import <PhotosImagingFoundation/IPAAutoRegistryEntry.h>
#import <PhotosImagingFoundation/IPAAutoRegistry.h>
#import <PhotosImagingFoundation/IPAAdjustmentEnvelope.h>
#import <PhotosImagingFoundation/IPAImageTransform.h>
#import <PhotosImagingFoundation/IPAImageIdentityTransform.h>
#import <PhotosImagingFoundation/IPAPhotoAdjustmentStackSerializer_SLM_v11.h>
#import <PhotosImagingFoundation/IPAImageTransformSequence.h>
#import <PhotosImagingFoundation/IPAAdjustmentStack.h>
#import <PhotosImagingFoundation/IPAVideoOperation.h>
#import <PhotosImagingFoundation/IPAPosterFrameOperation.h>
#import <PhotosImagingFoundation/IPATrimOperation.h>
#import <PhotosImagingFoundation/IPASloMoOperation.h>
#import <PhotosImagingFoundation/IPAVideoAdjustmentStackSerializer_SLM_v10.h>
