/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:43:05 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SAObjects/SAIntentGroupSnippetTemplate.h>

@class SAUIColor, SAIntentGroupDetailLabelTemplateComponent, SALocation, NSString;

@interface SAIntentGroupMapSnippetTemplate : SAIntentGroupSnippetTemplate

@property (nonatomic,retain) SAUIColor * color; 
@property (nonatomic,retain) SAIntentGroupDetailLabelTemplateComponent * detailLabelComponent; 
@property (assign,nonatomic) BOOL interactive; 
@property (nonatomic,retain) SALocation * location; 
@property (nonatomic,copy) NSString * mapSize; 
@property (nonatomic,retain) id<SAIntentGroupSetMapLocation> updateLocationCommand; 
+(id)mapSnippetTemplate;
+(id)mapSnippetTemplateWithDictionary:(id)arg1 context:(id)arg2 ;
-(id)encodedClassName;
-(id)groupIdentifier;
-(BOOL)interactive;
-(void)setInteractive:(BOOL)arg1 ;
-(SALocation *)location;
-(void)setLocation:(SALocation *)arg1 ;
-(SAIntentGroupDetailLabelTemplateComponent *)detailLabelComponent;
-(void)setDetailLabelComponent:(SAIntentGroupDetailLabelTemplateComponent *)arg1 ;
-(void)setMapSize:(NSString *)arg1 ;
-(id<SAIntentGroupSetMapLocation>)updateLocationCommand;
-(void)setUpdateLocationCommand:(id<SAIntentGroupSetMapLocation>)arg1 ;
-(NSString *)mapSize;
-(SAUIColor *)color;
-(void)setColor:(SAUIColor *)arg1 ;
@end

