#import <SchoolTime/SCLSettingsSyncErrorBehavior.h>
#import <SchoolTime/SCLSettingsSyncErrorHandler.h>
#import <SchoolTime/SCLPBUnlockHistoryItem.h>
#import <SchoolTime/SCLScheduleRecurrence.h>
#import <SchoolTime/SCLSchoolModeXPCClient.h>
#import <SchoolTime/SCLPBScheduleSettings.h>
#import <SchoolTime/SCLSimpleSchedule.h>
#import <SchoolTime/SCLMutableSimpleSchedule.h>
#import <SchoolTime/SCLSettingsSyncState.h>
#import <SchoolTime/SCLSettingsSyncStateSynced.h>
#import <SchoolTime/SCLSettingsSyncStatePendingSend.h>
#import <SchoolTime/SCLSettingsSyncStateSending.h>
#import <SchoolTime/SCLSettingsSyncStateSent.h>
#import <SchoolTime/SCLSettingsSyncStateFailed.h>
#import <SchoolTime/SCLHistoryGroupKey.h>
#import <SchoolTime/SCLHistoryGroup.h>
#import <SchoolTime/SCLScheduleFormatter.h>
#import <SchoolTime/SCLScheduleFormatterItem.h>
#import <SchoolTime/SCLScheduleTimeFormatter.h>
#import <SchoolTime/SCLTimeIntervalsFormatter.h>
#import <SchoolTime/SCLTransportService.h>
#import <SchoolTime/SCLSuppressSchoolModeAssertion.h>
#import <SchoolTime/SCLSchoolMode.h>
#import <SchoolTime/SCLSchoolModeConfiguration.h>
#import <SchoolTime/SCLUnlockHistoryItem.h>
#import <SchoolTime/SCLUnlockEvent.h>
#import <SchoolTime/SCLSchedulingParameters.h>
#import <SchoolTime/SCLSchedulingEngine.h>
#import <SchoolTime/SCLSchoolModeServer.h>
#import <SchoolTime/SCLSchedule.h>
#import <SchoolTime/SCLTransportController.h>
#import <SchoolTime/SCLState.h>
#import <SchoolTime/SCLPBScheduleRequestResponse.h>
#import <SchoolTime/SCLPBScheduleRecurrence.h>
#import <SchoolTime/SCLPBScheduleRequest.h>
#import <SchoolTime/SCLSchoolModeCoordinator.h>
#import <SchoolTime/SCLSchoolModeCoordinatorConfiguration.h>
#import <SchoolTime/SCLTimeInterval.h>
#import <SchoolTime/SCLPBTimeInterval.h>
#import <SchoolTime/SCLPersistentSettings.h>
#import <SchoolTime/SCLScheduleSettings.h>
#import <SchoolTime/SCLMutableScheduleSettings.h>
#import <SchoolTime/SCLScheduleIntervalFormatter.h>
#import <SchoolTime/SCLWatchServer.h>
#import <SchoolTime/SCLRecurrenceSchedule.h>
#import <SchoolTime/SCLUnlockHistoryPersistentStore.h>
#import <SchoolTime/SCLSchoolModeServerSettings.h>
#import <SchoolTime/SCLDailySchedule.h>
#import <SchoolTime/SCLMutableDailySchedule.h>
#import <SchoolTime/SCLSettingsSyncCoordinator.h>
#import <SchoolTime/SCLScheduleAttributes.h>
#import <SchoolTime/SCLPBScheduleTime.h>
#import <SchoolTime/SCLSuppressSchoolModeAssertionManager.h>
#import <SchoolTime/SCLSuppressSchoolModeAssertionClient.h>
#import <SchoolTime/SCLScheduleTime.h>
#import <SchoolTime/SCLMutableScheduleTime.h>
#import <SchoolTime/SCLSchoolModeClientProxy.h>
#import <SchoolTime/SCLSchoolModeManager.h>
#import <SchoolTime/SCLSchoolModeManagerConfiguration.h>
#import <SchoolTime/SCLSettingsSyncContext.h>
#import <SchoolTime/SCLSettingsSyncStateMachine.h>
