/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:39:19 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class GEOMapItemChildPlace, GEOMapItemChildAction, GEOPublisherResult;

@interface GEOMapItemChildItem : NSObject {

	long long _childItemType;
	GEOMapItemChildPlace* _childItemPlace;
	GEOMapItemChildAction* _childItemAction;
	GEOPublisherResult* _publisherResult;

}

@property (assign,nonatomic) long long childItemType;                              //@synthesize childItemType=_childItemType - In the implementation block
@property (nonatomic,retain) GEOMapItemChildPlace * childItemPlace;                //@synthesize childItemPlace=_childItemPlace - In the implementation block
@property (nonatomic,retain) GEOMapItemChildAction * childItemAction;              //@synthesize childItemAction=_childItemAction - In the implementation block
@property (nonatomic,readonly) GEOPublisherResult * publisherResult;               //@synthesize publisherResult=_publisherResult - In the implementation block
-(long long)childItemType;
-(void)setChildItemType:(long long)arg1 ;
-(GEOMapItemChildPlace *)childItemPlace;
-(void)setChildItemPlace:(GEOMapItemChildPlace *)arg1 ;
-(GEOMapItemChildAction *)childItemAction;
-(void)setChildItemAction:(GEOMapItemChildAction *)arg1 ;
-(id)initWithPublisherResult:(id)arg1 ;
-(id)initWithChildItem:(id)arg1 ;
-(id)initWithChildPlace:(id)arg1 ;
-(GEOPublisherResult *)publisherResult;
@end

