/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:36:21 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/RelevanceEngine.framework/RelevanceEngine
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol REBacktrackingTokenBuffer, REScriptParserDelegate;
@interface REScriptParser : NSObject {

	id<REBacktrackingTokenBuffer> _buffer;
	id<REScriptParserDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<REScriptParserDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)parse;
-(void)setDelegate:(id<REScriptParserDelegate>)arg1 ;
-(id<REScriptParserDelegate>)delegate;
-(id)initWithBacktrackingBuffer:(id)arg1 ;
@end

