#import <InstallCoordination/IXFileManager.h>
#import <InstallCoordination/IXRestoringAppInstallCoordinator.h>
#import <InstallCoordination/IXGlobalConfiguration.h>
#import <InstallCoordination/IXAppInstallCoordinator.h>
#import <InstallCoordination/IXOwnedDataPromiseSeed.h>
#import <InstallCoordination/IXGizmoInstallingAppInstallCoordinator.h>
#import <InstallCoordination/IXPromisedTransferToPath.h>
#import <InstallCoordination/IXDemotingAppInstallCoordinator.h>
#import <InstallCoordination/IXAppInstallObserver.h>
#import <InstallCoordination/IXPlaceholderSeed.h>
#import <InstallCoordination/IXPromisedOutOfBandTransferSeed.h>
#import <InstallCoordination/IXPromisedStreamingZipTransferSeed.h>
#import <InstallCoordination/IXPlaceholder.h>
#import <InstallCoordination/IXUninstallOptions.h>
#import <InstallCoordination/_IXSimpleInstallerDelegate.h>
#import <InstallCoordination/IXPromisedInMemoryData.h>
#import <InstallCoordination/IXPromisedInMemoryDictionarySeed.h>
#import <InstallCoordination/IXPromisedInMemoryDataSeed.h>
#import <InstallCoordination/IXPromisedOutOfBandStreamingZipTransferSeed.h>
#import <InstallCoordination/IXOwnedDataPromise.h>
#import <InstallCoordination/IXUpdatingAppInstallCoordinator.h>
#import <InstallCoordination/IXPromisedStreamingZipTransfer.h>
#import <InstallCoordination/IXPromotingAppInstallCoordinator.h>
#import <InstallCoordination/IXPromisedOutOfBandTransfer.h>
#import <InstallCoordination/IXOpaqueDataPromise.h>
#import <InstallCoordination/IXInitiatingAppInstallCoordinator.h>
#import <InstallCoordination/IXDataPromiseSeed.h>
#import <InstallCoordination/IXPromisedOutOfBandStreamingZipTransfer.h>
#import <InstallCoordination/IXPlaceholderAttributes.h>
#import <InstallCoordination/IXDataPromise.h>
#import <InstallCoordination/IXRestoringDemotedAppInstallCoordinator.h>
#import <InstallCoordination/_IXDemoteToPlaceholderDelegate.h>
#import <InstallCoordination/IXServerConnection.h>
#import <InstallCoordination/IXOpaqueDataPromiseSeed.h>
#import <InstallCoordination/IXPromisedTransferToPathSeed.h>
#import <InstallCoordination/IXAppInstallObserverProtocolInterface.h>
#import <InstallCoordination/IXAppInstallCoordinatorSeed.h>
#import <InstallCoordination/IXClientProtocolInterface.h>
#import <InstallCoordination/IXClientDelegateProtocolInterface.h>
#import <InstallCoordination/IXPromisedInMemoryDictionary.h>
