/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 24, 2020 at 12:37:53 AM British Summer Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /System/Library/PrivateFrameworks/ScoreBoard.framework/ScoreBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ScoreBoard/ScoreBoard-Structs.h>
#import <libobjc.A.dylib/NSMutableCopying.h>
#import <libobjc.A.dylib/BSDescriptionProviding.h>

@class NSDate, NSString;

@interface SCRSchedulingConfiguration : NSObject <NSMutableCopying, BSDescriptionProviding> {

	BOOL _wakeDeviceForDeadline;
	BOOL _requiresClassAAccess;
	BOOL _requiresNetworkAccess;
	NSDate* _earliestStartDate;
	double _schedulingWindow;

}

@property (nonatomic,readonly) NSDate * latestStartDate; 
@property (getter=isImmediate,nonatomic,readonly) BOOL immediate; 
@property (nonatomic,copy,readonly) NSDate * earliestStartDate;                //@synthesize earliestStartDate=_earliestStartDate - In the implementation block
@property (nonatomic,readonly) double schedulingWindow;                        //@synthesize schedulingWindow=_schedulingWindow - In the implementation block
@property (nonatomic,readonly) BOOL wakeDeviceForDeadline;                     //@synthesize wakeDeviceForDeadline=_wakeDeviceForDeadline - In the implementation block
@property (nonatomic,readonly) BOOL requiresClassAAccess;                      //@synthesize requiresClassAAccess=_requiresClassAAccess - In the implementation block
@property (nonatomic,readonly) BOOL requiresNetworkAccess;                     //@synthesize requiresNetworkAccess=_requiresNetworkAccess - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)configurationWithEarliestStart:(id)arg1 schedulingWindow:(double)arg2 ;
+(id)immediateConfiguration;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(id)_latestEffectiveStartDate;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)requiresNetworkAccess;
-(void)setEarliestStartDate:(NSDate *)arg1 ;
-(id)_initWithStartDate:(id)arg1 window:(double)arg2 ;
-(id)_copyWithClass:(Class)arg1 ;
-(id)descriptionBuilderWithMultilinePrefix:(id)arg1 ;
-(void)setSchedulingWindow:(double)arg1 ;
-(BOOL)requiresClassAAccess;
-(id)intersectionWith:(id)arg1 minimumWindow:(double)arg2 ;
-(id)_earliestEffectiveStartDate;
-(id)init;
-(BOOL)isSatisfiedBy:(id)arg1 ;
-(double)schedulingWindow;
-(BOOL)isEqual:(id)arg1 ;
-(BOOL)wakeDeviceForDeadline;
-(BOOL)_isSatisfiedBy:(id)arg1 strictly:(BOOL)arg2 ;
-(BOOL)isImmediate;
-(void)setWakeDeviceForDeadline:(BOOL)arg1 ;
-(NSDate *)latestStartDate;
-(id)succinctDescriptionBuilder;
-(void)setRequiresNetworkAccess:(BOOL)arg1 ;
-(unsigned long long)hash;
-(void)setRequiresClassAAccess:(BOOL)arg1 ;
-(id)succinctDescription;
-(BOOL)isCurrentlySatisfiedBy:(id)arg1 ;
-(id)descriptionWithMultilinePrefix:(id)arg1 ;
-(NSDate *)earliestStartDate;
-(NSString *)description;
@end

